zone/client.h
zone/corpse.cpp
zone/forage.cpp
zone/task_client_state.cpp
zone/task_client_state.h
zone/tradeskills.cpp

This fixes a bug that allowed looting items from a player's corpse to increment a task if it didn't have an npc target defined. It looks like this bug existed before the changes in 7482cfc0.
This also now passes count for task loot updates to handle item stacks.
Also fixes incorrectly casting Corpse to NPC on loot update

[Tasks] Only update loot tasks for NPC corpses

---

zone/attack.cpp
zone/embparser.cpp
zone/entity.cpp
zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/npc.cpp
zone/npc.h

This cleans up some of the NPC::Death event dispatch code.
Adds handlers for EVENT_SPAWN_ZONE and EVENT_DEATH_ZONE used by zone controller and fixes the death handler exports which were incorrect.

[Quest API] Add Lua handlers for zone controller events

---

zone/embparser.cpp
zone/lua_parser_events.cpp
zone/zoning.cpp

- Add `$from_instance_id` to EVENT_ZONE in Perl.
- Add `$from_instance_version` to EVENT_ZONE in Perl.
- Add `$target_instance_id` to EVENT_ZONE in Perl.
- Add `$target_instance_version` to EVENT_ZONE in Perl.
- Add `e.from_instance_id` to EVENT_ZONE in Lua.
- Add `e.from_instance_version` to EVENT_ZONE in Lua.
- Add `e.instance_id` to EVENT_ZONE in Lua.
- Add `e.instance_version` to EVENT_ZONE in Lua.
- This will allow Operators to prevent people from entering zones by Instance ID or Instance Version.

[Quest API] Add Instance ID/Version exports to EVENT_ZONE.

---

zone/attack.cpp
zone/embparser.cpp
zone/lua_parser_events.cpp

It wasn't possible to easily obtain the corpse from post-death events because the killed entity id is assigned to the corpse and reset to 0 on the entity before the events are dispatched.
This exposes the killed entity's corpse to EVENT_DEATH_COMPLETE and EVENT_DEATH_ZONE. Lua exports a Corpse object and perl exports a corpse entity id.
The purpose of this is to make it easier to add items dynamically on death. Ideally this would be done in EVENT_DEATH before the corpse is made, but there's currently some combat system bugs that make that event unusable since it can be dispatched multiple times.
A follow up will provide an api to reset corpse decay times since adding items after corpse creation will require quests to manually reset the decay timer in case the corpse had zero items.

[Quest API] Export corpse in EVENT_DEATH_COMPLETE

---

common/shared_tasks.cpp
common/shared_tasks.h
world/shared_task_manager.cpp
world/shared_task_manager.h
world/shared_task_world_messaging.cpp
world/zoneserver.cpp
zone/client.h
zone/embparser_api.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/lua_general.cpp
zone/perl_client.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/shared_task_zone_messaging.cpp
zone/task_client_state.cpp
zone/task_client_state.h
zone/task_manager.cpp
zone/task_manager.h
zone/worldserver.cpp

This required some minor shared task refactoring
- Shared task expiration handling was moved to world. Previously this was handled by zone and had clients self remove when a shared task expired. This resulted in wrong messages when a task ended.
- FailTask is now implemented for shared tasks which previously only made the client quit the shared task. It now fails the task for all members by ending the shared task.
The `Client::EndSharedTask` api will end the client's current shared task (removing all members). This is similiar to the `FailTask` api except it doesn't require a `task_id` and the red task fail banner is optional (live doesn't use it for shared tasks).
The global `end_dz_task` api was added for when a client context isn't available. This will end a shared task if the current …

[Quest API] Add apis to end shared tasks

---

common/item_instance.cpp
common/item_instance.h
zone/embparser.cpp
zone/embparser.h
zone/embperl.h
zone/lua_iteminst.cpp
zone/lua_iteminst.h
zone/perl_questitem.cpp
zone/task_client_state.cpp
zone/trading.cpp

This restores sending items to EVENT_TRADE that are updated by source controlled delivery tasks which was removed in 7cf96ca2d8.
That patch filtered out items consumed by task updates to fix a few bugs with items being returned despite incrementing a task:
- If an npc without a quest trade event handler was the target of a delivery task for a NoDrop/non-Quest item, the npc would auto return it due to the `ReturnNonQuestNoDropItems` rule.
- If an npc without a quest trade event handler was the target of a delivery task for a non-NoDrop item, the item would be added to the npc's loot.
- If an npc with an EVENT_ITEM/EVENT_TRADE quest handler used the Lua or Perl trade plugins, the plugins would return task items unless specific checks for the turned in slots existed.
The quest plugin item …

[Tasks] Send delivered task items in trade events

---

zone/client.cpp
zone/client.h
zone/spells.cpp

#scribespells previously wasn't aware of ranked spells.
This change will check if there's a higher rank spell available based on the max/min levels specified, and only learn the highest rank spell.
Fixes #727

[Feature] Change #scribespells to be aware of spellgroups & ranks

---

zone/lua_group.cpp
zone/lua_group.h
zone/perl_groups.cpp

- Add `$group->GetAverageLevel()` to Perl.
- Add `group:GetAverageLevel()` to Lua.
- Convert `group:GetHighestLevel()` from `int` to `uint32` in Lua.
- Convert `group:GetLowestLevel()` from `int` to `uint32` in Lua.

[Quest API] Add GetAverageLevel() to Perl/Lua.

---

zone/perl_groups.cpp
zone/perl_raids.cpp

- Add `$group->SplitMoney(copper, silver, gold, platinum, splitter)` to Perl.
- Add `$raid->SplitMoney(group_id, copper, silver, gold, platinum, splitter)` to Perl.

[Quest API] Add SplitMoney() overload with Client splitter to Perl.

---

common/item_instance.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/mob.h
zone/mob_appearance.cpp
zone/perl_mob.cpp

- Add `$mob->CloneAppearance(other)` to Perl.
- Add `$mob->CloneAppearance(other, clone_name)` to Perl.
- Add `mob:CloneAppearance(other)` to Lua.
- Add `mob:CloneAppearance(other, clone_name)` to Lua.
- Allows operators to easily clone appearance between mobs in a script without relying on a plugin or module.

[Quest API] Add CloneAppearance() to Perl/Lua.

---

zone/command.cpp
zone/gm_commands/emote.cpp

- Allow `^` separator to send multiple messages by name, world, or zone.

[Commands] Cleanup #emote Command.

---

zone/command.cpp
zone/gm_commands/depop.cpp

- Add optional `start_spawn_timer` parameter to start spawn timer of NPC when depopped.

[Commands] Cleanup #depop Command.

---

zone/client.cpp
zone/client.h
zone/command.cpp
zone/command.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->SendGMCommand(message)` to Perl.
- Add `$client->SendGMCommand(message, ignore_status)` to Perl.
- Add `client:SendGMCommand(message)` to Lua.
- Add `client:SendGMCommand(message, ignore_status)` to Lua.
- `ignore_status` allows you to have players use GM commands that they are not the required status level for through the Quest API.
- `ignore_status` is default false, so if you don't send it, it checks and makes sure the player can use the command you're sending before allowing it.

[Quest API] Add SendGMCommand() to Perl/Lua.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->GetOwner()` to Perl.
- Add `mob:GetOwnerID()` to Lua.
- `GetOwner()` exists in Lua, but not Perl.
- `GetOwnerID()` exists in Perl, but not Lua.

[Quest API] Add Owner methods to Perl/Lua.

---

zone/hate_list.cpp
zone/hate_list.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->DamageHateList(damage)` to Perl.
- Add `$mob->DamageHateList(damage, distance)` to Perl.
- Add `$mob->DamageHateListPercentage(damage)` to Perl.
- Add `$mob->DamageHateListPercentage(damage, distance)` to Perl.
- Add `$mob->DamageHateListBots(damage)` to Perl.
- Add `$mob->DamageHateListBots(damage, distance)` to Perl.
- Add `$mob->DamageHateListBotsPercentage(damage)` to Perl.
- Add `$mob->DamageHateListBotsPercentage(damage, distance)` to Perl.
- Add `$mob->DamageHateListClients(damage)` to Perl.
- Add `$mob->DamageHateListClients(damage, distance)` to Perl.
- Add `$mob->DamageHateListClientsPercentage(damage)` to Perl.
- Add `$mob->DamageHateListClientsPercentage(damage, distance)` to Perl.
- Add `$mob->DamageHateListNPCs(damage)` to Perl.
- Add …

[Quest API] Add Mob Hate Methods to Perl/Lua.

---

common/emu_constants.h
zone/entity.cpp
zone/entity.h
zone/hate_list.cpp
zone/hate_list.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->DamageArea(damage)`.
- Add `$mob->DamageArea(damage, distance)`.
- Add `$mob->DamageAreaBots(damage)`.
- Add `$mob->DamageAreaBots(damage, distance)`.
- Add `$mob->DamageAreaClients(damage)`.
- Add `$mob->DamageAreaClients(damage, distance)`.
- Add `$mob->DamageAreaNPCs(damage)`.
- Add `$mob->DamageAreaNPCs(damage, distance)`.
- Add `$mob->DamageAreaPercentage(damage)`.
- Add `$mob->DamageAreaPercentage(damage, distance)`.
- Add `$mob->DamageAreaBotsPercentage(damage)`.
- Add `$mob->DamageAreaBotsPercentage(damage, distance)`.
- Add `$mob->DamageAreaClientsPercentage(damage)`.
- Add `$mob->DamageAreaClientsPercentage(damage, distance)`.
- Add `$mob->DamageAreaNPCsPercentage(damage)`.
- Add `$mob->DamageAreaNPCsPercentage(damage, distance)`.
- Add `mob:DamageArea(damage)`.
- …

[Quest API] Add Area Damage Methods to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp

- Add `quest::ishotzone()`.
- Add `quest::sethotzone(is_hotzone)`.
- Add `eq.is_hotzone()`.
- Add `eq.set_hotzone(is_hotzone)`.
- Allows operators to toggle hotzone flags within a script dynamically, for stuff like making an instance a hotzone, but not necessarily all versions of the zone.

[Quest API] Add Hotzone Methods to Perl/Lua.

---

zone/entity.cpp

- Class ID wasn't being checked, must've been left out of commit.

[Bug Fix] Fix EntityList::GetBotListByCharacterID()

---

zone/bot.h
zone/botspellsai.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp

Add Perl & Lua method to validate if a Spell ID is in the Bot Spells Entries based on the Bot Class.
Perl: $bot->CheckBotSpellEntries;
Lua: bot:CheckBotSpellEntries;

[Quest API] Add HasBotSpellEntry() to Perl/Lua.

---

zone/client_packet.cpp

Adds support for Merchants to buyback Alt Currency items at a percentage value using the item LDoNSellBackRate attribute.
Currently this was only being supported for Adventure Merchants.

[Merchant] LDoNSellBackRate support for Merchant:EnableAltCurrencySell Rule

---

zone/botspellsai.cpp

- Reordering of Casting to allow De-buffs to be applied more quickly during casting logic
- Support for In Combat Buffs to Bot Classes (Twincast, Yaulp, etc)
- Melee Bots added support for "In Combat Buff Song" (Fists of Wu, Cry Havoc buffs)
- Melee Bots can now use Combat Abilities/Buffs (Will need to work on Disc support, under a separate change)

[Bots] Add Melee Support for Casting, Cleanup Bot Casting Logic

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::set_proximity_range(x_range, y_range)`.
- Add `quest::set_proximity_range(x_range, y_range, z_range)`.
- Add `quest::set_proximity_range(x_range, y_range, z_range, enable_say)`.
- Add `eq.set_proximity_range(x_range, y_range)`.
- Add `eq.set_proximity_range(x_range, y_range, z_range)`.
- Add `eq.set_proximity_range(x_range, y_range, z_range, enable_say)`.
- Allows a shorthand for setting proximities.
- Automatically uses NPC's current location versus having to provide it.

[Quest API] Add Proximity Range Methods to Perl/Lua.

---

common/database.h
common/database_instances.cpp
common/repositories/character_corpses_repository.h
zone/embparser_api.cpp
zone/gm_commands/instance.cpp
zone/gm_commands/zone_instance.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/zoning.cpp

- Add `quest::GetInstanceIDs(zone_name)`.
- Add `quest::GetInstanceIDsByCharID(zone_name, character_id)`.
- Add `quest::GetInstanceVersionByID(instance_id)`.
- Add `quest::GetInstanceZoneIDByID(instance_id)`.
- Add `eq.get_instance_ids(zone_name)`.
- Add `eq.get_instance_ids_by_char_id(zone_name, character_id)`.
- Add `eq.get_instance_version_by_id(instance_id)`.
- Add `eq.get_instance_zone_id_by_id(instance_id)`.
- The instance IDs methods return arrays of IDs for looping so you can check on mass the instances a player has for a zone.
- Keeps operators from having to guess which possible versions of a zone a player has an instance for or loop through them all to find out.
- Cleanup `common/database_instances.cpp` to mostly use repositories where possible.

[Quest API] Add Instance Methods to Perl/Lua.

---

common/repositories/character_peqzone_flags_repository.h
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp
zone/zoning.cpp

- Add `$client->GetPEQZoneFlags()`.
- Add `$client->GetZoneFlags()`.
- Add `client:GetPEQZoneFlags()`.
- Add `client:GetZoneFlags()`.
- Allows operators to get a list of all PEQ/zone flags to be looped through or listed out easily without having to have a list of individual zone IDs to check or otherwise.

[Quest API] Add Zone Flag Methods to Perl/Lua.

---

zone/entity.cpp
zone/entity.h
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/perl_entity.cpp

- Add `$entity_list->GetBotListByClientName(client_name, class_id)`.
- Add `eq.get_entity_list():GetBotListByClientName(client_name, class_id)`.
- Adds overload to get bots by client name and class ID.

[Quest API] Add GetBotListByClientName() Class Overload to Perl/Lua.

---

zone/client_packet.cpp
zone/dialogue_window.cpp
zone/entity.cpp
zone/loottables.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/lua_object.cpp
zone/lua_object.h
zone/mob.cpp
zone/mob.h
zone/mob_info.cpp
zone/npc.cpp
zone/npc_scale_manager.cpp
zone/object.cpp
zone/object.h
zone/perl_mob.cpp
zone/perl_object.cpp
zone/worldserver.cpp

- Add `$mob->GetEntityVariables()`.
- Add `$object->GetEntityVariables()`.
- Add `mob:GetEntityVariables()`.
- Add `object:GetEntityVariables()`.
- Convert all overloads and methods to use `std::string` for entity variables.
- Allows operators to get a list of a Mob's entity variables.

[Quest API] Add Entity Variable Methods to Perl/Lua.

---

common/strings.cpp
common/strings.h
zone/data_bucket.cpp
zone/data_bucket.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::timetoseconds(time_string)`.
- Add `eq.time_to_seconds(time_string)`.
- Allows operators to use this method in place of hardcoded values like `3600`.

[Quest API] Add Time String to Seconds Method to Perl/Lua.

---

zone/bot.cpp

Process will be run when spawning bots, or on zone. moved out of CalcBotStats to reduce number of DB queries.
Will eventually look at storing Bot Spell Entries in memory, and do data bucket comparisons via that method.

[Bots] Move Bot Spell Loading process to Bot Constructor 

---

zone/embparser.cpp

This condition caused the variables to show twice due to the way Sprie parses the source code, and the condition itself is unnecessary since we can just use an inline ternary in this case.

[Quest API] Fix Perl EVENT_HP double parsing in Spire.

---

zone/botspellsai.cpp

Fixes issue where Bots will spam cast ST_TargetsTarget buffs (and never successfully buff)
Will need to build Target of Target support for Bots, and revisit,

[Bot] Update Bot Logic to ignore ST_TargetsTarget when buffing

---

zone/entity.cpp

Also provides support for Mercs.
Player Auras will land on Bots & Mercs now.
PBAE Buffs willl land on Bots & Mercs now.
MGB Buffs will land on Bots & Mercs now.
NPC detrimental spells should also function if they didn't before (PBAE spells)

[Bot] Add Support for Bots to receive Auras, and other AoE Spells

---

zone/groups.cpp
zone/groups.h
zone/lua_group.cpp
zone/lua_group.h
zone/lua_raid.cpp
zone/lua_raid.h
zone/perl_groups.cpp
zone/perl_raids.cpp
zone/raids.cpp
zone/raids.h

- Add `$group->IsGroupMember(name)`.
- Add `$group->IsLeader(name)`.
- Add `$raid->IsRaidMember(client)`.
- Add `$raid->IsGroupLeader(client)`.
- Add `group:IsGroupMember(name)`.
- Add `group:IsLeader(name)`.
- Add `raid:IsGroupLeader(client)`.
- Add `raid:IsLeader(client)`.
- Add `raid:IsRaidMember(client)`.
- Adds overloads to these methods allowing operators to get by name or reference.

[Quest API] Add Group/Raid Overloads to Perl/Lua.

---

zone/bot.cpp
zone/bot.h
zone/bot_database.cpp
zone/bot_database.h

- Bots previously were running 23 individual queries to load their inventory versus grabbing their inventory all at once and referencing it in memory.

[Bots] Optimize inventory loading.

---

zone/questmgr.cpp

Adjustment to depop_all function to no longer require an owner under all conditions (allows use inside encounters)

[Quest API] Adjustment to depop_all function.

---

zone/client_packet.cpp

Clamp Item Ldon Sell Back Rates to prevent potential abuse if set to 100 or higher, could return more then the item is originally sold for.

[Fix] Clamp Item Ldon Sell Back Rates.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->WearChange(slot, texture)`.
- Add `mob:WearChange(slot, texture)`.
- Add `mob:WearChange(slot, texture, color, heros_forge_model)`.
- Add `mob:SendWearChange(slot)`.
- These overloads allow you to not have to send color.
- Lua didn't have an overload with Hero's Forge Model.
- SendWearChange existed in Lua, it just didn't have a definition.

[Quest API] Add WearChange Overloads to Perl/Lua.

---

common/spdat.cpp
common/spdat.h
zone/spell_effects.cpp

Currently sends error message about unknown spell effect ID.

[Bug Fix] Add SE_MakeDrunk to avoid error message.

---

zone/bot_command.cpp

Fix for ^spellsettingsadd Bot command to work. couldn't add new entries as ^spellsettingsupdate requires a Spell List entry to exist.

[Bug Fix] Fix Bot ^spellsettingsadd command

---

zone/bot.cpp
zone/bot_command.cpp

Following methods were moved out of Bot Loading Constructor as they could cause potential crashes, were moved to ^spawn method, which doesn't load on zones/botspawngroups.
**GetBotOwnerDataBuckets();
GetBotDataBuckets();
LoadBotSpellSettings();**
Moved to Bot::Spawn and verified this method is called properly on Spawn, Bot Spawn Groups, and Zoning.
Compiled and tested change.

[HotFix] Resolve issue with Bot Casting after zoning.

---

zone/gm_commands/suspend.cpp

- This command required you to properly send the name as it appears in the database otherwise it wouldn't kick the player.
- Solution is to `Strings::ToLower` then `Strings::UcFirst`.

[Bug Fix] Fix case-sensitivity in #suspend Command.

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->Fling(target_x, target_y, target_z)`.
- Add `$client->Fling(target_x, target_y, target_z, ignore_los)`.
- Add `$client->Fling(target_x, target_y, target_z, ignore_los, clip_through_walls)`.
- Add `client:Fling(target_x, target_y, target_z)`.
- Add `client:Fling(target_x, target_y, target_z, ignore_los)`.
- Add `client:Fling(target_x, target_y, target_z, ignore_los, clip_through_walls)`.
- These overloads calculate the speed based on the distance automatically.

[Quest API] Add Fling Overloads to Perl/Lua.

---

zone/client.cpp
zone/client.h
zone/command.cpp
zone/gm_commands/max_all_skills.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->MaxSkills()`.
- Add `client:MaxSkills()`.
- Allows operators an easy short hand for maxing a player's skills for their level without needing to do all the looping and stuff on their own.

[Quest API] Add MaxSkills() to Perl/Lua.

---

common/strings.cpp

- "F" or "f" weren't handled in this method, so they weren't working properly.
- Most people don't provide this parameter when setting a permanent data bucket, so wasn't noticed in testing.

[Bug Fix] Data Bucket Permanent Duration String

---

zone/bot.cpp
zone/merc.cpp

Rest Regen timer was only starting if the Bot was sitting, and resetting itself on movement.
Rest Timer should start when out of combat, and only start again once engaged.

[Bot/Merc] Cleanup Fast Rest Regen

---

common/repositories/rule_sets_repository.h
common/repositories/rule_values_repository.h
common/rulesys.cpp
common/rulesys.h
common/strings.cpp
common/strings.h
zone/client.cpp
zone/command.h
zone/gm_commands/rules.cpp
zone/zone.cpp

- Rewrite all rules logic to use `std::string` and repositories.

[Commands] Cleanup #rules Command. 

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `$mob->DoAnim(animation_id, animation_speed, ackreq)`.
- Add `$mob->DoAnim(animation_id, animation_speed, ackreq, filter)`.
- Add `quest::doanim(animation_id, animation_speed)`.
- Add `quest::doanim(animation_id, animation_speed, ackreq)`.
- Add `quest::doanim(animation_id, animation_speed, ackreq, filter)`.
- Add `eq.do_anim(animation_id)`.
- Add `eq.do_anim(animation_id, animation_speed)`.
- Add `eq.do_anim(animation_id, animation_speed, ackreq)`.
- Add `eq.do_anim(animation_id, animation_speed, ackreq, filter)`.
- Adds overloads and cleans up spots where `animation_speed` was named `type` erroneously.

[Quest API] Add DoAnim Overloads to Perl/Lua.

---

common/strings.cpp
zone/task_manager.cpp

Observed on KMRA
**Problem**
When `zones` field has `NaN` in it; the server doesn't handle it properly and crashes.
**Solution**
`Strings::IsNumber` was not attempting to `stoi` and did not throw an error when `NaN` was passed. Traded `stod` for `stoi` in the `IsNumber` helper. This could be swapper for a int64 try/catch later.
`zones` field is now resilient to non-integer input

[Tasks] Crash fix with data input sanitization

---

zone/embparser_api.cpp
zone/lua_general.cpp

- Add `eq.create_door(model_name, x, y, z, h)`.
- Add `eq.create_door(model_name, x, y, z, h, open_type)`.
- Lua door/object create methods were `void` type instead of `uint16`, so you couldn't get the entity ID of the door you created.
- Converted Perl's door/object create methods to return `uint16` instead of `int` as well.

[Quest API] Fix Lua Door/Object Create Methods.

---

zone/bot.cpp

Allows No Trade Items to be used for Bot Event_Trade, and also QoL as some users are used to just using ^invgive.

[Bots] Add Event_Trade Support for ^inventorygive Command

---

zone/bot.cpp
zone/bot.h
zone/inventory.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/lua_group.h
zone/perl_bot.cpp

Adds following Perl & Lua Methods:
$bot->ApplySpell
$bot->ApplySpellGroup
$bot->ApplySpellRaid
$bot->CountAugmentEquippedByID
$bot->CountItemEquippedByID
$bot->Escape
$bot->Fling
$bot->GetAugmentAt
$bot->GetAugmentIDAt
$bot->GetBaseAGI
$bot->GetBaseCHA
$bot->GetBaseDEX
$bot->GetBaseINT
$bot->GetBaseSTA
$bot->GetBaseSTR
$bot->GetBaseWIS
$bot->GetGroup
$bot->GetHealAmount
$bot->GetInstrumentMod
$bot->GetItemAt
$bot->GetItemIDAt
$bot->GetRaid
$bot->GetRawItemAC
$bot->GetSpellDamage
$bot->HasAugmentEquippedByID
$bot->HasItemEquippedByID
$bot->InZone
$bot->IncStats
$bot->IsGrouped
$bot->IsRaidGrouped
$bot->IsSitting
$bot->IsStanding
$bot->SendSpellAnim
$bot->SetSpellDuration
$bot->SetSpellDurationGroup
$bot->SetSpellDurationRaid
$bot->SetStats
$bot->Sit
$bot->Stand

[Bots] Add Quest API Methods

---

zone/bot_database.cpp

Bots were not saving their Base Gender when saving. This could result in bots with illusions saving as gender 2 and becoming a male human model upon illusion fade.

[Bots] Fix Gender not saving as GetBaseGender on BotSave

---

zone/client_process.cpp

- If you deleveled below a spell's level, you couldn't unmemorize it, this fixes that.

[Bug Fix] Allow High Level Spells to be Unmemorized.

---

zone/zoning.cpp

- These logs were extraneous and unnecessary, they fired any time a player had no flags, which is usually 100% of the time since most servers aren't using this functionality.

[Bug Fix] Remove unnecessary log messages.

---

zone/bot.cpp

Trade check was not checking GetBaseRace and would fail if the bot's illusion couldn't equip the item.

[Bots] Fix trading with bots when in an illusion.

---

common/strings.cpp
common/strings.h
zone/command.cpp
zone/gm_commands/feature.cpp
zone/gm_commands/reload.cpp

Certain commands like `#rq` and `#size` are hard wired in our lizard brains after years of muscle memory and usage. These commands can be conveniently aliased using the commands aliases system but only for top level commands. 
Some commands have been consolidated to a single place like `#reload` which makes far more sense, but when typing short-hands for example I'm used to `#rq` reloading quests and that is now `#reload quest`.
This PR adds some hard-coded command aliasing for some nested commands.
* `#rq` equates to `#reload quests`
* `#size` equates to `#feature size`
* `#rl` equates to `#reload logs`
**Help Menu Improvement**
`#help <search>` now searches descriptions instead of just the commands themselves.
**Misc**
* Add `Strings::IsFloat` to check if a string is a float similar to …

[Commands] Nested Command Aliases

---

common/repositories/template/base_repository.template
utils/scripts/generators/repository-generator.pl

This PR adds support for automatically generating Cereal library serialization against a repositories data model struct automatically. It also appends the cereal include to the repository automatically.
This is utilized in an upcoming PR for player events
**Before**
```cpp
struct PlayerEventLogs {
int64_t     id;
int64_t     account_id;
int64_t     character_id;
int32_t     zone_id;
int32_t     instance_id;
float       x;
float       y;
float       z;
float       heading;
int32_t     event_type_id;
std::string event_type_name;
std::string event_data;
time_t      created_at;
};
```
**After**
```cpp
struct PlayerEventLogs {
int64_t     id;
int64_t     account_id;
int64_t     character_id;
int32_t     zone_id;
int32_t     instance_id;
float       x;
float       y;
float       z;
float …
```

[Repositories] Add Cereal support to repository generator

---

zone/bot_command.cpp

quick fix (causes minor formatting issue), is properly fixed under Akkadius/player-event-logging branch.

[Hotfix] Compiling fails on FMT 9.1 with Bots

---

common/inventory_profile.cpp
common/inventory_profile.h
zone/lua_client.cpp
zone/lua_client.h
zone/lua_inventory.cpp
zone/lua_inventory.h
zone/perl_client.cpp
zone/perl_inventory.cpp

- Add `$client->GetAugmentIDsBySlotID(slot_id)`.
- Add `$inventory->GetAugmentIDsBySlotID(slot_id)`.
- Add `client:GetAugmentIDsBySlotID(slot_id)`.
- Add `inventory:GetAugmentIDsBySlotID(slot_id)`.
- Allows operators to get a list of augments from a specific slot instead of having to build a plugin or something to do it.
- Fix issue with Lua tables starting at index `1` versus index `0`, so you lost the first value of the table due to this.

[Quest API] Add GetAugmentIDsBySlotID() to Perl/Lua.

---

common/ruletypes.h
zone/exp.cpp

This adds the following rule:
Character:ExperiencePercentCapPerKill: (-1=disabled, 0+ enforced) (default = -1)
This rule allows server operators to cap experience gains to a percent of the players current level. Note that this cap is enforced AFTER AA exp is removed.
This cap is also enforced before any XP modifiers.
Tested and working on my local dev server.

[Rules] Rule to allow cap on % XP gain per kill

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->IsAttackAllowed(target)`.
- Add `$mob->IsAttackAllowed(target, is_spell_attack)`.
- Add `mob:IsAttackAllowed(target)`.
- Lua had `mob:IsAttackAllowed(target, is_spell_attack)` but not the other overload.
- Perl had neither.

[Quest API] Add IsAttackAllowed() to Perl/Lua.

---

common/repositories/base/base_npc_types_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2022_12_24_npc_keeps_sold_items.sql
zone/beacon.cpp
zone/client.cpp
zone/client_packet.cpp
zone/corpse.cpp
zone/encounter.cpp
zone/gm_commands/modifynpcstat.cpp
zone/gm_commands/npcedit.cpp
zone/lua_npc.cpp
zone/lua_npc.h
zone/mob.cpp
zone/mob.h
zone/npc.cpp
zone/perl_npc.cpp
zone/zonedb.cpp
zone/zonedump.h

- Add `$npc->GetKeepsSoldItems()`.
- Add `$npc->SetKeepsSoldItems(keeps_sold_items)`.
- Add `npc:GetKeepsSoldItems()`.
- Add `npc:SetKeepsSoldItems(keeps_sold_items)`.
- Add `#modifynpcstat keeps_sold_items`.
- Add `#npcedit keeps_sold_items`.
- Allows operators to keep specific NPCs from keeping items sold to them.
- Keeps NPCs from being cluttered with stuff like Cloth Caps, Bone Chips, etc.

[Feature] Add "Keeps Sold Items" Flag to NPCs

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp
zone/spells.cpp

- Add `$mob->BuffCount(is_beneficial)`.
- Add `$mob->BuffCount(is_beneficial, is_detrimental)`.
- Add `mob:BuffCount(is_beneficial)`.
- Add `mob:BuffCount(is_beneficial, is_detrimental)`.
- Allows operators to count only beneficial or detrimental buffs a mob has instead of always counting all buffs.

[Quest API] Add BuffCount() Overloads to Perl/Lua.

---

zone/bot.h
zone/bot_command.cpp
zone/bot_structs.h

Let players easily toggle ^enforcespellsettings
Make default behavior for spells added to Spell Settings List to be enabled by default.

[Bot Commands] Toggle Enforce Spell Settings

---

common/shareddb.cpp
common/shareddb.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::varlink(item_id, charges)`.
- Add `quest::varlink(item_id, charges, aug1)`.
- Add `quest::varlink(item_id, charges, aug1, aug2)`.
- Add `quest::varlink(item_id, charges, aug1, aug2, aug3)`.
- Add `quest::varlink(item_id, charges, aug1, aug2, aug3, aug4)`.
- Add `quest::varlink(item_id, charges, aug1, aug2, aug3, aug4, aug5)`.
- Add `quest::varlink(item_id, charges, aug1, aug2, aug3, aug4, aug5, aug6)`.
- Add `quest::varlink(item_id, charges, aug1, aug2, aug3, aug4, aug5, aug6, attuned)`.
- Add `eq.item_link(item_id, charges)`.
- Add `eq.item_link(item_id, charges, aug1)`.
- Add `eq.item_link(item_id, charges, aug1, aug2)`.
- Add `eq.item_link(item_id, charges, aug1, aug2, aug3)`.
- Add `eq.item_link(item_id, charges, aug1, aug2, aug3, aug4)`.
- Add `eq.item_link(item_id, …

[Quest API] Add Charges/Augment/Attuned Support to Varlink.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::do_augment_slots_match(item_one, item_two)`.
- Add `eq.do_augment_slots_match(item_one, item_two)`.
- Allows operators to see if augments slots across two items match for something like moving augments from one item to another.

[Quest API] Add DoAugmentSlotsMatch() to Perl/Lua.

---

common/item_instance.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::does_augment_fit(item, augment_id)`.
- Add `eq.does_augment_fit(item, augment_id)`.
- Returns the augment slot index where the augment fits within the item instance provided, returns `-1` if it doesn't fit or has no open slot to fit in.

[Quest API] Add DoesAugmentFit() to Perl/Lua.

---

zone/gm_commands/zone.cpp

- `#zone 0` was used to send you to safe coordinates, this has been broken for a while now.

[Bug Fix] Fix #zone 0.

---

zone/embparser.cpp
zone/entity.cpp

- Add `$area_id` export to EVENT_ENTER_AREA.
- Add `$area_type` export to EVENT_ENTER_AREA.
- Add `$area_id` export to EVENT_LEAVE_AREA.
- Add `$area_type` export to EVENT_LEAVE_AREA.
- This is so Spire will parse these events properly.

[Quest API] Cleanup Proximity Events

---

zone/client_packet.cpp

Old message when you attempted to promote or demote a player and did not have permissions to do so: "You dont have permission to invite."
New promote rejection message: "You dont have permission to promote."
New demote rejection message: "You dont have permission to demote."

[Bug Fix] Fixed message on promote/demote permissions check.

---

common/eq_constants.h
zone/command.cpp
zone/command.h
zone/gm_commands/setanon.cpp

- Adds `#setanon [Anonymous Flag]`.
- Adds `#setanon [Character ID] [Anonymous Flag]`.
- Allows operators to turn on/off a player's anonymous flag so they can view their Magelo.
- Flags are 0 = Not Anonymous, 1 = Anonymous, 2 = Roleplaying

[Commands] Add #setanon Command

---

zone/lua_raid.cpp
zone/lua_raid.h
zone/perl_raids.cpp
zone/raids.h

- Add `$raid->getLeader();`.
- Add `$raid->getLeaderName();`.
- Add `raid:GetLeader()`.
- Add `raid:GetLeaderName()`.
- Returns raid leader information, similar to the associated group methods.

[Quest API] Add GetLeader() and GetLeaderName() to Perl/Lua.

---

common/emu_oplist.h
common/eq_packet_structs.h
zone/client_packet.cpp

Item Name offset was off by 2 Bytes, causing first part of the Item Name to be cut off.
Fixed offset, confirmed working on RoF2.

[Bug Fix] AltCurrencySelectItemReply_Struct was not handled correctly.

---

zone/command.h
zone/gm_commands/guild.cpp
zone/guild_mgr.cpp
zone/guild_mgr.h

- Adds `#guild search [Search Criteria]` sub command.
- Allows operators to search for a guild instead of listing all guilds at once.
- Adds a method for sending guild sub commands to make code drier.

[Commands] Cleanup #guild Command

---

zone/exp.cpp

Resolves an experience calculation bug introduced by: https://github.com/EQEmu/Server/pull/2667 and reported by Aiden in discord: https://discord.com/channels/212663220849213441/1059233181498359888

[Bug Fix] Resolve XP Calculation Bug introduced w/ recent Rule addition

---

zone/mob.cpp

GM command npcstats was displaying incorrect faction text.

[Bug Fix] #npcstats command displying incorrect faction

---

zone/bot.cpp
zone/entity.cpp
zone/entity.h

- Event parsing was too early and memory wasn't fully allocated, meaning that sometimes you could use the NPC reference and other times you couldn't.
- Most people worked around this by setting timers in `EVENT_SPAWN` then using `EVENT_TIMER` to handle the stuff they wanted to do on spawn.
```pl
quest::shout($npc->GetCleanName() . " just spawned with an ID of " . $npc->GetID() . " and an NPC Type ID of " . $npc->GetNPCTypeID() . ".");
}
```

[Bug Fix] Fix NPC Reference in EVENT_SPAWN

---

zone/bot_command.cpp
zone/embparser.cpp
zone/event_codes.h
zone/lua_general.cpp
zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/questmgr.cpp
zone/spell_effects.cpp

- Add `EVENT_BOT_CREATE`.
- Exports `$bot_id`, `$bot_name`, `$bot_class`, `$bot_race`, and `$bot_gender`.
- Add `event_bot_create`.
- Exports `e.bot_id`, `e.bot_name`, `e.bot_class`, `e.bot_race`, and `e.bot_gender`.

[Quest API] Add EVENT_BOT_CREATE to Perl/Lua

---

zone/bot.cpp
zone/bot_database.cpp
zone/bot_database.h
zone/embparser.cpp
zone/entity.h
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/perl_entity.cpp

- Add `$entity_list->GetBotOwnerByBotID(bot_id)`.
- Add `$entity_list->GetBotOwnerByBotEntityID(entity_id)`.
- Add `$despawned_entity_id` export to `EVENT_DESPAWN`.
- Add `$despawned_bot_id` export to `EVENT_DESPAWN`.
- Add `$despawned_npc_id` export to `EVENT_DESPAWN`.
- Add `eq.get_entity_list():GetBotOwnerByBotID(bot_id)`.
- Add `eq.get_entity_list():GetBotOwnerByBotEntityID(entity_id)`.
- Add `e.other` export to `EVENT_DESPAWN_ZONE`.

[Bot] Add GetBotOwnerByBotID Method

---

libs/luabind/luabind/detail/policy.hpp

- Temporary fix for `int64` and `uint64` support in Lua on Windows.

[Lua Bind] Fix INT64 Support for Windows.

---

zone/bot.cpp
zone/bot.h
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp

- Add `$bot->Camp()`.
- Add `$bot->Camp(save_to_database)`.
- Add `bot:Camp()`.
- Add `bot:Camp(save_to_database)`.
- Saves to database by default, overload is for edge case where a user may not want bot to save to database.

[Quest API] Add Bot::Camp() to Perl/Lua.

---

zone/bot_database.cpp
zone/botspellsai.cpp

- Bots were producing error messages for "failing to load" spells and inventory when the bot had no spells, like a Warrior, or when the bot was naked, like a newly created bot.

[Bug Fix] Fix Bot "Failed to Load" Messages.

---

zone/bonuses.cpp

Fixes for potential Out of Bound memory access issues across misc code in zone/bonuses.cpp.
Appears to resolve 3 potential bugs:
1. `if (spells[spell_id].base_value[i] != 0)`
`Assuming 'IsAISpellEffect' is true | 
Loop condition is true. Entering loop body |
'IsAISpellEffect' is true | 
Taking false branch | 
Control jumps to 'case 10:' at line 2119`
2. ``switch(spells[spell_id].limit_value[i]``
`Assuming 'IsAISpellEffect' is true | 
Loop condition is true. Entering loop body | 
'IsAISpellEffect' is true | 
Taking false branch | 
Control jumps to 'case 262:' at line 2185`
3. `new_bonus->HPToManaConvert = spells[spell_id].base_value[i];`
`Assuming 'IsAISpellEffect' is true | 
Loop condition is true. Entering loop body| 
'IsAISpellEffect' is true | 
Taking false branch | 
Control jumps to …

[Bug Fixes] Fix Out of Bound Memory Access in zone/bonuses.cpp.

---

zone/lua_door.cpp
zone/lua_door.h
zone/perl_doors.cpp

- Add `$door->ForceClose(sender)`.
- Add `$door->ForceClose(sender, alt_mode)`.
- Add `$door->ForceOpen(sender)`.
- Add `$door->ForceOpen(sender, alt_mode)`.
- Add `$door->GetDisableTimer()`.
- Add `$door->SetDisableTimer(disable_timer)`.
- Add `door:GetID()`.
- Makes Perl/Lua Door scripting capabilities 1:1.

[Quest API] Add Door Methods to Perl/Lua.

---

zone/lua_mod.cpp

Return value (uint64) is being cast to a uint32. Maybe a copy and paste from above functions (which correctly cast to a uint32).
Remove unused variable.

[Bug Fix] Fix luamod GetExperienceForKill return value

---

zone/dialogue_window.cpp

"Balloon
— Today at 9:35 AM
I have a DiaWind box that explains some bonuses (e.g. +10 STR), but the + is being interpreted as an animation command and the display gets very screwy.  Is there a way to show a specific character without it being interpreted?  I've tried prefixing with the usual special chars and also using html &#43; to no avail."
We only replace content between plus signs when an animation is found

[Diawind] Plus sign markdown fix

---

zone/client_packet.cpp

Fixes instances where Server Operators set no Click Effect on an item, but leave Click Type set to a non-zero value.
This would prevent Aug Clickies from working correctly inside the item, along with some Events.

[Bug Fix] Fix Aug Clicks when Item has no Click Effect, but has a Click Type.

---

zone/entity.cpp
zone/entity.h
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/perl_entity.cpp

- Add `$entity_list->SignalAllBotsByOwnerName(owner_name)`.
- Add `eq.get_entity_list():SignalAllBotsByOwnerName(owner_name)`.
- Adds a way to signal all bots by owner name instead of only character ID.

[Quest API] Add SignalAllBotsByOwnerName() to Perl/Lua.

---

common/classes.h
common/inventory_profile.h
common/item_instance.cpp
world/lfplist.cpp
zone/bot.cpp
zone/bot.h
zone/bot_command.cpp
zone/bot_command.h
zone/client.cpp
zone/client.h
zone/client_bot.cpp
zone/client_packet.cpp
zone/entity.cpp
zone/entity.h
zone/lua_client.cpp
zone/lua_client.h
zone/lua_mob.cpp
zone/perl_client.cpp
zone/petitions.cpp
zone/questmgr.h

- Add `$client->CampAllBots()`.
- Add `$client->CampAllBots(class_id)`.
- Add `client:CampAllBots()`.
- Add `client:CampAllBots(class_id)`.
- Adds constants for `NO_CLASS` which is class `0` and uses `RACE_DOUG_0` for any spots that use race ID `0`.
- Cleans up magic number usage of race/class of `0`.

[Quest API] Add CampAllBots() to Perl/Lua.

---

common/item_instance.cpp
common/item_instance.h
zone/bot.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp
zone/spells.cpp

- Minor cleanup of variable types.
- Add `bot:GetAugmentAt(slot_id, augment_index)`.
- Add `bot:GetItemAt(slot_id)`.
- Add `bot:SendSpellAnim(target_id, spell_id)`.
- Properly implemented `bot:GetItemIDAt(slot_id)`.
- `bot:GetItemIDAt` existed in Lua, but didn't have a bind definition, so was non-functional.
- This makes Perl/Lua bot methods 1:1 as Perl had 75 and Lua had 72, they now both have 75.

[Quest API] Add Bot Methods to Lua.

---

zone/bot.cpp

- Resolves an issue where players could spawn more bots than allowed due to an edge-case where spawn limit by class/globally wasn't being checked on zone for individual bots nor spawn groups.
- Removes bots from group if they don't properly spawn.

[Bug Fix] Fix issue with Bot::LoadAndSpawnAllZonedBots.

---

zone/client_packet.cpp
zone/embparser.cpp
zone/event_codes.h
zone/lua_general.cpp
zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/tradeskills.cpp

- Add `EVENT_AUGMENT_INSERT_CLIENT`, exports `$augment_id`, `$augment_slot`, `$item_id`, and `$item_slot`.
- Add `EVENT_AUGMENT_REMOVE_CLIENT`, exports `$augment_id`, `$augment_slot`, `$destroyed`, `$item_id`, and `$item_slot`.
- Add `event_augment_insert_client`, exports `e.augment`, `e.augment_id`, `e.augment_slot`, `e.item`, `e.item_id`, and `e.item_slot`.
- Add `event_augment_remove_client`, exports `e.augment`, `e.augment_id`, `e.augment_slot`, `e.destroyed`, `e.item`, `e.item_id`, and `e.item_slot`.
- Allows operators to use augment insert and augment remove events outside of an item script.
- `$item_slot`/`e.item_slot` return `-1` if using a container.

[Quest API] Add Client Augment Events to Perl/Lua.

---

ucs/chatchannel.cpp
ucs/clientlist.cpp
ucs/database.cpp
ucs/database.h
ucs/ucs.cpp
ucs/worldserver.cpp

This PR addresses an issue that prevents developers from using repositories within UCS because it clashes with `./common/database.h` `Database` class.
Similarly to `ZoneDatabase` and `WorldDatabase` UCS's database was renamed from `Database` to `UCSDatabase` and inherits `Database` so it can use commonly leveraged connect, disconnect logic that was copy and pasted way back

[UCS] Database class name change

---

queryserv/database.cpp
queryserv/database.h
queryserv/lfguild.cpp
queryserv/queryserv.cpp
queryserv/worldserver.cpp

Similar to https://github.com/EQEmu/Server/pull/2742. Work done already in the player eventing branch to be PR'ed soon.
This PR addresses an issue that prevents developers from using repositories within QS because it clashes with `./common/database.h` `Database` class.
Similarly to `ZoneDatabase` and `WorldDatabase` QS's database was renamed from `Database` to `QSDatabase` and inherits `Database` so it can use commonly leveraged connect, disconnect logic that was copy and pasted way back

[QS] Database class name change

---

common/ruletypes.h
zone/client.h
zone/mob.h
zone/pets.cpp
zone/pets.h
zone/spells.cpp

Added a rule that allows server ops to apply "SPELL_TOO_POWERFUL" rule to NPCs just like PCs.
NPCBuffLevelRestrictions (default off to retain existing functionality)
While debuging this I found that NPC spells from the AI that fail in the CastSpell() portion of the spell casting chain do not recover ever - as the code relies on the casting_spell_id  and the spell slot to be valid in every function that calls the AI with AI_Event_SpellCastFinished.  As these variables are not set until later in the casting chain, the  AI was never getting reset.
This bug was much more obvious when setting my new rule, as NPC spells fail in the checking stage alot more.
This is a DRAFT PR until someone more adept with spells than I ok's the change.
I did test all the variant cases and it works, and I put a …

[Rule] Add rule for NPC Level Based Buff Restrictions.

---

zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->SendPath(target)`.
- Add `client:SendPath(target)`.
- Allows operators to send a path to a target arbitrarily with a script.

[Quest API] Add SendPath() to Perl/Lua.

---

zone/mob.h
zone/npc.cpp
zone/pets.cpp

Fixes numerous Zone Crashes that I've seen on KMRA recently where null instance is passed into methods.
here's some where HasPet() returns true, but GetPet() returns null... causing a crash.
[crash_lopingplains_version_0_inst_id_0_port_7061_684812.log](https://github.com/EQEmu/Server/files/10421306/crash_lopingplains_version_0_inst_id_0_port_7061_684812.log)
[crash_oldfieldofbone_version_0_inst_id_0_port_7033_3364593.log](https://github.com/EQEmu/Server/files/10421307/crash_oldfieldofbone_version_0_inst_id_0_port_7033_3364593.log)
[crash_lopingplains_version_0_inst_id_0_port_7043_1953522.log](https://github.com/EQEmu/Server/files/10421308/crash_lopingplains_version_0_inst_id_0_port_7043_1953522.log)

[Bug Fix] HasPet() Zone Crashes

---

zone/spells.cpp

This fixes ST_TargetsTarget Spells that are triggered from spell effects such as SE_ApplyEffect or SE_TriggerCast.
This was causing spells like Remote Manaflux which triggers a healing spell "Manaflux Enervation" on the TargetsTarget to fail as it has a restriction of "PCs and Mercs". It was doing the Target Restrictions against the original target of "Remote Manaflux" not the TargetsTarget (Client, Bot, Merc)

[Bug Fix] Fix ST_TargetsTarget Spells with Restrictions

---

zone/bot.cpp

Issue where zoning with a Bot would cause to a crash, introduced in #2733

[Hotfix] Resolve Zone Crashing when grouped with Bots.

---

zone/client_packet.cpp

Was using incorrect variable, which was still initialized as a nullptr.

[Bug Fix] Handle_OP_AugmentItem could cause Zone crash

---

zone/client.h
zone/doors.cpp
zone/zoning.cpp

This fixes a regression of desired behavior in zone flag checks. This one is interesting because the code change that changed the behavior is actually correct and cleans things up but revealed problems in our data. This fixes
* An issue where zone flags were being checked against the current zone and not the destination zone
* Previous behavior where zone flags with string types are not enforced
* Zones with flags are now additionally enforced earlier in the process to keep clients from getting punted to 0,0,0 in the zone right before the zoning process
**Example Issue**
Trakanon uses a key to enter the zone. On the zone table row there is `flag_needed` on the row but it wasn't truly enforced before and it is a non-bool. ProjectEQ quests also do nothing to award the flag to enter the …

[Fix] Zone Flags Regression

---

zone/bot_command.cpp

Regular Bot Spawn can't be used while Feigned, however it appears Bot Groups could be.

[Bot] Restrict Bot Groups from spawning while Feigned.

---

common/eqemu_logsys.cpp

* Force crash logs to always be on regardless of setting, this keeps operators from foot-gun and wasting time trying to find crashes if they accidentally turned the logs off. There's almost no circumstance in which you wouldn't want to be aware of a crash
* Categorize crashes as errors, which will highlight messages as red and pipe them to `stderr`

[Logging] Force crash logs to always be on regardless of setting

---

ucs/chatchannel.cpp
ucs/chatchannel.h
ucs/database.cpp
ucs/database.h

What:
These changes are an optimization to the changes introduced in PR #2706: name filters are loaded into memory when the server loads and new channels are compared against these memory values vs hitting the database each time.

[Optimization] Handle channel name filter checks in memory

---

ucs/database.cpp

LoadFilteredNamesFromDB() was not being called when channels were loaded.

[Bug Fix] Add omitted function call in UCS.

---

common/eqemu_logsys.cpp
common/eqemu_logsys.h
world/world_boot.cpp
world/world_boot.h
zone/zone.h

**What**
GM Say logging now includes `[Category]` and `[Function]` as prefixes to give more context to the category being logged and what function the log came from
This removes the need to prefix in logging statements the function that the log statement is calling from, which we have littered all over the code base.
**Examples**

[Logging] Improvements to GM Say Logging

---

zone/attack.cpp
zone/bot.h
zone/mob.cpp
zone/spell_effects.cpp
zone/spells.cpp

Adds Support for the following AA Bonuses to Bots, previously they were not being calculated.
Add Twinproc support to Bots from AAs
Add Twincast support to Bots from AAs
Add AA Melee and Ranged Procs Support to Bots
Add AA Defensive Proc Support to Bots
Add AA Stun Resist Support to Bots
Also ensures Bots are properly using Mob::GetFocusEffect over NPC::GetFocusEffect.

[Bots] Add Support for AA bonuses that were missing.

---

zone/main.cpp

* Don't load bot command settings when rule is not enabled
* Don't load bot spell chances when rule is not enabled
**Example Issue Snip**

[Bots] Post pre-processor fixes

---

zone/bot.cpp
zone/bot.h

**What:**
Adding a Virtual Override to point Bot::Attack to Mob::Attack, 
**Why**
As NPC has a virtual override of Attack, Bots will attempt to use that first if not specified.
This is to prevent anyone from accidentally removing the bot.cpp Mob::Attack() entries thinking they were a mistake.

[Bots] Add Virtual Override for Bot::Attack

---

zone/spells.cpp

#scribespells was causing errors on my server (using mySQL) due to using the keywork rank.
escaping the keyword fixed the problem and #scribespells works for me.
Can someone vouch for MariaDB with this fix?

[Commands] #scribespells triggered error on mysql keyword rank

---

zone/command.cpp
zone/command.h
zone/gm_commands/undye.cpp
zone/gm_commands/undyeme.cpp

- Removes redundant `#undyeme` command.
- Adds `GetGM()` check to `#undye` so players can't undye other players.

[Commands] Remove #undyeme Command.

---

zone/gm_commands/findaa.cpp
zone/zone.cpp

- These were not properly checking every possible AA ID.
- Before AAs like `Summon Resupply Agent` did not show up when `#findaa` was used or `quest::getaaname(9000)` was used.

[Bug Fix] Fix #findaa and GetAAName().

---

zone/worldserver.cpp

- Adds `bot_command_init` to `#reload commands` so that operators can reload bot commands if they enable/disable bots while the server is running.

[Bots] Add Bot Command Reloading

---

zone/bot.cpp

- Bots didn't check if the item was an augment before equipping, this stops them from equipping them.

[Bug Fix] Fix bots equipping augments.

---

zone/bot_command.cpp
zone/bot_database.cpp

Was displaying Group name per Bot, instead of unique Bot Group Name.

[Bug Fix] Fix botgrouplist to display unique entries.

---

common/server_event_scheduler.cpp

Found in a crash report linked below
http://spire.akkadius.com/dev/release/22.1.1?id=8

[Crash] Fix rarer world crash issue where scheduler database was not available

---

zone/effects.cpp

- Removes duplicate critical chance roll in `Mob::GetActSpellHealing`.
- Not sure if this was Live-like or an oversight, but it seems to drastically reduce the possibility of a HOT getting a critical.
- A 1% chance becomes a 0.01% chance being we have to roll twice.

[Bug Fix] Remove duplicate logic in GetActSpellHealing reducing HOT criticals

---

zone/bot_command.cpp

- Fix possible `nullptr` where we didn't check if spell was valid before using it.

[Bug Fix] Fix nullptr spell in BCSpells::Load() 

---

CHANGELOG.md
common/version.h
package.json

* Build / Release Pipeline Changes ([#2788](https://github.com/EQEmu/Server/pull/2788)) ([Akkadius](https://github.com/Akkadius)) 2023-01-24
* Cleanup #door Command. ([#2783](https://github.com/EQEmu/Server/pull/2783)) ([Kinglykrab](https://github.com/Kinglykrab)) 2023-01-24
* Fix rarer world crash issue where scheduler database was not available ([#2789](https://github.com/EQEmu/Server/pull/2789)) ([Akkadius](https://github.com/Akkadius)) 2023-01-24
* Fix nullptr spell in BCSpells::Load() ([#2790](https://github.com/EQEmu/Server/pull/2790)) ([Kinglykrab](https://github.com/Kinglykrab)) 2023-01-24
* Remove duplicate logic in GetActSpellHealing reducing HOT criticals ([#2786](https://github.com/EQEmu/Server/pull/2786)) ([Kinglykrab](https://github.com/Kinglykrab)) 2023-01-24

[Release] 22.1.2

---

common/eq_constants.h
common/eq_packet_structs.h
common/shareddb.cpp
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_01_24_item_recast.sql
zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/corpse.cpp
zone/inventory.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/object.cpp
zone/perl_client.cpp
zone/spells.cpp
zone/zonedb.cpp
zone/zonedb.h

Properly apply the cooldown to the item header with SetRecastTimestamp before sending item packet to player. 
Recast timer SHOULD show up in corpse window now as well as when the player loots the item into inventory.
Recast timer SHOULD show up in inventory when using SummonItem
All timers now saved to database  `character_item_recast` table
-Shared timers are - charid | recast_type | timestamp
-Items that have their own timer (-1 recast type) saved as - charid | item_id | timestamp
-SQL to alter recast_type to INT for this change to work
Implemented the `pTimerNegativeItemReuse` which is just pTimerNegativeItemReuse * itemid so timers stay unique

[Feature] ResetItemCooldown added to lua/perl and fix item re-cast times to show properly

---

common/eq_packet_structs.h

- This allows ROF2 to properly utilize their max buff count.
- May cause issues with older clients.

[Bug Fix] Resolve issue with max buff count being 25 in ROF2.

---

common/eq_packet_structs.h
common/repositories/base/base_merchantlist_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_01_29_merchant_status_requirements.sql
zone/client_process.cpp
zone/zone.cpp

- Allows operators to set a minimum and maximum status that an item will show for players.
- Allows operators to have items on a merchant that only a GM can see.
- Some servers may use status for different things, so having a minimum and a maximum will allow for more functionality.
- Default of `min_status` is `0` (Player) and default of `max_status` is `255` (Max).

[Feature] Add Min/Max Status to Merchants

---

eqlaunch/zone_launch.cpp
world/eqw_parser.cpp
zone/attack.cpp
zone/client_packet.cpp
zone/corpse.cpp
zone/embparser.cpp
zone/embparser.h
zone/embperl.cpp
zone/entity.cpp
zone/forage.cpp
zone/lua_general.cpp
zone/lua_parser.cpp
zone/lua_parser.h
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/object.cpp
zone/quest_interface.h
zone/quest_parser_collection.cpp
zone/quest_parser_collection.h
zone/spawn2.cpp
zone/tradeskills.cpp

- Several places use `push_back` instead of `emplace_back`.
- Several places use `std::string` instead of `const std::string&`.
- Several places were using ternaries for `true` and `false` instead of just checking `!= 0`.

[Quest API] Cleanup string copies and push_backs.

---

zone/zonedb.cpp

This bug was preventing anything other than 0 or 1 to be passed to see_invis, but per the current design, see_invis can be anything from 0 to 25499, which can give you level 254 invis. See design notes in Mob::GetSeeInvisibleLevelFromNPCStat.

[Bug Fix] Fixing % based mob see invis

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.cpp
zone/npc.h
zone/perl_npc.cpp

- Add `$npc->GetLDoNLockedSkill()`.
- Add `$npc->GetLDoNTrapType()`.
- Add `$npc->GetLDoNTrapSpellID()`.
- Add `$npc->IsLDoNLocked()`.
- Add `$npc->IsLDoNTrapped()`.
- Add `$npc->IsLDoNTrapDetected()`.
- Add `$npc->SetLDoNLocked(is_locked)`.
- Add `$npc->SetLDoNLockedSkill(skill_value)`.
- Add `$npc->SetLDoNTrapped(is_trapped)`.
- Add `$npc->SetLDoNTrapDetected(is_detected)`.
- Add `$npc->SetLDoNTrapSpellID(spell_id)`.
- Add `$npc->SetLDoNTrapType(trap_type)`.
- Add `npc:GetLDoNLockedSkill()`.
- Add `npc:GetLDoNTrapType()`.
- Add `npc:GetLDoNTrapSpellID()`.
- Add `npc:IsLDoNLocked()`.
- Add `npc:IsLDoNTrapped()`.
- Add `npc:IsLDoNTrapDetected()`.
- Add `npc:SetLDoNLocked(is_locked)`.
- Add `npc:SetLDoNLockedSkill(skill_value)`.
- Add `npc:SetLDoNTrapped(is_trapped)`.
- Add …

[Quest API] Add LDoN Methods to Perl/Lua

---

zone/spells.cpp

BuffLevelRestrictions were restricting group buffs if mob targetted at the time of casting.
This is due to the MOB::CheckSpellRestrictions being eliminated and a missing check in the shared version after my PR that added the NPCBuffRestrictions rule and did some refactoring and cleanup:
https://github.com/EQEmu/Server/pull/2708/files

[Bug Fix] BuffLevelRestrictions were restricting group buffs

---

common/item_instance.cpp
common/item_instance.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Allows you to check if the supplied augment ID fits in the specified augment slot of the item instance provided.

[Quest API] Add Augment Slot support to does_augment_fit

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.cpp
zone/npc.h
zone/npc_scale_manager.cpp
zone/npc_scale_manager.h
zone/perl_npc.cpp

- Add `$npc->ScaleNPC(level, always_scale_stats)`.
- Add `$npc->ScaleNPC(level, always_scale_stats, always_scale_special_abilities)`.
- Add `npc:ScaleNPC(level, always_scale_stats)`.
- Add `npc:ScaleNPC(level, always_scale_stats, always_scale_special_abilities)`.
- Allows operators to not have to set stats to 0 in order for scaling to kick in when scripting.
- Special ability override is separate in case you don't want to override some inherent special abilities the NPC has from a script or otherwise.

[Quest API] Add Override Parameters to ScaleNPC() in Perl/Lua.

---

zone/gm_commands/weather.cpp

- Condition falls back to sending message and can't turn weather off.

[Commands] Remove extraneous else from #weather

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.cpp
zone/npc.h
zone/npc_scale_manager.cpp
zone/npc_scale_manager.h
zone/perl_npc.cpp

- ScaleNPC will now always override stats, with the option to override special abilities.

[Quest API] Default ScaleNPC to always scale.

---

zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/task_client_state.cpp

Previously EVENT_TASKACCEPTED was only accesible in the NPC scope. 
This adds EVENT_TASKACCEPTED to the player scope for both Perl and Lua.
Tested on up-to-date binaries and works fine.

[Quest API] Add EVENT_TASKACCEPTED to Player scope

---

common/strings.cpp
common/strings.h
zone/lua_parser_events.cpp

It's been reported by numerous operators since https://github.com/EQEmu/Server/pull/2635 that Lua is throwing exceptions for `stoi` calls within the source. While this may not necessarily be breaking anything, it can cause Lua to throw exceptions and become noise to operators.
This may not fix all places that this occurs, but a common place where `std::stoi` is called and many assumptions are made about inputs are in all of the event bindings where we pass in inputs from event calls. To cleanly mitigate this issue for now, I've added a strings wrapper that will detect for a validity of a string before providing a fallback `default -1` and a fallback can be provided in general for other use cases.

[Lua] Resolve stoi Exception

---

zone/client.h
zone/client_packet.cpp
zone/entity.cpp
zone/npc.cpp
zone/npc.h

When zoning into some zones, NPCs can be "ghosted" at what appears to be zone ins or safe coordinates. This happens when NPCs are clipped into the geometry during the initial spawn of an NPC. The client auto corrects this by placing the actor in the safe coordinates. 
The client does other similar auto correcting behavior when the Z of a model is slightly in the ground, the client will correct it client side even if the server is wrong and the server is pushing the actor into the ground. 
The behavior occurs because the client treats the initial spawn struct differently than a position update. Years ago we used to brute force re-send position updates to the client even if they were on the other side of the zone and it "masked" the original problem because we sent the position always after …

[Fix] Fix NPC ghosting at safe coordinates

---

common/ruletypes.h
zone/client_packet.cpp
zone/doors.cpp

In certain zones, there are client controlled doors that are triggered or linked to other doors that the client will try to force into a desired state. It causes spam for GM's in various zones. This is even more so when many clients are in the zone all trying to force the state of the door simultaneously. 
It's fine to let the client control these doors, but the spam can be unruly and lead to believe that there is a deeper issue.
The solution for now is to distance check these doors for clients before trying to display the dev tools prompt and triggering quest door click events.
If not within distance, we still process `HandleClick` internally to let the client trigger the door back to the state it should be per normal

[Doors] Remove door dev tools spam on client controlled doors

---

common/ruletypes.h
zone/gm_commands/loc.cpp
zone/mob.h
zone/mob_movement_manager.cpp
zone/spells.cpp
zone/waypoints.cpp

Issue that has plagued servers for years now is that NPC's will Z correct and clip into the ceilings, causing all kinds of nasty pathing and aggro issues which are annoying for players and server operators
Two parts
* NPC's now calculate ground Z by targetting the true ground below them, not using their model and offset Z to perform the calculation. This would result in larger sized NPC's and models finding the ceiling to be closer than the ground below them and thus clipping into the ceiling
* When an NPC clips - which should happen far less frequently now. There is a mechanism to recover them when their previous Z is all of a sudden dramatically different from what it was previously and the NPC is still close to the player (Not taking Z into consideration), the NPC will gracefully …

[Pathing] Improvements to handling tight corridors pathing, clipping detection and recovery

---

common/eq_constants.h
zone/task_client_state.cpp
zone/task_manager.cpp

Implements alternate currency rewards. Spire already had implementation for this but we only handled Ebon / Radiant in source. This may not be specifically how live displays the reward but it gets the functionality in place until it is adjusted later. Right now we're only up until Dragons of Norrath content wise which does not care about alternate currencies so this is more focused to custom servers.
This currently utilizes the `reward_point_type` and `reward_points` fields to produce an item link of the alternate currency. It takes the place of what would otherwise be a simple item reward display in the task window.

[Tasks] Implement alternate currency rewards

---

zone/gm_commands/npcedit.cpp

Fix command crash with #npcedit weapon when second weapon not passed in
As observed in v22.2.0
http://spire.akkadius.com/dev/release/22.2.0?id=281

[Crash] Fix command crash with #npcedit weapon when second weapon not passed in

---

common/ruletypes.h
zone/client_mods.cpp

Added a rule for custom servers with low level caps to bypass hard coded level based haste caps and to default to "Character:HasteCap" and "Character:Hastev3Cap" for controlling haste cap behavior.

[Rule] Added rule to bypass level based haste caps.

---

utils/scripts/eqemu_server.pl

Windows has a tendenancy to be unreliable when manipulating the `Path` environment variable. Many folks even after an installation are still missing their path. That's even after our use of https://github.com/therootcompany/pathman within the installer.
This adds a file walker to find the MySQL binary automatically as a second measure if the path is not found. This is leading to updates not running for folks.
Long term solution will be to just embed database updates within the server binary and take it out of the script; we can also do some update checking to further reduce this issue

[DB Updates] Add Windows MySQL path auto detection for users where the path is not found

---

common/ruletypes.h
zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp
zone/tradeskills.cpp

…t bagtype as an alternate augmentation sealer. Use EVENT_COMBINE with UseAugmentContainer
Lua Example
```lua
function event_combine(e)
local bag_id = e.self:GetItemIDAt(e.container_slot)
if (bag_id == 1267) then
e.self:UseAugmentContainer(e.container_slot)
return 1;
end
end
```
Perl Example
```perl
sub EVENT_COMBINE {
my $bag_id = $client->GetItemIDAt($container_slot);
if ($bag_id == 1267) {
$client->UseAugmentContainer($container_slot); 
return 1; #We did a custom combine return 1
}
}
```

[Quest API] Add rule AlternateAugmentationSealer for using a different bagtype

---

common/database_conversions.cpp
common/rulesys.cpp
world/cli/database_version.cpp
world/world_boot.cpp

During bootup of a server, when bot tables exist but the rule is not enabled or set, there will be a query error that shows up each time the server is booted - making operators think that there is an issue. 
This fixes a regression in https://github.com/EQEmu/Server/pull/2593 that caused rules to not be able to be updated if they already exist. The table does not have a primary key (such as `id`) to bind to in order for the `UpdateOne` to work properly. 
This change replaces it with a raw update to restore functionality.
```
World |  QueryErr  | QueryDatabase [1064] [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rule_notes = 'Enable of disable bot functionality, default is false' WHERE ru...' at …
```

[Rules] Fix rule updates regression that affected bot booting checks

---

common/strings.cpp
common/strings.h
zone/mob_ai.cpp

This PR solves for a situation where NPC's clip through double doors because they have a trigger door and the current AI does not let them open doors that have a trigger door. This is usually because we don't want NPC's triggering for example a lever that elevates a platform.
We do want NPC's to be able to open double doors
When an NPC walks into a door that has a trigger door, compare the names without numbers to see if they are complimentary. In majority cases double doors are similarly named but have a different number suffix.
This automatically solves for the following zones that fall under a similar pattern (https://gist.github.com/Akkadius/cfbc826c193b33a1c4687fd0001fb915)
* gfaydark
* soltemple
* citymist
* hole
* paineel
* sleeper
* katta
* potactics
* potorment
* tutorialb
* …

[Doors] Have NPCs trigger double doors

---

zone/attack.cpp
zone/bonuses.cpp
zone/client.h
zone/mob.h
zone/tune.cpp

Heroic Strength wasn't applying to Shield AC, and Weapon damage hits for Bots, in addition this also lets Heroic Dex to apply to Archery + Throwing for them too.

[Bots] Add Additional HeroicStr modifiers.

---

zone/attack.cpp
zone/special_attacks.cpp
zone/tune.cpp

Allows Bots to benefit from HeroicAgi to their defense calculations.
Allows Bots to benefit from Heroic Dex for chance to Headshot or Assassinate

[Bots] Add Additional HeroicAgi/Dex Modifiers.

---

zone/attack.cpp

- CheckNumHitsRemaining() wasn't working when skill ID was `0` (1H Blunt).

[Bug Fix] Fix CheckNumHitsRemaining() with 1H Blunt

---

loginserver/client.cpp
ucs/clientlist.cpp
world/client.cpp
zone/client_packet.cpp

Adds the raw EQ opcode instead of `0x0000` when the opcode is `OP_Unknown`
We run the internal opcode through the patch translator and get the patch-specific opcode and when there's nothing that matches we simply get `0x0000` this at least gives us the protocol level opcode if we didn't find one through translators

[Logging] Add raw opcode when emu translated opcode is not found (OP_Unknown) via (C->S)

---

zone/effects.cpp

Allows ST_AreaClientOnly spells to land on Bots.
Allows MassGroupBuff spells to land on Bot Pets.
Also cleaned up instances where verbose conditionals were in use.

[Bots] Allow ST_AreaClientOnly spells to land on Bots

---

zone/attack.cpp

Potential (but unlikely) out of bounds memory access could be triggered in Mob::CommonDamage.

[Crash] Fix potential crash in Mob::CommonDamage 

---

zone/spells.cpp

Cleaned up uses of IsClient() that coincide with Bot/Merc usages

[Bots] Update Mob::ResistSpell to use client formula for Bots

---

zone/embparser.cpp

- Exports `$object` to `EVENT_CLICK_OBJECT` in Perl so you don't have to grab it from entity list.

[Quest API] Export $object to EVENT_CLICK_OBJECT in Perl

---

zone/embparser.cpp

- Exports `$door` to `EVENT_CLICKDOOR` in Perl so you don't have to grab it from entity list.

[Quest API] Export $door to EVENT_CLICKDOOR in Perl

---

zone/bot.cpp
zone/bot_command.cpp
zone/embparser.cpp
zone/inventory.cpp

- Exports `$item` to `EVENT_EQUIP_ITEM_CLIENT`, `EVENT_UNEQUIP_ITEM_CLIENT`, `EVENT_EQUIP_ITEM_BOT`, `EVENT_UNEQUIP_ITEM_BOT`, `EVENT_ITEM_CLICK_CLIENT`, and `EVENT_ITEM_CLICK_CAST_CLIENT`.

[Quest API] Export $item to Client/Bot Equip Events in Perl

---

zone/bot.cpp
zone/bot.h
zone/mob.h

Fixes a crash where bot_owner could be nullptr, detected with crash analysis http://spire.akkadius.com/dev/release/22.2.0?id=347
Cleaned up Bot Constructor & Deconstructors to not call virtual override methods (change to Final) for code smell purposes.

[Crash] Fix Bot Crash in Bot::Bot Constructor.

---

zone/bot.cpp

Bots were not checking if they had an Augment equipped that matches the loregroup of an augment being given to them in a piece of equipment.

[Bots] Add Lore Check for Augments.

---

zone/client_packet.cpp

- Optionally parses this event instead of always doing so.

[Quest API] (Performance) Check event exists before export and execute EVENT_CLICK_DOOR and EVENT_CLICK_OBJECT

---

zone/client_packet.cpp

- Optionally parses this event instead of always doing so.

[Quest API] (Performance) Check event exists before export and execute EVENT_POPUP_RESPONSE

---

zone/embparser.cpp
zone/mob.cpp

[Quest API] (Performance) Check event exists before export and execute EVENT_GROUP_CHANGE

---

zone/npc.cpp

[Quest API] (Performance) Check event exists before export and execute EVENT_DESPAWN and EVENT_DESPAWN_ZONE

---

zone/entity.cpp

- Optionally parses `EVENT_ENTER`, `EVENT_EXIT`, `EVENT_ENTER_AREA`, and `EVENT_LEAVE_AREA`.

[Quest API] (Performance) Check event exists before export and execute area events

---

zone/command.cpp

[Quest API] (Performance) Check event exists before export and execute EVENT_GM_COMMAND

---

zone/aa.cpp
zone/exp.cpp

[Quest API] (Performance) Check event EVENT_AA_BUY or EVENT_AA_GAIN exist before export and execute

---

zone/bonuses.cpp
zone/bot.cpp
zone/bot_command.cpp
zone/inventory.cpp

- Optionally parse `EVENT_SCALE_CALC`, `EVENT_ITEM_ENTER_ZONE`, `EVENT_UNEQUIP_ITEM_BOT`, `EVENT_EQUIP_ITEM_BOT`, `EVENT_EQUIP_ITEM`, `EVENT_UNEQUIP_ITEM`, `EVENT_EQUIP_ITEM_CLIENT`, and `EVENT_UNEQUIP_ITEM_CLIENT`

[Quest API] (Performance) Check equip or scale item events exist before export and execute

---

zone/client_packet.cpp

[Quest API] (Performance) Check event EVENT_TEST_BUFF exists before export and execute 

---

zone/npc.cpp

[Quest API] (Performance) Check event EVENT_TICK exists before export and execute 

---

zone/client_packet.cpp

[Quest API] (Performance) Check event EVENT_UNHANDLED_OPCODE exists before export and execute

---

zone/client_process.cpp

[Quest API] (Performance) Check event EVENT_RESPAWN exists before export and execute

---

zone/entity.cpp

[Quest API] (Performance) Check event EVENT_DUEL_LOSE or EVENT_DUEL_WIN exist before export and execute

---

zone/client.cpp
zone/mob.cpp

[Quest API] (Performance) Check event EVENT_ITEM_TICK or EVENT_WEAPON_PROC exist before export and execute

---

zone/attack.cpp

[Quest API] (Performance) Check event EVENT_SLAY exists before export and execute

---

zone/cheat_manager.cpp

- Parse this event optionally instead of always doing so.

[Quest API] (Performance) Check event EVENT_WARP exists before export and execute

---

zone/bot.cpp
zone/trading.cpp

[Quest API] (Performance) Check event EVENT_TRADE exists before export and execute

---

zone/cheat_manager.cpp
zone/mob_ai.cpp
zone/waypoints.cpp

[Quest API] (Performance) Check event EVENT_WAYPOINT_ARRIVE or EVENT_WAYPOINT_DEPART exist before export and execute

---

zone/mob.cpp

[Quest API] (Performance) Check event EVENT_HP exists before export and execute

---

zone/bot.cpp
zone/client.cpp
zone/mob_ai.cpp
zone/npc.cpp

[Quest API] (Performance) Check event EVENT_PAYLOAD or EVENT_SIGNAL exist before export and execute

---

zone/attack.cpp
zone/bot.cpp
zone/mob_ai.cpp

[Quest API] (Performance) Check event EVENT_AGGRO, EVENT_ATTACK, or EVENT_COMBAT exist before export and execute

---

zone/client_packet.cpp
zone/embparser.cpp
zone/lua_parser_events.cpp

- Export `$target` to `EVENT_CONSIDER`.
- Export `$corpse` to `EVENT_CONSIDER_CORPSE`.
- Export `e.other` to `event_consider`.
- Export `e.corpse` to `event_consider_corpse`.
- Allows operators to grab the target or corpse a player is considering.

[Quest API] Export targets to EVENT_CONSIDER and EVENT_CONSIDER_CORPSE

---

zone/client_packet.cpp
zone/zoning.cpp

[Quest API] (Performance) Check event EVENT_ENTER_ZONE or EVENT_ZONE exist before export and execute

---

zone/client.cpp
zone/questmgr.cpp

- Parse this event optionally instead of always doing so.

[Quest API] (Performance) Check event EVENT_TIMER exists before export and execute

---

zone/client_packet.cpp
zone/embparser.cpp
zone/tradeskills.cpp

- Exports `$item` and `$augment` to `EVENT_AUGMENT_INSERT_CLIENT` in Perl.
- Exports `$item` and `$augment` to `EVENT_AUGMENT_REMOVE_CLIENT` in Perl.
- Allows operators to use item and augment reference instead of just item IDs.

[Quest API] Export $item and $augment to augment events in Perl

---

zone/client_packet.cpp
zone/embparser.cpp

- Exports `$target` to `EVENT_INSPECT`.
- Allows operators to get information from target directly instead of using entity list.

[Quest API] Add $target export to EVENT_INSPECT in Perl

---

zone/embparser.cpp
zone/hate_list.cpp

- Exports `$hate_entity` to `EVENT_HATE_LIST`.
- Allows operators to see which mob is joining/leaving an NPC's hatelist.

[Quest API] Export $hate_entity to EVENT_HATE_LIST in Perl

---

zone/task_client_state.cpp
zone/tasks.cpp

- Optionally parses `EVENT_TASK_BEFORE_UPDATE`, `EVENT_TASK_ACCEPTED`, `EVENT_TASK_STAGE_COMPLETE`, `EVENT_TASK_UPDATE`, `EVENT_TASK_COMPLETE`, and `EVENT_TASK_FAIL`.

[Quest API] (Performance) Check task events exist before export and execute

---

zone/attack.cpp
zone/embparser.cpp

- Exports `$killed_npc` to `EVENT_NPC_SLAY` to Perl.
- Allows operators to use NPC reference in event instead of just NPC ID.

[Quest API] Export $killed_npc to EVENT_NPC_SLAY to Perl

---

zone/client_packet.cpp

Anytime we interrupt the client we need to "SendSpellBarEnable" to make sure it doesn't lock the client up. This allows you to stop item spell casts with scripts.

[Bug Fix] Fix for interrupting item casts to no longer lock the client if cast time of item greater than 0

---

zone/client_packet.cpp

- Optionally parses this event instead of always doing so.

[Quest API] (Performance) Check event EVENT_ENVIRONMENTAL_DAMAGE exists before export and execute

---

zone/client_packet.cpp
zone/client_process.cpp

[Quest API] (Performance) Check event EVENT_CONNECT or EVENT_DISCONNECT exist before export and execute

---

zone/client.cpp

[Quest API] (Performance) Check event EVENT_DISCOVER_ITEM exists before export and execute  

---

zone/attack.cpp

[Quest API] (Performance) Check event EVENT_KILLED_MERIT exists before export and execute

---

zone/attack.cpp
zone/bot.cpp

[Quest API] (Performance) Check event EVENT_DEATH, EVENT_DEATH_COMPLETE, or EVENT_DEATH_ZONE exist before export and execute

---

zone/client_packet.cpp
zone/spell_effects.cpp
zone/spells.cpp

- Optionally parses `EVENT_CAST`, `EVENT_CAST_BEGIN`, `EVENT_CAST_ON`, `EVENT_SPELL_EFFECT_NPC`, `EVENT_SPELL_EFFECT_CLIENT`, `EVENT_SPELL_EFFECT_BOT`, `EVENT_SPELL_EFFECT_BUFF_TIC_CLIENT`, `EVENT_SPELL_EFFECT_BUFF_TIC_NPC`, `EVENT_SPELL_EFFECT_BUFF_TIC_BOT`, `EVENT_SPELL_FADE`, and `EVENT_SPELL_EFFECT_TRANSLOCATE_COMPLETE`.

[Quest API] (Performance) Check spell or cast events exist before export and execute

---

zone/attack.cpp
zone/client.cpp

[Quest API] (Performance) Check event EVENT_LANGUAGE_SKILL_UP, EVENT_SKILL_UP, or EVENT_USE_SKILL exist before export and execute

---

zone/client_packet.cpp

- Optionally parses `EVENT_ALT_CURRENCY_MERCHANT_BUY`, `EVENT_ALT_CURRENCY_MERCHANT_SELL`, `EVENT_MERCHANT_BUY`, and `EVENT_MERCHANT_SELL`.

[Quest API] (Performance) Check merchant events exist before export and execute

---

zone/client_packet.cpp
zone/exp.cpp

- Optionally parses these events instead of always doing so.

[Quest API] (Performance) Check event exists before export and execute EVENT_LEVEL_UP and EVENT_LEVEL_DOWN

---

zone/corpse.cpp
zone/embparser.cpp

- Exports `$item` and `$corpse` to `EVENT_LOOT` in Perl.
- Exports `$item` and `$corpse` to `EVENT_LOOT_ZONE` in Perl.

[Quest API] Export $item and $corpse to EVENT_LOOT and EVENT_LOOT_ZONE in Perl

---

zone/bot.cpp
zone/embparser.cpp
zone/entity.cpp

- Exports `$spawned` to `EVENT_SPAWN_ZONE` in Perl.
- Allows operators to use the mob reference instead of having to grab it from entity list.

[Quest API] Export $spawned to EVENT_SPAWN_ZONE in Perl

---

zone/client_packet.cpp
zone/embparser.cpp
zone/entity.cpp
zone/forage.cpp

- Exports `$item` to `EVENT_FISH_SUCCESS` in Perl.
- Exports `$item` to `EVENT_FORAGE_SUCCESS` in Perl.

[Quest API] Export $item to Fishing and Forage Events in Perl

---

zone/embparser.cpp
zone/object.cpp

- Exports `$item` to `EVENT_PLAYER_PICKUP` in Perl so that you have access to the item itself.

[Quest API] Export $item to EVENT_PLAYER_PICKUP in Perl.

---

zone/attack.cpp

We weren't checking if attacker was null before trying to dereference it.

[Crash] Fix crash in Mob::CommonDamage when attacker was null

---

zone/embparser.cpp
zone/lua_parser.cpp
zone/lua_parser_events.cpp
zone/lua_parser_events.h
zone/mob.cpp

- Export `$target` to `EVENT_TARGET_CHANGE`.
- Export `e.other` to `event_target_change`.
- Allows operators to not have to grab bot, Client, or NPC's target in Perl with `GetTarget()`.
- Allows operators to not have to grab Client's target in Lua with `GetTarget()`.

[Quest API] Export target to EVENT_TARGET_CHANGE in Perl/Lua.

---

zone/spells.cpp

Limited checks were being performed in Mob::FindType to determine if returned spell_id was valid. obviously we should also try to determine why an invalid spell ID can be entered into Buffs_Struct in the first place. But I wanted a fix to resolve the crashing seeing on karana.

[Crash] Fix Crash in Mob::FindType

---

common/json/json_archive_single_line.h

Fixes a MSVC compilation bug via workaround. There are other references in the class that follow the alias properly but it doesn't in the constructor. Not worth trying to fix and statically inserted the value. This is a class I inserted for JSON minification for player events
```
16>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
16>Project not selected to build for this solution configuration 
========== Build: 11 succeeded, 0 failed, 13 up-to-date, 5 skipped ==========
```

[Windows] Fix MSVC compilation bug via workaround

---

utils/scripts/build/windows-build.ps1

Build errors are no longer squashed by the `should-release` check

[CI] Fix Windows stderr not bubbling properly

---

zone/client_packet.cpp

Fixes a regression where logic that was expected to happen when no quest was available is no longer able to execute. Moved the zero-state logic out of band from behind the `SpellHasQuestSub` gating
Regression caused by #2897

[Hotfix] Fix EVENT_SPELL_EFFECT_TRANSLOCATE_COMPLETE regression caused by  #2897

---

zone/object.cpp

Was investigating an issue around groundspawns and found that ROF2+ lore groundspawn pickups desync the client entirely.
This change properly sends the cursor deletion packet to the client, sends the groundspawn despawn to other clients to prevent expected state (desync) and then immediately respawns the groundspawn

[Fix] Fix issue where Lore groundspawn pickups will desync ROF2+

---

zone/spells.cpp

My changes in PR: https://github.com/EQEmu/Server/pull/2708 broke self only spell (if someone else is targetted),
This PR assures that self only spells always work.
Should resolve issue: https://github.com/EQEmu/Server/issues/2923
@Natedog2012

[Bug Fix] Self Only Spells now work again (BuffSpellRestrictions)

---

zone/client.cpp

- `const` didn't like the `std::any_cast`, also was passing `EQ::ItemData*` instead of `EQ::ItemInstance*`.
```pl
sub EVENT_DISCOVER_ITEM {
quest::debug("itemid " . $itemid);
quest::debug("item " . $item->GetName() . " (" . $item->GetID() . ")");
}
```
```
[02-14-2023 18:34:25] [Zone] [Crash] #9  0x000055ee20d68df4 in std::__throw_bad_any_cast () at /usr/include/c++/10/any:63
[02-14-2023 18:34:25] [Zone] [Crash] #10 0x000055ee20d6a277 in std::any_cast<EQ::ItemInstance*> (__any=std::any containing const EQ::ItemInstance * = {...}) at /usr/include/c++/10/any:475
```

[Bug Fix] Fix crash in EVENT_DISCOVER_ITEM

---

zone/perl_npc.cpp

Due to regression in the Perl bind work, this functions optional parameters did not get moved over. This broke shorthand usage of the API call.
Was requiring 3rd, 4th args - should no longer

[Quest] Fix SetSimpleRoamBox in Perl to have optional params again

---

zone/object.cpp
zone/object.h

Correct Z on spawn for groundspawns to keep them from floating high off the ground.
Titanium would correct this automatically client side, RoF2+ does not. We did this for tradeskills and it worked well
**Before**
**After**

[Groundspawns] Fix issue where groundspawns appear floating high off the ground

---

zone/lua_parser.cpp

This fixes a crash seen all over servers who have updated recently where dropping an item crashes the zone.
Example crash @ http://spire.akkadius.com/dev/release/22.3.0-dev?id=439

[Hotfix] Fix crash where dropped items crash Lua logic

---

zone/doors.h

This fixes a datatype issue preventing NPC's from being able to open doors because their AI logic checks for `door_param > 0` then don't open door. 
Because `-1` or sub-zero values are being loaded into an unsigned integer, this is overflowing those values into positives causing the discrepancy in behavior.
Tested and fixed, in Griegs End, all doors are `-1`
https://user-images.githubusercontent.com/3319450/219086126-1152ba0b-0146-4896-91b5-74c8c1099358.mp4
```
select count(*) as count, door_param from doors group by door_param having count > 10;
+-------+------------+
| count | door_param |
+-------+------------+
|    54 |         -3 |
|  7497 |         -1 |
|  8032 |          0 |
|   125 |          1 |
|    22 |          2 |
|    83 |          5 |
|   109 |          6 |
|    33 | …
```

[Doors] Fix issue where NPC's wouldn't open doors because door param overflow

---

zone/gm_commands/heromodel.cpp

Crash fix where invalid input to #heromodel would crash zone
Seen @ http://spire.akkadius.com/dev/release/22.3.0?id=510

[Crash] Crash fix where invalid input to #heromodel would crash zone

---

zone/inventory.cpp

Should wait to null out invalid_drop until after it is used in log message.

[Crash] Fix crash issue with dropping items and order of operations

---

zone/aa.cpp
zone/attack.cpp
zone/bonuses.cpp
zone/bot.cpp
zone/bot_database.cpp
zone/client.cpp
zone/client_packet.cpp
zone/client_process.cpp
zone/merc.cpp
zone/mob.cpp
zone/pets.cpp
zone/spell_effects.cpp
zone/spells.cpp
zone/zonedb.cpp

**What**
This PR aims to reduce issues where an invalid Spell ID is being passed, by replacing checks that were only comparing if the spell id was SPELL_UNKNOWN
**Why**
as noticed in numerous Crash analysis:
http://spire.akkadius.com/dev/release/22.3.0?id=492
http://spire.akkadius.com/dev/release/22.3.1-dev?id=393
http://spire.akkadius.com/dev/release/22.3.1-dev?id=392hnj

[Bug Fix] Replace uses of SPELL_UNKNOWN with IsValidSpell()

---

zone/string_ids.h
zone/tradeskills.cpp

We previously were not checking if the results of a combine would cause a Lore Conflict, and resulting items would be eaten.
Message Client receives now, when there is a Lore Conflict, and preventing the combine from occurring.
Added Item Links 
(I have no idea what is with the formatting on string_ids.h everything I do seems to make it worse, but it looks fine in my IDE.

[Tradeskills] Check if Combine would result in Lore Conflict.

---

common/events/player_event_logs.cpp

Turn off KILLED_NPC (trash) off by default. 
After running this on PEQ for a week it is by far the most spammy of events producing almost no value currently since `KILLED_NAMED_NPC` and `KILLED_RAID_NPC` are also enabled and those are more notable events to record.
At current rate after almost a week, we have 300MB of events
```
select event_type_id, event_type_name, count(*) as count from player_event_logs group by event_type_id order by count desc;
+---------------+--------------------+--------+
| event_type_id | event_type_name    | count  |
+---------------+--------------------+--------+
|            44 | Killed NPC         | 709472 |
|            46 | Killed Raid NPC    | 160395 |
|             2 | Zoning             |  51735 |
|             9 | Item Destroy       |  35199 |
| …
```

[Player Events] Turn off KILLED_NPC (trash) off by default

---

common/database_instances.cpp

Fix issue with AssignRaidToInstance that was using the groups repository instead of raid

[Fix] Issue with AssignRaidToInstance that was using the groups repository instead of raid

---

common/events/player_event_logs.cpp

Fix rare out of bound issue when loading event types when the database has more events stored than what is defined locally

[Player Events] Fix rare out of bound issue when loading event types

---

CHANGELOG.md
package.json

* Set Taunt to enabled for SK/Paladin Bots by Default. ([#2941](https://github.com/EQEmu/Server/pull/2941)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-17
* Fix NPC targetting dev tools display window ([#2943](https://github.com/EQEmu/Server/pull/2943)) ([Akkadius](https://github.com/Akkadius)) 2023-02-17
* Issue with AssignRaidToInstance that was using the groups repository instead of raid ([#2947](https://github.com/EQEmu/Server/pull/2947)) ([Akkadius](https://github.com/Akkadius)) 2023-02-17
* Missing comma in schema list breaking dumps  ([Akkadius](https://github.com/Akkadius)) 2023-02-17
* Fix issue with item instances not being validated properly before accessing causing crashes on handin ([#2945](https://github.com/EQEmu/Server/pull/2945)) …

[Release] 22.4.1

---

zone/tradeskills.cpp

Will skip Lore Conflict check where a loregroup > 0 is used. Will want to eventually implement a better solution when I have time that doesn't completely ignore the loregroup in these scenarios but instead does checks based on stacks, and if item is part of the combine.

[Tradeskills] Fix regression caused by #2932

---

zone/entity.cpp
zone/forage.cpp

Remove noisy raid/group/forage errors
Since we are bubbling `stderr` properly in our `Error` category, errors have become more noticeable. For example in the Windows Perl launcher, `stdout` is squashed, but `stderr` still makes it through
I'm sure there are more errors that are noisy but these ones at least produce no value and are not real errors, they are more debugging.
Reported by Tossica on Discord

[Logging] Remove noisy raid/group/forage errors

---

loginserver/main.cpp
ucs/ucs.cpp

This adds MySQL keepalives to both UCS and Loginserver to MySQL. Zone and World already have them and have had them for a long time.
This hasn't posed any issues but recently @noudess reported an issue with his MySQL 8 instance and it appears MySQL 8 is going to be a bit more sensitive.
This PR keeps the connection fresh by issuing pings every 10 seconds
Noudess "This message always comes out on 1st login attempt after an account has been logged out for long periods of time.  Can someone help me find where this is in the code?  I searched for some of this text and cannot find it.  From just the error message, it feels like some previous logout was missed and a new attempt to login triggers the error.  After 1 failure to login, all works again as normal.
Message:
[02-16-2023 10:34:38] …

[MySQL] Add keepalives to UCS and Loginserver

---

common/eqemu_logsys.h
common/eqemu_logsys_log_aliases.h
common/events/player_event_logs.cpp

Add logging category to hold processing batch logs
Reported by Perc in Discord
These batch processing messages on a populated server can get pretty noisy since they are flushing every 5 seconds. They are useful and we don't want to completely get rid of them but we can put them behind a new `PlayerEvents` category that is disabled by default

[Player Events] Add logging category to hold processing batch logs

---

CHANGELOG.md
common/version.h
package.json

* Added optional SQL 2023_02_17_fix_sseru_mischief_doors.sql to fix sseru/mischief doors ([#2955](https://github.com/EQEmu/Server/pull/2955)) ([Akkadius](https://github.com/Akkadius)) 2023-02-18
* Remove noisy raid/group/forage errors ([#2952](https://github.com/EQEmu/Server/pull/2952)) ([Akkadius](https://github.com/Akkadius)) 2023-02-18
* Add keepalives to UCS and Loginserver ([#2953](https://github.com/EQEmu/Server/pull/2953)) ([Akkadius](https://github.com/Akkadius)) 2023-02-18
* Add logging category to hold processing batch logs ([#2954](https://github.com/EQEmu/Server/pull/2954)) ([Akkadius](https://github.com/Akkadius)) 2023-02-18
* Fix regression caused by #2932 ([#2956](https://github.com/EQEmu/Server/pull/2956)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-18

[Release] 22.4.2

---

zone/bot_database.cpp

Change to Replace instead of Insert to reduce scenarios where the timer is expired, and the old entry hasn't been cleaned up yet.
Client Timers use a "Replace" Statement to store Timers as well.

[Bot] Change SaveTimers to Replace instead of Insert.

---

world/eqemu_api_world_data_service.cpp

Add world handlers for certain opcodes. Because world is the one sending the packets instead of zone originating them, we aren't hitting the world opcode handlers that would otherwise reload rules/logs. This adds handling for it

[Reload API] Add world handlers for certain opcodes

---

common/events/player_event_logs.cpp
common/events/player_events.h
zone/inventory.cpp

Created new player event `ITEM_CREATION` that is invoked during SummonItem. It is not a catch-all and events like this will likely need to be refined over time.

[Player Events] Create new event ITEM_CREATION

---

zone/bot.cpp

While ^enforcespellsettings was enabled, new spells learned wouldn't be listed under ^spells until you toggled off ^enforcespellsettings. this fixes the behavior by loading the correct spell struct to ^spells while ^enforcespellsettings is enabled.

[Bots] Fix output of ^spells while ^Enforcespellsettings is enabled

---

common/events/player_event_logs.cpp
common/ruletypes.h

Fix world crash in player event processing where batch MySQL insertions when the bulk insert query exceeds `max_allowed_packet`
"When a MySQL client or the mysqld server receives a packet bigger than max_allowed_packet bytes, it issues an ER_NET_PACKET_TOO_LARGE error and closes the connection."
This forces batch insertion of 10k entries if the queue reaches that size before it has had a chance to flush
I've only observed this on larger servers such as Lazarus, PEQ, EZ where the event generation would produce enough of a batch insertion size to trigger this event within a 5 second flush interval.
- http://spire.akkadius.com/dev/release/22.3.0-dev?id=433
- http://spire.akkadius.com/dev/release/22.4.0-dev?id=635

[Crash] Fix world crash in player event processing

---

zone/perl_npc.cpp

- These overloads were non-functional as they didn't have a method to actually fall back to.

[Quest API] Fix Perl SetSimpleRoamBox Overloads

---

zone/perl_client.cpp

- Fixes an issue with Guild Lobby quests not properly using `client` as first parameter in `mob->SignalClient(client, signal_id)` method.

[Quest API] Add client->SignalClient() overload to Perl

---

zone/bot.cpp
zone/bot.h
zone/gm_commands/gearup.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp

HasBotItem() should have originally returned the slot_id of the item_id equipped. this would make it coincide with the client method of  $client->inventory()->HasItem() returns the slot_id of the item_id equipped.
Bots already have a boolean check if an item is equipped by ID $bot->HasItemEquippedByID (uint32 item_id);

[Bots] HasBotItem to return slot_id instead of bool.

---

zone/mob.cpp
zone/mob.h

On live, if an NPC summons a client pet that is on guard, the pet returns to its guard position.
On eqemu, the pet's guard position is changed to the summon location, which is incorrect.
This PR fixes this case.

[Pets] Client Pet summoned by NPC should not change guard location.

---

world/zoneserver.cpp

- #oocmute was not functioning as the packet wasn't being handled by the server.

[Bug Fix] Fix OOCMute not functioning

---

zone/client_packet.cpp

- These items weren't showing as MIR due to this condition being typo'd in https://github.com/EQEmu/Server/pull/1611.

[Bug Fix] Fix MIR LDoN Theme Items on LDoN Merchants

---

common/dbcore.cpp
common/dbcore.h
common/events/player_event_logs.cpp
common/repositories/base/base_player_event_logs_repository.h

This addresses and issue that has been manifesting in world deadlocks lately influenced by player events.
This issue has been seen by multiple servers (Lazarus, PEQ, EZ, KMRA etc.)
This has been running on EZ for 2 days, confirmed no deadlocks, other folks have ran the same changes without issues.
Other notable things
* This uses native MySQL string escaping instead of the one we rolled on our own that is used all over the source. The MySQL client library native function is going to be more con-formative to character sets configured on the database instance and give the best escaping overall
* The mutex in player events was not locking before reading if the queue was empty, this can lead to racey memory access, deadlocks and memory corruption

[Database] Address deadlock in player events

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->IsAutoFireEnabled()`.
- Add `client:IsAutoFireEnabled()`.
- Allows operators to check if a client has auto fire enabled.

[Quest API] Add IsAutoFireEnabled() to Perl/Lua

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->IsAutoAttackEnabled()`.
- Add `client:IsAutoAttackEnabled()`.
- Allows operators to check if a client has auto attack enabled.

[Quest API] Add IsAutoAttackEnabled() to Perl/Lua

---

zone/bot.cpp

**What:** This PR aims to ensure the Bots Group is in a valid state when being joined. these checks are already being performed on Bot::LoadAndSpawnAllZonedBots, but not all scenarios are covered such as Bot group autospawn functionality, and regular invites.
**Why:**
Numerous crashes are being seen caused likely by dangling Group member pointers. This can be seen in the following crashes where we check if the pointer is nullptr, pointer is not null, and yet we still crash when trying to call a member function:
http://spire.akkadius.com/dev/release/22.4.2?id=691
http://spire.akkadius.com/dev/release/22.4.2?id=690
http://spire.akkadius.com/dev/release/22.4.2?id=709

[Bots] Verify Group Integrity during Bot::AddBotToGroup

---

common/features.h
zone/client_packet.cpp

Notes:
Previously, the server-side reuse of Mend was set to 290 seconds rather than 360 seconds (6 minutes).
Mend was not accepting reduction timers from potential items, buffs or AAs (Hastened Mend).
Mend was outputting duplicate success messages on critical mends, it will now only output a regular Mend message upon success (You mend your wounds and heal some damage) or the critical message upon critical success (You magically mend your wounds and heal considerable damage), not both.

[Bug Fix] Correct Mend reuse time and add reduction support.

---

zone/bot_database.cpp

Added Checks to initialize all buff slots (mimics Client LoadBuffs method)
Cleaned up all atoi conversions, change to Strings::ToInt and atoul where applicable.

[Bots] Cleanup BotDatabase::LoadBuffs

---

zone/client.h
zone/tradeskills.cpp

This fixes a regression issue where components of the combine could be lore, causing the combine to fail on the lore check if the components were returned on success, failure, or salvage.

[Tradeskills] Fix for Lore Conflict

---

zone/questmgr.cpp

Fix EVENT_TIMER crash when entity is no longer available
Checks pointer before trying to access
Crash originally reported by @noudess 
```
[02-23-2023 13:39:25] [Zone] [Crash] #0  0x00007f3ed0f2149f in __GI___wait4 (pid=32889, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
[02-23-2023 13:39:25] [Zone] [Crash] #1  0x0000559269973d0b in print_trace () at /home/felinicity/server-013023/Server/common/crash.cpp:284
[02-23-2023 13:39:25] [Zone] [Crash] #2  <signal handler called>
[02-23-2023 13:39:25] [Zone] [Crash] #3  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
[02-23-2023 13:39:25] [Zone] [Crash] #4  0x00007f3ed14a55cb in Perl_sv_setpv () from /lib/x86_64-linux-gnu/libperl.so.5.34
[02-23-2023 13:39:25] [Zone] [Crash] #5  0x00005592692672b7 …
```

[Quest API] Fix EVENT_TIMER crash when entity is no longer available

---

zone/doors.cpp
zone/doors.h

@noudess reported his zone was spamming
```
Zone |    Info    | operator() New client from [192.168.0.5:62944] -- [paineel] (Paineel) inst_id [0]
Zone |    Info    | GetZoneID Failed to get zone_name [none] -- [paineel] (Paineel) inst_id [0]
```
This sources from door logic when opening a door and the code is not properly checking for "none". The code makes attempts to do so but my guess is some sort of case sensitivity / collation is occurring with the database.
This PR attempts to clean some of that up and make the code a bit more readable.
This PR also needs to be tested to ensure no regressions

[Doors] Fix doors triggering invalid zone fetches of dest_zone of "none"

---

zone/mob.cpp

Beneficial Procs that were of Target Type ST_TargetsTarget were attempting to be cast on the Players Target, and not the Player's Targets Target, as we were passing the spells target as **this** for all Beneficial proc spells.
This changes the behavior to correctly pass the spell target as the players current target, which will result in the correct Target being used.

[Bug Fix] Fix Beneficial Target of Target procs

---

zone/bot.cpp
zone/mob_ai.cpp
zone/npc.cpp
zone/npc.h
zone/waypoints.cpp

This improves roambox logic to have a little bit more intelligence and in many ways feel more natural
* Roamboxes will make up to 10 attempts to find a valid x,y,z within the box before waiting for next interval
* Roamboxes will now use LOS checks to determine a destination with pillar search
* Roamboxes will do a "pillar search" for valid line of sight to the requested x,y to try to attempt to path. This means, instead of just doing line of sight at the current Z of the NPC, it will attempt (current_z - 250) and (current_z + 250) with LOS checks. This solves for the scenario where when in a pit and you try to LOS against the best Z of a X/Y just over a slope, the NPC will not be able to see it, however if you add 250 degrees to it, the NPC should be able to see above that point. This …

[Pathing] Improve roambox logic

---

common/dbcore.cpp
common/events/player_event_logs.cpp
queryserv/queryserv.cpp
queryserv/worldserver.cpp
ucs/ucs.cpp
world/main.cpp

* Implement processing in QS (Apparently I had forgotten to hook this up)
* Remove player event processor from its own thread and bring into main thread
* Revert dbcore mutex changes for now to original mutex usage
Proof given `Logging:PlayerEventsQSProcess` is enabled

[Player Events] Add QS processing, mutex tweaks

---

client_files/export/main.cpp
client_files/import/main.cpp
common/dbcore.cpp
common/dbcore.h
shared_memory/main.cpp
world/cli/database_concurrency.cpp
world/main.cpp
world/world_boot.cpp
world/world_boot.h
world/world_server_cli.cpp
world/world_server_cli.h
zone/main.cpp

The MYSQL structure in the MySQL C api is not copy aware. This isn't enforced because, well, C doesn't enforce anything really. 
See: [MySQL Structures](https://dev.mysql.com/doc/c-api/8.0/en/c-api-data-structures.html)
This changes the copy of an existing connection to instead create a second backup connection with the same data as what is being copied.  This does introduce another connection into the mix which are a limited resource but given the potential seriousness of the bug in question it seems like a fair tradeoff for now.  
Long term we can rewrite the dbcore class to use a underlying pointer instead of a pinned in place variable.

[Bug Fix] Fix for undefined MySQL library behavior.

---

zone/mob_ai.cpp
zone/npc.cpp
zone/waypoints.cpp

* Improve z-clipping logic, use Z offset calculations
* Z-clipping reset no longer resets NPC "guard" location (spawn point)
* Wurms (Race 158) as a fixed size model are now statically set to size 15 on spawn to make up for data issues
* Adjust Spectral Iksar (Race 147) offset causing an edge case where it would clip into the ground just below the surface mesh in Trakanon 
Below the NPC does not return to spawn point after z-clip correction, this has been fixed.
https://user-images.githubusercontent.com/3319450/221330680-0506a994-a5ad-4025-9b66-d66ad6588a8d.mp4
Wurm is falsely detected as under or below player simply because the size of the NPC is not taken into consideration in relation to the player. Both player and NPC offsets are taken into account and this no longer occurs.
NPC's …

[Pathing] More z-clip improvements, Wurm and Spectral Iksar race adjustments

---

CHANGELOG.md
common/version.h
package.json

* Add Caster Range Command, and IsValidSpellRange Checks ([#2942](https://github.com/EQEmu/Server/pull/2942)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-23
* Cleanup BotDatabase::LoadBuffs ([#2981](https://github.com/EQEmu/Server/pull/2981)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-24
* Verify Bots Group Integrity on join ([#2980](https://github.com/EQEmu/Server/pull/2980)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-23
* Cleanup #peekinv Command ([#2969](https://github.com/EQEmu/Server/pull/2969)) ([Kinglykrab](https://github.com/Kinglykrab)) 2023-02-23
* Fix doors triggering invalid zone fetches of dest_zone of "none" ([#2985](https://github.com/EQEmu/Server/pull/2985)) ([Akkadius](https://github.com/Akkadius)) 2023-02-24
* Adjust database manifest to include .sql …

[Release] 24.4.4

---

zone/client.h

[Cleanup] Remove GetCombinedAC_TEST() from client.h

---

zone/client.h

[Cleanup] Remove DumpPacketProfile() from client.h

---

zone/client.h

[Cleanup] Remove GetDamageMultiplier() from client.h

---

zone/bot.cpp
zone/botspellsai.cpp

Cleaned up Logic in AI_IdleCastCheck Logic to not be as wasteful (Melee classes don't heal others, either do pure int casters, cept pets, etc)
Also added bot_group->VerifyGroup(); to attempt to help with stability.
Bot::AI_IdleCastCheck will eventually need to be refactored when I have time, should be split off into additional methods.

[Bots] Cleanup AI_IdleCastCheck Logic

---

zone/tradeskills.cpp

This resolves issues seen with BiC quest line combines, where the item is returned on success, fail, salvage. However the recipe entries for each different return type are split between multiple rows. 
My previous PR was meant to fix the above, but was incorrect logic. my testing failed to find this, as the checks worked correctly on the first component if it was lore, not later components.
The correct implementation is to loop through all components first before performing any lore checks, allowing us to exclude any components that are lore, but have a separate row for return on success, fail, salvage.
Verified all previous use cases work as expected as well, meaning:
- Combine uses a lore container, which is returned.
- Combines that have a Lore Group component (Epic Lore Group, or …

[Bug Fix] Fix for Lore Components where component is returned.

---

zone/tradeskills.cpp

tre_update_item_inst was only being validated in the bool prior, this was causing a crash when trying to dereference tre_update_item_inst.
Confirmed with Cleric Epic 1.5 combine.

[Crash] Fix crash in CheckTradeskillLoreConflict

---

zone/zonedb.cpp

If a Server Operator attempts to cleanup disciplines after they are learned from the database, they may encounter issues after the fact when players try to learn new disciplines due to how we were loading data into the Disciplines_Struct.
We were loading data in with no accounting for Slot_id, so when learning a new Discipline if an older row was deleted the Struct would not match up with the correct Slot_id numbers, causing players to overwrite disciplines they have already learned.
This allows a null entry to be added to the Disciplines_Struct.disciplines.value, so when we learn a new discipline it'll find the null and insert to the slot that is free, and not try to insert at the end.

[Bug Fix] Fix for Discipline Loading from Database causing issues with slot_ids

---

zone/client.cpp
zone/client_packet.cpp

Fix issue where quest saylink responses would occur before the NPC's response

[Fix] Fix issue where quest saylink responses would occur before the NPC's response

---

zone/bot.cpp

Bots were previously not receiving increases to HP Regen, Base HP, Base Mana from heroic stats.

[Bots] Add additional Heroic Sta/Wis/Int bonuses for Bots.

---

zone/questmgr.h

- Sets default speed to `0` which makes the animations run at normal speed instead of `1` that makes them run is slow motion.

[Bug Fix] Fix DoAnim quest method default speed

---

zone/mob.cpp
zone/questmgr.cpp
zone/questmgr.h

Entries in the QTimerList for clients used mob as the key when deciding if a timer's client was in the zone and was the correct client.
If you log in character a, start a timer, log out character a and log in character b  (in the same zone from the same instance of client) character b inherits and runs character a's timer.
This PR adds charid as a secondary key for client timers.
Please note that the existing code cleans up timers when a client is no longer in zone.  My patch does the exact same thing if a clients character ID has changed.  I noticed that a previous patch (that I am not running yet) also checks to make sure that the client has an EVENT_TIMER subroutine.  That change is good, but it leaves the client timer in the QTimerList forever, until the Client leaves the zone.  So …

[Bug Fix] Fix an issue where EVENT_TIMER timers would not be cleaned up after zone

---

ucs/chatchannel.cpp
ucs/clientlist.cpp
ucs/database.cpp
ucs/database.h

Removes trailing commas/spaces from UCS log messages when no saved channels exist during load.

[Bug Fix] Fix log messages when players join channel

---

zone/npc.cpp
zone/npc.h

This fixes a longstanding bug where the UI state of the pet taunt button has little to no connection with the command state of the pet.

[Bug Fix] Ensure synchronization of pet taunt state with UI

---

zone/client_packet.cpp

- Before now, alternate currency and LDoN adventure merchants did not trigger item discovery.

[Bug Fix] Fix Discovered Items with Alternate Currency and LDoN Adventure Merchants

---

common/ruletypes.h
zone/corpse.cpp

Upon death if a character has coin on cursor it will not transfer to the corpse, rather stay on cursor after death. This fix will remove all coin on cursor and save it to the corpse.

[Bug Fix] Cursor Coin Upon Death

---

common/termcolor/rang.hpp

Add `IS_TTY` to force terminal coloring output
This is used to enable outside processes to force terminal output to be colored. For example, Spire Admin panel has a pre-flight checks that is ran to ensure the server is in working order and has no errors. The output gets sent as ANSI and parsed from ANSI to HTML to give the colored resemblance of what you would expect to see in the console.

[Console] Add IS_TTY to force terminal coloring output

---

common/repositories/base/base_npc_scale_global_base_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_02_28_npc_scaling_zone_list_version_list.sql
zone/npc_scale_manager.cpp
zone/zone.cpp

- Allows `|` separated zone IDs and instance versions within the scaling data.
- Loads scaling data on zone bootup as well, without needing to repop for it to initialize.

[Scaling] Add support for pipe-separated zone IDs and versions

---

common/ruletypes.h
zone/spells.cpp

Notes:
This adds the rule Spells:ResurrectionEffectsBlock that will prevent anything from overwriting Resurrection Sickness Effects. Currently they are able to be overwritten by certain spells.
Default state: Disabled/False.

[Rules] Add ResurrectionEffectsBlock

---

zone/bot_command.cpp

Fixing an issue with bot portal/circle lists not sending the correct command when the player interacts. The bot command char, `^`, was not being properly formatted to a string.

[Bots] Place BOT_COMMAND_CHAR inside messages

---

common/strings.cpp

This PR augments https://github.com/EQEmu/Server/pull/2873 where try/catch mechanisms are added to the actual string conversion functions for the sake of safety.
It combines performance improvements from the previous PR in conjunction with this current change by utilizing the fast functions for validating `IsNumber` and `IsFloat` early before passing the string into the converter.
We just ran into a situation where character loading produced `__throw_out_of_range` for a value (42949672950) fits outside normal integer range. While we should be responsible programmers and use proper types for loading data, we also should still utilize guard rails where they make sense and don't provide massive penalties otherwise. In this case, the penalty is extremely negligible and yields large safety …

[Strings] Add exception handling to converters themselves

---

zone/client.cpp

[Cleanup] Remove unused command variables in client.cpp

---

zone/client.cpp
zone/client.h

[Cleanup] Remove unused player update variables in client.cpp/client.h

---

zone/client.cpp
zone/client.h

[Cleanup] Remove unused client queued work variable in client.cpp/client.h

---

zone/bot.h
zone/bot_structs.h

[Cleanup] Remove unused BotAA struct in bot_structs.h

---

zone/bot_command.h

[Cleanup] Remove unused ^evacuate and ^succor subcommands from bot_command.h

---

zone/gm_commands/resetaa.cpp
zone/gm_commands/resetaa_timer.cpp

[Commands] Cleanup #resetaa and #resetaa_timer

---

zone/command.cpp
zone/gm_commands/level.cpp

- Defaults target to GM so that you don't have to target yourself to use the command.

[Commands] Cleanup #level Command

---

zone/command.cpp
zone/gm_commands/hideme.cpp

[Commands] Cleanup #hideme Command

---

zone/command.cpp
zone/gm_commands/haste.cpp

- No longer requires you to re-equip your weapon for the haste to take effect.
- Can now use on targeted client if you have `#gm on` enabled.

[Commands] Cleanup #haste Command

---

zone/client.cpp
zone/gm_commands/ginfo.cpp
zone/guild_mgr.cpp

- Due to changing the popups to use strings, these show as squares, instead of the proper character.

[Fix] Checkmarks and X characters in popup messages

---

common/repositories/base/base_npc_scale_global_base_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_03_04_npc_scale_global_base_heroic_strikethrough.sql
zone/npc_scale_manager.cpp
zone/npc_scale_manager.h

- Adds Heroic Strikethrough support to NPC scaling.
- Cleans up `std::stoul` to use `Strings::ToUnsignedInt` since recent changes.
- Sets default values to sane values and removes support for `NULL` values.

[Feature] Add Heroic Strikethrough to NPC Scaling

---

zone/spells.cpp

Notes:
https://user-images.githubusercontent.com/53322305/223123434-2bcba221-d13f-4320-9995-e6a3619ccb84.mp4
Bots currently do not do a mana check until the spell cast has already been started which results in an interrupt immediately after. If it is the last spell for a bot to cast, it tends to result in interrupt spam until the bot has enough mana. This will block the interrupt spam if the spell is invalid.

[Bots] Prevent interrupt spam when OOM

---

common/repositories/base/base_npc_scale_global_base_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_02_28_npc_scaling_zone_list_version_list.sql
utils/sql/git/required/2023_03_08_npc_scale_global_base_avoidance.sql
zone/attack.cpp
zone/mob.h
zone/npc_scale_manager.cpp
zone/npc_scale_manager.h

* Adds Avoidance support to NPC scaling.
* Adds HP Regen Per Second support to NPC scaling.
* Set HP_Regen and HP to int64 to align with npc_types.
Fixed issue with SQL from #3015 trying to add a default on a Text column

[Feature] Add Avoidance and HP Regen Per Second too NPC Scaling.

---

zone/raids.cpp

Fixes Bug where Raid invites would never move a client to groupless state in the raid from the client perspective, Database however would show accurate group ID. 
```groupNum``` was incorrectly declared as an int prior to change in #2873, so it was incorrectly set to use Strings::ToInt.
This was causing all sorts of undefined behavior when inviting to a raid:
* clients showing as in a raid group in the raid window, but not in their party.
* Ability to accidentally invite a 7th player to Group 0, which would cause a client crash, and failure to log back into the game world.

[HotFix] Fix Raid Invites causing client desync issues

---

zone/mob_info.cpp

Adds NPC Stat Heroic Strikethrough  and HP Regen Per Second to the GM Entity Info Window.

[Feature] Add Heroic Strikethrough & HP Regen Per Second to GM Entity Info

---

zone/effects.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->GetActDoTDamage(spell_id, value, target)`.
- Add `$mob->GetActDoTDamage(spell_id, value, target, from_buff_tic)`.
- Add `$mob->GetActReflectedSpellDamage(spell_id, value, effectiveness)`.
- Add `$mob->GetActSpellDamage(spell_id, value, target)`.
- Add `$mob->GetActSpellHealing(spell_id, value, target)`.
- Add `$mob->GetActSpellHealing(spell_id, value, target, from_buff_tic)`.
- Add `mob:GetActDoTDamage(spell_id, value, target)`.
- Add `mob:GetActDoTDamage(spell_id, value, target, from_buff_tic)`.
- Add `mob:GetActReflectedSpellDamage(spell_id, value, effectiveness)`.
- Add `mob:GetActSpellCasttime(spell_id, cast_time)`.
- Add `mob:GetActSpellCost(spell_id, cost)`.
- Add `mob:GetActSpellDamage(spell_id, value)`.
- Add `mob:GetActSpellDamage(spell_id, value, target)`.
- Add …

[Quest API] Add Spell GetActX methods to Perl/Lua

---

zone/lua_mob.cpp
zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->SendIllusion(race, gender, texture, helmtexture, face, hairstyle, haircolor, beard, beardcolor, drakkin_heritage, drakkin_tattoo, drakkin_details, size, target)`.
- Add `$mob->SendIllusionPacket(illusion_table_ref)`.
- Add `target` to `mob:SendIllusion(table)`.
- Cleanup data types.
- Adds overloads with a specific client capability and a hash capability in Perl.
```pl
my %illusion_data = (
"race" => 522,
"gender" => 0,
"texture" => 3,
"size" => 20
);
$client->SendIllusionPacket(\%illusion_data);
}
}
```

[Quest API] Add SendIllusion overloads/parameters to Perl/Lua

---

zone/mob.h

[Cleanup] Remove DoBuffWearOffEffect() from mob.h

---

zone/mob.h

[Cleanup] Remove last_max_hp from mob.h

---

zone/mob.h

[Cleanup] Remove casting_spell_type from mob.h

---

zone/mob.h
zone/spells.cpp

[Cleanup] Remove IsAffectedByBuff()

---

zone/bot.h

[Cleanup] remove _botOrderAttack from bot.h

---

zone/bot.h

[Cleanup] Remove _botRole from bot.h

---

zone/bot.cpp
zone/bot.h

[Cleanup] Remove _baseBotStance from bot.h

---

zone/doors.h

[Cleanup] Remove GetDestination() from doors.h

---

zone/npc.cpp
zone/npc.h

[Cleanup] Remove FlushLootStats() from npc.h

---

zone/oriented_bounding_box.h

[Cleanup] Remove GetTransformation() and GetInvertedTransformation() from oriented_bounding_box.h

---

world/launcher_link.h

[Cleanup] Remove CountZones() from launcher_link.h

---

world/wguild_mgr.h

[Cleanup] Remove MakeGuildMembers() from wguild_mgr.h

---

zone/botspellsai.cpp

Regression caused by refactoring in #2782, could cause specific Bot spells to not cast, this was mostly impacting bards.

[Bug Fix] Fix Bard Bot Casting

---

common/ruletypes.h
zone/task_client_state.cpp

When rewarding exp through the task system using percentage based rewards were being reduced by the optional rule "AddLevelBasedExp" this adds a rule to let percentage based xp rewards to ignore "LevelBasedEXPMods"

[Rule] Add Task System Rule ExpRewardsIgnoreLevelBasedEXPMods

---

queryserv/database.h

[Cleanup] Remove DBInitVars() and HandleMysqlError() from queryserv/database.h

---

eqlaunch/zone_launch.cpp
eqlaunch/zone_launch.h

[Cleanup] Remove GetStartCount() and InitStartTimer() from zone_launch.cpp and zone_launch.h

---

zone/bot.cpp
zone/groups.cpp
zone/raids.cpp

This fixes a crash where Group members were not being cleaned out prior to Entity bot_list was cleared out, causing conflicts with dangling pointers in Group Members.
As noticed here http://spire.akkadius.com/dev/release/22.4.5-dev?id=1697

[Crash] Fixes Crash when Zoning with XTarget when Bots are in group.

---

common/ruletypes.h
zone/bonuses.cpp
zone/bot.cpp
zone/merc.cpp
zone/special_attacks.cpp

- Allows `Character:ItemExtraDmgCap` to be disabled if set to `-1` or lower.
- Allows operators to set `Character:ItemExtraSkillDamageCalcAsPercent` to `true` to allow skill damage for Frenzy, Backstab, Bash, Slam, Kick, and all Monk attacks to scale with a percentage based on `extradmgamt` values from items and spells.

[Feature] Add Item Extra Skill Damage Percent Modifier

---

common/ruletypes.h
zone/effects.cpp

Allows you to set Spell Casting Skills to Item Field "ExtraDmgSkill" or SPA 220.
Items won't display the value, however these are displayed with #mystats window.

[Rule] Add Rule to allow ExtraDmgSkill/SPA 220 to effect Spell Skills

---

utils/sql/db_update_manifest.txt

- This was causing this query to run over and over.

[Fix] Fix typo for bot_id raid_members column in db_update_manifest.txt

---

zone/bot.cpp
zone/bot.h
zone/entity.cpp
zone/entity.h
zone/groups.cpp

This PR resolves a number of crashes where a group member or leader pointer goes stale.
Namely this should fix the following 4 crashes with the first two being regression introduced in #2782.
http://spire.akkadius.com/dev/release/22.4.5-dev?id=1745
http://spire.akkadius.com/dev/release/22.4.5-dev?id=1746
http://spire.akkadius.com/dev/release/22.4.5-dev?id=1764
http://spire.akkadius.com/dev/release/22.4.5-dev?id=1763

[Crash] Fix dangling Group member pointers for Bots.

---

zone/client_packet.cpp

This fixes an issue where a player could disband the raid if the Raid leader was not in the same zone as them (only if Bot rule was enabled)

[Bug Fix] Fix for Raid Disband if leader not in same zone.

---

zone/mob.h
zone/special_attacks.cpp

Values for Weapon Damage were capped at uint16 for SPA 193, changed to signed int32 as we use signed Int for Weapon Damage elsewhere, and don't want to allow overflowing of weapon dmg if done by mistake in a spell entry.

[Fix] Change SPA 193 Weapon Damage to allow values over 65,535

---

zone/bot_raid.cpp
zone/client_packet.cpp
zone/raids.cpp
zone/raids.h

Camped/offline Bots could be left in an existing Raid in specific scenarios if there owner had left the raid.

[Bug Fix] Fix edge cases where camped bots would be left in a raid

---

common/eq_packet_structs.h

Resolves regression introduced in #3123 where items looted off a corpse will have an uninitialized ornamenticon, ornamentidfile, and ornament_hero_model values causing undefined behavior such as causing the incorrect item icons to be displayed.
As seen in the following screenshot:
https://cdn.discordapp.com/attachments/1089149382802284584/1089150391779860481/Exquisite_Rune.png
https://cdn.discordapp.com/attachments/1089149382802284584/1089149383192363058/Silverwing_Loop.png

[Hotfix] Fix for Item display issues when looting items from corpses.

---

common/database.cpp
common/database_conversions.cpp
common/events/player_events.h
common/shareddb.cpp
loginserver/database.cpp
zone/aa.cpp
zone/aa_ability.h
zone/aa_rank.h
zone/aa_rank_effects.h
zone/bot.cpp
zone/zoning.cpp

Corrected a number of instances where Strings::ToInt was being used incorrectly, where ToBool or ToUnsignedInt would be preferred. Will continue cleanup of these as I have time.

[Cleanup] Cleanup Strings::ToInt uses.

---

zone/spells.cpp

Fixes regression from refactoring where NPCs with 0 mana were failing to complete spell casts, and constantly being interrupted.

[Bug Fix] Fix for NPCs having spells interrupted.

---

zone/bot.cpp
zone/spell_effects.cpp

Added checks to prevent crashes as seen in the below instances:
http://spire.akkadius.com/dev/release/22.8.0?id=2826
http://spire.akkadius.com/dev/release/22.8.0?id=2830
Mob::SpellEffect needs refactored eventually, but these checks should help ensure we don't call an out of bounds memory address. 
buffslot can be either -2, -1 or a positive value (that should be valid) so anywhere we use buffslot to access buffs[buffslot] we need to ensure there's a check to ensure we're not out of bounds.

[Crash] Add Checks for out of bounds & dereferencing nullptrs

---

zone/client_process.cpp

- We were only sending `EVENT_DISCONNECT` on GM instant camps or linkdeads.

[Fix] Fix an issue with EVENT_DISCONNECT not firing on regular /camp

---

common/ruletypes.h
zone/client_packet.cpp
zone/guild.cpp
zone/zone.cpp

- This rule is useless as guild bank zone ID is hard-coded into the client.

[Rules] Remove Guild Bank Zone ID Rule

---

zone/bot_raid.cpp
zone/client.h
zone/client_packet.cpp

Added check to verify Rule (Bots, Enabled) is true before we attempt to summon any Bots the owner previously had in their raid when they connect. Without this we were trying to run a database query against bot_data even if the server didn't have the bot schema.
https://cdn.discordapp.com/attachments/1090037315394613389/1090037447703937085/image.png

[Bug Fix] Check Rule "Bots Enabled" to prevent bot database calls on connect

---

zone/bot.cpp
zone/bot_raid.cpp
zone/client.cpp
zone/string_ids.h

Previously we were not handling OOZ group updates when a Bot joined or left a group gracefully, this likely was causing undefined behavior, and also a source of potential crashes.
Also added Group/Raid full checks and relevant string_ids.

[Bug Fix] Fix for OOZ Group updates when removing/inviting Bots

---

zone/groups.cpp

VerifyyGroup should not be setting a members name to '\0' if they are out of zone, this would cause issues with ensuring group integrity, updated LearnMembers to be more explicit in ensuring ptrs are set to nullptr to prevent uninitialized ptrs.

[Fix] Prevent VerifyGroup from setting OOZ membername to Null character.

---

zone/aggro.cpp
zone/attack.cpp
zone/aura.cpp
zone/bot.cpp
zone/botspellsai.cpp
zone/client.cpp
zone/client_packet.cpp
zone/client_process.cpp
zone/embparser.cpp
zone/groups.cpp
zone/hate_list.cpp
zone/inventory.cpp
zone/merc.cpp
zone/mob.cpp
zone/pets.cpp
zone/spawn2.cpp
zone/spell_effects.cpp
zone/trap.cpp
zone/zone.cpp

I ran a code analysis with PVS Studio, and corrected any entries where we were de-referencing a pointer before checking if it was valid.
V595 - https://pvs-studio.com/en/docs/warnings/v595/print/

[Crash] Add Checks for valid pointers or fix existing logic.

---

zone/bonuses.cpp

Limit values were being overwritten by lesser effects due to missing braces on both SE_SlayUndead & SE_HeadShotLevel in condition statement. confirmed with Kayen this appears to be unintended, and other SE_SlayUndead handling confirmed this.

[Bug Fix] Correct SE_SlayUndead & SE_HeadShotLevel limit values to not be overwritten by lesser effects.

---

zone/zone.cpp

- This is unnecessary, since `safe_delete_array` checks for validity.

[Cleanup] Remove unnecessary validation check in Zone::ClearBlockedSpells()

---

zone/zone.cpp

- We were not validating pointer here, could cause issues.

[Cleanup] Add client pointer validation to Zone::GetClosestZonePoint()

---

CHANGELOG.md
common/version.h
package.json

* Remove Bot Groups Functionality ([#3165](https://github.com/EQEmu/Server/pull/3165)) @Aeadoin 2023-04-01
* Cleanup excessive type casting: string -> char * -> string ([#3169](https://github.com/EQEmu/Server/pull/3169)) @Aeadoin 2023-04-01
* Add Checks for valid pointers or fix existing. ([#3164](https://github.com/EQEmu/Server/pull/3164)) @Aeadoin 2023-04-01
* Fix out of bound arrays, other potential crashes ([#3166](https://github.com/EQEmu/Server/pull/3166)) @Aeadoin 2023-04-01
* Correct SE_SlayUndead & SE_HeadShotLevel limit Value when applied. ([#3171](https://github.com/EQEmu/Server/pull/3171)) @Aeadoin 2023-04-01
* Prevent VerifyGroup from setting OOZ membername to Null character. ([#3168](https://github.com/EQEmu/Server/pull/3168)) @Aeadoin 2023-04-01
* Add missing Luabind …

[Release] 22.9.0

---

zone/lua_iteminst.cpp
zone/lua_iteminst.h

Fixes a warning where EQ::ItemInstance is an incomplete type due to destructor not being implemented in source, but instead under header.

[Bug Fix] Correct Forward Declaration compilation warning

---

common/content/world_content_service.cpp
common/content/world_content_service.h

- This is more performant.
- https://pvs-studio.com/en/docs/warnings/v813/
- https://pvs-studio.com/en/docs/warnings/v820/

[Cleanup] Use a constant reference for content_flags in SetContentFlags()

---

zone/botspellsai.cpp

- `max_hp` was named after a member variable.

[Cleanup] Cleanup variable names in Bot::AddSpellToBotList()

---

zone/botspellsai.cpp

- These all returned `false`, no need to be separate.

[Cleanup] Move cases in Bot::AICastSpell()

---

zone/bot.cpp

- Member variable is named `level`, change variable to `bot_level` so we don't cause issues.

[Cleanup] Change level to bot_level in Bot::DoClassAttacks() to not overlap member variable

---

zone/bot.cpp

- Unnecessarily assigning the value twice simultaneously.

[Cleanup] gid is assigned 2 values simultaneously in bot.cpp

---

zone/aa.cpp

- We already set `made_npc->loottable_id` to `0` above.

[Cleanup] Remove extraneous loottable_id setting in WakeTheDead in aa.cpp

---

zone/aa.cpp

[Cleanup] summon_count > MAX_SWARM_PETS  is always false in aa.cpp

---

zone/botspellsai.cpp

- We already check if `botCaster` is invalid above, no need to do so again.

[Cleanup] Remove unnecessary botCaster check in Bot::GetDebuffBotSpell()

---

zone/botspellsai.cpp

- These checks are unnecessary as we know it doesn't pass previous checks.

[Cleanup] Remove unnecessary hpr checks in Bot::BotCastHeal()

---

zone/botspellsai.cpp

- We check if valid above, no need to do it again.

[Cleanup] Remove unnecessary spell_list validation check in botspellsai.cpp

---

zone/botspellsai.cpp

- The default is already `SPELL_TYPE_COUNT`, no need to set it again.

[Cleanup] Remove unnecessary setting of spell_type_index in Bot::GetChanceToCastBySpellType()

---

zone/botspellsai.cpp

- These are always `>= 0` since they're `uint16`.

[Cleanup] Remove unnecessary >= 0 checks for procs in botspellsai.cpp

---

zone/bot.cpp

- Not casting explicitly we lost precision.

[Cleanup] Explicitly cast to float for more precision in Bot::GenerateBaseHitPoints()

---

zone/bot.cpp

- `skill_to_use` will never be `-1` as it passes through the switch and checks class.

[Cleanup] Remove unnecessary skill_to_use check in Bot::DoClassAttacks()

---

zone/bot.cpp

- We already break if there is no group above, revalidation is unnecessary.

[Cleanup] Remove unnecessary group validation in Bot::Death()

---

common/database_instances.cpp

- Variable was defined but never used.

[Cleanup] Remove unused query variable in Database::DeleteInstance()

---

common/eqemu_logsys.cpp

- Both cases have the same return.
- https://pvs-studio.com/en/docs/warnings/v1037/

[Cleanup] Multiple cases with same outcome in GetGMSayColorFromCategory()

---

common/database.cpp

- This is improper and should just check if we have no result, return `0`, otherwise return `row[0]` of the row we queried.

[Cleanup] Unconditional return in for loop in GetRaidByCharID()

---

zone/aa.cpp

- Member variable is also named `target`.

[Cleanup] Wake The Dead argument was named the same as a member variable in Mob

---

zone/attack.cpp

- `skip` is set to `attacker` before it's set to `attacker` again.
- Multiple spots in `Mob::AttackAnimation` use the same animations.

[Cleanup] Multiple cases same outcome and set skip variable to same value

---

common/database/database_dump_service.cpp
common/database/database_dump_service.h
common/file.cpp
common/file.h
common/process/process.cpp
world/cli/database_dump.cpp

This PR fixes an issue where database dumps would not bubble `stderr` from the underlying process execution. Currently this pipes `stderr` to `stdout` so we don't miss errors, this could be later improved to hold a response object containing `status` `stderr` and `stdout`
This is to prevent server operators from experiencing any sort of data loss if they are missing a table that the database backup is trying to request explicitly. If a table is missing, `mysqldump` will normally stop. 
We could ignore this but this really is something that should be addressed immediately otherwise it could cause worse pain to ignore.
* We now cleanup SQL files after compression is requested and a compression binary is found
* When a `mysqldump` error is detected, the world process is exited forcefully
* …

[Backups] Fix database dump error reporting

---

zone/client.cpp

- Fix possible overflows by casting properly.

[Cleanup] Fix possible overflows in Client::AddPlatinum() and Client::TakePlatinum()

---

zone/client.cpp

- Value can never be less than `0` as it's unsigned.

[Cleanup] Fix always false conditions in Client::IncStats()

---

zone/client.cpp

- `!this` isn't valid, as `this` can never be nullptr.

[Cleanup] Fix check for !this in Client::SendHPUpdateMarquee()

---

zone/client.cpp

- Use `.empty()` instead of using a variable storing size in condition.

[Cleanup] Use .empty() in Client::ScribeSpells() and Client::LearnDisciplines()

---

zone/client.cpp

- We already assign `current_endurance` to `0`, no need to do it again.

[Cleanup] Remove extra assignment of current_endurance in Client ctor

---

zone/client.cpp

- We check `FilterHide` prior to the secondary conditions, so it can never show up.

[Cleanup] Remove unnecessary conditions in Client::FilteredMessageCheck()

---

zone/client.cpp

- `target->GetLastName()` was always true, we need to make sure the target has a last name.

[Cleanup] Fix GetLastName() length check in Client::SendWindow()

---

zone/client.cpp

- We check `increase < 0` prior to this, so this can't ever happen.

[Cleanup] Remove unnecessary conditions in Client::Consume()

---

zone/client.cpp

- `value == 0` is unnecessary as it can only be 0 if we fail the `value > 0` check.

[Cleanup] Cleanup unnecessary condition in Client::SendAlternateCurrencyValue()

---

zone/client.cpp

- `faction_value < this_faction_max` and `faction_value > this_faction_min` are always true if they get to that point in the code.

[Cleanup] Remove unnecessary conditions in Client::SendFactionMessage()

---

zone/attack.cpp

- This condition was causing them to be used as `booleans` versus being checked individually.

[Cleanup] Fix filter condition in attack.cpp

---

zone/attack.cpp

- This is unnecessary as we always have a skill value.

[Cleanup] Fix skill_used being used as boolean in Mob::CommonDamage()

---

zone/bonuses.cpp

[Cleanup] SE_AttackSpeed3 effect_value is always less than 0

---

zone/bonuses.cpp

- We checked both, we only need to check one.

[Cleanup] Remove extraneous check for NegateAttacks in SE_NegateAttacks

---

zone/bonuses.cpp

- This code was unreachable since it was inside the switch and should have been checked on its own in the condition where we verify we are using AISpellEffects.

[Cleanup] Move unreachable code in ApplySpellsBonuses()

---

zone/bonuses.cpp

- Spell bonuses `Illusion` is the spell ID, not a boolean.

[Cleanup] Set Illusion bonuses to use spell ID instead of boolean

---

zone/bonuses.cpp

- Many spots were missing a `break;` or a `return` for their value.

[Cleanup] Add missing breaks and returns in bonuses.cpp

---

common/events/player_event_logs.cpp

- All 4 of these use `FormatWithNodata`.

[Cleanup] Multiple cases with same outcome in GetDiscordPayloadFromEvent()

---

common/inventory_profile.cpp

- We check the opposites therefore we don't need either.
- https://pvs-studio.com/en/docs/warnings/v728/

[Cleanup] Remove unnecessary check for IsStackable() in DeleteItem()

---

common/say_link.cpp

- This is always true since we check `!saylinks.empty()` prior to this.

[Cleanup] Remove always true statement in say_link.cpp

---

common/shared_tasks.cpp
common/shared_tasks.h

- This variable was named `m_db_shared_task` which is the same as `SharedTask::m_db_shared_task`.

[Cleanup] Fix shared_tasks.cpp/shared_tasks.cpp variable named same as class member

---

common/strings.cpp

[Cleanup] Remove always true condition in Strings::Commify()

---

common/cli/eqemu_command_handler.cpp

- `x = ""` has less performance than `x.clear()`.
- https://pvs-studio.com/en/docs/warnings/v815/

[Cleanup] Use .clear() instead of setting string to empty in eqemu_command_handler.cpp

---

common/database.cpp

- This variable was created but never used.
- https://pvs-studio.com/en/docs/warnings/v808/

[Cleanup] Remove unused variable in Database::CopyCharacter()

---

common/database.cpp

- This is more performant.
- https://pvs-studio.com/en/docs/warnings/v815/

[Cleanup] Utilize .empty() instead of checking for an empty string in Database::ReserveName()

---

common/database.cpp

- This is more performant and we don't unnecessarily define a variable we can't use.
- https://pvs-studio.com/en/docs/warnings/v821/

[Cleanup] Only define row if we have results in Database::GetCharacterID()

---

common/database/database_dump_service.cpp

- This was unused except for in this one spot, move to scope of condition where it's used.
- https://pvs-studio.com/en/docs/warnings/v821/

[Cleanup] Move variable definition to more relevant scope in DatabaseDumpService::Dump()

---

common/database_conversions.cpp

- Use these methods to increase performance.

[Cleanup] Use .clear() and .empty() instead of comparing to empty string or setting to empty string in CheckDatabaseConvertPPBlob()

---

common/dbcore.cpp
common/dbcore.h

- Passing by constant reference is more performant.
- Checking for empty string with `!= '\0'` is more performant.
- https://pvs-studio.com/en/docs/warnings/v805/
- https://pvs-studio.com/en/docs/warnings/v813/

[Cleanup] Use constant reference and check for empty string properly in dbcore.cpp

---

zone/bot_command.cpp

- No need to use a `std::list` here.

[Cleanup] Convert equipable_slot_list to std::vector from std::list in bot_command.cpp

---

common/eq_stream_ident.cpp
common/eq_stream_ident.h

- More performant to pass by value than by reference.

[Cleanup] Cleanup cheap-to-copy reference to use value instead in eq_stream_ident.cpp/eq_stream_ident.h

---

common/eqdb.cpp
common/eqdb.h

- Use `= default;` instead of an empty ctor.
- https://pvs-studio.com/en/docs/warnings/v832/

[Cleanup] Use default ctor instead of an empty ctor.

---

common/eqtime.cpp
common/eqtime.h

- This is better than using an empty dtor.

[Cleanup] Use default dtor instead of empty dtor for EQTime in eqtime.cpp/eqtime.h

---

common/net/tcp_connection.cpp
world/clientlist.cpp
world/zonelist.cpp

Fixes an issue with the `fmt` (9.0) upgrade that causes encoding issues on output
Fixed
```
> zonestatus
World Locked: No
Zoneservers online:
#1   :: D :: 127.0.0.1:53438 ::  1 :: xxx:7000 :: poair (215) :: (726505)
1 servers listed. 1 servers online.
0 zones are static zones, 1 zones are booted zones, 0 zones available.
```

[Telnet] Telnet encoding fix

---

zone/client.cpp

- We were not setting `aug_item` to the ornamentation augment when we found one.

[Cleanup] Fix ornamentation augment icons in inspect requests

---

zone/bot.cpp

- Bash, Kick, and Taunt have the same reuse time, no reason to set it to the same value.

[Cleanup] Remove unnecessary setting of reuse variable in Bot::DoClassAttacks()

---

common/item_data.h
common/item_instance.h

This PR fixes an issue where ```const ItemData*	m_item``` could be left in an uninitialized state, which would cause a crash when we attempt to dereference it, as seen in the below crash:
http://spire.akkadius.com/dev/release/22.9.1-dev?id=3061
This would also fix the following crash as well:
https://discord.com/channels/212663220849213441/1093971541382934630/1093971541382934630
I use Non Static Data Members Initialization (also called In-Class Member Initialization) to initialize the values for both objects, this ensures any value that doesn't get assigned have a valid assignment (0, "" or nullptr) depending on type.

[Crash] Resolve crash due to uninitialized pointer.

---

common/shareddb.cpp

This resolves regression introduced in #3190, we need to return true from GetSharedBank() or the player inventory will fail to load.

[Hotfix] Resolve loading of inventory

---

common/ruletypes.h
zone/mob.cpp
zone/spell_effects.cpp

Add an optional rule to disable summon spells when the player is already within melee range of an NPC.
This kind of summoning is most apparent in North Temple of Veeshan, but might be in place elsewhere.

[Rules] Optional summoning when already in melee range

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp
zone/spells.cpp

- Add `$mob->GetBuffSpellIDs()`.
- Add `$mob->GetBuffSpellIDs()`.
- These methods allow operators to get a list of a mob's buff IDs without having to loop through their buffs themselves.

[Quest API] Add GetBuffSpellIDs() to Perl/Lua

---

zone/lua_bot.cpp
zone/lua_bot.h

- Add `$bot->ApplySpellRaid(spell_id)`.
- Add `$bot->ApplySpellRaid(spell_id, duration)`.
- Add `$bot->ApplySpellRaid(spell_id, duration, allow_pets)`.
- Add `$bot->ApplySpellRaid(spell_id, duration, allow_pets, is_raid_group_only)`.
- Add `$bot->SetSpellDuration(spell_id)`.
- Add `$bot->SetSpellDuration(spell_id, duration)`.
- Add `$bot->SetSpellDuration(spell_id, duration, allow_pets)`.
- Add `$bot->SetSpellDuration(spell_id, duration, allow_pets, is_raid_group_only)`.
- Add `bot:ApplySpellRaid(spell_id)`.
- Add `bot:ApplySpellRaid(spell_id, duration)`.
- Add `bot:ApplySpellRaid(spell_id, duration, allow_pets)`.
- Add `bot:ApplySpellRaid(spell_id, duration, allow_pets, is_raid_group_only)`.
- Add `bot:SetSpellDuration(spell_id)`.
- Add `bot:SetSpellDuration(spell_id, duration)`.
- Add …

[Quest API] Add ApplySpellRaid() and SetSpellDurationRaid() to Bots in Perl/Lua

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp

- Add `quest::removeldonloss(theme_id)`.
- Add `quest::removeldonwin(theme_id)`.
- Fix `eq.remove_ldon_win(theme_id)` as it was using `quest_manager.addldonwin(theme_id)` instead of `quest_manager.removeldonwin(theme_id)`.

[Quest API] Fix LDoN Methods in Perl/Lua

---

zone/tasks.cpp

- `task_state` is verified by `safe_delete`.
- `size` is the name of a member variable, we should just use `sizeof(uint32_t)` instead.

[Cleanup] Remove unnecessary condition and cleanup variable name in tasks.cpp

---

zone/task_client_state.cpp

- `!tasks_enabled.empty()` is always true.
- `tasks_disabled.size()` is always true.

[Cleanup] Remove always true statements in task_client_state.cpp

---

zone/task_manager.cpp

- Remove unused `query` and `item` variable.
- Use a reference for task data instead of calling `cts->m_completed_tasks[task_index]` over and over.

[Cleanup] Remove unused variables and use reference in task_manager.cpp

---

zone/xtargetautohaters.h
zone/zone_event_scheduler.cpp

- Utilize default dtor.
- Remove unused ctor.

[Cleanup] Remove unused ctor and use default dtor in xtargetautohaters.h 

---

zone/zoning.cpp

- Duplicate outcome cases in `Client::Handle_OP_ZoneChange`.
- Use `.length()` over `strlen` in array defintition.
- Remove unnecessary `else if` in `Client::ZonePC`

[Cleanup] Cleanup zone/zoning.cpp

---

zone/questmgr.cpp
zone/questmgr.h

[Cleanup] Remove item_timers from questmgr.cpp/questmgr.h

---

zone/qglobals.cpp
zone/qglobals.h

[Cleanup] Remove GetQGlobal() from qglobals.cpp/qglobals.h

---

zone/embparser.cpp
zone/embparser.h

[Cleanup] Remove ExportVarComplex() from embparser.cpp/embparser.h

---

zone/mob.h

[Cleanup] Remove _GetMovementSpeed() from mob.h

---

common/item_instance.cpp
common/item_instance.h
zone/attack.cpp

This PR fixes a crash where an uninitialized item instance is called (this forces a nullptr on initialization), this also fixes a "crash" where the zone would get stuck in a while loop.
I believe both of these are regression issues, however the while loop has been in place for a very significant time (years) it's likely that this code was never actually being hit before.
http://spire.akkadius.com/dev/release/22.9.1-dev?id=3186

[Crash] Fix crash with uninitialized item instance, and Bot timeout

---

zone/bot.cpp
zone/client_packet.cpp
zone/raids.cpp

This PR adds an additional integrity check when we spawn Bots to ensure we don't have an invalid Raid state.

[Crash] Add additional raid integrity checks on Bot Spawn.

---

common/item_instance.cpp
common/item_instance.h
common/patches/rof.cpp
common/patches/rof2.cpp
common/patches/uf.cpp
common/ruletypes.h
zone/client.cpp
zone/client_packet.cpp
zone/mob_appearance.cpp

- On Live there are augments that are not type 20/21 and are ornamentations.
- We also only allow a singular augment type to be ornamentation augment types, this will allow you to use any augment type as an ornamentation if it has a proper Hero's Forge model or a non-IT63/non-IT64 idfile.
- Remove `Character:OrnamentationAugmentType` rule as it's no longer necessary.
- This will not break any servers using the previous rule functionality as it will check the augment itself for things that make it a valid ornamentation.

[Feature] Make ornamentations work with any augment type

---

zone/spell_effects.cpp

- These breaks were inside conditions, meaning the case wasn't always broken.

[Cleanup] Breaks in wrong spot in cases in spell_effects.cpp

---

ucs/chatchannel.cpp

To recreate existing crash quickly:
Set rule Channels:DeleteTimer to 1
Add this to a char's INI file: channelAutoJoin=cheesehoppers:Ditrid to add a temp password protected channel
Log that character in
Log that charecter out
In about 2 minutes the UCS will throw a segv and crash
The problem comes from using an second iterator on the same linked list to removecurrent.  The top iterator was getting corrupted.
Tested and it now works everytime.

[UCS/BugFix] Fix crash when Removing empty password protected channel.

---

zone/client_process.cpp

Previous to #2782 clients were not removed from a raid when they camped, would prefer to retain old functionality in this regard, believe this was added mistakenly.

[Bug Fix] Camping was causing player to leave raid, causing unexpected behavior

---

zone/client_mods.cpp

As seen in http://spire.akkadius.com/dev/release/22.10.0?id=3353 it appears that the Zone Ptr could cause a crash if de-referenced in some circumstances, adding check to prevent dereference of a nullptr. 
Default Zone Fast Regen value used if nullptr. 
If this continues to be a problem, then it means that we have a dangling/uninitialized Zone Ptr... and will require further investigation.

[Crash] Fix possible dereference of nullptr in Client::CalcHPRegen

---

zone/exp.cpp

- We could possibly not have a `zone` here, causing a crash.
- http://spire.akkadius.com/dev/release/22.9.1?id=3051
- http://spire.akkadius.com/dev/release/22.9.1?id=3052
- http://spire.akkadius.com/dev/release/22.9.1?id=3073
- http://spire.akkadius.com/dev/release/22.9.1?id=3102
- http://spire.akkadius.com/dev/release/22.9.1?id=3103
- http://spire.akkadius.com/dev/release/22.9.1?id=3104
- http://spire.akkadius.com/dev/release/22.9.1?id=3107
- http://spire.akkadius.com/dev/release/22.9.1?id=3108
- http://spire.akkadius.com/dev/release/22.9.1?id=3109
- http://spire.akkadius.com/dev/release/22.9.1?id=3110
- http://spire.akkadius.com/dev/release/22.9.1?id=3111
- http://spire.akkadius.com/dev/release/22.9.1?id=3112
- http://spire.akkadius.com/dev/release/22.9.1?id=3113
- …

[Crash] Fix possible nullptr in Client::GetCharMaxLevelFromQGlobal()

---

zone/questmgr.cpp

- We didn't check for `owner` before calling `owner->IsNPC()`.

[Cleanup] Fix possible nullptr in quest::addloot()

---

zone/questmgr.cpp

- We didn't check for `owner` before doing `owner->GetName()`.

[Cleanup] Add check for owner in quest::pausetimer()

---

zone/questmgr.cpp

- We didn't check for owner before doing `owner->GetName()`.

[Cleanup] Add check for owner in quest::resumetimer()

---

zone/questmgr.cpp

- Add `initiator` check to `quest::permaclass()`.
- Add `initiator` check to `quest::permarace()`.
- Add `initiator` check to `quest::permagender()`.
- Add `initiator` check to `quest::scribespells()`.
- Add `initiator` check to `quest::traindiscs()`.
- Add `initiator` check to `quest::unscribespells()`.
- Add `initiator` check to `quest::untraindiscs()`.
- Cleanup `initiator` check in `quest::pvp()`.
- Cleanup `initiator` check in `quest::movepc()`.
- Cleanup `initiator` check in `quest::gmmove()`.
- Cleanup `initiator` check in `quest::movegrp()`.
- Add `owner` check to `quest::doanim()`.
- Cleanup `initiator` check in `quest::addskill()`.
- Cleanup `initiator` check in `quest::setlanguage()`.
- Cleanup `initiator` check in `quest::setskill()`.
- Cleanup `initiator` check in …

[Cleanup] Add initiator/owner checks to various methods in questmgr.cpp

---

zone/questmgr.cpp

- We initialize this variable, so it can never be a nullptr.

[Cleanup] quest::createBot() unnecessary check against nullptr

---

zone/bonuses.cpp
zone/loottables.cpp

This PR is to resolve a problem brought up [here](https://discord.com/channels/212663220849213441/1098664193357520996).
The issue is that pets were often not using armor traded to them any longer because the Bonuses code had been consolidated into a single module and that module was applying some client restrictions like race/class, which cannot pass for pets. (As an aside, the same problem was created for NPCs of various races).
That consolidation was done in [PR](https://github.com/EQEmu/Server/pull/3136).
While working on this, I also found a longer term problem in that an item traded to a pet was not actually impacting that pet's AC or other stats until another event which would impact bonuses occurred. The older code did not have this issue, as NPCs were using their internal …

[BugFix/NPCs] Fix issue with NPCs no longer using some armor.

---

zone/exp.cpp

I have verified on titanium and rof2 that we always get 2 "you have LOST a level" messages and that the one in yellow is from OUR code, the one in RED I can find nowhere so I am thinking the client is generating it.
I cannot find anywhere in our code where the constant LOSE_LEVEL is used other than SetExp and nowhere do we send the entire message hard coded or use the value 442 in a message.
Therefore I think we can remove this message and rely on the client.

[Messages] Remove duplicate you have lost a level message

---

zone/client.cpp

- These methods were ignoring the sixth augment slot and could cause item to be summoned attuned being `EQ::invslot::slotCursor` is a non-zero value.

[Bug Fix] Possible issues with SummonItem in Client::QuestReward() methods

---

zone/merc.cpp

Issue with scope, where we were declaring npc_type_to_copy inside a block statement which was recently added to ensure validity of the client ptr. this would cause npc_type_to_copy to always be nullptr.

[Bug Fix] Fix issue with spawning Mercs

---

ucs/ucs.cpp

This fixes a crash that occurs when UCS receives a packet to reload log settings. This is because there isn't a valid database pointer held within the player event logging manager within the context of UCS. We fix this by instantiating player event logs and passing the database connection instance pointer to the class.
* http://spire.akkadius.com/dev/release/22.9.1?id=3298
* http://spire.akkadius.com/dev/release/22.10.0?id=3380

[Crash] Fix UCS crash that occurs during log reloading

---

utils/scripts/eqemu_server.pl

Maps are a choke point, this updates with a releases artifact that is 13x faster
Test from my laptop
**Before** 4 minutes
**After** 18 seconds
9 seconds tested out of the datacenter

[Maps] Update download with faster releases link

---

zone/oriented_bounding_box.h

- Use default ctor/dtor instead of empty ones.

[Cleanup] Use default ctor/dtor in oriented_bounding_box.h

---

common/crash.cpp

[Cleanup] Remove unused variable in common/crash.cpp

---

zone/questmgr.cpp

- Remove unnecessary double check of `initiator`.
- Cleanup logic to use `EQ::skills::GetSkillTypeMap()`.

[Cleanup] quest::setallskill() had always true condition.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp

- Add `$mob->GetDefaultRaceSize(race_id)`.
- Add `$mob->GetDefaultRaceSize(race_id, gender_id)`.
- Add `mob:GetDefaultRaceSize(race_id)`.
- Add `mob:GetDefaultRaceSize(race_id, gender_id)`.
- This allows you to get a default size for a race and gender that isn't the current mob's race and gender.

[Quest API] Add GetDefaultRaceSize() overloads to Perl/Lua

---

zone/bot.cpp
zone/bot.h

- Remove `DoFinishedSpellAETarget()`.
- Remove `SendBotArcheryWearChange()`.
- These are unused.

[Cleanup] Remove unused methods in zone/bot.cpp and zone/bot.h

---

zone/merc.h

[Cleanup] Remove GetClassHPFactor() from zone/merc.h

---

zone/client.cpp
zone/client.h

- Remove `CheckAccess()` in `zone/client.cpp`.
- Remove `CheckAccess()` in `zone/client.h`.
- Remove `CheckQuests()` in `zone/client.h`.
- Remove `MakeCorpse()` in `zone/client.h`.
- Remove `HPTick()` in `zone/client.h`.
- Remove `ProcessPackets()` in `zone/client.h`.
- These methods are unused.

[Cleanup] Remove unused methods in zone/client.cpp and zone/client.h

---

zone/npc.h

[Cleanup] Remove pDontCastBefore_casting_spell from zone/npc.h

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/perl_mob.cpp

- Add `$mob->HasSpellEffect(effect_id)`.
- Add `mob:HasSpellEffect(effect_id)`.
- Allows operators to see if a Mob has an effect ID from any of their buffs.

[Quest API] Add HasSpellEffect() to Perl/Lua

---

zone/attack.cpp

Healing yourself with a spell that does > 100 hp of healing was resulting in:
[Tue May 02 16:18:46 2023] Logg has healed you for 350 points.
[Tue May 02 16:18:46 2023] You have healed Logg for 350 points.
Fixed to only display one message in this case.

[Messages] Remove duplicate heal message for healing yourself

---

zone/bonuses.cpp

Lazarus updated to master and started having zones grow to several GB's of memory before the OS runs out of memory and kills the zone. It had been happening for several weeks now and become a big issue of stability and zones would OOM kill many times throughout a given day. Notably, EZ and PEQ have not updated for a few months to see the issue at the same scale
I ran https://github.com/KDE/heaptrack on a problem zone given common zones the behavior was introduced in so we can collect data to understand the issue.
The issue stems from constantly creating new item instances which `new`'s up new objects every time CalcBonuses is called and never destroys them.
This reverts changes made in https://github.com/EQEmu/Server/pull/3136/files for a small part of the offending code …

[Memory Leak] Fix large memory leak introduced in CalcItemBonuses

---

common/item_instance.h
zone/client.h
zone/inventory.cpp
zone/lua_iteminst.cpp
zone/lua_iteminst.h
zone/string_ids.h
zone/tradeskills.cpp

- `Object::HandleAugmentation` did not properly check for `augrestrict` values. This allowed augment restrictions to be bypassed with `#augmentitem` or anything else that uses this method.
- `Client::SummonItem` already properly checked these, so I just broke it out into a `Client::IsAugmentRestricted()` method.

[Bug Fix] #augmentitem bypasses augment restrictions

---

zone/zone.cpp

- Before this, quests/plugins would be cached in an old state, so you'd have to either enter the zone and `#reload quest` or `#reload world` to get them to update.

[Bug Fix] ReloadQuests() on Zone::Init() to avoid cached global quests/plugins

---

zone/bonuses.cpp

Fetch inventory using the `InventoryProfile` method `GetItem(int16 slot_id)` the prior `m_inv` direct access never appeared to actually work

[Hotfix] Fix mob item bonus calc

---

common/shareddb.cpp
common/shareddb.h
zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/trading.cpp
zone/zonedb.cpp

There is quite a bit of idle query volume of players constantly querying for mail key when it barely changes. When players save, the mail key is queried, when UCS reconnects the mail key is queried from the DB.
This PR loads the mail key into memory on player load and re-uses the cache where referenced in the code
**Query Example**
```
5/7/2023 9:27:18 PM SELECT `mailkey` FROM `character_data` WHERE `id`='687628' LIMIT 1 -- (1 row returned) (0.000318s)
5/7/2023 9:27:18 PM SELECT `mailkey` FROM `character_data` WHERE `id`='736323' LIMIT 1 -- (1 row returned) (0.000143s)
5/7/2023 9:27:18 PM SELECT `mailkey` FROM `character_data` WHERE `id`='732663' LIMIT 1 -- (1 row returned) (0.000369s)
5/7/2023 9:27:18 PM SELECT `mailkey` FROM `character_data` WHERE `id`='734796' LIMIT 1 -- (1 row …
```

[Performance] Mail key is now cached during player load

---

zone/client.cpp
zone/zonedb.cpp
zone/zonedb.h
zone/zoning.cpp

This PR combines individual `character_bind` queries during `Save()` into one
This also fixes a long time bug where character heading is not being properly saved in bind
```
Zone |   Query    | QueryDatabase DELETE FROM character_bind WHERE id = 1 -- (5 rows affected) (0.008630s)-- [poair] (The Plane of Air) inst_id [0]
Zone |   Query    | QueryDatabase INSERT INTO character_bind (id, slot, zone_id, instance_id, x, y, z, heading)  VALUES (1,0,189,0,18.000000,-147.000000,20.000000,192.000000),(1,1,29,0,-456.000000,560.000000,-26.000000,192.000000),(1,2,29,0,-456.000000,560.000000,-26.000000,192.000000),(1,3,29,0,-456.000000,560.000000,-26.000000,192.000000),(1,4,29,0,-456.000000,560.000000,-26.000000,192.000000) -- (5 rows affected) (0.000310s)-- [poair] (The Plane of Air) inst_id [0]
```

[Performance] Character bind is now bulk saved

---

zone/zonedb.cpp

Similar to https://github.com/EQEmu/Server/pull/3336
When character `Save()` is triggered character pet data get saved individually for every buff, inventory item and info. In situations where character `Save()` routines are being triggered more aggressively, the query volume adds up quickly.
Attached is an example on Lazarus within 12 seconds there are almost 1k in queries with `Save()` related queries making up a bulk.
This PR reduces all individual insert queries into one bulk insert for each buff pet `info` `buff` and `inventory` row.
We also now only purge data from the table only if there is data to save
https://gist.github.com/Akkadius/0553f9fd49e8da9caf57ce6e0da4a475
```
Zone |   Query    | QueryDatabase DELETE FROM character_pet_info WHERE char_id = 1 -- (2 rows affected) …
```

[Performance] Character pet bulk saving

---

zone/zonedb.cpp

When character `Save()` is triggered `character_buffs` get saved individually for every buff. In situations where character `Save()` routines are being triggered more aggressively, the query volume adds up quickly.
Attached is an example on Lazarus within 12 seconds there are almost 1k in queries with `Save()` related queries making up a bulk.
This PR reduces all individual buff insert queries into one bulk insert
https://gist.github.com/Akkadius/0553f9fd49e8da9caf57ce6e0da4a475

[Performance] Character buffs now save in bulk

---

common/classes.cpp
common/classes.h
zone/bonuses.cpp

So users on Retribution server were complaining about their manastones actually reducing mana from max mana, and basically capping  quite a bit under their real max mana. I traced it down to the patch done about 2 months ago on heroic stat changes. I made these modifications to correct it and seems to work fine. This seems to have only impacted Pal/SK/Ranger/Beastlord. 
Made new Is Checks to make sure I didn't impact logic that is located in other places.

[Bug Fix] Fix Heroic INT/WIS Bonuses

---

common/emu_constants.h
zone/hate_list.cpp
zone/hate_list.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

Had the need in a new event to get the closest client on the hate list, random existed but not closest, and closest hate seems to be able to return pets.
Copied the closest and just added a small filter to make sure they were a client.

[Quest API] Add GetHateListClosest(), GetHateListClosestBot(), GetHateListClosestClient(), and GetHateListClosestNPC() methods/overloads to Perl/Lua

---

zone/combat_record.cpp
zone/combat_record.h

[Cleanup] Remove GetDamageReceived() and GetHealReceived() from combat_record.cpp/combat_record.h

---

zone/hate_list.cpp
zone/hate_list.h

[Cleanup] Remove GetEscapingEntOnHateList() from hate_list.cpp/hate_list.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove CountNPC(), FindDefenseNPC(), and QueueManaged() from entity.cpp/entity.h

---

zone/npc.cpp
zone/npc_scale_manager.cpp

A user on Ret submitted a bug where they were one shot by a low level mob. I was able to reproduce this and started to diagnose the issue. It seemed to be where a Min Dmg value of 0 and a max dmg value of 3 was set in the database for this NPC. 
The min dmg scaling kicks in, but you get into a situation where MIN DMG > MAX DMG (12 vs 3 in this case)
It leads to situations like thus. 
Looking at it deeper it seems to be in the calculation area for rounding. 
I worked with Kingly and setup some sanity code to prevent wild situations of being hit for millions of damage, but needed to go one step further. 
I also changed it so that if you set Min Dmg to 0, it means max damage is also auto calculated... this had the mob working as I would expect a lvl 28 mob to be.

[Bug Fix] Mob scaling issue with min dmg set to zero while max dmg is not

---

zone/loottables.cpp

If you trade a pet a new helm(replacing one currently in use), the helm does not replace as the item counted in Bonuses until you zone.  This was due to two items in itemlist having the same equip-slot.

[Bug Fix] NPC Armor Upgrade to a slot not handled correctly

---

zone/gm_commands/spawn.cpp
zone/npc.cpp

- NPCs when spawned with this command have 0 health by default, requiring operators to manually edit their health if they're using this NPC as an NPC in their hub.

[Cleanup] Fix #spawn command NPCs having 0 health

---

zone/gm_commands/zheader.cpp

- Argument 2 and 3 were being used when it should have been arguments 1 and 2.

[Bug Fix] Fix typos in #zheader

---

common/ruletypes.h
zone/gm_commands/questerrors.cpp
zone/quest_interface.h

- Allows operators to display more than 30 errors with #questerrors if they want.

[Rules] Add World:MaximumQuestErrors Rule

---

zone/gm_commands/npcedit.cpp

- `#npcedit special_attacks` and `#npcedit special_abilities` send duplicate messages since the `d` variable wasn't being set and a message was being sent instead, meaning a message was sent inside the condition as well as a blank message at the bottom of the command.

[Bug Fix] Fix duplicate messages in #npcedit

---

common/zone_store.cpp
common/zone_store.h
zone/embparser_api.cpp
zone/lua_general.cpp

- Add `quest::GetZoneSafeX(zone_id)`.
- Add `quest::GetZoneSafeX(zone_id, version)`.
- Add `quest::GetZoneSafeY(zone_id)`.
- Add `quest::GetZoneSafeY(zone_id, version)`.
- Add `quest::GetZoneSafeZ(zone_id)`.
- Add `quest::GetZoneSafeZ(zone_id, version)`.
- Add `quest::GetZoneSafeHeading(zone_id)`.
- Add `quest::GetZoneSafeHeading(zone_id, version)`.
- Add `quest::GetZoneMinimumLevel(zone_id)`.
- Add `quest::GetZoneMinimumLevel(zone_id, version)`.
- Add `quest::GetZoneMaximumLevel(zone_id)`.
- Add `quest::GetZoneMaximumLevel(zone_id, version)`.
- Add `quest::GetZoneMinimumStatus(zone_id)`.
- Add `quest::GetZoneMinimumStatus(zone_id, version)`.
- Add `quest::GetZoneTimeZone(zone_id)`.
- Add `quest::GetZoneTimeZone(zone_id, version)`.
- Add `quest::GetZoneMaximumPlayers(zone_id)`.
- Add …

[Quest API] Add zone data methods to Perl/Lua

---

zone/command.cpp
zone/command.h
zone/gm_commands/findcurrency.cpp

- Allows you to find alternate currencies by item ID or name.
- Has a saylink for summoning a stack of the currency if the GM can use the `#summonitem` command.

[Commands] Add #findcurrency Command

---

common/spdat.h

[Cleanup] Remove CalcPetHp from spdat.h

---

zone/client_packet.cpp
zone/groups.cpp

We weren't properly nulling Group membership prior to loading Group membership from the database.
This could cause issues where duplicate entries could appear causing a client to be in the group multiple times. 
We also weren't correctly handling Member Roles, causing these to possibly break when the group changed in some fashion.

[Bug Fix] Fix issue with Group Pointers/Member roles

---

common/database_schema.h
common/repositories/base/base_character_tribute_repository.h
common/repositories/character_tribute_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2023_05_08_character_tribute_primary_key.sql
zone/client.cpp
zone/client_packet.cpp
zone/zonedb.cpp
zone/zonedb.h

This pull request combines individual `character_tribute` queries during `Save()` into one.
This pull request also adds a primary key of `id` to `character_tribute` and renames the pre-existing `id` column to `character_id`, this allows us to use repositories for this table.

[Performance] Character tribute is now bulk saved

---

world/console.cpp
world/zoneserver.cpp
zone/client.cpp
zone/client_packet.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/perl_client.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::send_channel_message(channel_number, guild_id, language_id, language_skill, message)`.
- Add `quest::send_channel_message(from, channel_number, guild_id, language_id, language_skill, message)`.
- Add `quest::send_channel_message(from, to, channel_number, guild_id, language_id, language_skill, message)`.
- Add `eq.send_channel_message(channel_number, guild_id, language_id, language_skill, message)`.
- Add `eq.send_channel_message(from, channel_number, guild_id, language_id, language_skill, message)`.
- Add `eq.send_channel_message(from, to, channel_number, guild_id, language_id, language_skill, message)`.
- This allows operators to send channel messages from scripts like a broadcast or tell.
- Cleaned up spots where we were using magic numbers for channels instead of our …

[Quest API] Add SendChannelMessage() to Perl/Lua

---

zone/doors.cpp

Due to the data types in the client packet, door_id was not being logged correctly.  Replaced the value from the packet with the simple m_door_id.
The old code displayed a seemingly random value for the same door, I assume because of casting.

[Logging] Fixed statements that logged incorrect data

---

zone/common.h

[Cleanup] Remove _BECOMENPCPET() and _NPCPET() from zone/common.h

---

zone/common.h

[Cleanup] Remove CHECK_LOS_STEP from zone/common.h

---

zone/entity.h

[Cleanup] Remove struct DynamicZoneSafeReturn from zone/entity.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove WriteEntityIDs() from zone/entity.cpp and zone/entity.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove Evade() from zone/entity.cpp and zone/entity.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove GateAllClients() from zone/entity.cpp and zone/entity.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove RemoveMob() and RemoveRaid() from zone/entity.cpp and zone/entity.h

---

zone/entity.h

[Cleanup] Remove SendAATimer() from zone/entity.h

---

zone/entity.cpp
zone/entity.h

[Cleanup] Remove GetGroupByBot(), GetRaidByMob(), and GetRaidByLeaderName() from zone/entity.cpp and zone/entity.h

---

zone/npc.h

- These are unimplemented and unused.

[Cleanup] Remove InteractiveChat() and TakenAction() from zone/npc.h

---

zone/client_packet.cpp
zone/string_ids.h

On live if you have something targetted, and you type /tar Innothule, but Innothule is not around, you get an error message and your current target is unmodifed.
Prior to this patch, if you do this on eqemu, it "looks" like your current target is unchanged, but you no longer get updates.
This change fixes that.  But I have a couple of questions:
1. The code differentiates between AI controlled clients and non-AI controlled clients.  Is not the /tar command unable to be send if you are AI controlled, meaning I could also delete those lines?  If not, perhaps the code I moved down inside non-ai controlled needs to be down in AI controlled as well?  My take is that those lines can be deleted.
2. The ONLY time all of the code after the // HoTT comment executes if its a NON-AI-CONTROLLED …

[Targeting] /tar <bad target> should not untarget existing target

---

common/eq_packet_structs.h
zone/client_packet.cpp

- X and Y were swapped in GMSummon_Struct so it displayed XYZ incorrectly in /find, adding its own struct fixes this.

[Cleanup] Add GMFind_Struct to packet structures

---

zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->GetEXPForLevel(check_level)`.
- Add `client:GetEXPForLevel(check_level)`.
- This allows operators to see the required experience for a level based on the client provided, this takes race/class modifiers into account as well if enabled.

[Quest API] Add GetEXPForLevel() to Perl/Lua

---

common/spdat.cpp
common/spdat.h
zone/aa.cpp
zone/aggro.cpp
zone/attack.cpp
zone/bot.cpp
zone/botspellsai.cpp
zone/client_packet.cpp
zone/client_process.cpp
zone/effects.cpp
zone/embparser_api.cpp
zone/gm_commands/castspell.cpp
zone/lua_general.cpp
zone/merc.cpp
zone/mob.cpp
zone/mob_ai.cpp
zone/npc.cpp
zone/pets.cpp
zone/special_attacks.cpp
zone/spell_effects.cpp
zone/spells.cpp

- Add `quest::CalculateCorruptionCounters(spell_id)`.
- Add `quest::CalculateCounters(spell_id)`.
- Add `quest::CalculateCurseCounters(spell_id)`.
- Add `quest::CalculateDiseaseCounters(spell_id)`.
- Add `quest::CalculatePoisonCounters(spell_id)`.
- Add `quest::GetSpellEffectDescriptionNumber(spell_id)`.
- Add `quest::GetSpellEffectIndex(spell_id, effect_id)`.
- Add `quest::GetSpellFuriousBash(spell_id)`.
- Add `quest::GetSpellMinimumLevel(spell_id)`.
- Add `quest::GetSpellNimbusEffect(spell_id)`.
- Add `quest::GetSpellPartialMagicRuneAmount(spell_id)`.
- Add `quest::GetSpellPartialMagicRuneReduction(spell_id)`.
- Add `quest::GetSpellPartialMeleeRuneAmount(spell_id)`.
- Add `quest::GetSpellPartialMeleeRuneReduction(spell_id)`.
- Add `quest::GetSpellProcLimitTimer(spell_id)`.
- Add …

[Quest API/Cleanup] Add several spell methods to Perl/Lua

---

common/ruletypes.h
zone/botspellsai.cpp
zone/client.h
zone/client_process.cpp
zone/mob.h
zone/spells.cpp

Let's try this again :P --- This is a duplicate of #2268 which went stale.
This adds rules to enable or disable checks for spells and autofire to prevent casting or autofire from landing if the player or bot do not match their targets plane in regards to water.
Currently players and bots can cast or autofire if they are not in the water but their target is and vice versa, this should not be possible.
RuleB(Combat, WaterMatchRequiredForAutoFireLoS) set to True (default) checks that both parties are in or out of the water for AutoFire to work.
RuleB(Spells, WaterMatchRequiredForLoS) set to True (default) checks that both parties are in or out of the water for spells to land.

[Feature] Add Water Line of Sight Checks

---

zone/client_packet.cpp

Using /tar on an invalid target should not negate a current target. (Tested on live)
My previous attempt to fix this was invalid, as Handle_OP_Target was getting called for multiple packets, so my fix could not reside there alone.
In my digging I found that hitting escape (to remove target), mobs dying, clicking with the mouse, all issued direct OP_TargetMouse commands which should bahave as we have always done them.  However, our code also called the same code for OP_Target, which actually only seems to be meant to server as a validation of a /tar command.  If we accept the target, the client immediately sends the corresponding OP_TargetMouse.  If we reject it, the client sends nothing further.
This fix seems to solve the original issue while not breaking the rest, which is much better …

[Targeting] Fix bug when using /tar on invalid target

---

world/console.cpp

- Add `czcast`, `czmove`, `wwcast`, and `wwmove` to Telnet functionality.
- Allows operators to cast spells across zone/world-wide and move players across zone/world-wide from telnet.

[Telnet] Add cross zone/world wide cast and move functionality to Telnet

---

common/database/database_dump_service.cpp
common/eqemu_logsys.cpp
common/eqemu_logsys.h

Related to work in https://github.com/EQEmu/Server/pull/2857
* Add methods `EnableMySQLErrorLogs` and `DisableMySQLErrorLogs` when we want to use them during database migrations
* Keeps a copy of `pre_silenced` log settings so enabling console logging restores what was loaded from the database prior to silencing during CLI execution
* Returns `DatabaseDumpService` early when no tables are specified when `--drop-table-syntax-only` flag is set
* Reloads log settings from the database after a dump
* Colors console messages as red when bracket content matches `missing` or `error
* Colors console messages as green when bracket content matches `ok`
* Color matching `[<red>variable] would produce [variable] with red inside brackets`

[Logging] Logging improvements, console silencing, terminal coloring

---

common/database/database_dump_service.cpp
common/database/database_dump_service.h

This PR moves the `DatabaseDumpService` to use a credentials file instead of passing credentials on the command line.
This is done by temporarily creating a temporary credentials file before the command is executed and then is cleaned up after the dump is created. The reason for this is that `mysqldump` or invocations of `mysql` on the command line will echo warnings of 
```
mysqldump: [Warning] Using a password on the command line interface can be insecure.
```
This warning gets in the dump files and will halt execution of the dump entirely. This warning is produced on later versions of MySQL.
**File Creation and Deletion**
Below is a `cat` during invocation and immediately after.
```
eqemu@332a3650bfe4:~/server$ cat login.my.cnf
[mysqldump]
user=eqemu
password=xxx
host=mariadb
port=3306 …
```

[Backups] Move world database:dump to use MySQL credentials file

---

common/cli/eqemu_command_handler.cpp
world/cli/database_dump.cpp

Related to work in https://github.com/EQEmu/Server/pull/2857
Currently in `database:dump` when you run help, the root CLI menu `--help` takes over and shows the command menu instead of printing the help for the command itself.
**Before**
```
eqemu@332a3650bfe4:~/server$ ./bin/world database:dump --help
> EQEmulator [World] CLI Menu
character
character:copy-character     Copies a character into a destination account
database
database:dump                Dumps server database tables
database:schema              Displays server database schema
database:set-account-status  Sets account status by account name
database:version             Shows database version
world
world:version                Shows server version
```
**After**
```
eqemu@332a3650bfe4:~/server$ ./bin/world database:dump --help …
```

[CLI] Console menu validation fixes

---

common/dbcore.cpp
common/dbcore.h

Related to work in https://github.com/EQEmu/Server/pull/2857
This PR adds multi-statement execution support in MySQL queries only through `QueryDatabaseMulti`. 
**This is never to be used under normal operating circumstances as it creates a security risk.** 
This is implemented purely for native database migration support so that DDL multi-statement migrations can be ran from a single string

[Database] Add query multi statement execution support

---

common/strings.cpp
common/strings.h
zone/embparser_api.cpp
zone/lua_general.cpp

- Add `quest::convert_money_to_string(money_hash)`.
- Add `eq.convert_money_to_string(money_table)`.
- Allows operators to convert money in to a readable string using `Strings::Money`.
```pl
my %money_data = (
"platinum" => 3123,
"gold" => 5692,
"copper" => 9
);
quest::message(315, quest::convert_money_to_string(%money_data));
}
}
```
```lua
if e.message:find("#a") then
local money_data = {
gold = 12,
silver = 523904,
copper = 3
}
eq.message(315, "Lua: " .. eq.convert_money_to_string(money_data))
end
end
```

[Quest API] Add convert_money_to_string() to Perl/Lua

---

zone/gm_commands/npcedit.cpp

- We default to `Hand to Hand (Skill ID 28)` in the database, so we need to default to this in `#npcedit meleetype` in case the operator only sets the first melee type this avoids the NPC hitting with `1H Blunt (Skill ID 0)`.

[Cleanup] Default skill type to Hand to Hand in #npcedit meleetype

---

zone/gm_commands/npcedit.cpp

- Using `#npcedit weapon` without the secondary model had a chance to crash the zone you were in, i.e `#npcedit weapon 1`.
```txt
[06-18-2023 16:26:55] [Zone] [Crash] [New LWP 802548]
[06-18-2023 16:26:55] [Zone] [Crash] [New LWP 802549]
[06-18-2023 16:26:55] [Zone] [Crash] [New LWP 802550]
[06-18-2023 16:26:55] [Zone] [Crash] [New LWP 802551]
[06-18-2023 16:26:55] [Zone] [Crash] [Thread debugging using libthread_db enabled]
[06-18-2023 16:26:55] [Zone] [Crash] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[06-18-2023 16:26:55] [Zone] [Crash] 0x00007f22b2b14207 in __GI___wait4 (pid=819104, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
[06-18-2023 16:26:55] [Zone] [Crash] [Current thread is 1 (Thread 0x7f22b29eab00 (LWP 802540))] …
```

[Bug Fix] Fix possible crash with #npcedit weapon

---

zone/gm_commands/npcedit.cpp

- Add `#npcedit model [Race ID]` to edit an NPC's race model.
- Add `#npcedit heroic_strikethrough [Heroic Strikethrough]` to edit an NPC's heroic strikethrough.
- Add `#npcedit faction_amount [Faction Amount]` to edit an NPC's faction amount.

[Commands] Add missing subcommands to #npcedit

---

common/database/database_update.cpp
common/dbcore.cpp
common/mysql_request_result.cpp
common/mysql_request_result.h

This PR fixes an issue where multi-statement processing was not returning the errors properly

[Database] Fix multi-statement error reporting

---

zone/client_process.cpp
zone/spells.cpp

- Oversight on my part, should've been `==`, not `&&`.

[Bug Fix] Fix improper condition in Water LOS checks

---

common/database/database_update.cpp
common/database/database_update.h

When a server operator does not have bots enabled, it is possible for `CheckVersions` to improperly return "not up to date" because bots version values can be incorrectly compared.
This fixes an edge case where if bots are **not** enabled - it will always return **up-to-date**

[Database] Fix database version checking edge case issue

---

zone/merc.h

[Cleanup] Remove acmod() from zone/merc.h

---

zone/merc.h

[Cleanup] Remove GetACMit() from zone/merc.h

---

zone/npc.h

[Cleanup] Remove _ClearWaypints() from zone/npc.h

---

zone/global_loot_manager.cpp
zone/gm_commands/shownpcgloballoot.cpp
zone/gm_commands/showzonegloballoot.cpp
zone/zone.h

- Utilize Dialogue Window tables.

[Commands] Cleanup #shownpcgloballoot and #showzonegloballoot Commands

---

zone/command.h

[Cleanup] Remove command_showpetspell in zone/command.h

---

zone/command.h

[Cleanup] Remove command_packetprofile from zone/command.h

---

zone/command.h

[Cleanup] Remove command_unlock from zone/command.h

---

zone/client.cpp
zone/client.h
zone/command.cpp
zone/command.h
zone/gm_commands/showspells.cpp

- Add `#showspells` command to show your or your target's memorized spells or learned disciplines.

[Commands] Add #showspells Command

---

zone/merc.h

[Cleanup] Remove GetACAvoid() from zone/merc.h

---

common/ruletypes.h
zone/npc.cpp

- This rule defaults to `true` and maintains `Kinglykrab's Pet` as my pet's last name, disabling allows you to manually modify the last name or have pets with no last name.

[Rules] Add ClientPetsUserOwnerNameInLastName rule

---

zone/npc.cpp

- `merchant_open` was only set to `true` if class was `MERCHANT`.

[Bug Fix] Merchant Open Flag set only for regular Merchants

---

zone/bot_command.cpp

Check for underscores in bot names as the server will replace with a space and add to the database. The bot can't be deleted/summoned or changed except by editing the database.
Other symbols seem to be properly ignored (they are just deleted, like # or *). I added a simple check to prevent names with _'s. 
**Command:** ^botcreate Tuday_bot_healer 1 1 1
The server replaces _'s with spaces and adds the bot. Here is an example:
You can no longer delete/summon/alter the bot in anyway without editing SQL.

[Bug Fix] Add check for underscores in botcreate command

---

common/classes.cpp
common/classes.h
common/races.cpp
common/races.h
zone/bot_command.cpp
zone/client.cpp
zone/client.h
zone/client_mods.cpp
zone/client_packet.cpp
zone/gm_commands/find/class.cpp
zone/gm_commands/find/race.cpp
zone/gm_commands/mystats.cpp
zone/gm_commands/showstats.cpp
zone/gm_commands/texture.cpp
zone/mob.cpp
zone/mob.h

- Cleans up a lot of the display in the popup window and uses tables instead of `.` and `&nbsp;`.
- Optionally displays a lot more data versus always displaying it, allowing us more room for things within the window.
- Converts `Client::SendStatsWindow(client, use_window)` to a Mob method.
- Converts `Mob::IsPlayerClass(class_id)` to a utility method.
- Converts `Mob::IsPlayerRace(race_id)` to a utility method.
- Adds `GetPlayerClassAbbreviation(class_id)` as a utility method.
- Adds `GetPlayerRaceAbbreviation(race_id)` as a utility method.
- Cleans up `#mystats` logic.
- Cleans up `#showstats` logic.

[Cleanup/Feature] Add support for bots to #showstats/#mystats

---

common/eqemu_logsys.cpp

As seen here http://spire.akkadius.com/dev/release/22.16.0?id=5229
We eventually need to get rid of all legacy logging that does not use `vStringFormat` formatting. If a string is passed with a `%` it can be interpreted as a `printf` code http://personal.ee.surrey.ac.uk/Personal/R.Bowden/C/printf.html

[Logging] Fix logging crash when % are sent through query logs

---

common/dbcore.cpp

When we run a multi-statement query, sometimes we return early and don't quite get to the end of the function to turn multi-statements back off

[Database] Set multi statements off when returning early

---

zone/CMakeLists.txt
zone/embparser.cpp
zone/perl_entity.cpp
zone/perl_spawn.cpp

- Add `$entity_list->GetSpawnByID(spawn_id)`.
- Add `$entity_list->GetSpawnList()`.
- Add `$spawn->Depop()`.
- Add `$spawn->Disable()`.
- Add `$spawn->Enable()`.
- Add `$spawn->ForceDespawn()`.
- Add `$spawn->GetCurrentNPCID()`.
- Add `$spawn->GetHeading()`.
- Add `$spawn->GetID()`.
- Add `$spawn->GetKillCount()`.
- Add `$spawn->GetRespawnTimer()`.
- Add `$spawn->GetSpawnCondition()`.
- Add `$spawn->GetSpawnGroupID()`.
- Add `$spawn->GetVariance()`.
- Add `$spawn->GetX()`.
- Add `$spawn->GetY()`.
- Add `$spawn->GetZ()`.
- Add `$spawn->IsEnabled()`.
- Add `$spawn->IsNPCPointerValid()`.
- Add `$spawn->LoadGrid()`.
- Add `$spawn->Repop()`.
- Add `$spawn->Repop(delay)`.
- Add `$spawn->Reset()`.
- Add `$spawn->SetCurrentNPCID(npc_id)`.
- Add `$spawn->SetNPCPointer(npc_pointer)`.
- Add …

[Quest API] Add Spawn2 Class to Perl

---

zone/lua_hate_list.cpp
zone/lua_hate_list.h
zone/perl_hateentry.cpp

- Add `$hate_entry->GetFrenzy()`.
- Add `$hate_entry->SetDamage(value)`.
- Add `$hate_entry->SetEnt(mob)`.
- Add `$hate_entry->SetFrenzy(is_frenzy)`.
- Add `$hate_entry->SetHate(value)`.
- Convert `hate_entry:GetFrenzy()` to `bool` instead of `int`, as `is_entity_frenzy` is a `bool`.

[Quest API] Add Hate Entry Methods to Perl

---

common/classes.cpp
common/races.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_bot.cpp
zone/perl_client.cpp

- Add `$bot->GetClassAbbreviation()`.
- Add `$bot->GetRaceAbbreviation()`.
- Add `$client->GetClassAbbreviation()`.
- Add `$client->GetRaceAbbreviation()`.
- Add `bot:GetClassAbbreviation()`.
- Add `bot:GetRaceAbbreviation()`.
- Add `client:GetClassAbbreviation()`.
- Add `client:GetRaceAbbreviation()`.
- Allows operators to easily get a player race/class abbreviation, example being `Warrior` as `WAR`.

[Quest API] Add GetClassAbbreviation() and GetRaceAbbreviation() to Perl/Lua

---

common/languages.h
zone/lua_iteminst.cpp
zone/lua_iteminst.h
zone/perl_questitem.cpp

- Add `$questitem->AddEXP(exp)`.
- Add `$questitem->ClearTimers()`.
- Add `$questitem->Clone()`.
- Add `$questitem->DeleteCustomData(identifier)`.
- Add `$questitem->GetAugmentItemID(slot_id)`.
- Add `$questitem->GetAugmentType()`.
- Add `$questitem->GetColor()`.
- Add `$questitem->GetCustomData(identifier)`.
- Add `$questitem->GetCustomDataString()`.
- Add `$questitem->GetEXP()`.
- Add `$questitem->GetItem(slot_id)`.
- Add `$questitem->GetItemID(slot_id)`.
- Add `$questitem->GetItemScriptID()`.
- Add `$questitem->GetKillsNeeded()`.
- Add `$questitem->GetMaxEvolveLevel()`.
- Add `$questitem->GetPrice()`.
- Add `$questitem->GetTotalItemCount()`.
- Add `$questitem->IsAmmo()`.
- Add `$questitem->IsAugmentable()`.
- Add `$questitem->IsAugmented()`.
- Add `$questitem->IsEquipable(slot_id)`.
- …

[Quest API] Add missing Item Methods to Perl/Lua.

---

zone/lua_parser.cpp

- `EVENT_LANGUAGE_SKILL_UP` only takes `3` values whereas `EVENT_SKILL_UP` takes `4`.

[Bug Fix] EVENT_LANGUAGE_SKILL_UP in Lua was using EVENT_SKILL_UP logic

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- This is an `unsigned int`, not an `int`, so this fixes that.

[Bug Fix] Fix data type of GetAggroCount()

---

common/repositories/account_flags_repository.h
zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/lua_mob.cpp
zone/lua_object.cpp
zone/perl_client.cpp

- Add `$client->ClearAccountFlag(flag)`.
- Add `$client->GetAccountFlags()`.
- Add `client:ClearAccountFlag(flag)`.
- Add `client:GetAccountFlags()`.
- Made use of repositories and cleaned up existing code.

[Quest API] Add ClearAccountFlag() and GetAccountFlags() to Perl/Lua

---

common/inventory_profile.cpp
zone/loottables.cpp

- This was causing an insane amount of error logs because we were always using `PutItem`, even with a `slot_id` of `-1`.

[Bug Fix] Fix _PutItem having a slot_id of -1 on mobs with no items

---

common/zone_store.cpp
common/zone_store.h

- Compiler did not like possibly returning a reference to a local variable.

[Bug Fix] Fix issue in zone store of returning reference to local variable

---

common/database/database_update_manifest.cpp
common/version.h

- This should resolve issues where the old query fails because it's adding an already existing column to another table.

[Bug Fix] Add chatchannel_reserved_names to a new manifest

---

zone/gm_commands/find/item.cpp

- Move the summon links to the front so they're in a consistent location.

[Cleanup] Move #find item summon links to front

---

zone/command.cpp

- `#itemsearch` did not exist in this alias list.

[Commands] Add #itemsearch alias to #find aliases

---

zone/bot_command.cpp
zone/bot_command.h

Adds pickpocket command for bots true to the version a normal character uses
I was recently doing GoD progression with a bot group and could not progress without the pickpocket skill so wanted to help others that end up stuck in the same spot.

[Bots] Add Pickpocket Command

---

zone/spell_effects.cpp

Add on to a fix a few months back to make sure "stand" was correct on charm.  It turns out follow/guard and stop also need to be initialized.

[Bug Fix] Fix charmed pets to follow when charmed.

---

zone/lua_entity.cpp
zone/lua_entity.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->IsAura()`.
- Add `$mob->IsEncounter()`.
- Add `$mob->IsMerc()`.
- Add `$mob->IsOfClientBot()`.
- Add `$mob->IsOfClientBotMerc()`.
- Add `$mob->IsTemporaryPet()`.
- Add `entity:IsAura()`.
- Add `entity:IsOfClientBot()`.
- Add `entity:IsOfClientBotMerc()`.
- Add `mob:IsTemporaryPet()`.

[Quest API] Add Mob/Entity type check methods to Perl/Lua

---

zone/bot.cpp
zone/bot_command.cpp

- Refactor previous fix #3458 to prevent _'s to leverage the existing "IsValidName" bot method.
- Add more explanation to error message depending on server rule on CamelCase bot names
- Add detection for numbers which would get removed and duplicate bot names created

[Bug Fix] Update bot naming check and add more explanation

---

common/database/database_update_manifest.cpp
common/repositories/base/base_npc_types_repository.h
common/version.h
zone/embparser_api.cpp
zone/gm_commands/wc.cpp
zone/inventory.cpp
zone/lua_general.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/merc.h
zone/mob.h
zone/mob_appearance.cpp
zone/npc.cpp
zone/npc.h
zone/perl_mob.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/zonedb.cpp
zone/zonedump.h

- We were previously using `uint16` which has a max of `65,535`, but some of the new Live textures that are being used have values way beyond this.
- Updates quest API, commands, and database tables that also used `uint16`.

[Feature] Add Support for item textures higher than 65,535

---

common/item_instance.cpp
zone/tradeskills.cpp
zone/zonedb.h

- Keeps players from doing tradeskill combines with augmented items.
- Behavior is Live-like, we don't need a rule since `EVENT_COMBINE` is separate and processed prior to the recipe check.
- String is hard-coded as it's not part of ROF2 `eqstr_us.txt`.

[Bug Fix] Fix Tradeskill Combines with augmented items

---

common/database/database_update_manifest.cpp

The syntax was failing against MariaDB 10.1.  Updated to not use (0) and ("").  Tested against 10.1 and ran fine.

[Database] Fix database manifest entry for #3443

---

common/ruletypes.h
zone/bot_command.cpp

- Add rule for allowing pickpocket
- Fix method that is supposed to check rule, needed to check for false
- Changed Z axis to use Zoffset to account for differences in heights of models

[Bug Fix] Fix rule check and add rule for pickpocket command

---

zone/client.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `$client->SetLDoNPoints(theme_id, points)`.
- Add `client:SetLDoNPoints(theme_id, points)`.
- Allows operators to directly set LDoN Points.

[Quest API] Add SetLDoNPoints() to Perl/Lua

---

zone/mob_ai.cpp

Don't issue zclip adjustments when NPC is not moving

[Z Clipping] Don't issue zclip adjustments when NPC is not moving

---

common/database/database_update_manifest.cpp
common/repositories/base/base_data_buckets_repository.h
common/version.h
zone/bonuses.cpp
zone/bot.cpp
zone/client_process.cpp
zone/data_bucket.cpp
zone/data_bucket.h
zone/exp.cpp
zone/lua_mob.cpp
zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp
zone/spells.cpp

This PR implements scoped data buckets
This means that for common primitives such as `character` `npc` or `bot` that use data-buckets that we represent them as their own columns within the data model and have a unique constraints applied against them.
For example, Quest API methods that use `mob:SetData(name, value)` will automatically scope the `key` to the entity under the hood without an operator needing to additionally add nested keying.
This PR also is pre-cursor to other work, such as distributed data bucket caching and other features.
**This PR still needs to be tested in its entirety**
* Allow for easier manipulation of `data_buckets` as it relates to a mechanism for storing character progress and flags to copy a character, migrate a character's flags and easily select what flags …

[Data Buckets] Implement scoped data buckets

---

zone/mob_ai.cpp
zone/npc.cpp
zone/npc.h
zone/waypoints.cpp

This PR improves pathing
* Roambox logic when path finding will now reject random paths that result in a z difference of 100 units or more. This prevents mobs from choosing to climb mountains like a goat looking entirely unnatural. This will allow mobs to choose more sane pathing decisions.
* Roambox logic no longer relies on line of sight for path finding, it uses the navmesh data to determine if the path is findable, if the path can not be routed to, it will return and attempt another path (there are 10 attempts to find a path in one roambox path finding cycle)
* Should resolve an issue where if an NPC gets drug out of its roambox and it no longer chooses to route back to the roambox because it no longer has line of sight
* Z-Clipping correction now uses navigation mesh path finding to …

[Pathing] Improvements to roambox logic, pathing

---

zone/data_bucket.cpp
zone/data_bucket.h
zone/exp.cpp
zone/mob.cpp
zone/spells.cpp

Fix issue with expired databuckets not being expired and returned properly
**Testing**
```lua
local ldon_request_timer_bucket = ("LDoN_Request-"..e.self:CharacterID());
if eq.get_data(ldon_request_timer_bucket) ~= "" then
e.self:DialogueWindow(string.format("{red} You must wait longer before re-requesting an adventure.~"));
return;
else
e.self:DialogueWindow(string.format("{green} YOU CAN REQUEST ONE NOW.~"));
end
eq.set_data(ldon_request_timer_bucket,"1",tostring(eq.seconds("1m"))); -- 1 minute request cooldown
end
```
Before expired
When expired

[Databuckets] Fix issue with expired databuckets not being expired and returned properly

---

zone/spells.cpp

This PR replaces https://github.com/EQEmu/Server/pull/3501 and removes the hard coded arbitrary blocking of teleport spells within the `tutorial` and `load` zones.
Server operators can still block spells dynamically via db edits.

[Cleanup] Remove arbitrary teleport blocking in Tutorial and Load zones

---

zone/data_bucket.cpp

This fixes a rarer scenario where if you have two keys named the same but one exists globally and one exists on a player, it can result in one being fetched first over the other because global queries where not explicitly filtering out character,npc,bot entries

[Databuckets] Fix rarer same bucket name scoping overlap issue

---

common/say_link.cpp

This fixes some scenarios where saylinks were not being cached at all
Noticed during initial use of `#help` (every command is not cached and not cached once found)
Entries looked up from the database were not being added to the cache either once found

[Saylink] Fix cases where saylinks were not being cached

---

zone/zonedb.cpp

Currently, setting Spells:MaxTotalSlotsPET above the client allowed maximum of 30 will cause the server to crash and could also cause database corruption. This caps the rule at 30.
Still doing some testing on this.

[Crash Fix] Guard against Spells:MaxTotalSlotsPET being set above client allowed maximum.

---

common/repositories/items_repository.h

- String wasn’t being escaped, so things with `’` in the name causes issues.

[Bug Fix] Escape search string in #find item

---

zone/client_packet.cpp
zone/corpse.cpp

- These were uppercase and should be lowercase.

[Cleanup] Fix casing in corpse money and decay time.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->GetMobTypeIdentifier()`.
- Add `mob:GetMobTypeIdentifier()`.
- Gets unique identifier independent of mob type.

[Quest API] Add GetMobTypeIdentifier() to Perl/Lua

---

zone/doors.cpp
zone/doors.h
zone/mob.cpp
zone/mob.h
zone/mob_ai.cpp

There was an issue on Discord that is incredibly obscure, apparently only on Windows, can't be reproduced in a way that makes it easy to trap. @hgtw @KimLS both tried to reproduce and failed to do so and they run Windows development setups as well.
The issue is stems from a door in the zone that is a switch that appears to also be client controlled. Never have I seen in any zone outside of this zone where the client tries to control a door entity in this way. Related PR and issue https://github.com/EQEmu/Server/pull/2824
When a NPC opens it and the door it is related to, the client will try to "force" the door into a zero state when the server hasn't done so itself fast enough and will spam "OP_CLICKDOOR" packets over and over.
Since we've dumped a ton of time into this with no real …

[Doors] Add door blacklist

---

zone/gm_commands/set.cpp

- Typo lead to `#gm on` and `#gm off` not functioning.

[Bug Fix] Fix #gm top level alias for #set gm

---

common/servertalk.h
world/eqemu_api_world_data_service.cpp
world/zoneserver.cpp
zone/client.cpp
zone/data_bucket.cpp
zone/data_bucket.h
zone/gm_commands/reload.cpp
zone/worldserver.cpp

This PR
* Fixes an issue where misses cache isn't properly getting cleared in certain circumstances
* Fixes an issue where updates could be potentially discarded early
* Adds command #reload data_buckets_cache to the reload menu to clear the cache

[Databuckets] Improvements to distributed cache, reload commands

---

zone/npc.cpp
zone/npc_scale_manager.cpp

This is a refinement of a fix by @Kinglykrab in the following PR:
https://github.com/EQEmu/Server/pull/3351
@Kinglykrab addressed an issue where min_dmg was 0 in db and max_dmg was not.  This caused the npc_scale_manager to only scale the min_dmg side, which can result in the min_dmg being bigger than the max_dmg.
This PR fixes a side effect of that PR wherein when min_dmg and max_dmg are both 0 in the db, setting min_dmg 1st results in min_dmg getting put into max_dmg (due to his attempts to keep max_dmg greater than min_dmg inside of ModifyNPCStat()) at all times.
My belief is that if _either min or max dmg is 0 in the db, both need to be processed.  His earlier PR assures that, so long as min_dmg is 0, but not when min_dmg is non-zero and max_dmg is 0.  Admittedly an unlikely case, but …

[Scaling/Bug Fix] Scaling where min and max damage was bugged

---

zone/spell_effects.cpp

- Fixes an issue where Drakkin illusions that used different Drakkin Heritages were not properly applying the Drakkin Heritage due to not sending the Face Appearance.

[Feature] Add Support for Drakkin Heritage Illusions

---

zone/gm_commands/show/zone_loot.cpp

- An item ID was being required, we don't want to do that.
- Cleanup messages to only show item name/item ID

[Cleanup] Cleanup #view zone_loot Command

---

zone/lua_entity_list.cpp
zone/perl_entity.cpp

This PR does a few minor but performance impacting changes
* We shouldn't reserve on the container when we don't know for certain whether or not we end up filtering ourself in the list, we end up returning blank values to the user in the Quest API results. You can double loop but the juice is not worth the squeeze performance wise - I measured this very recently. 
* Also - we are even further filtering based on the distance passed in by the user which further filters down the close list that is compiled from 600 units

[Quest API] Adjust GetCloseMobList calls internally

---

zone/entity.cpp

This wasn't an issue until recently when Quest API entries were exposed that add the ability to read the close mob list.
The close mob list is not scanned until after `EVENT_SPAWN` this moves scanning before EVENT_SPAWN so script callers can rely on the information being there.

[Fix] Fix issue with mob scanning when trying to use EVENT_SPAWN

---

common/item_data.cpp
common/item_data.h
common/ruletypes.h
zone/trading.cpp

Adds the following rule: Pets:CanTakeQuestItems, default true.
As name suggests, rejects items flagged as "Quest" when traded to a pet. The main purpose for this rule is to block players accidentally trading quest items to their pet instead of the desired quest NPC.
Everything works so far in testing.

[Rules] Add rule to toggle pets accepting quest items

---

common/ruletypes.h
zone/effects.cpp

Came up on discord as a useful configuration for some custom servers.

[Rules] Add a rule to adjust the randomization range for Wizard\Caster Merc innate critical ratio.

---

zone/trading.cpp

Quick fix to escape the item names in Trader Audit.

[Bug] Escape item name in trader audit.

---

common/ruletypes.h
zone/npc.cpp
zone/npc.h
zone/trading.cpp
zone/zonedb.cpp
zone/zonedump.h

Adds the following rules: `NPC:ReturnQuestItemsFromNonQuestNPCs`
Default: false
This is another lever to allow server operations to control which NPCs will accept quest flagged items. When enabled, only NPCs flagged as Quest NPCs will accept quest items.
This has been tested on my end succesfully.

[Rules] Add rule to restrict hand in of quest items to quest flagged NPCs.

---

zone/spawn2.cpp

Fixes a rarer issue where spawn2 is not being properly content filtered
As observered when @regneq was working on PoK spawns and was splitting the same NPC onto two separate grids and the wrong pathgrid was being loaded 
**Before**
**After**

[Spawns] Fixes a rarer issue where spawn2 is not being properly content filtered

---

zone/bot.cpp
zone/bot.h
zone/bot_database.cpp

Bots were not loading AA's properly on Spawn due to ```m_expansion_bitmask``` being set after the Bot constructor was called.

[Bug Fix] Bots will now load AAs properly when spawned.

---

zone/bot.cpp

Fixed regression from #3498, Bot::CheckDataBucket was not properly checking owner buckets as ```k.key``` was not being set after ```k = GetBotOwner()->GetScopedBucketKeys();```.

[Bug Fix] Fix Bot::CheckDataBucket to work with Owner Buckets.

---

common/ruletypes.h
zone/aggro.cpp
zone/common.h
zone/hate_list.cpp
zone/mob.h
zone/mob_ai.cpp

This functionality is needed for fights like Ture to be accurate, where their ramp range was 101% of their melee safe range.
Example in lua of utilizing this scripting
```
e.self:SetSpecialAbilityParam(SpecialAbility.area_rampage,8,101;
```

[Feature] Add adjustability for AERampage Range.

---

common/database/database_dump_service.cpp
common/database/database_dump_service.h
utils/sql/peq-dump/peq-dump.sh
world/cli/database_dump.cpp

This solves for an issue where `instance_list` is classified as a state table, yet we hold some semblance of content data in it because some zones are classified as "static global instances" which never expire and are used for v1/v2 zone expansion switches.
We only export static data after the structure of the table was already created.
**Example Output**
```
./bin/world database:dump --static-instance-data --dump-output-to-console
```
```sql
-- MariaDB dump 10.19  Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: mariadb    Database: peq
-- ------------------------------------------------------
-- Server version	10.5.4-MariaDB-1:10.5.4+maria~focal
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET …
```

[Database] Extend dumper CLI utility to export static instance data

---

zone/gm_commands/reload.cpp
zone/worldserver.cpp

- This allows operators to globally reload zone headers without going to every zone individually to do so.

[Feature] Change #reload zone to reload zone headers globally.

---

zone/entity.cpp
zone/entity.h
zone/mob.h
zone/spell_effects.cpp
zone/spells.cpp

On classic servers that do not use the rule AlwaysSendTargetsBuffs, we can only see a charmed pet's buffs if we manually retarget after the charm.  These buffs also remain displayed (including the charm) after charm breaks unless we re-target.  This is a bug.
This PR fixes this issue by updating all client target windows when a mob they have targeted is charmed.  It also clears all the buffs from that clients sight when the charm drops (unless client is a GM, AlwaysSendTargetsBuffs is set, or the groupAAInspectBuffsis in play).

[Charm] Fix to update target windows on charm on/off

---

common/database_instances.cpp

Logic to select next available instance id was incorrect. The correct logic selected the max id + 1 or max reserved + 1, but then it would overwrite if we enabled recycling ids. Additionally, it was incrementing the reserved ids and assigning ids to the max reserved id vice the next available. Finally, it was running the logic twice.

[Instances] Honor reserved instances

---

zone/exp.cpp

This PR fixes a bug introduced in #3554 which would cause the final raid exp modifier to not apply correctly due to it being calculated too late in the code path.

[Bug Fix] Minor adjustment to formula calc position to fix modifier bug.

---

common/ruletypes.h

Rule explanation was incorrect (maybe that was the original implementation?)
Per Bot::CalcManaRegen()
```	float mana_regen_rate = RuleR(Bots, ManaRegen);
if (mana_regen_rate < 0.0f)
mana_regen_rate = 0.0f;
regen = (regen * mana_regen_rate);
return regen;

[Rules] Correct explanation of Bots:ManaRegen

---

zone/entity.cpp

Previous changes to QueueClientsByTarget to allow for clearing the target window of clients who have a charmed mob targetted at the time charm wears off had a bug where it could also clear a client target window that had something else targetted.
The use of the new flag clear_target_window needed to be limited in scope to when inspect_buffs is true.

[HotFix] Clearing target window on CHARM wear off had a side effect

---

zone/bot.cpp

Bots weren't benefiting from AAs that increases Mana.

[Bots] Add Support for Mana Pool AA Bonuses.

---

zone/attack.cpp

@Kinglykrab reported a problem from his server where some pet damage from spells was being missed by observers.
While I think pet damage isn't seen by others on live, as there is no others-pet-filters, this was always a part of eqemu and many parsers used it.
The bug came from my PR back in 2022: https://github.com/EQEmu/Server/pull/2170/files
That PR removed many duplicate messages and added missing color messages, but omitted the ones this PR fixes.
New output as seen by owner of pet that is procing:
[Fri Aug 18 14:11:03 2023] Bristlebanes Warder begins to cast a spell. (Spirit of Scorpion Strike)
[Fri Aug 18 14:11:03 2023] Bristlebanes Warder strikes Kizdean Gix for 92 points of damage.
[Fri Aug 18 14:11:03 2023] Kizdean Gix spasms as the spirit of a scorpion rips through their body . …

[Combat Messages] Fix issue where pet proc damage was not showing up

---

common/database_instances.cpp

Since the IDs start above the minimum, we needed to check if the first slot was available.
Recycle IDs with a gap at max reserved:
```
+----+------+---------+-----------+------------+-----------+---------------+
| id | zone | version | is_global | start_time | duration  | never_expires |
+----+------+---------+-----------+------------+-----------+---------------+
|  1 |   25 |       1 |         1 |          0 |         0 |             1 |
|  2 |   25 |       2 |         1 |          0 |         0 |             1 |
|  3 |  151 |       1 |         1 |          0 |         0 |             1 |
|  4 |  114 |       1 |         1 |          0 |         0 |             1 |
|  5 |  344 |       1 |         1 |          0 |         0 |             1 |
|  6 |  202 |       0 |         1 |          0 | …
```

[Instances] Refine id selection

---

zone/client.cpp

When you click on a target and hit "tracking", the you begin to track <target> message is coming out twice.
Removing this from the server results in one and only one message on both Titanium and RoF2.  
Any reason not to merge this?  Other test I should do?

[Messages] Remove duplicate message on tracking begin

---

zone/attack.cpp

In a previous PR: https://github.com/EQEmu/Server/pull/3551 I fixed a problem where proc messages for some situations were lost.  In the process, I moved all pet messages to the same spot in the code, so they could all be handled correctly using the correct filters.
That spot, was using GetOwnerID() instead of GetOwner() to tell if an npc was a pet.  For some reason Swarm pets do not have an OwnerID.  
This PR only fixes the messaging issue by using GetOwner() in this one spot, to make sure swarm pet messages are not missed.
If swarm pets should have a OwnerID() I leave that to someone with more knowledge of swarms.

[Messages] Swarm pet normal damage messages were missing

---

common/ruletypes.h
zone/attack.cpp

- Allows operators to modify the level gap penalty and level gap required for the penalty for defensive procs' level gap penalty.
- Setting `Spells:DefensiveProcPenaltyLevelGap` to `-1` will disable the penalty.

[Feature] Add Defensive Proc Rules for Level Gap Penalty

---

common/servertalk.h
world/console.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/worldserver.cpp
zone/zoning.cpp

- Add `quest::crosszonemoveplayerbycharid(character_id, zone_short_name, x, y, z)`.
- Add `quest::crosszonemoveplayerbycharid(character_id, zone_short_name, x, y, z, heading)`.
- Add `quest::crosszonemoveplayerbygroupid(group_id, zone_short_name, x, y, z)`.
- Add `quest::crosszonemoveplayerbygroupid(group_id, zone_short_name, x, y, z, heading)`.
- Add `quest::crosszonemoveplayerbyraidid(raid_id, zone_short_name, x, y, z)`.
- Add `quest::crosszonemoveplayerbyraidid(raid_id, zone_short_name, x, y, z, heading)`.
- Add `quest::crosszonemoveplayerbyguildid(guild_id, zone_short_name, x, y, z)`.
- Add `quest::crosszonemoveplayerbyguildid(guild_id, zone_short_name, x, y, z, heading)`.
- Add `quest::crosszonemoveplayerbyexpeditionid(expedition_id, zone_short_name, x, y, z)`.
- Add …

[Quest API] Add XYZ/XYZH Overloads to Cross Zone Move Methods

---

zone/gm_commands/castspell.cpp
zone/mob.cpp
zone/mob.h

- Entities killed by a spell with #cast were not reporting their pre-death entity ID properly.
- Added an `entity_id_override` to `GetTargetDescription()` and added a pre-defined entity ID variable to the cast command so we can message the proper pre-death entity ID.

[Bug Fix] Fix Entity ID on death with #castspell

---

zone/gm_commands/find.cpp
zone/gm_commands/set.cpp
zone/gm_commands/show.cpp

- We were not validating `sep->arg[i]` so we could possibly be pushing a `nullptr` in.

[Bug Fix] Add Validation to #find, #set, and #show args

---

zone/spell_effects.cpp

Swarm pets were created with a space in the name instead of an underscore.
Thereafter, all uses of GetCleanName() resulted in : PlayerName`spet in messages.

[Swarm Pets] Fix pet names to use '_' instead of ' '

---

zone/waypoints.cpp

Call to `Pause` and `Resume` wandering happen with quest subs and shouldn't be considered errors.

[Logs] Change pathing log messages from `Error` to `Pathing`.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp
zone/spells.cpp

- Add `$mob->FindBuff(spell_id, caster_id)`.
- Add `mob:FindBuff(spell_id, caster_id)`.
- Allows operators to check if the spell ID is cast by a specific entity ID.
- We don't use `Mob*` reference here since the mob may have died, left zone, etc.

[Quest API] Add Caster ID Parameter to FindBuff in Perl/Lua

---

zone/groups.cpp

As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11616
Does not look like we validate the bot owner exists trying to compare a potential null pointer. Not guaranteed to fix this.

[Crash] Bot member zoned crash fix

---

zone/aa.cpp

As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11674

[Crash] Fix CanUseAlternateAdvancementRank crash

---

common/ruletypes.h
zone/special_attacks.cpp

- Allows operators to add extra classes to the "Kick" skill.
- Without this only Warrior, Ranger, Monk, Beastlord, and Berserker could kick.

[Feature] Add Extra Kick Classes

---

zone/perl_mob.cpp

- Spire parses methods based on parameters being on the same line, so these were not being parse properly since they were newlines.

[Parser Fix] Fix SendIllusion Spire parsing

---

utils/scripts/import_13th_floor.pl

Legacy research tomes have the wrong bagtype (BACKPACK) blocking the clients from showing the combine button.

[Scripts] Update 13th Floor script for legacy research tome bagtypes

---

common/features.h
zone/gm_commands/castspell.cpp

- Defaulted to using cast time instead of instant.

[Bug Fix] Fix #cast defaulting to cast time

---

zone/aa.cpp
zone/client.h
zone/command.cpp
zone/gm_commands/grantaa.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add optional `level` argument to `#grantaa` so you can grant AAs up the specified level.
- Add `$client->GrantAllAAPoints()`.
- Add `$client->GrantAllAAPoints(unlock_level)`.
- Add `client:GrantAllAAPoints()`.
- Add `client:GrantAllAAPoints(unlock_level)`.
- Grants all AA abilities up to client's current level or a specified level.

[Quest API] Add GrantAllAAPoints() to Perl/Lua and Modify #grantaa

---

zone/bot.cpp
zone/bot.h

- Bots were having a hard time keeping up with players.
- Part of this was due to using walk until a certain distance.
- Another part was their ctor only having `0.7f` run speed versus our Mob sanity check of `1.25f`.
- We check movement stuff now before idle checks so bots are more likely to start moving earlier.

[Bots] Adjust Bot Movement Speed

---

zone/raids.cpp

Regression from #3524. Forming a raid would cause a crash at ```members[i].note = std::string(row[10]);```
Tried multiple resolutions along with @neckkola, however the only way that worked consistently was after switching the method to use Repositories to load in the database.

[Crash] Resolve crash when assigning empty raid note.

---

zone/embparser.cpp
zone/lua_parser_events.cpp
zone/spells.cpp

- Add `$spell` export to `EVENT_CAST`, `EVENT_CAST_BEGIN`, `EVENT_CAST_BEGIN`, `EVENT_ITEM_CLICK`, `EVENT_ITEM_CLICK_CAST`, `EVENT_ITEM_CLICK_CLIENT`, `EVENT_ITEM_CLICK_CAST_CLIENT`, `EVENT_SPELL_EFFECT_BUFF_TIC_BOT`, `EVENT_SPELL_EFFECT_BUFF_TIC_CLIENT`, `EVENT_SPELL_EFFECT_BUFF_TIC_NPC`, `EVENT_SPELL_EFFECT_BOT`, `EVENT_SPELL_EFFECT_CLIENT`, `EVENT_SPELL_EFFECT_NPC`, `EVENT_SPELL_FADE`, `EVENT_DEATH`, `EVENT_DEATH_COMPLETE`, `EVENT_DEATH_ZONE`, `EVENT_DAMAGE_GIVEN`, and `EVENT_DAMAGE_TAKEN` in Perl.
- Add `$target_id`and `$target` exports to `EVENT_CAST`, `EVENT_CAST_BEGIN`, and `EVENT_CAST_ON` in Perl.
- Add `e.target_id` and `e.target` exports to `EVENT_CAST`, `EVENT_CAST_BEGIN`, and `EVENT_CAST_ON` in Lua.

[Quest API] Add target ID and spell exports to events

---

common/database/database_update_manifest.cpp

Our `items` table has 5 fields that need to adjust in order to pull data from 13th Floor.

[DB] Adjust `items` structure for import

---

zone/mob.cpp

As observed in http://spire.akkadius.com/dev/release/22.25.0?id=12036
Spell data bucket being accessed when we don't know if the spell is valid

[Crash] Fix crash in Mob::ShowBuffs

---

common/database/database_update_manifest.cpp
common/version.h

The field itself is unimplemented currently, just adds the field to the database to accompany eqtraders data imports

[Tradeskills] Add learned_by_item_id field

---

zone/attack.cpp

- We were double adding `spellbonuses` and not adding `itembonuses` per https://github.com/EQEmu/Server/issues/3636.

[Bug Fix] Fix Finishing Blow Proc Chance

---

zone/bot.cpp

Change to use CleanName.
[crash_sleeper_version_2_inst_id_11115_port_7020_2611722.log](https://github.com/EQEmu/Server/files/13058476/crash_sleeper_version_2_inst_id_11115_port_7020_2611722.log)

[Bug Fix] Fix crash when checking Bot Group/Raid membership

---

common/database/database_update_manifest.cpp
common/version.h
zone/zone.cpp
zone/zonedb.cpp
zone/zonedb.h

- Allows operators to filter blocked spells behind expansions or content flags.
- Requested in https://github.com/EQEmu/Server/issues/3582

[Feature] Add Expansion and Content Flag support to Blocked Spells

---

zone/command.cpp

- We were checking for `arguments >= 2` when we should just be checking for if there are any arguments and comparing `sep.arg[0]` (the command) and `sep.arg[1]` (the subcommand) to our `command_subsettings` to see if it exists and if we pass the requirements.
- This fix will let operators properly set a subcommand to a lower or higher status level than the parent command.

[Bug Fix] Fix issue with subcommand settings not working

---

zone/command.cpp

If no hotfix name is provided, the hotfix command won't need the empty string.
Seen in http://spire.akkadius.com/dev/release/22.28.0?id=13585

[Bug Fix] Hotfix command without hotfix name

---

ucs/database.cpp

No need to verify mail key when none exist.
As seen in http://spire.akkadius.com/dev/release/22.28.0?id=12069

[Bug Fix] Verifying mail keys when none exist

---

zone/embparser.cpp
zone/embparser.h

Perl wasn't implementing quest interface's Init which is called by Zone::Bootup. This should fix zone's that were in standby not using the latest version of perl plugin scripts.
This needs tested to make sure it doesn't break something. This doesn't touch lua but I'm not sure why https://github.com/EQEmu/Server/pull/3333/files would have broken encounters since lua parser already implements Init and calls ReloadQuests after zone init.

[Perl] Reload perl quests on zone bootup

---

zone/spell_effects.cpp

This closes a small exploit wherein casting the alliance line of spells on a charmed pet impacted all NPCs of that pet's original faction within the zone.
Casting alliance on a charmed pet on live has no observable impact whatsoever.

[Pets] Disallow effect of alliance line when cast on pets.

---

zone/bot.cpp

Not checking if the vector is empty before it inserts still inserts when there’s nothing.

[Bug Fix] Fix empty insert many in bot starting items.

---

zone/trading.cpp

This fixes part 3 of issue [932](https://github.com/EQEmu/Server/issues/932).
Part 2 is already fixed.
Part 1 is a feature to me.  So unless anyone cares that the mob turns toward you when you do a task turn in, I'd be all for closing issue 932.  If not, this PR stands on its own strength.
The previous [attempt ](https://github.com/EQEmu/Server/pull/3585)at fixing this did not work properly and the review was never replied to.

[Trading] Fix part 3 of Issue 932.

---

utils/scripts/build/linux-build.sh

As seen in Linux release build, we are missing symbols http://spire.akkadius.com/dev/release/22.30.2?id=13725
We still want the binaries to be optimized as well

[Linux] Add symbols to release builds

---

zone/command.cpp

As seen in http://spire.akkadius.com/dev/release/22.28.0?id=13588
Using the client pointer may not necessarily be thread safe, safer to just broadcast a GM message to the world

[Crash] Fix crash when client pointer does not exist during #hotfix

---

zone/zoning.cpp

- These messages were sending to users and not being logged.
- `Message(Chat::Red, "Error: OP_EndLootRequest: Corpse not found (ent = 0)");` sends often when corpse expires right as you try to loot, so it makes the user think there's a true error.

[Logs] Convert Loot Messages to Error Logs

---

zone/embparser_api.cpp

- Two lines were using the same parameters.

[Bug Fix] Fix Perl__worldwideremovetask Package

---

zone/embparser_api.cpp

- This formatting was causing Spire not to pick up the parameters.

[Parser] Cleanup Spire Parsing for crosszonemoveplayerbyexpeditionid

---

zone/embparser_api.cpp

- This formatting was causing Spire not to pick up the parameters.

[Parser] Cleanup Spire Parsing for crosszonemoveplayerbyguildid

---

zone/embparser_api.cpp

- This formatting was causing Spire not to pick up the parameters.

[Parser] Cleanup Spire Parsing for crosszonemoveplayerbygroupid

---

zone/embparser_api.cpp

- This formatting was causing Spire not to pick up the parameters.

[Parser] Cleanup Spire Parsing for crosszonemoveplayerbycharid

---

zone/embparser_api.cpp

- `IsTGBCompatibleSpell` was not exported properly.

[Bug Fix] Add IsTGBCompatibleSpell() to package.add

---

common/serverinfo.h

Fixes ` ‘uint64_t’ does not name a type ` error under GCC 13

[GCC] Compatibility fix for GCC 13

---

zone/raids.cpp
zone/raids.h

A crash condition was being seen in CentOS after the conversion of raid notes from char[] to std::string.  It was not seen in other linux distros or on windows though it appears that it would have eventually been seen.
Issue was duplicated on a new CentOS 7 install and was traced to the memset usage in the raid constructors and LearnMembers as it was overwriting the std::string structure.  
Added default initializers to RaidMember struct as well.
Tested with the CentOS install and on a windows install by forming a raid with a Bot, moving/rearranging groups, attacking and zoning.  Would appreciate others testing as an added layer.  OP of crash is testing in the next few days.
Thanks,
Neckkola

[CRASH] Fix crash on CentOS when forming a raid with PCs or BOTs

---

zone/bot_command.cpp

Previously this check allowed bots of invalid races to be created. If a race was neither a valid combination or a valid player race, it would pass the check and allow bots of any race to be created.
**^create 1 123 0** could create a Male Innoruuk Warrior
_I can modify this if needed to allow the IsPlayerRace check to remain, although I feel if players modify their creation table to allow non-player races, they should be allowed to create them even if it causes items to not be usable_

[Bots] Fix invalid races from being created

---

CHANGELOG.md
common/version.h
package.json

* Fix invalid races from being created ([#3681](https://github.com/EQEmu/Server/pull/3681)) @nytmyr 2023-11-06
* Fix crash on CentOS when forming a raid with PCs or BOTs ([#3676](https://github.com/EQEmu/Server/pull/3676)) @neckkola 2023-11-06
* Add IsTGBCompatibleSpell() to package.add ([#3675](https://github.com/EQEmu/Server/pull/3675)) @Kinglykrab 2023-11-04
* Fix Perl__worldwideremovetask package ([#3670](https://github.com/EQEmu/Server/pull/3670)) @Kinglykrab 2023-11-04
* Revert " Fix Killed XYZH support in EVENT_DEATH in Perl. " (#3682) ([#3591](https://github.com/EQEmu/Server/pull/3591)) @fryguy503 2023-11-06
* Compatibility fix for GCC 13 ([#3677](https://github.com/EQEmu/Server/pull/3677)) @joligario 2023-11-05
* Cleanup Spire Parsing for crosszonemoveplayerbycharid …

[Release] 22.32.0

---

zone/embparser_api.cpp

- This was incorrect and would cause `GetZoneGravity()` to function improperly in Perl.

[Bug Fix] Fix GetZoneGravity package.add

---

common/item_data.h
common/shareddb.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/lua_item.cpp
zone/lua_item.h
zone/perl_questitem_data.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add `quest::getitemcomment(item_id)`.
- Add `quest::getitemlore(item_id)`.
- Add `$questitemdata->GetComment()`.
- Add `eq.get_item_comment(item_id)`.
- Add `eq.get_item_lore(item_id)`.
- Add `item:Comment()`.
- Added the ability for operators to pull these fields from item data without a database hit.
- Fixed a bug in `embparser_api.cpp` where `GetZoneGravity` was connected to the wrong methods.

[Feature] Add Comment to Item Data/Quest API

---

zone/mob.cpp

This PR re-fixes the issue I fixed in this [PR](https://github.com/EQEmu/Server/pull/3376).
It was rebroken as a result of many fixes put in via this [PR](https://github.com/EQEmu/Server/pull/3520).
The problem is that when using RandomizeFeatures (which does not alter texure), textture gets set back to 0xFF.
I reapplied my fix to the new code and it once again works properly.
To see bug: spawn an npc wth a custom texture (like 12).
Use RandomizeFeatures.
Texture is lost.
This fixes it by not saving the texture if it was not supplied as a value other that 0xFF.

[Illusions] RandomizeFeatures erased texture.

---

common/eq_constants.h
zone/client.cpp
zone/gm_commands/show/currencies.cpp

- Cleans up messages.
- Adds an enum for `MoneyTypes` and `MoneySubtypes` so we're not using magic numbers for `GetMoney` anymore.
- Converts money amounts to `uint64`.

[Cleanup] Cleanup #show currencies Command

---

zone/gm_commands/giveitem.cpp
zone/gm_commands/summonitem.cpp

- Adds summoned messages for `#giveitem` and `#summonitem`.
- `#summonitem` did not stop you from summoning items beyond your status level.
- Use `Strings::ToUnsignedInt` instead of `Strings::ToInt` for augment item IDs.

[Cleanup] Cleanup #giveitem and #summonitem

---

zone/botspellsai.cpp

Hate Reduction, Slow and DoT spells were failing IsValidSpellRange checks due to improper spell IDs being checked.
They were using the first spell in a bot's spell list by checking botSpell.SpellId vs the proper spells in the loop.

[Bug Fix] Fix some spell types failing IsValidSpellRange check

---

zone/mob.cpp

I PR'd this rule a while back but only modified the CalcHaste function in client_mods.cpp. It wasn't until recently I discovered that #mystats/#showstats was displaying incorrect haste values. After making a thread in discord about it Nite pointed out that showstats uses GetHaste in mob.cpp to calculate haste to display and suggested we should probably update GetHaste to incorporate this rule. This seems to work as expected and I'm getting proper haste display in #showstats as of now. I made sure to include IsClient() checks as Nite suggested since this function is also used by mobs.

[Bug Fix] Add "IgnoreLevelBasedHasteCaps" rule to GetHaste() to fix showstats

---

zone/hate_list.cpp

- https://github.com/EQEmu/Server/pull/3595 caused bots, bot pets, and mercenaries to be removed from hate list because we were only checking for `IsClient()` not `IsOfClientBotMerc()`.
- Resolves an issue mentioned [here](https://discord.com/channels/212663220849213441/1177288302383079534) where NPCs would run past bots/mercenaries to attack the owner.

[Bug Fix] Fix bots/Mercenaries being removed from hatelist

---

zone/gm_commands/guild.cpp

Seems like it just spews a message.
Using #guild set Bobo 0 does not remove Bobo from the guild he is in.
It does now.
Poor Bobo.

[Commands] #guild set CharName 0 did not remove char from guild.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->GMMove(x, y, z, heading, save_guard_spot)`.
- Add `mob:GMMove(x, y, z, heading, save_guard_spot)`.
- Operators weren't able to disable saving guard spots, so moving with `GMMove` meant NPCs stayed where they were moved.

[Quest API] Add GMMove Overloads to Perl/Lua

---

common/repositories/command_subsettings_repository.h
zone/aa.cpp
zone/client.h
zone/gm_commands/show.cpp
zone/gm_commands/show/aas.cpp

- Allows operators to view AAs a player has purchased from ingame and their ranks.

[Commands] Add #show aas Command

---

zone/client.h
zone/gm_commands/task.cpp
zone/task_client_state.cpp
zone/task_client_state.h

- `#task complete [Task ID]` allows operators to complete an entire task without updating individual activities.
- Added task names to messages so you know which task you updated, assigned, etc.

[Commands] Add #task complete Command

---

zone/groups.cpp
zone/groups.h

- Utilizes fixes posted in https://github.com/EQEmu/Server/issues/3706 to resolve https://github.com/EQEmu/Server/issues/368.
- Changing group leader caused issues because we assumed `member[0]` was always leader.

[Bug Fix] Changing Group Leader Invalidated GetLeaderName()

---

zone/mob.cpp
zone/mob.h

The alliance line of faction spells can only impact (1) faction at a time.  The existing code allows an infinate #.
This video shows on live how it works:
https://github.com/EQEmu/Server/assets/8644833/9977a8ba-caf8-4e79-bff4-28ffeb874ad1
Looking at my local DB and projecteq, there are only 6 spells that use SE_AddFaction and they are all the alliance line, or a guide version of it.
If someone has added a custom SE_AddFaction to there server, and wants it stick, regardless of the alliance line, we'd need something further.  But as it stands, this is much siumpler, and more accurate.

[Faction] Alliance line is only allowed 1 faction change at a time.

---

zone/worldserver.cpp

Reports that guild mail would fail if sending to 50 members.
Analysis indicated that the buffer holding the inbound message was set with a 512 char limit.  This truncated the message and caused the issue. 
Refactored to adjust the size of the buffer based on the inbound message size.

[Bug Fix] Guild Message limits

---

common/database/database_update_manifest.cpp
common/repositories/base/base_starting_items_repository.h
common/shareddb.cpp
common/version.h

- Convert `class`, `deityid`, `race`, and `zoneid` columns to `|` separated columns.
- Consolidates up to 15 rows per item down to a singular row.
- Allows ease of use for operators.
- Entire process is automated and creates a backup of pre-existing table.

[Database] Consolidate Starting Items Table

---

common/database/database_update_manifest.cpp
common/repositories/base/base_items_repository.h
common/repositories/items_repository.h
common/version.h

From https://mariadb.com/kb/en/datetime/, `datetime` can be ZERO_DATE (`0000-00-00` with no time component) or between `1000-01-01 00:00:00.000000` and `9999-12-31 23:59:59.999999`. Currently, `updated` is the only datetime field that is `NOT NULL` and improperly defaulted to `0000-00-00 00:00:00`. This change matches existing structures of the other `datetime` columns.

[Database] Modify `updated` column in `items` table with proper default.

---

zone/client.cpp

- Using this method did not call `EVENT_AA_GAIN`.

[Quest API] Add EVENT_AA_GAIN to AddAAPoints()

---

zone/mob_ai.cpp

- https://github.com/EQEmu/Server/pull/3595 made swarm pets require the `npc_aggro` flag to be set to attack.

[Bug Fix] Fix Swarm Pets Requiring NPC Aggros Flag

---

zone/bot.cpp

Previously bots would need to be zoned or camped/spawned to begin using new spells for their level.

[Bots] Fix bots learning spells on level

---

common/ruletypes.h
zone/bot.cpp

Adds the rule ***Bots, BotHealOnLevel***, default false, to control whether or not bots will gain full health and mana when their owner levels.

[Bots] Add BotHealOnLevel to fully heal/mana on level.
