- zone/gm_commands/timers.cpp
- Cleanup popup window and add a message for if there are no recast timers.
> [Commands] Cleanup #timers Command.

- zone/bot.cpp
- zone/embparser.cpp
- zone/lua_parser.cpp
- zone/lua_parser_events.cpp
- zone/lua_parser_events.h
- zone/quest_parser_collection.cpp
* [Bots] Add Bot support for EVENT_TRADE
> [Bot] Add EVENT_TRADE Support to Bots.

- zone/embparser.cpp
#ifdef BOTS is needed for non-Bots compile.
> [Hot Fix] Fix non-Bot Compile.

- common/database_instances.cpp
> [Hotfix] Instances Repository Fix

- zone/command.cpp
- zone/gm_commands/chat.cpp
> [Commands] Cleanup #chat Command.

- common/database_instances.cpp
- zone/command.h
- zone/gm_commands/npcedit.cpp
- Make use of repositories and cleanup logic.
> [Commands] Cleanup #npcedit Command.

- zone/command.cpp
- zone/gm_commands/gearup.cpp
- Add support for gearing up target client (with #gm on) and/or target bots.
> [Commands] Cleanup #gearup Command.

- zone/bot.cpp
- zone/botspellsai.cpp
Bards previously wouldn't cast any Buff Type spells (not commonly used, but can be some exceptions)
> [Bot] Add Buff support for Bards under AI_IdleCastChecks

- common/database_instances.cpp
- common/repositories/instance_list_player_repository.h
Instance code used to use a `REPLACE INTO`, add an extended repository method to do this so we're not getting `DUPLICATE` errors.
> [Bug Fix] Fix Instance Repository

- common/repositories/base/base_bot_data_repository.h
- common/repositories/template/base_repository.template
- zone/bot.h
- zone/bot_database.cpp
- General code cleanup, as manually adding to these queries doesn't scale very well.
> [Bots] Convert Load, Save, SaveNew, and Delete to Repositories.

- common/repositories/base/base_bot_data_repository.h
- common/repositories/template/base_repository.template
> [Hot Fix] Fix Bot Data Repository

- zone/command.cpp
- zone/gm_commands/scale.cpp
> [Commands] Cleanup #scale Command.

- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/mob.cpp
- zone/mob.h
- zone/perl_mob.cpp
- Add `$mob->CopyHateList(to_mob)`.
- Add `mob:CopyHateList(to_mob)`.
- Allows operators to easily copy and entire hatelist from one mob to another.
> [Quest API] Add CopyHateList() to Perl/Lua.

- common/ruletypes.h
- zone/client_packet.cpp
Allows preventing pet zoning from happening for more classic servers.
> [Rules] rule gate pet zoning

- common/eqemu_logsys_log_aliases.h
- common/shareddb.cpp
- zone/attack.cpp
- zone/bot.cpp
- zone/botspellsai.cpp
- zone/client_mods.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/groups.cpp
- zone/merc.cpp
- zone/mob.cpp
- zone/mob_ai.cpp
- zone/raids.cpp
- zone/spell_effects.cpp
- zone/waypoints.cpp
- zone/worldserver.cpp
Make logging similar between Bots, NPC, Mercs. less waypoint spam at General/Moderate logging levels.
> [Logging] More AI Logging Cleanup

- common/servertalk.h
- zone/command.cpp
- zone/command.h
- zone/gm_commands/suspendmulti.cpp
- zone/worldserver.cpp
- Allows operators to suspend multiple people at once in case they have  a player who is boxing and want to suspend them all at once.
> [Commands] Add #suspendmulti Command.

- zone/attack.cpp
- This log fires every time for no reason.
> [Bug Fix] Remove Unnecessary Attack Log

- zone/embperl.cpp
Add back in process based syntax validation. The overhead was not that bad until we can get the Perl C API to return errors and not require `return 1` at the end of a plugin
> [Quests] Improve Quest Error Handling

- zone/object.cpp
Added code to allow ground spawns to be discovered items.
> Add ground spawns to discovered items feature.

- common/ruletypes.h
- zone/client.cpp
This rule allows death to fully fill Mana or Endurance.
> [Rule] Add ManaOnDeath and EndurOnDeath

- zone/aggro.cpp
Formatting, and cleanup Magic Numbers
> [Aggro] Cleanup Mob::CombatRange

- common/ruletypes.h
- zone/special_attacks.cpp
Add rules to disable elemental and bane damage on backstab.
> [Rules] Add Backstab Rules

- utils/sql/git/required/2022_12_15_character_exp_toggle.sql
- utils/sql/git/required/2022_12_24_character_exp_toggle.sql
Was not correctly named under #2676
> [Hotfix] Corrected misnamed Database Query file for Experience Toggle

- .gitignore
These were starting to drive me crazy, figure might be useful for others.
> [Git] Add Clangd Generated Files to .gitignore

- common/inventory_profile.h
- zone/embparser_api.cpp
- zone/inventory.cpp
- zone/lua_general.cpp
- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/mob.cpp
- zone/mob.h
- zone/perl_mob.cpp
- zone/questmgr.cpp
- zone/questmgr.h
- Adds the ability to get an item's augment slot types and augment slot visibility information.
> [Quest API] Add Augment Slot Type/Visible to GetItemStat

- zone/inventory.cpp
Causes compile error on Windows as it can't handle it.
https://kb.froglogic.com/coco/troubleshoot/blocks-nested-too-deeply/
> [Hotfix] Blocks are nested too deeply.

- zone/entity.cpp
Should be EventPlayer, not EventNPC.
> [Bug Fix] EVENT_ENTER_AREA/EVENT_LEAVE_AREA.

- zone/doors.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Using `#door create` then `#door save` was overwriting doors instead of using the next highest ID.
- Remove the following unused methods.
```cpp
uint32 GetGuildEQID(uint32 guilddbid);
void UpdateDoorGuildID(int doorid, int guild_id);
int32 GetDoorsCount(uint32* oMaxID, const char *zone_name, int16 version);```
> [Bug Fix] Fix #door Save

- common/ruletypes.h
- zone/zone.cpp
- Adds a rule for LDoN Adventure Loot.
- Resolves https://github.com/EQEmu/Server/issues/670
> [Rules] Add LDoN Loot Count Modifier Rule

- zone/command.cpp
- zone/command.h
- zone/gm_commands/findcharacter.cpp
- Add `#findcharacter [Search Criteria]`.
- Allows operators to search for characters by ID or a portion of their name to easily get ID/Name.
> [Commands] Add #findcharacter Command

- common/spdat.cpp
- common/spdat.h
- zone/botspellsai.cpp
Adds support for Bots to use Healing spells that use a Trigger, added SPAs below:
SE_TriggerOnCast
SE_SpellTrigger
SE_ApplyEffect
SE_Trigger_Spell_Non_Item
> [Bots] Add Support to Heals to allow Trigger based Spells

- common/spdat.h
- utils/mods/spell_formula.lua
- zone/lua_general.cpp
- zone/lua_mod.cpp
- zone/lua_mod.h
- zone/lua_parser.cpp
- zone/lua_parser.h
- zone/mob.h
- zone/spell_effects.cpp
Example code in utils/mods/spell_formula.lua
> [Luamod] Add CalcSpellEffectValue_formula to luamods 

- zone/effects.cpp
- zone/spell_effects.cpp
- zone/zone.cpp
- Resolves https://github.com/EQEmu/Server/issues/338
> [Cleanup] Make use of std::abs where possible.

- zone/exp.cpp
- zone/groups.h
- zone/raids.h
Fixes issue where XP was broken when grouped, introduced under #2741
> [Bug Fix] Fix Group XP not working.

- common/rulesys.cpp
- common/rulesys.h
Just do some casts and add some constants to make life easier
> [C++20] Arithmetic on different enums is deprecated on C++20

- zone/command.cpp
- zone/gm_commands/appearanceeffects.cpp
- zone/mob.cpp
- zone/mob.h
> [Commands] Cleanup #appearanceeffects Command.

- zone/doors.cpp
- zone/doors.h
- zone/gm_commands/door_manipulation.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Resolves an issue with `.1` versus `0.1`.
- Resolves an issue with updating a pre-existing door.
- Adds `heading` to the update/insert.
> [Cleanup] Cleanup #door Command.

- zone/bot_command.cpp
- These messages were showing weirdly and inconsistently, cleaned them up to show at max 4 per line.
- `^viewcombos` now shows class name and ID in the popup title.
- `^create help` now shows proper class names and IDs instead of `{}`.
`^create help`
`^viewcombos 1`
> [Bots] ^create and ^viewcombos popup messages fix.

- world/client.cpp
Seen: http://spire.akkadius.com/dev/release/22.1.2?id=231
> [Crash] Fix crash issue with log formatting during character creation

- zone/lua_bot.cpp
- zone/lua_bot.h
- zone/perl_bot.cpp
Added to both Lua and Perl following methods for Bots:
GetAugmentIDsBySlotID 
AddItem
> [Bots] Add GetAugmentIDsBySlotID & AddItem with table ref Methods.

- zone/embparser_api.cpp
- zone/lua_general.cpp
- zone/questmgr.cpp
DoesAugmentFit finds if an Aug Slot is free, changed overload method to check if Aug fits slot... as that was the original purpose for adding it.
> [Bug Fix] Fix does_augment_fit_slot method.

- zone/gm_commands/list.cpp
The #list command will now search entities / objects without case sensitivity
> [Command] #list now searches without case sensitivity

- zone/bot_command.cpp
Fix crash in bot command botdyearmor
Was assuming valid input
As seen in v22.2.0 http://spire.akkadius.com/dev/release/22.2.0?id=282
> [Crash] Fix crash in bot command botdyearmor

- CHANGELOG.md
- common/version.h
- package.json
- utils/scripts/build/linux-build.sh
- utils/scripts/build/should-release/go.mod
- utils/scripts/build/should-release/main.go
- utils/scripts/build/windows-build.ps1
* Add GetAugmentIDsBySlotID & AddItem with table ref Methods. ([#2805](https://github.com/EQEmu/Server/pull/2805)) ([Aeadoin](https://github.com/Aeadoin)) 2023-01-29
* #list now searches without case sensitivity ([#2825](https://github.com/EQEmu/Server/pull/2825)) ([Akkadius](https://github.com/Akkadius)) 2023-02-06
* Remove extraneous else from #weather ([#2819](https://github.com/EQEmu/Server/pull/2819)) ([Kinglykrab](https://github.com/Kinglykrab)) 2023-02-01
* Fix IsUnderwaterOnly crash where npc data references can be stale ([#2830](https://github.com/EQEmu/Server/pull/2830)) ([Akkadius](https://github.com/Akkadius)) 2023-02-06
* Fix command crash with #npcedit weapon when second weapon not passed ni ([#2829](https://github.com/EQEmu/Server/pull/2829)) …
> [Release] 22.3.0

- zone/client.cpp
- zone/embparser.cpp
- Exports `$item` to `EVENT_DISCOVER_ITEM`.
> [Quest API] Export $item to EVENT_DISCOVER_ITEM in Perl

- zone/client.cpp
- zone/entity.cpp
- zone/entity.h
> [Quest API] (Performance) Check event exists before export and execute EVENT_AGGRO_SAY, EVENT_SAY, and EVENT_PROXIMITY_SAY

- zone/cheat_manager.cpp
- zone/entity.cpp
- zone/task_client_state.cpp
> [Quest API] (Performance) Check event EVENT_FEIGN_DEATH exists before export and execute

- zone/bot_command.cpp
- zone/questmgr.cpp
> [Quest API] (Performance) Check event exists before export and execute EVENT_BOT_CREATE

- zone/client.h
- zone/mob.cpp
- zone/mob.h
- zone/spell_effects.cpp
- zone/spells.cpp
Bots and Mercs had no support for Sympathetic Procs
> [Bots & Mercs] Add Support for TrySympatheticProc

- zone/spell_effects.cpp
Bots were not receiving Item or AA Bonuses for TryTriggerOnCastFocusEffect
> [Bots] Add Support for TryTriggerOnCastFocusEffect

- zone/mob.cpp
Fix issue with EVENT_HP firing, regression from https://github.com/EQEmu/Server/pull/2904
> [Hotfix] Fix issue with EVENT_HP firing regression from #2904

- zone/mob.cpp
Fixes HP_EVENT regression. Previous hotfix https://github.com/EQEmu/Server/pull/2924 was merged prematurely before adequate testing
> [Hotfix] Fix HP_EVENT regression

- CHANGELOG.md
- common/version.h
- package.json
* Add Additional HeroicAgi/Dex Modifiers. ([#2838](https://github.com/EQEmu/Server/pull/2838)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-07
* Add Additional HeroicStr modifiers. ([#2837](https://github.com/EQEmu/Server/pull/2837)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-07
* Add IsBot() to methods in attack.cpp where applicable. ([#2840](https://github.com/EQEmu/Server/pull/2840)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-09
* Add Lore Check for Augments. ([#2874](https://github.com/EQEmu/Server/pull/2874)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-12
* Add Pet Power Support for Temp Pets. ([#2853](https://github.com/EQEmu/Server/pull/2853)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-11
* Add Support for TryTriggerOnCastFocusEffect …
> [Release] 22.4.0

- zone/questmgr.cpp
Fix issue with item instances not being validated properly before accessing causing crashes on hand-in
Related to https://github.com/ProjectEQ/projecteqquests/pull/1373
> [Player Events] Fix issue with item instances not being validated properly before accessing causing crashes on handin

- zone/mob.cpp
Fix NPC targetting dev tools display window
Stopped working from https://github.com/EQEmu/Server/pull/2870
> [Fix] Fix NPC targetting dev tools display window

- zone/bot.cpp
- zone/bot_command.cpp
Resolved crash with EVENT_UNEQUIP_ITEM_BOT to do with casting of pointer to const value.
> [Crash] Fix crash with EVENT_UNEQUIP_ITEM_BOT

- CHANGELOG.md
- common/version.h
- package.json
* Change HasBotItem(item_id) to return slot_id instead of bool. ([#2966](https://github.com/EQEmu/Server/pull/2966)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-19
* Change SaveTimers to Replace instead of Insert. ([#2951](https://github.com/EQEmu/Server/pull/2951)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-18
* Fix output of ^spells while ^Enforcespellsettings is enabled ([#2959](https://github.com/EQEmu/Server/pull/2959)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-18
* Fix crash with EVENT_UNEQUIP_ITEM_BOT ([#2973](https://github.com/EQEmu/Server/pull/2973)) ([Aeadoin](https://github.com/Aeadoin)) 2023-02-20
* Fix world crash in player event processing ([#2960](https://github.com/EQEmu/Server/pull/2960)) ([Akkadius](https://github.com/Akkadius)) 2023-02-18
* Address …
> [Release] 22.4.3

- zone/command.h
- zone/gm_commands/peekinv.cpp
- `#peekinv all`
- `#peekinv equip`
- `#peekinv bank`
> [Commands] Cleanup #peekinv Command

- zone/tradeskills.cpp
This accounts for bad data in Tradeskill Recipe Entries, and fixes regression bug with lore checks being performed against loregroups above 0.
Bad Data is being entered into Tradeskill Recipe Entries where  PEQ Editor (possibly other tools) creates a separate entry for success/failcount/salvage, and components even if it's the same item_id, instead of just updating the existing entry in the database.
This PR will find if an item has a component count, and then ignore any duplicate entries of that item_id.
I've performed extensive testing of this, and confirmed the issue described in http://www.projecteq.net/forums/index.php?threads/dru-2-0-turnin-crash.17503/ has been resolved.
> [Bug Fix] Account for bad data in Tradeskill Recipe Entries

- zone/client.h
> [Cleanup] Remove unused ClientFactory in client.h

- zone/client.h
- zone/inventory.cpp
> [Cleanup] Remove ReturnItemPacket from client.h/inventory.cpp

- zone/mob.h
> [Cleanup] Remove class EGNode from mob.h

- zone/titles.cpp
- zone/titles.h
> [Cleanup] Remove NumberOfAvailableTitles() from titles.h

- zone/zonedb.cpp
> [Cleanup] Remove unused iterator from LoadCharacterDisciplines

- zone/embparser_api.cpp
- zone/questmgr.cpp
- zone/questmgr.h
> [Bug Fix] Fix npcfeature and playerfeature

- CHANGELOG.md
- common/version.h
- package.json
* Add additional Heroic Sta/Wis/Int bonuses for Bots. ([#3013](https://github.com/EQEmu/Server/pull/3013)) @Aeadoin 2023-03-01
* Cleanup AI_IdleCastCheck Logic ([#3004](https://github.com/EQEmu/Server/pull/3004)) @Aeadoin 2023-02-26
* Delete unused zone/skills.h ([#3007](https://github.com/EQEmu/Server/pull/3007)) @Kinglykrab 2023-02-27
* Remove DumpPacketProfile() from client.h ([#3000](https://github.com/EQEmu/Server/pull/3000)) @Kinglykrab 2023-02-26
* Remove GetCombinedAC_TEST() from client.h ([#2999](https://github.com/EQEmu/Server/pull/2999)) @Kinglykrab 2023-02-26
* Remove GetDamageMultiplier() from client.h ([#3001](https://github.com/EQEmu/Server/pull/3001)) @Kinglykrab 2023-02-26
* Remove NumberOfAvailableTitles() from titles.h …
> [Release] 22.4.5

- zone/client.cpp
- zone/client.h
- zone/lua_client.cpp
- zone/lua_client.h
- zone/perl_client.cpp
- This is unused and does nothing in both Perl and Lua.
> [Cleanup] Remove unused SaveBackup in client.h

- zone/client.h
> [Cleanup] Remove unused HandleUpdateTasksOnKill in client.h

- zone/client.h
> [Cleanup] Remove unused AbilityTimer variable in client.h

- zone/client.cpp
- zone/client.h
- This function was unused, make use of it.
> [Cleanup] Utilize SetFilter in client.cpp

- zone/bot_structs.h
> [Cleanup] Remove unused bot structs in bot_structs.h

- zone/command.cpp
- zone/gm_commands/wc.cpp
> [Commands] Cleanup #wc Command

- zone/gm_commands/picklock.cpp
> [Commands] Cleanup #picklock Command

- zone/command.cpp
- zone/gm_commands/interrupt.cpp
> [Commands] Cleanup #interrupt Command

- zone/npc_scale_manager.cpp
- These had typos and didn't work.
> [Bug Fix] Fix Heal Scale and Spell Scale in NPC Scaling

- zone/bot.cpp
- zone/merc.cpp
- zone/mob.cpp
- zone/mob_ai.cpp
- This method was unused, make use of it.
> [Cleanup] Utilize GetPlayerState() in mob methods

- zone/mob.h
- zone/spells.cpp
> [Cleanup] Remove current_buff_count

- zone/client.h
> [Cleanup] Remove class EQStream from client.h

- zone/mob.h
> [Cleanup] Remove fixedZ from mob.h

- world/client.h
- zone/client.h
> [Cleanup] Remove CLIENT_TIMEOUT from world/client.h and zone/client.h

- world/client.h
> [Cleanup] Remove firstlogin and realfirstlogin from world/client.h

- zone/bot.cpp
- zone/bot.h
> [Cleanup] Remove _previousTarget from bot.h

- zone/corpse.cpp
- zone/corpse.h
> [Cleanup] Remove can_corpse_be_rezzed from corpse.h

- zone/npc.h
> [Cleanup] Remove GetAILevel() from npc.h

- zone/object.h
> [Cleanup] Remove SetDBID() from object.h

- zone/object.cpp
- zone/object.h
> [Cleanup] Remove m_inuse, m_z, and m_heading from object.h

- zone/petitions.h
> [Cleanup] Remove last_insert_id from petitions.h

- zone/position.cpp
- zone/position.h
> [Cleanup] Remove IsOrigin(glm::vec2) from position.h

- zone/spawngroup.cpp
- zone/spawngroup.h
> [Cleanup] Remove RemoveSpawnGroup() from spawngroup.h

- zone/trap.cpp
> [Cleanup] Utilize SetHiddenTrigger in trap.cpp

- zone/worldserver.cpp
> [Cleanup] Utilize GetScheduler() in zone/worldserver.cpp

- zone/zonedb.h
> [Cleanup] Remove CommandRequirement() from zonedb.h

- world/cliententry.cpp
- world/cliententry.h
> [Cleanup] Remove CheckAuth(), SetOnline(), and pMD5Pass from cliententry.h

- world/clientlist.cpp
- world/clientlist.h
> [Cleanup] Remove FindByName() from clientlist.h

- world/launcher_link.cpp
- world/launcher_link.h
> [Cleanup] Remove authenticated from launcher_link.cpp and launcher_link.h

- world/world_config.h
> [Cleanup] Remove DisableStats(), EnableStats(), DisableLoginserver(), and EnableLoginserver() from world_config.h

- world/worlddb.h
> [Cleanup] Remove StoreCharacter() from worlddb.h

- world/zoneserver.cpp
- world/zoneserver.h
> [Cleanup] Remove is_authenticatd, LSShutDownUpdate(), and SetInstanceID() from zoneserver.h

- zone/raids.cpp
Calling a client method against a Bot would cause a crash in these methods.
> [Bug Fix] Fix Raid methods that could cause crashes with Bots in raid

- ucs/database.cpp
- ucs/database.h
> [Cleanup] Remove DBInitVars(), HandleMysqlError(), and IsChatChannelInDB() in ucs/database.h

- loginserver/account_management.cpp
- loginserver/account_management.h
> [Cleanup] Remove UpdateLoginserverWorldAdminAccountPasswordById() from account_management.cpp

- loginserver/database.h
> [Cleanup] Remove IsConnected() from loginserver/database.h

- loginserver/login_types.h
> [Cleanup] Remove PlayerLogin_Struct from login_types.h

- loginserver/server_manager.cpp
- loginserver/server_manager.h
> [Cleanup] Remove GetServerByAddress() from server_manager.h

- loginserver/world_server.h
> [Cleanup] Remove SetConnection() from loginserver/world_server.h

- zone/mob.h
> [Cleanup] Remove ChangeHP() from mob.h

- common/struct_strategy.cpp
- common/struct_strategy.h
> [Cleanup] Remove FindPatch() from struct_category.cpp and struct_category.h

- zone/zonedb.cpp
Regression from #2873, will go through other String changes in another PR to ensure all are correct against what's loaded from DB.
> [Bug Fix] Fix for incorrect bindpoint x,y,z,headings

- CHANGELOG.md
- common/version.h
- package.json
* Place BOT_COMMAND_CHAR inside messages ([#3027](https://github.com/EQEmu/Server/pull/3027)) @trentdm 2023-03-05
* Prevent interrupt spam when OOM ([#3011](https://github.com/EQEmu/Server/pull/3011)) @nytmyr 2023-03-07
* Cleaning up Raid.cpp ([#3125](https://github.com/EQEmu/Server/pull/3125)) @Aeadoin 2023-03-20
* Cleanup unused methods and variables in world/main.cpp and world/main.h ([#3105](https://github.com/EQEmu/Server/pull/3105)) @Kinglykrab 2023-03-17
* Cleanup uses of Strings::ToInt to match correct type. ([#3054](https://github.com/EQEmu/Server/pull/3054)) @Aeadoin 2023-03-22
* Delete deprecated/perlxs folder ([#3110](https://github.com/EQEmu/Server/pull/3110)) @Kinglykrab 2023-03-17
* Delete queues.h ([#3089](https://github.com/EQEmu/Server/pull/3089)) @Kinglykrab 2023-03-17 …
> [Release] 22.7.0

- zone/main.cpp
> [Cleanup] Remove extern bool Critical

- common/version.h
- utils/sql/db_update_manifest.txt
- utils/sql/git/required/2023_03_24_npc_scale_global_base_verify.sql
Query was failing when adding heroic_strikethrough, added fix and running cleanup to ensure all columns are correct
> [Fix] Fix for SQL Query in npc_scale_global_base

- CHANGELOG.md
- common/version.h
- package.json
* Cleanup Strings::ToInt uses. ([#3142](https://github.com/EQEmu/Server/pull/3142)) @Aeadoin 2023-03-26
* Remove extern bool Critical ([#3146](https://github.com/EQEmu/Server/pull/3146)) @Kinglykrab 2023-03-25
* Fix for crash in Raid::QueuePacket ([#3145](https://github.com/EQEmu/Server/pull/3145)) @Aeadoin 2023-03-25
* Add support for -1 extradmgskill to allow all skills to be scaled. ([#3136](https://github.com/EQEmu/Server/pull/3136)) @Kinglykrab 2023-03-26
* Fix for Items looted from corpses. ([#3147](https://github.com/EQEmu/Server/pull/3147)) @Aeadoin 2023-03-26
* Fix for SQL Query in npc_scale_global_base ([#3144](https://github.com/EQEmu/Server/pull/3144)) @Aeadoin 2023-03-26
> [Release] 22.8.0

- CHANGELOG.md
- common/version.h
- package.json
* "equipped" not "equiped", "dual" not "duel". ([#3149](https://github.com/EQEmu/Server/pull/3149)) @Kinglykrab 2023-03-27
* Add Checks for out of bounds & dereferencing nullptrs ([#3151](https://github.com/EQEmu/Server/pull/3151)) @Aeadoin 2023-03-28
* Check Rule "Bots Enabled" to prevent bot database calls on connect ([#3154](https://github.com/EQEmu/Server/pull/3154)) @Aeadoin 2023-03-29
* Correct logic checks for Bot rule AllowOwnerOptionAltCombat ([#3158](https://github.com/EQEmu/Server/pull/3158)) @Aeadoin 2023-03-30
* Fix an issue with EVENT_DISCONNECT not firing on regular /camp ([#3153](https://github.com/EQEmu/Server/pull/3153)) @Kinglykrab 2023-03-28
* Fix bot_raid_members.sql for MYSQL. ([#3155](https://github.com/EQEmu/Server/pull/3155)) @Aeadoin 2023-03-28
* Fix for OOZ …
> [Release] 22.8.2

- zone/aa.cpp
- zone/aggro.cpp
- zone/attack.cpp
- zone/bonuses.cpp
- zone/bot.cpp
- zone/corpse.cpp
- zone/doors.cpp
- zone/groups.cpp
- zone/raids.cpp
Fix a number of out of bound issues, null de-referencing, and duplicate ptr checks where not needed.
> [Crash] Fix out of bound arrays, other potential crashes

- common/database.cpp
- common/http/httplib.h
- common/misc.cpp
- common/rulesys.cpp
- ucs/chatchannel.cpp
- ucs/clientlist.cpp
- world/client.cpp
- world/cliententry.cpp
- world/console.cpp
- world/world_boot.cpp
- zone/attack.cpp
- zone/client.cpp
- zone/client.h
- zone/data_bucket.cpp
- zone/dialogue_window.cpp
- zone/gm_commands/door_manipulation.cpp
- zone/gm_commands/faction.cpp
- zone/heal_rotation.cpp
- zone/lua_general.cpp
- zone/main.cpp
- zone/mob.cpp
- zone/questmgr.cpp
- zone/zone.cpp
- zone/zone_event_scheduler.cpp
This PR focuses on cleaning up excessive type casting: string -> char * -> string, identified these via PVS Studio. There's likely more but this was pretty sufficient for this PR.
> [Cleanup] Cleanup excessive type casting: string -> char * -> string

- zone/bot.cpp
> [Cleanup] Further bot.cpp nullptr checks

- zone/client_packet.cpp
> [Bug Fix] Fix issue with Bot Raid invites not working.

- zone/bonuses.cpp
- We were doing `e = 3` instead of doing `e += 3`.
> [Cleanup] Fix loop and code duplication for SE_ProcOnKillShot

- zone/bot.cpp
- Possible dereferenced nullptrs based on logic.
> [Cleanup] Remove possible dereferenced nullptrs in bot.cpp

- common/emu_constants.cpp
- Possible dereferencing of invalid iterator based on logic: https://pvs-studio.com/en/docs/warnings/v783/
> [Cleanup] Fix possible dereferencing of invalid iterator in constants

- zone/bonuses.cpp
- These conditions did the same thing, combining them is simpler.
> [Cleanup] Fix SEResist array settings duplicate code

- common/eqemu_config.cpp
- These conversions are unnecessary since we can just use the string itself.
> [Cleanup] Cleanup unnecessary string -> char* -> string conversions in eqemu_config.cpp

- CHANGELOG.md
- common/version.h
- package.json
* Add client pointer validation to Zone::GetClosestZonePoint() ([#3173](https://github.com/EQEmu/Server/pull/3173)) @Kinglykrab 2023-04-01
* Change level to bot_level in Bot::DoClassAttacks() to not overlap member variable ([#3239](https://github.com/EQEmu/Server/pull/3239)) @Kinglykrab 2023-04-03
* Cleanup unnecessary string -> char* -> string conversions in eqemu_config.cpp ([#3207](https://github.com/EQEmu/Server/pull/3207)) @Kinglykrab 2023-04-03
* Cleanup uses of insert/push_back when a temp object is used. ([#3170](https://github.com/EQEmu/Server/pull/3170)) @Aeadoin 2023-04-03
* Cleanup variable names in Bot::AddSpellToBotList() ([#3248](https://github.com/EQEmu/Server/pull/3248)) @Kinglykrab 2023-04-03
* Explicitly cast to float for more precision in Bot::GenerateBastHitPoints() …
> [Release] 22.9.1

- zone/bot_command.cpp
> [Cleanup] Delete unused strings in bot_command.cpp

- zone/bot_command.cpp
- We were converting back and forth between types unnecessarily.
> [Cleanup] Cleanup string -> char* -> string conversions in bot_command.cpp

- zone/bot_command.cpp
- Calling multiple times is less performant than using a variable.
> [Cleanup] Use variable for c->GetTarget() instead of calling multiple times in bot_command.cpp

- zone/client.cpp
- These cases were the same, consolidating them is better.
> [Cleanup] Combine similar cases in Client::InitInnates()

- zone/client.cpp
- Store character in a variable instead of looping a list of 1 entry.
> [Cleanup] Use variable for character instead of a loop

- zone/attack.cpp
- `other` is always defined since we check it prior to checking here.
> [Cleanup] other is always defined in these cases in attack.cpp

- zone/aa.cpp
- These conditions were identical and could be consolidated.
> [Cleanup] Identical conditions right beside each other in aa.cpp

- zone/bonuses.cpp
- These were the same code duplicated.
> [Cleanup] SE_StrikeThrough and SE_StrikeThrough2 are the same in bonuses.cpp

- zone/bonuses.cpp
- Lots of duplicate conditions.
> [Cleanup] Cleanup duplicate conditions in negate bonuses in bonuses.cpp

- zone/bot.cpp
- Validate for nullptrs in these spots in bot.cpp before using the variable.
> [Cleanup] Validate for nullptrs in bot.cpp

- common/database.cpp
- This was unnecessary since `QueryDatabase()` runs regardless.
> [Cleanup] results variable is assigned but never used in SaveCharacterCreate()

- common/eq_packet.cpp
- common/eq_packet.h
> [Cleanup] Remove unused code in eq_packet.cpp/eq_packet.h

- common/types.h
> [Cleanup] Remove unused macros in common/types.h

- common/eqemu_config.h
> [Cleanup] Remove unused SetConfigFile in common/eqemu_config.h

- zone/bot.cpp
- Some of these conditions were always true or false based on previous conditions.
> [Cleanup] Remove always true/false conditions from bot.cpp

- common/shareddb.cpp
- We weren't continuing if we had a `nullptr`.
> [Cleanup] Fix possible nullptr inst in GetSharedBank()

- zone/client.cpp
- zone/client.h
> [Cleanup] Remove position_same_update_count from client.cpp/client.h

- common/skills.cpp
- common/skills.h
> [Cleanup] Remove IsMeleeDmg() from skills.cpp/skills.h

- zone/mob.h
> [Cleanup] Remove pendinggroup from mob.h

- zone/mob.cpp
- zone/mob.h
> [Cleanup] Remove IsFullHP from mob.cpp/mob.h

- zone/mob.cpp
- zone/npc.cpp
- zone/pets.cpp
- zone/special_attacks.cpp
> [Cleanup] Utilize IsTaunting(), SetPetPower(), SetPetType(), and SetTaunting()

- CHANGELOG.md
- common/version.h
- package.json
* Fix database dump error reporting ([#3175](https://github.com/EQEmu/Server/pull/3175)) @Akkadius 2023-04-04
* Cleanup GetBotTables() ([#3270](https://github.com/EQEmu/Server/pull/3270)) @Aeadoin 2023-04-06
* Only define row if we have results in Database::GetCharacterID() ([#3199](https://github.com/EQEmu/Server/pull/3199)) @Kinglykrab 2023-04-05
* Add missing breaks and returns in bonuses.cpp ([#3231](https://github.com/EQEmu/Server/pull/3231)) @Kinglykrab 2023-04-05
* Breaks in wrong spot in cases in spell_effects.cpp ([#3297](https://github.com/EQEmu/Server/pull/3297)) @Kinglykrab 2023-04-22
* Cleanup always true/false statements in shareddb.cpp ([#3189](https://github.com/EQEmu/Server/pull/3189)) @Kinglykrab 2023-04-05
* Cleanup cheap-to-copy reference to use value instead in …
> [Release] 22.10.0

- world/ucs.h
- world/world_boot.cpp
- world/world_boot.h
Adds discord webhook callback processing to world
Needs to be tested
> [Discord] Add Discord webhook callback processing to world

- zone/client.h
- zone/client_mods.cpp
> [Cleanup] Remove GetClassHPFactor() from zone/client_mods.cpp and zone/client.h

- CHANGELOG.md
- common/version.h
- package.json
* Add check for owner in quest::pausetimer() ([#3304](https://github.com/EQEmu/Server/pull/3304)) @Kinglykrab 2023-04-23
* Add check for owner in quest::resumetimer() ([#3305](https://github.com/EQEmu/Server/pull/3305)) @Kinglykrab 2023-04-23
* Add initiator/owner checks to various methods in questmgr.cpp ([#3306](https://github.com/EQEmu/Server/pull/3306)) @Kinglykrab 2023-04-23
* Fix possible nullptr in quest::addloot() ([#3303](https://github.com/EQEmu/Server/pull/3303)) @Kinglykrab 2023-04-23
* Remove GetClassHPFactor() from zone/client_mods.cpp and zone/client.h ([#3313](https://github.com/EQEmu/Server/pull/3313)) @Kinglykrab 2023-04-30
* Remove GetClassHPFactor() from zone/merc.h ([#3314](https://github.com/EQEmu/Server/pull/3314)) @Kinglykrab 2023-04-30
* Remove …
> [Release] 22.11.0

- zone/attack.cpp
- zone/client.cpp
- zone/client.h
- zone/client_mods.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/lua_client.cpp
- zone/lua_client.h
- zone/perl_client.cpp
- zone/tune.cpp
Added SetIntoxication and GetIntoxication for client to match how things like hunger/thirst have setters and getters.
Added GetIntoxication functions for perl and Lua. 
No set function function, since it'd only take effect when zoning and might be confusing.
> [Feature] Intoxication setter/getter for source, getter for Perl/Lua

- zone/perl_mob.cpp
- zone/pets.cpp
- Add `$mob->GetPet()`.
- This exists in Lua, but not Perl.
> [Quest API] Add GetPet() to Perl

- common/item_instance.h
- zone/lua_iteminst.cpp
- zone/lua_iteminst.h
- Augment type can be `-1` for all augment types.
> [Cleanup] Set GetAugmentType() to int again

- zone/client.h
- zone/trading.cpp
> [Cleanup] Remove TraderUpdate() from trading.cpp/client.h

- zone/common.h
- zone/trading.cpp
> [Cleanup] Remove SetTradeCash() from trading.cpp/common.h

- zone/zone.cpp
- zone/zone.h
> [Cleanup] Remove DumpMerchantList() from zone.cpp/zone.h

- zone/embparser_api.cpp
- These were spelled incorrectly.
> [Quest API] Cleanup The Darkened Sea Quest Methods Names

- zone/gm_commands/setskill.cpp
- zone/gm_commands/setskillall.cpp
- No need to cap at 400 for max skill.
- When setting skill/skills, if we go over cap, set to cap.
> [Cleanup] Cleanup #setskill and #setskillall Commands

- common/spdat.h
> [Cleanup] Remove Z_AGGRO from spdat.h

- zone/raids.h
> [Cleanup] Remove numMembers from raids.h

- zone/raids.h
> [Cleanup] Remove IsRaid() from raids.h

- zone/aa_ability.cpp
- zone/aa_ability.h
> [Cleanup] Remove GetMaxRank() from aa_ability.cpp/aa_ability.h

- zone/zonedb.cpp
This PR fixes inconsistencies where stale data would not get deleted unless new data existed to be saved. This deletes previous data regardless before inserting to maintain upsertion consistency
> [Pets] Fix saving inconsistencies with pets

- zone/gm_commands/setanim.cpp
- Make use of constants instead of hard-coded strings.
> [Commands] Cleanup #setanim

- CHANGELOG.md
- common/version.h
- package.json
* Cleanup #setskill and #setskillall Commands ([#3367](https://github.com/EQEmu/Server/pull/3367)) @Kinglykrab 2023-05-25
* Delete message.h ([#3348](https://github.com/EQEmu/Server/pull/3348)) @Kinglykrab 2023-05-17
* Fix #spawn command NPCs having 0 health ([#3371](https://github.com/EQEmu/Server/pull/3371)) @Kinglykrab 2023-05-21
* Remove CalcPetHp from spdat.h ([#3364](https://github.com/EQEmu/Server/pull/3364)) @Kinglykrab 2023-05-25
* Remove CountNPC() and QueueManaged() from entity.cpp/entity.h ([#3346](https://github.com/EQEmu/Server/pull/3346)) @Kinglykrab 2023-05-17
* Remove DumpMerchantList() from zone.cpp/zone.h ([#3343](https://github.com/EQEmu/Server/pull/3343)) @Kinglykrab 2023-05-17
* Remove GetDamageReceived() and GetHealReceived() from combat_record.cpp/combat_record.h …
> [Release] 22.12.0

- zone/npc.cpp
- zone/npc.h
> [Cleanup] Remove NPC::AddCash() from npc.cpp/npc.h

- zone/common.h
> [Cleanup] Remove SPECIALIZE_MANA_REDUCE from zone/common.h

- zone/entity.h
> [Cleanup] Remove GetClient(ip, port) from zone/entity.h

- zone/entity.h
> [Cleanup] Remove pDBAsyncWorkID from zone/entity.h

- zone/entity.cpp
- zone/entity.h
> [Cleanup] Remove CheckCoordLosNoZLeaps() from zone/entity.cpp and zone/entity.h

- zone/entity.cpp
- zone/entity.h
> [Cleanup] Remove CountTempPets() from zone/entity.cpp and zone/entity.h

- zone/entity.cpp
- zone/entity.h
> [Cleanup] Remove GetClientCount() from zone/entity.cpp and zone/entity.h

- zone/client_packet.cpp
Reverting erroneous changes.  Sorry, I guess I didnt deploy this locally correctly, hence I didn't find the bug.
> [Targeting] Revert #3383

- CHANGELOG.md
- common/version.h
- package.json
* Revert #3383 ([#3405](https://github.com/EQEmu/Server/pull/3405)) @noudess 2023-06-13
> [Release] 22.13.1

- tests/string_util_test.h
This PR adds more test cases for string utilities
> [Strings] Add more test cases for string utils

- tests/cppunit/config.h
- utils/scripts/build/linux-build.sh
This PR enables building static Linux binaries, testing the pipeline run before actual merge
> [CI] Build static linux binaries

- CHANGELOG.md
- common/version.h
- package.json
* Move world database:dump to use MySQL credentials file ([#3410](https://github.com/EQEmu/Server/pull/3410)) @Akkadius 2023-06-17
* Add support for static linking (portable) binaries ([#3417](https://github.com/EQEmu/Server/pull/3417)) @Akkadius 2023-06-18
* Build static linux binaries ([#3419](https://github.com/EQEmu/Server/pull/3419)) @Akkadius 2023-06-18
* Add `bots:enable` and `bots:disable` commands ([#3415](https://github.com/EQEmu/Server/pull/3415)) @Akkadius 2023-06-17
* Add `mercs:enable` and `mercs:disable` commands ([#3416](https://github.com/EQEmu/Server/pull/3416)) @Akkadius 2023-06-18
* Console menu validation fixes ([#3413](https://github.com/EQEmu/Server/pull/3413)) @Akkadius 2023-06-17
* Add query multi statement execution support …
> [Release] 22.14.1

- zone/npc.cpp
- zone/npc.h
> [Cleanup] Remove DatabaseCastAccepted() from zone/npc.cpp and zone/npc.h

- zone/command.cpp
- zone/command.h
- zone/gm_commands/findlanguage.cpp
- Add `#findlanguage` command.
> [Commands] Add #findlanguage Command

- zone/gm_commands/viewcurrencies.cpp
- Utilize Dialogue Window table for cleanliness and readability.
> [Commands] Cleanup #viewcurrencies Command

- common/deity.cpp
- common/deity.h
- common/inventory_profile.cpp
- zone/command.cpp
- zone/command.h
- zone/gm_commands/finddeity.cpp
- zone/mob.h
- zone/questmgr.cpp
- Add `#finddeity` command.
- Remove `ConvertDeityTypeBitToDeityType` as it's unused.
- Rename `ConvertDeityTypeToDeityTypeBit` to `GetDeityBitmask`.
> [Commands] Add #finddeity Command

- common/database/database_update_manifest.cpp
world process did not start. An strace showed something wrong in 2023_01_21_bots_raid_members.sql.  Seemed like a snap&paste error.
> [Bug Fix] Fix error in 2023_01_21_bots_raid_members.sql

- CHANGELOG.md
- common/version.h
- package.json
* Default skill type to Hand to Hand in #npcedit meleetype ([#3422](https://github.com/EQEmu/Server/pull/3422)) @Kinglykrab 2023-06-19
* Delete common/worldconn.cpp ([#3436](https://github.com/EQEmu/Server/pull/3436)) @Kinglykrab 2023-06-24
* Remove DatabaseCastAccepted() from zone/npc.cpp and zone/npc.h ([#3449](https://github.com/EQEmu/Server/pull/3449)) @Kinglykrab 2023-06-24
* Remove GetACAvoid() from zone/merc.h ([#3447](https://github.com/EQEmu/Server/pull/3447)) @Kinglykrab 2023-06-25
* Remove GetACMit() from zone/merc.h ([#3446](https://github.com/EQEmu/Server/pull/3446)) @Kinglykrab 2023-06-24
* Remove _ClearWaypints() from zone/npc.h ([#3445](https://github.com/EQEmu/Server/pull/3445)) @Kinglykrab 2023-06-24
* Remove acmod() from zone/merc.h …
> [Release] 22.16.0

- zone/CMakeLists.txt
- zone/embparser.cpp
- zone/perl_mob.cpp
- zone/perl_stat_bonuses.cpp
- Add `$mob->GetAABonuses()`.
- Add `$mob->GetItemBonuses()`.
- Add `$mob->GetSpellBonuses()`.
- Add `$statbonuses->GetAbsorbMagicAttack(slot)`.
- Add `$statbonuses->GetAC()`.
- Add `$statbonuses->GetAccuracy(slot)`.
- Add `$statbonuses->GetAdjustedCastingSkill()`.
- Add `$statbonuses->GetAggroRange()`.
- Add `$statbonuses->GetAGI()`.
- Add `$statbonuses->GetAGICapModifier()`.
- Add `$statbonuses->GetAlterNPCLevel()`.
- Add `$statbonuses->GetAmbidexterity()`.
- Add `$statbonuses->GetAmplification()`.
- Add `$statbonuses->GetAntiGate()`.
- Add `$statbonuses->GetArcheryDamageModifier()`.
- Add `$statbonuses->GetAssassinate(slot)`.
- Add `$statbonuses->GetAssassinateLevel(slot)`.
- Add `$statbonuses->GetAssistRange()`.
- Add `$statbonuses->GetAStacker(slot)`.
- Add `$statbonuses->GetATK()`. …
> [Quest API] Add StatBonuses Class to Perl

- zone/CMakeLists.txt
- zone/embparser.cpp
- zone/lua_item.cpp
- zone/lua_item.h
- zone/lua_iteminst.cpp
- zone/lua_iteminst.h
- zone/perl_questitem.cpp
- zone/perl_questitem_data.cpp
- Add `$questitem->GetItem()`.
- Add `$questitem->GetUnscaledItem()`.
- Add `$questitemdata->GetAGI()`.
- Add `$questitemdata->GetAC()`.
- Add `$questitemdata->GetCHA()`.
- Add `$questitemdata->GetDEX()`.
- Add `$questitemdata->GetINT()`.
- Add `$questitemdata->GetSTA()`.
- Add `$questitemdata->GetSTR()`.
- Add `$questitemdata->GetAWis()`.
- Add `$questitemdata->GetAccuracy()`.
- Add `$questitemdata->GetArtifactFlag()`.
- Add `$questitemdata->GetAttack()`.
- Add `$questitemdata->GetAttuneable()`.
- Add `$questitemdata->GetAugmentDistiller()`.
- Add `$questitemdata->GetAugmentRestrict()`.
- Add `$questitemdata->GetAugmentSlotType(slot_id)`.
- Add `$questitemdata->GetAugmentSlotUnk2(slot_id)`.
- Add `$questitemdata->GetAugmentSlotVisible(slot_id)`.
- Add `$questitemdata->GetAugmentType()`. …
> [Quest API] Add ItemData Class to Perl

- zone/lua_parser_events.cpp
- zone/lua_parser_events.h
> [Cleanup] Remove handle_npc_single_npc from zone/lua_parser_events.cpp and zone/lua_parser_events.h

- CHANGELOG.md
- common/version.h
- package.json
* Add support for bots to #showstats/#mystats ([#3427](https://github.com/EQEmu/Server/pull/3427)) @Kinglykrab 2023-07-01
* Remove LoadItemDBFieldNames() from common/misc.cpp and common/misc.h ([#3473](https://github.com/EQEmu/Server/pull/3473)) @Kinglykrab 2023-07-04
* Remove handle_npc_single_npc from zone/lua_parser_events.cpp and zone/lua_parser_events.h ([#3467](https://github.com/EQEmu/Server/pull/3467)) @Kinglykrab 2023-07-03
* Set multi statements off when returning early ([#3462](https://github.com/EQEmu/Server/pull/3462)) @Akkadius 2023-07-01
* Add Strings::BeginsWith() and Strings::EndsWith() ([#3471](https://github.com/EQEmu/Server/pull/3471)) @Kinglykrab 2023-07-03
* Add check for underscores in botcreate command ([#3458](https://github.com/EQEmu/Server/pull/3458)) @tuday2 …
> [Release] 22.17.0

- zone/gm_commands/copycharacter.cpp
> [Commands] Cleanup #copycharacter Command

- CHANGELOG.md
- common/version.h
- package.json
* Add Pickpocket Command ([#3484](https://github.com/EQEmu/Server/pull/3484)) @tuday2 2023-07-08
* Move #find item summon links to front ([#3483](https://github.com/EQEmu/Server/pull/3483)) @Kinglykrab 2023-07-05
* Remove LoadItemDBFieldNames() from common/misc.cpp and common/misc.h ([#3473](https://github.com/EQEmu/Server/pull/3473)) @Kinglykrab 2023-07-04
* Add #itemsearch alias to #find aliases ([#3485](https://github.com/EQEmu/Server/pull/3485)) @Kinglykrab 2023-07-08
* Consolidate #show commands into a singular #show command ([#3478](https://github.com/EQEmu/Server/pull/3478)) @Kinglykrab 2023-07-08
* Fix _PutItem having a slot_id of -1 on mobs with no items ([#3474](https://github.com/EQEmu/Server/pull/3474)) @Kinglykrab 2023-07-04
* Add Skills:TrivialTradeskillCombinesNoFail Rule …
> [Release] 22.19.0

- CHANGELOG.md
- common/version.h
- package.json
* Remove orphaned commands related to botgroup ([#3489](https://github.com/EQEmu/Server/pull/3489)) @tuday2 2023-07-09
* Consolidate #set-like commands into a singular #set command ([#3486](https://github.com/EQEmu/Server/pull/3486)) @Kinglykrab 2023-07-15
* Add Support for item textures higher than 65,535 ([#3494](https://github.com/EQEmu/Server/pull/3494)) @Kinglykrab 2023-07-14
* Update raid features ([#3443](https://github.com/EQEmu/Server/pull/3443)) @neckkola 2023-07-13
* Fix Tradeskill Combines with augmented items ([#3490](https://github.com/EQEmu/Server/pull/3490)) @Kinglykrab 2023-07-15
* Fix charmed pets to follow when charmed. ([#3488](https://github.com/EQEmu/Server/pull/3488)) @noudess 2023-07-08
* Update bot naming check and add more explanation …
> [Release] 22.20.0

- zone/gm_commands/show/petition.cpp
- zone/gm_commands/show/petition_info.cpp
Where Statement was using incorrect field name.
> [Bug] Show Petition and Show Petition_Info fix

- zone/gm_commands/set/title_suffix.cpp
- Off by one on argument index.
> [Bug Fix] #set title_suffix Argument Position

- CHANGELOG.md
- common/version.h
- package.json
* Fix casing in corpse money and decay time. ([#3511](https://github.com/EQEmu/Server/pull/3511)) @Kinglykrab 2023-07-23
* Guard against Spells:MaxTotalSlotsPET being set above client allowed maximum. ([#3507](https://github.com/EQEmu/Server/pull/3507)) @Valorith 2023-07-22
* Distributed Databucket Caching ([#3500](https://github.com/EQEmu/Server/pull/3500)) @Kinglykrab 2023-07-24
* Fix console output in database:dump --dump-output-to-console  @Akkadius 2023-07-25
* Escape search string in #find item ([#3510](https://github.com/EQEmu/Server/pull/3510)) @Kinglykrab 2023-07-22
* Add GetMobTypeIdentifier() to Perl/Lua ([#3512](https://github.com/EQEmu/Server/pull/3512)) @Kinglykrab 2023-07-28
* Fix cases where saylinks were not being cached …
> [Release] 22.22.0

- zone/lua_parser_events.cpp
- We were not using separated values.
> [Bug Fix] Fix NPC Cast Events not parsing properly.

- zone/gm_commands/door_manipulation.cpp
- We were checking if this was a number, not a float.
> [Bug Fix] Fix +/- 0.1 XYZ Door Manipulation

- zone/client.cpp
- zone/global_loot_manager.cpp
- zone/gm_commands/find/aa.cpp
- zone/gm_commands/find/character.cpp
- zone/gm_commands/find/currency.cpp
- zone/gm_commands/find/faction.cpp
- zone/gm_commands/find/item.cpp
- zone/gm_commands/find/npctype.cpp
- zone/gm_commands/find/recipe.cpp
- zone/gm_commands/find/spell.cpp
- zone/gm_commands/find/task.cpp
- zone/gm_commands/npcedit.cpp
- zone/gm_commands/show/group_info.cpp
- zone/gm_commands/show/recipe.cpp
- zone/gm_commands/show/timers.cpp
- zone/gm_commands/show/zone_loot.cpp
- zone/gm_commands/spawneditmass.cpp
- zone/mob.cpp
- Removes commification from unique identifiers.
> [Cleanup] Remove Strings::Commify from all identifier values

- CHANGELOG.md
- common/version.h
- package.json
* Record character stats to `character_stats_record` table ([#3522](https://github.com/EQEmu/Server/pull/3522)) @Akkadius 2023-08-05
* Cleanup #view zone_loot Command ([#3523](https://github.com/EQEmu/Server/pull/3523)) @Kinglykrab 2023-08-02
* Remove Strings::Commify from all identifier values ([#3528](https://github.com/EQEmu/Server/pull/3528)) @Kinglykrab 2023-08-02
* Add Support for Drakkin Heritage Illusions ([#3521](https://github.com/EQEmu/Server/pull/3521)) @Kinglykrab 2023-08-01
* Bug fix for raid mark NPC across zones ([#3525](https://github.com/EQEmu/Server/pull/3525)) @neckkola 2023-08-05
* Bugs table should not target content database ([#3535](https://github.com/EQEmu/Server/pull/3535)) @Akkadius 2023-08-05
* Fix +/- 0.1 XYZ Door Manipulation …
> [Release] 22.24.0

- zone/bot.cpp
This PR Resolves the following issues I found with Bot behavior in Groups/Raids:
**Corrects Behavior in Bot::Spawn** 
**Expected**: Bots rejoins Groups/Raids when Spawned, or after zoning if they were previously a member of the Group/Raid.
**Actual**:  Bots were not correctly rejoining Group/Raid gracefully.
**Fix:** 
1. Check if Bot is a member of a Group/Raid.
2. Verify if the Bot Owner is a member of the same Group/Raid. 
- Change to use ```IsRaidMember(const char *name)``` and ```IsGroupMember(const char *name)```
- Previous method of using Client Pointer seemed to cause issues sometimes on Zone. 
- If Owner is a member, Bot rejoins the Group/Raid.
- If Owner is not a member, Bot gracefully is removed from Group/Raid.
**Corrects Behavior in Bot::Death**
**Expected**: Bots would become …
> [Bug Fix] Resolve Bot Group/Raid issues after death/spawn.

- zone/bot_command.cpp
Cleaned up references per #3541
> [Bots] Remove In-Game Command References to Bot Groups

- common/eqemu_logsys.h
- common/eqemu_logsys_log_aliases.h
- world/zoneserver.cpp
- zone/client.cpp
- zone/client.h
- zone/worldserver.cpp
- zone/zonedb.cpp
- zone/zoning.cpp
This is for being able to trace the zoning process more comprehensively, used in aid of other development work
> [Logging] Add detailed zoning logging

- zone/gm_commands/set.cpp
- zone/gm_commands/set/motd.cpp
- This command was non-functional since the consolidation due to an oversight on my part.
> [Bug Fix] Fix #motd/#set motd Command

- common/database/database_update_manifest.cpp
Needed for MySQL 8 compatibility.
> [Database] Change primary key entry to NOT NULL

- zone/client_packet.cpp
Not sure why this was here. DoN merchants have 482 items
> [Merchants] Remove hard limit on currency merchant

- zone/embparser_api.cpp
- zone/lua_general.cpp
- zone/zone.cpp
- zone/zone.h
Reload content flags globally when a content flag is set
> [Quest API] Reload content flags globally when a content flag is set

- world/zoneserver.cpp
This PR also reloads rules in world when #reload rules is invoked
> [Rules] Also reload rules in world when #reload rules invoked

- zone/gm_commands/set.cpp
- zone/gm_commands/set/faction.cpp
- This was an oversight on my part in `#set` command consolidation.
> [Bug Fix] Fix #set faction/#setfaction Command

- common/database/database_update_manifest.cpp
- common/ruletypes.h
- zone/aa.cpp
- zone/aa_ability.h
- zone/client.h
- zone/client_packet.cpp
- zone/command.cpp
- zone/command.h
- zone/entity.cpp
- zone/exp.cpp
- zone/gm_commands/grantaa.cpp
WIP AA system improvements.
- AA expansion flag behavior is a bit more consistent with how you'd expect it to work.
- AAs will always be loaded even if the expansion is "wrong", this allows refund AA to work more consistently when expansion is changed.
- #reload aa command now will reload the AAs on existing clients.
- Initial implementation of an auto grant system.
> [Fixes] AA System Fixes

- zone/bot.cpp
- zone/bot.h
- zone/client.cpp
- zone/client.h
- zone/lua_bot.cpp
- zone/lua_bot.h
- zone/lua_client.cpp
- zone/lua_client.h
- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/mob.h
- zone/perl_bot.cpp
- zone/perl_client.cpp
- zone/perl_mob.cpp
- zone/spell_effects.cpp
- Add `$bot->ApplySpell(spell_id, duration, level)`.
- Add `$bot->ApplySpell(spell_id, duration, level, allow_pets)`.
- Add `$bot->ApplySpellGroup(spell_id, duration, level)`.
- Add `$bot->ApplySpellGroup(spell_id, duration, level, allow_pets)`.
- Add `$bot->ApplySpellRaid(spell_id)`.
- Add `$bot->ApplySpellRaid(spell_id, duration)`.
- Add `$bot->ApplySpellRaid(spell_id, duration, level)`.
- Add `$bot->ApplySpellRaid(spell_id, duration, level, allow_pets)`.
- Add `$bot->ApplySpellRaid(spell_id, duration, level, allow_pets, is_raid_group_only)`.
- Add `$bot->SetSpellDuration(spell_id, duration, level)`.
- Add `$bot->SetSpellDuration(spell_id, duration, level, allow_pets)`.
- Add `$bot->SetSpellDurationGroup(spell_id, duration, level)`.
- Add `$bot->SetSpellDurationGroup(spell_id, duration, …
> [Quest API] Add ApplySpell() and SetBuffDuration() overloads to Perl/Lua

- zone/client_packet.cpp
- zone/groups.cpp
- zone/groups.h
Implements changes suggested in https://github.com/EQEmu/Server/issues/2498
> [Feature] Cleanup Group Split Money Logic

- zone/spells.cpp
https://github.com/EQEmu/Server/issues/2360
> [Bug Fix] Check for Song Skill Increase on Bard Pulse

- zone/attack.cpp
- zone/embparser.cpp
> [Bug Fix] Fix Killed XYZH support in EVENT_DEATH in Perl.

- CHANGELOG.md
- common/version.h
- package.json
* Additional Wild Ramp param was causing an overflow it appears at least on local testing. ([#3589](https://github.com/EQEmu/Server/pull/3589)) @fryguy503 2023-09-11
* npc_edit faction and #setfaction duplicate and incorrect. ([#3577](https://github.com/EQEmu/Server/pull/3577)) @noudess 2023-09-03
* Add Defensive Proc Rules for Level Gap Penalty ([#3580](https://github.com/EQEmu/Server/pull/3580)) @Kinglykrab 2023-09-17
* Add opcodes for Cast and Scribe book buttons ([#3578](https://github.com/EQEmu/Server/pull/3578)) @hgtw 2023-09-17
* Cleanup Group Split Money Logic ([#3583](https://github.com/EQEmu/Server/pull/3583)) @crdunwel 2023-09-17
* AA System Fixes ([#3572](https://github.com/EQEmu/Server/pull/3572)) @KimLS 2023-09-17
* Check for Song Skill Increase on Bard Pulse …
> [Release] 22.26.0

- zone/mob.cpp
- zone/mob.h
Fixes https://github.com/EQEmu/Server/issues/2212
> [Bug Fix] Invis vs. Undead/Animal Breaks Charm for Pets

- zone/gm_commands/show/group_info.cpp
- zone/gm_commands/show/zone_data.cpp
- Wasn't using `DialogueWindow::TableCell` so they weren't showing up.
- Fixed `red1` to `red_1` so it shows.
> [Bug Fix] Fix #show group_info Popup

- common/file.cpp
As observed http://spire.akkadius.com/dev/release/22.26.2?id=11457
> [Crash] Fix rarer crash with File::Makedir

- zone/gm_commands/summon.cpp
- zone/mob.cpp
As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11632
> [Crash] Fix #summon crash

- zone/lua_mob.cpp
As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11741
> [Crash] Fix crash in CastSpell Quest API input cast

- zone/bot.cpp
As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11806
> [Crash] Fix dangling pointer crash observed in SendHPPacketsFrom

- zone/gm_commands/movechar.cpp
As observed in http://spire.akkadius.com/dev/release/22.26.2?id=11815
> [Crash] Fix crash in #movechar

- CHANGELOG.md
- common/version.h
- package.json
- zone/bot.cpp
* Bot member zoned crash fix ([#3607](https://github.com/EQEmu/Server/pull/3607)) @Akkadius 2023-10-07
* Fix #summon crash ([#3608](https://github.com/EQEmu/Server/pull/3608)) @Akkadius 2023-10-07
* Fix CanUseAlternateAdvancementRank crash ([#3609](https://github.com/EQEmu/Server/pull/3609)) @Akkadius 2023-10-07
* Fix crash in #movechar ([#3612](https://github.com/EQEmu/Server/pull/3612)) @Akkadius 2023-10-07
* Fix crash in CastSpell Quest API input cast ([#3610](https://github.com/EQEmu/Server/pull/3610)) @Akkadius 2023-10-07
* Fix dangling pointer crash observed in SendHPPacketsFrom ([#3611](https://github.com/EQEmu/Server/pull/3611)) @Akkadius 2023-10-07
* Fix rarer crash with File::Makedir ([#3606](https://github.com/EQEmu/Server/pull/3606)) @Akkadius 2023-10-07
* Add Validation to …
> [Release] 22.27.0

- zone/common.h
- zone/lua_mob.cpp
- zone/special_attacks.cpp
- Allows mobs normally susceptible to Assassinate to be made immune to it.
> [Feature] Add Immune to Assassinate Special Ability

- zone/gm_commands/summon.cpp
- Not setting target to a default of `nullptr` or in this case `c` gave undefined behavior.
> [Crash] Fix Crash with #summon

- common/database/database_update_manifest.cpp
- common/version.h
- utils/scripts/import_13th_floor.pl
Overhaul to script.
- Now uses `eqemu_config.json`
- More descriptive during the process
- Accounts for adjustments (`idfile`, `prockunk1`)
- No longer needs to adjust `UNK132`
> [Scripts] Update 13th Floor importer

- CHANGELOG.md
- common/version.h
- package.json
* Adjust Bot Movement Speed ([#3615](https://github.com/EQEmu/Server/pull/3615)) @Kinglykrab 2023-10-14
* Fix bot removal on zone, regression from #3611 ([#3631](https://github.com/EQEmu/Server/pull/3631)) @Akkadius 2023-10-16
* Fix Crash with #summon ([#3618](https://github.com/EQEmu/Server/pull/3618)) @Kinglykrab 2023-10-14
* Fix crash in Mob::ShowBuffs ([#3632](https://github.com/EQEmu/Server/pull/3632)) @Akkadius 2023-10-16
* Resolve crash when assigning empty raid note. ([#3628](https://github.com/EQEmu/Server/pull/3628)) @Aeadoin 2023-10-15
* Add Extra Kick Classes ([#3613](https://github.com/EQEmu/Server/pull/3613)) @Kinglykrab 2023-10-11
* Add Immune to Assassinate Special Ability ([#3622](https://github.com/EQEmu/Server/pull/3622)) @Kinglykrab 2023-10-14
* Add Immune to Headshot …
> [Release] 22.28.0

- CHANGELOG.md
- common/version.h
- package.json
* Fix manifest for blocked spells ([#3646](https://github.com/EQEmu/Server/pull/3646)) @joligario 2023-10-21
* Fix issue with subcommand settings not working ([#3643](https://github.com/EQEmu/Server/pull/3643)) @Kinglykrab 2023-10-21
* Hotfix command without hotfix name ([#3644](https://github.com/EQEmu/Server/pull/3644)) @joligario 2023-10-21
* Verifying mail keys when none exist ([#3645](https://github.com/EQEmu/Server/pull/3645)) @joligario 2023-10-21
> [Release] 22.29.1

- common/database/database_update_manifest_bots.cpp
Fixes mismatched condition versus match.
> [Bug Fix] Fix Bot Starting Items SQL

- CHANGELOG.md
- common/version.h
- package.json
* Fix empty InsertMany in bot starting items. ([#3653](https://github.com/EQEmu/Server/pull/3653)) @Kinglykrab 2023-10-24
> [Release] 22.30.1

- zone/entity.cpp
- zone/entity.h
- zone/mob.cpp
Should hopefully address crash in http://spire.akkadius.com/dev/release/22.30.2?id=13719
> [Crash] Fix spell in AESpell related to beacons

- CHANGELOG.md
- common/version.h
- package.json
* Fix crash when client pointer does not exist during #hotfix ([#3661](https://github.com/EQEmu/Server/pull/3661)) @Akkadius 2023-10-29
* Fix spell in AESpell related to beacons ([#3659](https://github.com/EQEmu/Server/pull/3659)) @Akkadius 2023-10-29
* Add id to variables table ([#3658](https://github.com/EQEmu/Server/pull/3658)) @Akkadius 2023-10-29
* Add symbols to release builds ([#3660](https://github.com/EQEmu/Server/pull/3660)) @Akkadius 2023-10-29
* Revert " Reload perl quests on zone bootup " ([#3648](https://github.com/EQEmu/Server/pull/3648)) @Akkadius 2023-10-26
* Fix part 3 of Issue 932. ([#3654](https://github.com/EQEmu/Server/pull/3654)) @noudess 2023-10-29
> [Release] 22.31.0

- CHANGELOG.md
- common/version.h
- package.json
* Force raids off content database ([#3665](https://github.com/EQEmu/Server/pull/3665)) @joligario 2023-10-31
* Revert " Fix spell in AESpell related to beacons " ([#3659](https://github.com/EQEmu/Server/pull/3659)) @Akkadius 2023-10-31
* Fix issue with blocked spells not loading properly  @Akkadius 2023-10-31
* Convert Loot Messages to Error Logs ([#3663](https://github.com/EQEmu/Server/pull/3663)) @Kinglykrab 2023-10-31
> [Release] 22.31.3

- common/eq_constants.h
- common/eqtime.cpp
- common/eqtime.h
- zone/spells.cpp
- zone/string_ids.h
Should only be cast at night from 7pm to 4am be cast at night from 7pm to 4am.
> [Spells] Added IsNightTime() for Dance of the Fireflies

- zone/attack.cpp
- zone/embparser.cpp
This reverts commit 9b992167f00fabda47ed4740eb28a1351ea6caf5.
> Revert "[Bug Fix] Fix Killed XYZH support in EVENT_DEATH in Perl. (#3591)"

- zone/lua_parser.cpp
This will add the event name to assist with finding source errors that break lua events
> [Quest API] Add details to Lua event dispatch errors

- common/repositories/command_subsettings_repository.h
- zone/gm_commands/show.cpp
- zone/gm_commands/show/aa_points.cpp
- Adds a command to view a player's current, spent, and total AA Points.
> [Commands] Add #show aa_points Command

- zone/bot_command.cpp
This adds raid support to actionables for bot commands.
This also addresses Issue #3567
If in a group, group based commands will function as normal, however if in a raid they will support raids and use the group of the bot that fits  the criteria.
This adds new actionables as well; namely, **ownerraid**, **byclass** and **byrace**.
**byclass** and **byrace** use the int of the chosen class/race. IE Shadowknight is 5, Barbarian is 2. **^create help** is an easy way for players to identify numbers associated with classes and races.
**targetgroup** will now select all bots that meet the criteria within a raid group in addition to the current functionality of groups.
**namesgroup** will now select all bots that meet the criteria within a raid group in addition to the current functionality of …
> [Bots] Add command support for raids, add additional arguments for actionables

- zone/hate_list.cpp
- zone/hate_list.h
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
This should assist with prevention of NPC Faction waring. I have been using this code on my server for over 5 years with no coredumps or any noted bugs. This was brought up as users have reported a few events where they can trigger NPC's to fight each other.
> [Bug Fix] NPC Faction War prevention.

- loginserver/database.cpp
- loginserver/login_util/login_tickets.sql
The existing /ticket code hadn't been touched in a long time, this updates the table to be less insane and actually add SQL for sourcing it so it can be used.
Something to think about: invalidating used tickets?
> [Loginserver] Update ticket login table structure

- CHANGELOG.md
- common/version.h
- package.json
* Update date in changelog ([#3698](https://github.com/EQEmu/Server/pull/3698)) @joligario 2023-11-19
* Fix typo in #giveitem ([#3704](https://github.com/EQEmu/Server/pull/3704)) @Kinglykrab 2023-11-22
* Add "IgnoreLevelBasedHasteCaps" rule to GetHaste() ([#3705](https://github.com/EQEmu/Server/pull/3705)) @jcr4990 2023-11-23
* Fix bots/Mercenaries being removed from hatelist ([#3708](https://github.com/EQEmu/Server/pull/3708)) @Kinglykrab 2023-11-23
* Fix some spell types failing IsValidSpellRange check ([#3707](https://github.com/EQEmu/Server/pull/3707)) @nytmyr 2023-11-23
* Update ticket login table structure ([#3703](https://github.com/EQEmu/Server/pull/3703)) @KimLS 2023-11-22
> [Release] 22.34.2

- zone/gm_commands/disarmtrap.cpp
> [Commands] Cleanup #disarmtrap Command

- zone/gm_commands/list.cpp
- Introduce a struct so we don't have to duplicate so much code.
> [Commands] Cleanup #list Command

- zone/gm_commands/movement.cpp
> [Commands] Cleanup #movement Command

- common/database.cpp
- common/database.h
- zone/gm_commands/acceptrules.cpp
- Utilize repositories in database methods.
> [Commands] Cleanup #acceptrules Command

- zone/gm_commands/petname.cpp
#petname would change PC to be named Nobody if selected.
> [Commands] #petname changes PC to Nobody if selected.

- common/features.h
- zone/client_packet.cpp
- zone/doors.cpp
- zone/gm_commands/castspell.cpp
- zone/gm_commands/corpse.cpp
- zone/gm_commands/doanim.cpp
- zone/gm_commands/guild.cpp
- zone/gm_commands/interrogateinv.cpp
- zone/gm_commands/invsnapshot.cpp
- zone/gm_commands/movechar.cpp
- zone/gm_commands/show/flags.cpp
- zone/gm_commands/show/peqzone_flags.cpp
- zone/zoning.cpp
- Removed the hard-coded GM status checks since if you have access to the command we can now limit access to subcommands if necessary.
> [Cleanup] Remove hard-coded Status Checks

- common/servertalk.h
- world/console.cpp
- world/zoneserver.cpp
- zone/gm_commands/zonebootup.cpp
- zone/gm_commands/zoneshutdown.cpp
- zone/worldserver.cpp
> [Commands] Cleanup #zonebootup and #zoneshutdown Commands

- utils/scripts/import_13th_floor.pl
InnoDB doesn't like the lengths. Will need to address that in the future.
> [Scripts] Revert database engine change from #3702.

- common/database/database_update_manifest.cpp
> [Bug Fix] Fix 9245 SQL

- common/repositories/base/base_blocked_spells_repository.h
Ran generator to update blocked_spells Repo
> [Bug Fix] PR 3638 Missed the blocked spells repository updates

- zone/zonedb.cpp
> [Bug Fix] Fix blocked spells regression from #3638

- CHANGELOG.md
- common/version.h
- package.json
* Add BotHealOnLevel to fully heal/mana on level. ([#3745](https://github.com/EQEmu/Server/pull/3745)) @nytmyr 2023-12-08
* Fix bots learning spells on level ([#3744](https://github.com/EQEmu/Server/pull/3744)) @nytmyr 2023-12-08
* Fix blocked spells regression from #3638 ([#3753](https://github.com/EQEmu/Server/pull/3753)) @joligario 2023-12-11
* PR 3638 Missed the blocked spells repository updates ([#3748](https://github.com/EQEmu/Server/pull/3748)) @fryguy503 2023-12-08
* Update minimum version of CMake ([#3743](https://github.com/EQEmu/Server/pull/3743)) @joligario 2023-12-08
* Remove hard-coded Status Checks ([#3727](https://github.com/EQEmu/Server/pull/3727)) @Kinglykrab 2023-12-03
* #guild set CharName 0 did not remove char from guild. …
> [Release] 22.35.0

- common/database/database_update_manifest.cpp
- common/repositories/base/base_starting_items_repository.h
- common/shareddb.cpp
- common/version.h
- `race_list` comes before `class_list`, query had them in the wrong order.
Fixes #3764
> [Bug Fix] Fix Starting Items SQL

- CHANGELOG.md
- common/version.h
- package.json
* Add rule to toggle DT hitting owner ([#3757](https://github.com/EQEmu/Server/pull/3757)) @nytmyr 2023-12-11
* Enable auto-saving of bots. ([#3758](https://github.com/EQEmu/Server/pull/3758)) @nytmyr 2023-12-13
* Cleanup classes.cpp/classes.h ([#3752](https://github.com/EQEmu/Server/pull/3752)) @Kinglykrab 2023-12-13
* Fix /corpse command regression from #3727 ([#3770](https://github.com/EQEmu/Server/pull/3770)) @Akkadius 2023-12-16
* Make it clearer to users that a database backup is occurring ([#3769](https://github.com/EQEmu/Server/pull/3769)) @Akkadius 2023-12-16
* When database version is greater than binary, we are up to date ([#3771](https://github.com/EQEmu/Server/pull/3771)) @Akkadius 2023-12-16
* Fix Starting Items SQL ([#3766](https://github.com/EQEmu/Server/pull/3766)) …
> [Release] 22.36.0

- world/main.cpp
- zone/gm_commands/set/time.cpp
- zone/lua_general.cpp
- zone/questmgr.cpp
- zone/zone.cpp
> [Bug Fix] Fixed the discrepacy with time using command #time and in quests.

- zone/gm_commands/summon.cpp
- zone/mob.cpp
- zone/mob.h
> [Bug Fix] Fix NPCs routing to 0.0, 0.0 on #summon

- zone/client_packet.cpp
- Resolves https://github.com/EQEmu/Server/issues/663.
[Drop Invisibility Trap Test](https://github.com/EQEmu/Server/assets/89047260/d6e96704-ee6d-4b16-bd52-4122e3b37577)
> [Bug Fix] Drop Invisibility when hit by traps

- CHANGELOG.md
- common/version.h
- package.json
* Add ScanCloseMobs support to fix AEs ([#3786](https://github.com/EQEmu/Server/pull/3786)) @nytmyr 2023-12-18
* Expand ^itemuse options ([#3756](https://github.com/EQEmu/Server/pull/3756)) @nytmyr 2023-12-17
* Fix ^defensive from checking aggressive disciplines. ([#3787](https://github.com/EQEmu/Server/pull/3787)) @nytmyr 2023-12-18
* Fix ^oo autodefend from sending bots/pets to invalid haters ([#3772](https://github.com/EQEmu/Server/pull/3772)) @nytmyr 2023-12-16
* Fix unnecessary failed to save timer error ([#3788](https://github.com/EQEmu/Server/pull/3788)) @nytmyr 2023-12-18
* [Quest API] Add ^clickitem, ^timer, fix GetBestBotSpellForCure ([#3755](https://github.com/EQEmu/Server/pull/3755)) @nytmyr 2023-12-17
* Switch to use clang for Linux builds (speed) …
> [Release] 22.37.0

- common/inventory_profile.cpp
- zone/client.h
- zone/effects.cpp
- zone/inventory.cpp
- zone/lua_client.cpp
- zone/lua_client.h
- zone/perl_client.cpp
- Add `$client->SummonItemIntoInventory(item_data)`.
```pl
my %item_data = (
"item_id" => 32557,
"charges" => 1
);
$client->SummonItemIntoInventory(\%item_data);
}
}
```
- Add `client:SummonItemIntoInventory(item_data)`.
```lua
if e.message:find("#a") then
local item_data = {
"item_id" = 32557,
"charges" = 1
}
e.self:SummonItemIntoInventory(item_data)
end
end
```
> [Quest API] Add SummonItemIntoInventory() to Perl/Lua

- common/say_link.cpp
Fixes issue present in MySQL 8.0+ servers
Resolves issue https://github.com/EQEmu/Server/issues/3573
> [Database] Fix issue with saylinks query in MySQL 8.0+

- zone/hate_list.cpp
- zone/hate_list.h
- zone/mob.h
- These were separate methods and duplicated a lot of code, consolidated into the singular method using the `EntityFilterType`.
> [Cleanup] Consolidate GetHateRandom(), GetHateRandomBot(), GetHateRandomClient(), and GetHateRandomNPC()

- common/repositories/template/base_repository.template
Came up in a use case in PR https://github.com/EQEmu/Server/pull/3699
> [Repositories] Add ReplaceOne and ReplaceMany

- CHANGELOG.md
- common/version.h
- package.json
* Remove unnecessary error on SetItemReuse ([#3795](https://github.com/EQEmu/Server/pull/3795)) @nytmyr 2023-12-20
* Consolidate GetHateRandom(), GetHateRandomBot(), GetHateRandomClient(), and GetHateRandomNPC() ([#3794](https://github.com/EQEmu/Server/pull/3794)) @Kinglykrab 2023-12-25
* Race constants refactor ([#3782](https://github.com/EQEmu/Server/pull/3782)) @Akkadius 2023-12-23
* Fix issue with saylinks query in MySQL 8.0+ ([#3800](https://github.com/EQEmu/Server/pull/3800)) @Akkadius 2023-12-24
* Update faction mods with Live data ([#3799](https://github.com/EQEmu/Server/pull/3799)) @joligario 2023-12-23
* Disable Hide/Improved Hide on Trap damage ([#3791](https://github.com/EQEmu/Server/pull/3791)) @Kinglykrab 2023-12-19
* Fix Bard Invisibility Songs breaking every 4 ticks …
> [Release] 22.38.0

- common/database/database_update_manifest.cpp
- common/repositories/base/base_tasks_repository.h
- common/version.h
- world/shared_task_manager.cpp
- zone/task_manager.cpp
Adds an enabled column (default enabled) so we can import live task data framing and set them as disabled until fully implemented
> [Tasks] Add enabled column

- common/eqemu_logsys.cpp
- common/repositories/base/base_logsys_categories_repository.h
This PR is similar to https://github.com/EQEmu/Server/pull/3806 where if you install a new server and you have a bunch of log categories to be injected. Depending on which process launches first it can fire its inserts and cause another processes init inserts to fail, making the operator confused to think that there may be some sort of issue when really there isn't any. 
1) We no longer throw errors when two process initialize the same settings.
2) Less database calls during initialization by doing bulk insertion
3) We also reload settings after running through the entire routine
**Testing**
```
Zone |    Info    | LoadLogDatabaseSettings Automatically adding new log category [AA] (1) 
Zone |    Info    | LoadLogDatabaseSettings Automatically adding new log category [AI] (2) 
Zone | …
```
> [Logs] Bulk insert new log settings

- CHANGELOG.md
- common/version.h
- package.json
* Fix character copier due to schema change ([#3805](https://github.com/EQEmu/Server/pull/3805)) @Akkadius 2023-12-28
* Disarm was not dropping item to ground due to bug ([#3811](https://github.com/EQEmu/Server/pull/3811)) @noudess 2023-12-27
* Bulk insert new log settings ([#3810](https://github.com/EQEmu/Server/pull/3810)) @Akkadius 2023-12-28
* Reclassify unhelpful Info message ([#3809](https://github.com/EQEmu/Server/pull/3809)) @Akkadius 2023-12-28
* Fix MySQL Query error formatting ([#3808](https://github.com/EQEmu/Server/pull/3808)) @Akkadius 2023-12-28
* Remove "No objects to load for zone" error message ([#3807](https://github.com/EQEmu/Server/pull/3807)) @Akkadius 2023-12-28
* Bulk replace settings on boot ([#3806](https://github.com/EQEmu/Server/pull/3806)) @Akkadius 2023-12-28 …
> [Release] 22.39.0

- zone/entity.cpp
- zone/gm_commands/appearanceeffects.cpp
- zone/mob.cpp
- zone/mob.h
- zone/perl_mob.cpp
> [Cleanup] Appearance not appearence

- common/races.cpp
- common/races.h
- zone/attack.cpp
- zone/beacon.cpp
- zone/bot.cpp
- zone/bot_command.cpp
- zone/client.cpp
- zone/encounter.cpp
- zone/gm_commands/fixmob.cpp
- zone/gm_commands/set/gender.cpp
- zone/gm_commands/set/gender_permanent.cpp
- zone/merc.cpp
- zone/mob.cpp
- zone/npc.cpp
- zone/pathfinder_waypoint.cpp
- zone/spell_effects.cpp
- zone/titles.cpp
- zone/tradeskills.cpp
- zone/trap.cpp
- zone/zonedb.h
- Convert to a `Gender` namespace using `constexpr`.
- Cleanup spots where we were using magic numbers for gender values.
> [Cleanup] Gender constants cleanup

- zone/mob.cpp
- zone/mob.h
> [Cleanup] Remove MakeSpawnUpdateNoDelta from mob.cpp/mob.h

- zone/mob.cpp
- zone/mob.h
> [Cleanup] Remove SendStunAppearance from mob.cpp/mob.h

- zone/mob.cpp
- zone/mob.h
> [Cleanup] Remove unused PlotPosition methods from mob.cpp/mob.h

- zone/client_packet.cpp
- Logic was incorrect.
- Fixes #3822.
> [Bug Fix] Fix crash in Client::Handle_OP_GMGoto

- zone/attack.cpp
- zone/embparser.cpp
- zone/lua_parser_events.cpp
- Death events were happening too early so stuff checking for dead NPCs was non-functional.
> [Quest API] Fix issue with death events.

- CHANGELOG.md
- common/version.h
- package.json
* Appearance not appearence ([#3819](https://github.com/EQEmu/Server/pull/3819)) @Kinglykrab 2023-12-30
* Delete errmsg.h in common and zone ([#3821](https://github.com/EQEmu/Server/pull/3821)) @Kinglykrab 2023-12-30
* Gender constants cleanup ([#3817](https://github.com/EQEmu/Server/pull/3817)) @Kinglykrab 2023-12-30
* Remove MakeSpawnUpdateNoDelta from mob.cpp/mob.h ([#3816](https://github.com/EQEmu/Server/pull/3816)) @Kinglykrab 2023-12-31
* Remove SendStunAppearance from mob.cpp/mob.h ([#3818](https://github.com/EQEmu/Server/pull/3818)) @Kinglykrab 2023-12-31
* Remove unused PlotPosition methods from mob.cpp/mob.h ([#3820](https://github.com/EQEmu/Server/pull/3820)) @Kinglykrab 2023-12-31
* Database update improvements, content db and terminal checks …
> [Release] 22.39.1

- common/inventory_profile.cpp
- Code was not checking for a `-1` value and was assuming everyone used valid bitmasks.
> [Bug Fix] Fix issue with 9th/10th inventory slot

- common/repositories/base/base_character_material_repository.h
- zone/client.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `DeleteCharacterMaterialColor`, `LoadCharacterMaterialColor`, and `SaveCharacterMaterialColor` to repositories.
> [Character] Convert Delete/Load/Save of Character Material to Repositories

- common/repositories/base/base_character_data_repository.h
- zone/zonedb.cpp
- Converts `LoadCharacterData` and `SaveCharacterData` to repositories.
> [Character] Convert Load/Save of Character Data to Repositories

- zone/gm_commands/petname.cpp
> [Commands] Cleanup #petname Command

- common/repositories/base/base_character_skills_repository.h
- zone/zonedb.cpp
- Converts `LoadCharacterSkills` and `SaveCharacterSkill` to repositories.
> [Character] Convert Load/Save of Character Skills to Repositories

- common/repositories/base/base_character_potionbelt_repository.h
- zone/client_packet.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Converts `LoadCharacterPotionBelt` and `SaveCharacterPotionBelt` to repositories.
> [Character] Convert Load/Save of Character Potion Belt to Repositories

- common/repositories/base/base_character_currency_repository.h
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `LoadCharacterCurrency` and `SaveCharacterCurrency` to repositories.
> [Character] Convert Load/Save of Character Currency to Repositories

- common/repositories/base/base_character_alternate_abilities_repository.h
- zone/aa.cpp
- zone/aa.h
- zone/client.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `DeleteCharacterAAs`, `LoadAlternateAdvancement`, `RemoveExpendedAA` and `SaveAA` to repositories.
- Add `AACategory` namespace for AA Categories.
- Cleanup some logic/formatting in modified methods.
> [Character] Convert Delete/Load/Remove/Save of Character AA to Repositories

- common/repositories/base/base_character_bind_repository.h
- zone/zonedb.cpp
- Convert `LoadCharacterBindPoint` to repositories.
- `SaveCharacterBinds` was already using repositories, cleanup logic.
> [Character] Convert Load/Save of Character Bind to Repositories

- zone/bot.cpp
- zone/bot.h
- zone/bot_command.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- With the new saylink functionality, bots no longer need their own saylink method.
> [Cleanup] Remove bot-based saylink method

- common/eq_constants.h
- common/repositories/base/base_character_pet_buffs_repository.h
- common/repositories/base/base_character_pet_info_repository.h
- common/repositories/base/base_character_pet_inventory_repository.h
- zone/client.h
- zone/zonedb.cpp
- Convert `LoadPetInfo` to repositories.
- `SavePetInfo` already used repositories, cleanup logic.
> [Pets] Convert Load/Save of Pet Info to Repositories

- common/repositories/base/base_character_buffs_repository.h
- zone/entity.cpp
- zone/entity.h
- zone/zonedb.cpp
- Convert `LoadBuffs` to repositories.
- `SaveBuffs` was already using repositories, cleanup logic.
> [Character] Convert Load/Save of Character Buffs to Repositories

- common/repositories/base/base_character_auras_repository.h
- zone/zonedb.cpp
- Convert `LoadAuras` and `SaveAuras` to repositories.
> [Characters] Convert Load/Save of Character Auras to Repositories

- common/repositories/base/base_character_item_recast_repository.h
- common/shareddb.cpp
- zone/spells.cpp
- zone/zonedb.cpp
- Convert `ClearOldRecastTimestamps`, `DeleteItemRecast`, `GetItemRecastTimeStamp`, `GetItemRecastTimestamps`, and `UpdateItemRecast` to repositories.
> [Character] Convert Clear/Delete/Get/Update of Character Item Recast to Repositories

- common/repositories/base/base_account_repository.h
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `GetKarma` and `UpdateKarma` to repositories.
> [Account] Convert Get/Update Account Karma to Repositories

- zone/client.cpp
- zone/client.h
- zone/lua_client.cpp
- zone/lua_client.h
- zone/perl_client.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `UpdateGMStatus` to repositories.
- Convert parameter of status to `int`.
> [Account] Convert UpdateGMStatus to Repositories

- common/repositories/character_data_repository.h
- zone/client_process.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Create a custom `GetSecondsSinceLastLogin` repository method to use in `NoRentExpired`.
>  [Character] Convert NoRentExpired to Repositories

- common/ruletypes.h
- zone/client_packet.cpp
Allows server admins to toggle if they want to prevent players from retaining mounts on zone. false is default to maintain current feature set.
> [Rule] Mounts will wear off on zone

- zone/client_process.cpp
Class trainers log an error when you have reached your max train in the specific skill. They will continue to "Appear" to eat money and practices however they will be returned on logout/in or zone.
> [Bug Fix] Class Trainers dont steal your money!

- common/ruletypes.h
- zone/spells.cpp
Enabling UseLegacyFizzleCode will enable the legacy fizzle code system.
New fizzle codes modeled on extensive testing in 2001/2002 (thank you druid's grove and graffe)
> [Feature] Legacy Fizzle Code

- common/spdat.h
- zone/spell_effects.cpp
- zone/spells.cpp
Fixed the difference of procs for Vampiric Embrace between Necros and Shadow Knights.
> [Bug Fix] Vampiric Embrace Fixes

- common/ruletypes.h
- zone/aggro.cpp
Add rule for undead aggro and check for undead at aggro check time
> [Rule] Undead Aggro

- zone/spells.cpp
Nothing conflicts with stacking with resurrection effects
> [Bug Fix] Rez Effects Stacking

- zone/client_packet.cpp
No fall damage underwater, need to move to skill up swimming
> [Bug Fix] Swim Skillup and Underwater Fall Damage Fix

- common/ruletypes.h
- zone/spell_effects.cpp
clear aggro on evac spells, special case of wiping aggro for clients
> [Rules] Evac Aggro Wipe

- common/ruletypes.h
- zone/spells.cpp
Casting charm on target with level above max level of spell will give resist message and aggro
> [Rule] Casting Charm on over level = Aggro

- zone/attack.cpp
- zone/bot.cpp
- zone/entity.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/perl_npc.cpp
When clearing a client from the hatelist, also clear them from ramp
> [Bug Fix] Clear Ramp when Clearing hate

- zone/client_packet.cpp
Clear client to be rezzed aggro when rezzing in zone.
> [Bug Fix] Rez in zone clear aggro

- zone/spells.cpp
Align client and server on buff position (easiest fix to sync client/server)
> [Bug Fix] Buff Sync

- zone/attack.cpp
Rune doesn't stop invis breaking
> [Bug Fix] Rune Invis Break

- zone/mob.h
- zone/special_attacks.cpp
Target locked pets shouldn't taunt
> [Bug Fix] Target Locked Pet Taunt

- CHANGELOG.md
- common/version.h
- package.json
* Convert Get/Update Account Karma to Repositories ([#3858](https://github.com/EQEmu/Server/pull/3858)) @Kinglykrab 2024-01-07
* Convert UpdateGMStatus to Repositories ([#3859](https://github.com/EQEmu/Server/pull/3859)) @Kinglykrab 2024-01-07
* Resist Spell Fix ([#3840](https://github.com/EQEmu/Server/pull/3840)) @dariusuknuis 2024-01-07
* Negative Aggro Fix ([#3866](https://github.com/EQEmu/Server/pull/3866)) @fryguy503 2024-01-07
* Convert Clear/Delete/Get/Update of Character Item Recast to Repositories ([#3857](https://github.com/EQEmu/Server/pull/3857)) @Kinglykrab 2024-01-07
* Convert Delete/Load/Remove/Save of Character AA to Repositories ([#3849](https://github.com/EQEmu/Server/pull/3849)) @Kinglykrab 2024-01-07
* Convert Delete/Load/Save of Character Bandolier to Repositories …
> [Release] 22.40.0

- common/ruletypes.h
- zone/effects.cpp
Legacy Manaburn can crit, however normal or crit has same hard cap.
Created a rule to better manage the cap for server owners.
> [Bug Fix] Legacy Manaburn should have hard cap.

- zone/effects.cpp
Adjusted logic order for HT/Improved HT/Unholy Touch
> [Bug Fix] Harm Touch, Improved Harm Touch, and Unholy Touch

- zone/spells.cpp
Occasionally bards would get an error when singing songs with another group member targetted.
> [Bug Fix] TGB - Added logic to stop bard errors on group songs.

- common/ruletypes.h
- zone/special_attacks.cpp
Added NPCBackstabMod - Default 1.9 - Lower mod = higher backstab.
> [Rules] Backstab Damage Modifier

- zone/spell_effects.cpp
Mistakenly removed BuffFadeBySlot(buffSlot);
> [Bug] DI Buff Fade

- zone/expedition.cpp
Per HG, this will resolve issues with HasLockoutByCharacterID
> [Bug Fix] Fix for HasLockoutByCharacterID

- world/zonelist.cpp
- zone/gm_commands/worldshutdown.cpp
Moved World Shutdown to the System filter from base yellow.
> [Bug Fix] World Shutdown Filter

- zone/zonedb.cpp
> [Bug Fix] Fix Typo in Character Skills loading

- zone/fearpath.cpp
Added a hard return on Undead Body Types. They should never flee under any circumstance.
> [Bug Fix] Undead Should Never Flee

- common/ruletypes.h
- common/spdat.cpp
- common/spdat.h
- zone/effects.cpp
- zone/spells.cpp
This is used to tune and bring HT Crits more in line with the correct values as proven in screenshots.
> [Bug Fix] Harm Touch Critical Ratio

- common/ruletypes.h
- zone/client.cpp
- zone/client.h
- zone/gm_commands/summon.cpp
- zone/zoning.cpp
Disable to silently summon players with #summon.
Converted SummonPC to a MessageString
> [Rule] Allow GMs to silently summon

- common/ruletypes.h
- zone/aggro.cpp
BardAggroCap - Default 40
Allows adjustment of per song bard aggro cap.
> [Rule] Add rule for Bard Song Aggro Cap

- zone/attack.cpp
Occasions where a corpse will allow skillups from attacks being turned on (even if no damage)
> [Bug Fix] Attack Corpse Skill Up Fix

- zone/attack.cpp
- zone/mob.h
- zone/mob_ai.cpp
Rampage should Hit 1-2 times (Primary / Secondary) should not be Triple/Quadable
> [Bug Fix] Rampage Number of Hits Limit

- zone/mob.cpp
- Uses pre-defined constants and cleanup code.
- Move `IsPlayerRace()` check so it's an early return instead of using an `else`.
> [Cleanup] Cleanup RandomizeFeatures()

- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/mob.cpp
- zone/mob.h
- zone/perl_mob.cpp
- Use `EQ::Clamp()` for logic instead of basic comparsions.
- Rename restriction parameter to `unrestricted`.
> [Cleanup] Cleanup ChangeSize()

- zone/zone.cpp
- Convert `LoadLevelEXPMods()` to repositories.
> [Experience Modifiers] Convert Load of Level Experience Modifiers to Repositories

- common/repositories/base/base_character_languages_repository.h
- zone/zonedb.cpp
- Convert `SaveCharacterLanguage()` to repositories.
- Was missed in the other languages changes.
> [Character] Convert Save of Character Languages to Repositories

- zone/zone.cpp
- Convert `LoadLDoNTraps()` and `LoadLDoNTrapEntries()` to repositories.
> [Traps] Convert Load of LDoN Traps/Trap Entries to Repositories

- common/repositories/base/base_respawn_times_repository.h
- common/repositories/respawn_times_repository.h
- zone/questmgr.cpp
- zone/spawn2.cpp
- zone/zone.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `respawn_times` based methods to repositories.
```pl
quest::updatespawntimer(4312, 5000);
}
}
```
> [Respawns] Convert Respawn Times to Repositories

- common/eq_packet_structs.h
- common/patches/rof2_structs.h
- common/patches/rof_structs.h
- common/patches/sod_structs.h
- common/patches/sof_structs.h
- common/patches/titanium_structs.h
- common/patches/uf_structs.h
- zone/object.cpp
- zone/zone.cpp
- zone/zonedb.h
- Convert `LoadGroundSpawns()` to repositories.
> [Ground Spawns] Convert Ground Spawns to Repositories

- zone/pets.cpp
- zone/zonedb.h
- Convert `GetPoweredPetEntry()` to repositories.
> [Pets] Convert Pets to Repositories

- zone/gm_commands/object_manipulation.cpp
- zone/object.cpp
- zone/zonedb.h
- Convert `AddObject()`, `DeleteObject()`, and `UpdateObject()` to repositories.
> [Objects] Convert Add/Delete/Update of Objects to Repositories

- zone/mob.cpp
- zone/mob.h
- Cleanup `GetOwner()`, `GetOwnerOrSelf()`, `GetUltimateOwner()`, `HasOwner()`, and `IsPet()` methods.
> [Cleanup] Cleanup Owner Related Mob Methods

- common/repositories/base/base_npc_types_repository.h
- common/repositories/base/base_spawn2_repository.h
- common/repositories/base/base_spawnentry_repository.h
- common/repositories/base/base_spawngroup_repository.h
- common/repositories/npc_types_repository.h
- zone/npc.cpp
- zone/zonedb.h
- Convert `AddNewNPCSpawnGroupCommand()`, `AddNPCTypes()`, `AddSpawnFromSpawnGroup()`, `CreateNewNPCCommand()`, `DeleteSpawnLeaveInNPCTypeTable()`, `DeleteSpawnRemoveFromNPCTypeTable()`, `NPCSpawnDB()`, and `UpdateNPCTypeAppearance()`.
> [Commands] Convert NPC Spawn Methods to Repositories

- common/eq_packet_structs.h
- zone/gm_commands/set/zone.cpp
- zone/gm_commands/show/zone_data.cpp
- zone/questmgr.cpp
- zone/zone.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `SaveZoneCFG()` to repositories.
> [Zones] Convert SaveZoneCFG to Repositories

- zone/aura.cpp
- Convert `GetAuraEntry()` to repositories.
> [Auras] Convert Get of Auras to Repositories

- common/emu_constants.cpp
- common/emu_constants.h
- zone/attack.cpp
- zone/client.cpp
- zone/entity.cpp
- zone/gm_commands/npcedit.cpp
- zone/mob_ai.cpp
- zone/npc.cpp
- zone/npc.h
- zone/zone.cpp
- zone/zone.h
- Convert `LoadNPCEmotes()` to repositories.
> [NPCs] Convert Load of NPC Emotes to Repositories

- common/repositories/base/base_object_contents_repository.h
- zone/zonedb.cpp
- Convert world containers to repositories.
> [Objects] Convert World Containers to Repositories

- zone/horse.cpp
- zone/horse.h
- zone/mob.h
- zone/string_ids.h
- Convert `BuildHorseType()` to repositories.
- Removed unused code, parameters, and member variables in horses.
> [Horses] Convert Horses to Repositories

- common/repositories/base/base_global_loot_repository.h
- utils/scripts/generators/repository-generator.pl
- zone/loottables.cpp
- Convert `LoadGlobalLoot()` to repositories.
> [Global Loot] Convert Global Loot to Repositories

- zone/zonedb.cpp
- zone/zonedb.h
> [Cleanup] Remove GroupCount() and RaidGroupCount()

- common/database.cpp
- common/repositories/base/base_merchantlist_temp_repository.h
- common/repositories/merchantlist_temp_repository.h
- zone/zonedb.cpp
- Convert `ClearMerchantTemp()`, `DeleteMerchantTemp()`, and `SaveMerchantTemp()` to repositories.
> [Merchants] Convert Clear/Delete/Save of Temporary Merchant Lists to Repositories

- common/repositories/base/base_character_corpse_items_repository.h
- common/repositories/base/base_character_corpses_repository.h
- common/repositories/character_corpses_repository.h
- common/shareddb.cpp
- common/shareddb.h
- world/adventure.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/corpse.cpp
- zone/embparser_api.cpp
- zone/gm_commands/show/buried_corpse_count.cpp
- zone/lua_client.cpp
- zone/lua_client.h
- zone/lua_general.cpp
- zone/perl_client.cpp
- zone/questmgr.cpp
- zone/questmgr.h
- zone/zonedb.cpp
- zone/zonedb.h
- Convert corpse-related methods to repositories.
> [Character] Convert Character Corpses to Repositories

- common/repositories/zone_repository.h
- zone/gm_commands/set/time_zone.cpp
- zone/zone.cpp
- zone/zonedb.cpp
- zone/zonedb.h
- Convert `GetZoneTimezone()` and `SetZoneTimeZone()` to repositories.
> [Zones] Convert Get/Set of Zone Timezone to Repositories

- CHANGELOG.md
- common/version.h
- package.json
* Convert Loading of AAs to Repositories ([#3963](https://github.com/EQEmu/Server/pull/3963)) @Kinglykrab 2024-01-13
* Convert Get of Auras to Repositories ([#3964](https://github.com/EQEmu/Server/pull/3964)) @Kinglykrab 2024-01-13
* Character EXP Modifiers in Memory ([#3934](https://github.com/EQEmu/Server/pull/3934)) @Kinglykrab 2024-01-13
* Convert Character Corpses to Repositories ([#3941](https://github.com/EQEmu/Server/pull/3941)) @Kinglykrab 2024-01-13
* Convert Save of Character Languages to Repositories ([#3948](https://github.com/EQEmu/Server/pull/3948)) @Kinglykrab 2024-01-12
* Cleanup AddCash() and RemoveCash() NPC Methods ([#3957](https://github.com/EQEmu/Server/pull/3957)) @Kinglykrab 2024-01-12
* Cleanup ChangeSize() ([#3959](https://github.com/EQEmu/Server/pull/3959)) …
> [Release] 22.42.0

- common/database/database_update_manifest.cpp
> [Bug Fix] Fix zone database update manifest

- CHANGELOG.md
- common/version.h
- package.json
* Fix zone database update manifest ([#3972](https://github.com/EQEmu/Server/pull/3972)) @Kinglykrab 2024-01-13
* quest::processmobswhilezoneempty() fix. ([#3971](https://github.com/EQEmu/Server/pull/3971)) @noudess 2024-01-13
> [Release] 22.42.1

- common/database/database_update_manifest.cpp
- common/version.h
Deprecated / removed in https://github.com/EQEmu/Server/pull/3955
**Testing**
Tested migration
```
World |    Info    | LoadRules Loaded [765] rules(s) in rule_set [default] id [1] 
World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
World |    Info    | CheckVersionsUpToDate   Server | database [9254] binary [9255] checking updates 
World |    Info    | CheckVersionsUpToDate   Config | [server.auto_database_updates] [true] 
World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
World |    Info    | UpdateManifest [9255]  [missing] | [2024_01_13_drop_item_tick_deprecated.sql] 
World |    Info    | UpdateManifest …
```
> [Database] Drop deprecated item_tick table

- zone/gm_commands/npcedit.cpp
- zone/gm_commands/petitems.cpp
- Adds `#npcedit grid_id [Grid ID]` to `#npcedit`.
> [Commands] Add `#npcedit set_grid [Grid ID]` to `#npcedit`

- zone/position.cpp
> [Cleanup] Cleanup position methods

- CHANGELOG.md
- common/version.h
- package.json
* ^mez command spell list fix ([#3998](https://github.com/EQEmu/Server/pull/3998)) @dariusuknuis 2024-01-19
* Cleanup position methods ([#4015](https://github.com/EQEmu/Server/pull/4015)) @Kinglykrab 2024-01-25
* Add `#npcedit set_grid [Grid ID]` to `#npcedit` ([#4004](https://github.com/EQEmu/Server/pull/4004)) @Kinglykrab 2024-01-22
* Fix crash when creating Frogloks/Drakkin ([#4016](https://github.com/EQEmu/Server/pull/4016)) @Kinglykrab 2024-01-25
* Reverting PR #3877 ([#3997](https://github.com/EQEmu/Server/pull/3997)) @fryguy503 2024-01-17
* Drop deprecated item_tick table ([#3977](https://github.com/EQEmu/Server/pull/3977)) @Akkadius 2024-01-14
* Drop item_tick if exists tweak in manifest ([#3985](https://github.com/EQEmu/Server/pull/3985)) @Akkadius 2024-01-15
* Increase max …
> [Release] 22.43.2

- zone/spawn2.cpp
- zone/spawn2.h
- zone/zonedb.h
- Convert `CreateSpawn2()`, `GetCondition()`, `LoadSpawnConditions()`, `LoadSpawnEvent()`, `UpdateSpawnCondition()`, and `UpdateSpawnEvent()` to repositories.
[Bixie Day/Night](https://github.com/EQEmu/Server/assets/89047260/3a75e556-9e8c-4e6e-a4b2-e448ab3f8fb7)
> [Spawn2] Convert Spawn2 Methods to Repositories

- common/eq_constants.h
- zone/attack.cpp
- Add constants for Raid loot types.
> [Cleanup] Add Raid Loot Type Constants

- zone/zone.cpp
- zone/zone.h
- Convert `GetMerchantDataForZoneLoad()` to repositories.
> [Merchants] Convert Merchant Load to Repositories

- zone/trap.cpp
- zone/zonedb.h
- Convert `LoadTraps()` and `SetTrapData()` to repositories.
> [Traps] Convert Load/Set of Traps to Repositories

- common/repositories/grid_entries_repository.h
- common/repositories/grid_repository.h
- common/repositories/spawn2_repository.h
- zone/gm_commands/grid.cpp
- zone/gm_commands/wp.cpp
- zone/gm_commands/wpadd.cpp
- zone/questmgr.cpp
- zone/questmgr.h
- zone/spawn2.cpp
- zone/waypoints.cpp
- zone/zonedb.h
- Convert `AddWaypoint()`, `AddWaypointForSpawn()`, `DeleteWaypoint()`, `GetHighestWaypoint()`, `GetRandomWaypointFromGrid()`, `GridExistsInZone()`, and `ModifyGrid()` to repositories.
> [Grids] Convert Grid/Grid Entries to Repositories

- common/repositories/base/base_traps_repository.h
- utils/scripts/generators/repository-generator.pl
- zone/spawn2.cpp
- zone/trap.cpp
- zone/zone.cpp
This PR hotfixes a few issues
* The traps PR was causing issues because `group` is a reserved word https://github.com/EQEmu/Server/pull/3994 preventing zone from booting at all
* Removed instances where loading 0 entries causes an error, prevents the zone from loading and removed places where we check a bool where we don't return a false anyways
> [Hotfix] Fix database loading routines

- zone/forage.cpp
- zone/zonedb.h
- Convert `GetZoneFishing()` and `GetZoneForage()` to repositories.
- Add support for `zoneid` of `0` in `forage` for custom global forage items.
> [Zone] Convert Fishing/Foraging to Repositories

- CHANGELOG.md
- common/version.h
- package.json
* Add lock_status method to world API ([#4028](https://github.com/EQEmu/Server/pull/4028)) @Akkadius 2024-01-29
* Convert Load of Alternate Currencies to Repositories ([#3993](https://github.com/EQEmu/Server/pull/3993)) @Kinglykrab 2024-01-29
* Cleanup Beacons Code ([#4024](https://github.com/EQEmu/Server/pull/4024)) @Kinglykrab 2024-01-29
* Convert Bot Database Methods to Repositories ([#4023](https://github.com/EQEmu/Server/pull/4023)) @Kinglykrab 2024-01-29
* Missing boolean returns on DeletePetStats and SaveInspectMessage ([#4031](https://github.com/EQEmu/Server/pull/4031)) @joligario 2024-01-30
* Add Raid Loot Type Constants ([#4022](https://github.com/EQEmu/Server/pull/4022)) @Kinglykrab 2024-01-29
* Cleanup cross-zone/world-wide OPCode handling …
> [Release] 22.43.3

- zone/attack.cpp
- These were not displaying because bots pass the `attacker && attacker->GetOwner()` check which assumes they're a pet because we weren't confirming it wasn't a bot.
> [Bug Fix] Fix Bot Non-Melee Damage Messages

- zone/tradeskills.cpp
Some minor formatting updates.
> [Cleanup] Remove redundant check in Object::HandleCombine

- world/client.cpp
- Switch was using the wrong race ID.
> [Bug Fix] Fix Froglok Starting Languages

- common/ruletypes.h
- zone/special_attacks.cpp
- zone/string_ids.h
RULE: ClassicTauntSystem
Completely seperate logic for each system. Could potentially be re-writte to be more inline but there are a good bit of minor differences.
> [Feature] Classic Taunt (Pre 2006) style of taunt

- CHANGELOG.md
- common/version.h
- package.json
* Remove from shared memory and simplify ([#4045](https://github.com/EQEmu/Server/pull/4045)) @Kinglykrab 2024-02-05
* Separate Bot Commands into Individual Files ([#4035](https://github.com/EQEmu/Server/pull/4035)) @Kinglykrab 2024-02-01
* Convert Quest Ornament Methods to Repositories ([#4048](https://github.com/EQEmu/Server/pull/4048)) @Kinglykrab 2024-02-10
* Remove redundant check in Object::HandleCombine ([#4041](https://github.com/EQEmu/Server/pull/4041)) @joligario 2024-02-03
* Add #show special_abilities ([#4043](https://github.com/EQEmu/Server/pull/4043)) @Kinglykrab 2024-02-05
* Update Spire to use SSL ([#4055](https://github.com/EQEmu/Server/pull/4055)) @Akkadius 2024-02-10
* Correct manifest migration entries that should be content …
> [Release] 22.44.0

- common/database/database_update_manifest.cpp
Caught in https://github.com/EQEmu/Server/commit/6bc9bcf15a5a431373b8e9d33117db87898f8f7f#r138512868
Thanks, hg
> [Database] Fix table name in manifest

- CHANGELOG.md
- common/version.h
- package.json
* Fix Issue with ClearSpawnTimers() ([#4070](https://github.com/EQEmu/Server/pull/4070)) @Kinglykrab 2024-02-13
> [Release] 22.44.3

- CHANGELOG.md
- common/version.h
- package.json
* Fix ClearSpawnTimers() ([#4073](https://github.com/EQEmu/Server/pull/4073)) @Kinglykrab 2024-02-13
> [Release] 22.44.4

- common/database_schema.h
Remove "item_tick" from database schema per https://github.com/EQEmu/Server/pull/3985
> [Database] Remove "item_tick" from database schema per #3985

- common/repositories/base/base_zone_flags_repository.h
- common/repositories/zone_flags_repository.h
- zone/zoning.cpp
- Converts `ClearZoneFlag()`, `LoadZoneFlags()`, and `SetZoneFlag()` to repositories.
```pl
sub EVENT_SAY
{
$client->SendZoneFlagInfo($client);
my $random_flag = quest::ChooseRandom(1..999);
$client->SetZoneFlag($random_flag);
} elsif ($text=~/#c/i) {
my @zone_flags = $client->GetZoneFlags();
my $random_flag = quest::ChooseRandom(@zone_flags);
$client->ClearZoneFlag($random_flag);
}
}
```
> [Repositories] Convert Zone Flags to Repositories

- zone/lua_parser.cpp
This adds an error msg handler for lua calls to add a stack trace to error messages. Lua 5.1 does not have luaL_traceback like luajit and lua 5.2+ so debug.traceback() is used directly as the msg handler.
The traceback will add more detail to errors than just logging package and event names. Exceptions in C++ binds and luabind errors will now show script context instead of just the error message.
e.g., for a luabind overload error:
```
No matching overload found, candidates:
void signal(int,int,int)
void signal(int,int)
stack traceback:
[C]: in function 'signal'
quests/arena/player.lua:10: in function 'somefn'
quests/arena/player.lua:27: in function <quests/arena/player.lua:17>
```
> [Quest API] Add tracebacks to Lua error messages

- common/database.cpp
- common/database.h
- common/eq_constants.h
- common/repositories/base/base_character_data_repository.h
- world/adventure.cpp
- world/client.cpp
- zone/expedition.cpp
- zone/expedition_request.cpp
- zone/gm_commands/instance.cpp
- zone/gm_commands/movechar.cpp
- zone/gm_commands/summon.cpp
- Converts `Database::GetCharacterID()`, `Database::SaveCharacterCreate()`, and `Client::OPCharCreate` to repositories.
- Cleanup a spot we were doing a queries in a loop.
[Screencast from 02-19-2024 05:37:25 PM.webm](https://github.com/EQEmu/Server/assets/89047260/f4060d20-d60b-4292-9bb8-458011bc2202)
> [Repositories] Cleanup and Convert Character Creation to Repositories

- common/database/database_update_manifest.cpp
> [Database] Add content_database flag for zone changes

- CHANGELOG.md
- common/version.h
- package.json
* Revert a few lines of PR #4024 that broke beacons ([#4118](https://github.com/EQEmu/Server/pull/4118)) @noudess 2024-02-24
* Cleanup empty `bot_commands` files ([#4095](https://github.com/EQEmu/Server/pull/4095)) @Kinglykrab 2024-02-19
* Remove Alt Combat Functionality ([#4067](https://github.com/EQEmu/Server/pull/4067)) @Kinglykrab 2024-02-12
* Update fmt to 10.2.1 ([#4071](https://github.com/EQEmu/Server/pull/4071)) @hgtw 2024-02-16
* Use explicit conversions for enum formatting ([#4064](https://github.com/EQEmu/Server/pull/4064)) @hgtw 2024-02-12
* Add content_database flag for zone changes ([#4104](https://github.com/EQEmu/Server/pull/4104)) @joligario 2024-02-20
* Remove "item_tick" from database schema per https://github.com/EQEmu/Server/pull/3985 …
> [Release] 22.45.0

- world/client.cpp
Reliably produces valid names (sufficient characters, not already in use), and attempts to produce names which are vaguely pronounceable and aesthetically pleasing.
> [Character Creation] Improved Random Name Generator

- common/database/database_dump_service.cpp
As seen in https://spire.akkadius.com/dev/release/22.45.0?id=19601
> [Crash] Fix crash issue during database dump

- CHANGELOG.md
- common/version.h
- package.json
* Improved Random Name Generator ([#4081](https://github.com/EQEmu/Server/pull/4081)) @catapultam-habeo 2024-02-27
* Fix Server Rules Documentation Generation ([#4125](https://github.com/EQEmu/Server/pull/4125)) @Kinglykrab 2024-02-26
* Remove unnecessary stoptimer logs ([#4128](https://github.com/EQEmu/Server/pull/4128)) @Kinglykrab 2024-02-28
* Add `#forage` command ([#4133](https://github.com/EQEmu/Server/pull/4133)) @joligario 2024-02-29
* Fix crash issue during database dump ([#4127](https://github.com/EQEmu/Server/pull/4127)) @Akkadius 2024-02-29
* D20 crash if mitigation average resulted in 0 ([#4131](https://github.com/EQEmu/Server/pull/4131)) @nytmyr 2024-02-29
* Fix forage returning first result from table ([#4130](https://github.com/EQEmu/Server/pull/4130)) @nytmyr 2024-02-29
* …
> [Release] 22.45.1

- common/emu_constants.cpp
- common/emu_constants.h
- zone/aggro.cpp
- zone/attack.cpp
- zone/entity.cpp
- zone/lua_mob.cpp
- zone/mob.cpp
- zone/npc.cpp
- Adds `IMMUNE_AGGRO_BOT` and `IMMUNE_DAMAGE_BOT` for uses in special abilities.
> [Quest API] Add Bot Special Attacks for Immune Aggro/Damage

- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/perl_mob.cpp
- Add `$mob->IsDestructibleObject()`.
- Add `mob:IsDestructibleObject()`.
- Allows operators to determine if a mob is a destructible object.
> [Quest API] Add IsDestructibleObject() to Perl/Lua

- common/database/database_update_manifest.cpp
- common/version.h
Added the id field to the guild_bank table to resolve a repo query error.  Also set as the primary key.
> [Bug Fix] Add id to the guild_bank table

- common/database/database_update_manifest.cpp
- common/version.h
- Add support for string-based rules.
> [Feature] Adjust String-based Rules Length

- zone/worldserver.cpp
Noticed a crash log on spire 22.46.1 id 19965 fp 5ea4e 
Added a check on guild to resolve.  
Cleaned up the formatting as well.
> [Crash Fix] Added a guild_mgr check

- CHANGELOG.md
* Added a guild_mgr check ([#4163](https://github.com/EQEmu/Server/pull/4163)) @neckkola 2024-03-06
* Goto Command could crash using Developer Tools ([#4158](https://github.com/EQEmu/Server/pull/4158)) @neckkola 2024-03-04
* Groundspawn Memory Corruption ([#4157](https://github.com/EQEmu/Server/pull/4157)) @neckkola 2024-03-04
* Update to location of qGlobals initialization ([#4144](https://github.com/EQEmu/Server/pull/4144)) @neckkola 2024-03-02
* Adds rules to control level requirements for Double Backstab, Assassinate, and Double Bowshot  (#4159) ([#29](https://github.com/EQEmu/Server/pull/29)) @catapultam-habeo 2024-03-04
* Adjust String-based Rules Length ([#4138](https://github.com/EQEmu/Server/pull/4138)) @Kinglykrab 2024-03-06
* Exempt a zone from IP-limit checks. …
> [Release] 22.47.0

- world/clientlist.cpp
https://spire.akkadius.com/dev/release/22.46.1?id=19955
https://spire.akkadius.com/dev/release/22.46.1?id=19948
https://spire.akkadius.com/dev/release/22.46.0?id=19945
> [Bug Fix] Fix Crash in ClientList::GetCLEIP

- zone/bot.cpp
This addresses crashes related to IsValidTarget on multiple servers.
Unsure of the exact reason if anyone can explain why changing from const bool to bool in this situation fixes the problem.
Is it because the const is somehow crashing on a bad pointer or is it attempting to be force changed?
> [Bots] IsValidTarget crash fix

- zone/lua_mob.cpp
- zone/lua_mob.h
- zone/perl_mob.cpp
- Add `$mob->GetDeityName()`.
- Add `mob:GetDeityName()`.
- Allows operators to get a mob's deity name.
> [Quest API] Add GetDeityName() to Perl/Lua

- common/database.cpp
- common/database.h
- zone/entity.cpp
- zone/expedition_request.cpp
- zone/expedition_request.h
- zone/groups.cpp
- zone/groups.h
- zone/lua_group.cpp
- zone/lua_group.h
- We were getting bogus data in this.
- Made it its own method.
- This works across zones as well because it calls the database.
> [Bug Fix] Fix GetLeaderName() for Groups

- common/crash.cpp
> [Process] Windows preprocessor define in crash.cpp

- CHANGELOG.md
- common/version.h
- package.json
* IsValidTarget Crash Fix ([#4187](https://github.com/EQEmu/Server/pull/4187)) @nytmyr 2024-03-12
* Move BotGroupSay to Pet Response ([#4171](https://github.com/EQEmu/Server/pull/4171)) @nytmyr 2024-03-08
* Cleanup Zone Get Methods ([#4169](https://github.com/EQEmu/Server/pull/4169)) @Kinglykrab 2024-03-09
* An Update to Xtarget to exclude Bot owned Temp/Swarm Pets ([#4172](https://github.com/EQEmu/Server/pull/4172)) @MortimerGreenwald 2024-03-08
* Fix #serverrules Command ([#4193](https://github.com/EQEmu/Server/pull/4193)) @Kinglykrab 2024-03-20
* Fix Bot Cloning ([#4186](https://github.com/EQEmu/Server/pull/4186)) @Kinglykrab 2024-03-17
* Fix Crash in ClientList::GetCLEIP ([#4173](https://github.com/EQEmu/Server/pull/4173)) @Kinglykrab 2024-03-10
* Fix Default Value in `rule_values` …
> [Release] 22.48.0

- zone/groups.cpp
> [Hot Fix] Hot Fix for Group::AddToGroup Hot Fix

- common/ruletypes.h
- zone/forage.cpp
Reported here: https://www.projecteq.net/forums/index.php?threads/fishing-issues.17823/
Fix regression from #4008 where the item count wasn't being incremented
Move the zone table chance to a rule
General cleanup of some initializers and variable types
> [Bug Fix] Fix fishing chances

- common/database.cpp
- common/database.h
- zone/mob.cpp
- zone/mob.h
Minor clean up from #4054 and #4181
> [Cleanup] Remove unnecessary reference types

- zone/hate_list.cpp
- Bots were reportedly being bypassed by NPCs due to not taking into consideration their raid group's damage.
- Must have been missed when bot raids were implemented.
- Thanks to @MortimerGreenwald for reporting.
> [Bug Fix] Fix Issue With Bot Raid Aggro

- common/database/database_update_manifest.cpp
Fixes an issue with schema type for skill caps manifest entry
Tested on remote PEQ instance
> [Fix] Fix manifest for skill caps schema type

- CHANGELOG.md
- common/version.h
- package.json
* Avoid unnecessary copies in database functions ([#4220](https://github.com/EQEmu/Server/pull/4220)) @joligario 2024-03-29
* Reference type in `GetRaidLeaderName` ([#4218](https://github.com/EQEmu/Server/pull/4218)) @joligario 2024-03-28
* Remove unnecessary reference types ([#4212](https://github.com/EQEmu/Server/pull/4212)) @joligario 2024-03-28
* Check mob pointer before trying to remove it ([#4230](https://github.com/EQEmu/Server/pull/4230)) @Akkadius 2024-04-01
* Add Character Auto Login ([#4216](https://github.com/EQEmu/Server/pull/4216)) @Kinglykrab 2024-04-15
* Add LuaMod functions for CommonDamage and HealDamage ([#4227](https://github.com/EQEmu/Server/pull/4227)) @xackery 2024-03-31
* Add RegisterBug LuaMod ([#4209](https://github.com/EQEmu/Server/pull/4209)) @xackery …
> [Release] 22.49.0

- common/database/database_update_manifest.cpp
- common/version.h
Breaking out changes to `npc_types` table to its own update since we need to alter the content schema. See #4198.
> [Database] Break out changes to `npc_types` from parcels

- world/shared_task_manager.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/corpse.cpp
- zone/doors.cpp
- zone/entity.cpp
- zone/expedition_request.cpp
- zone/object.cpp
- zone/questmgr.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
- zone/tasks.cpp
- zone/tradeskills.cpp
- zone/trading.cpp
- zone/trap.cpp
- zone/zoning.cpp
- Adds messages for the following:
1. `GetGM()` checks where having your GM Flag allows you to bypass a restriction, limit, or otherwise.
2. `Admin()` checks where having your GM Status allows you to bypass a restriction, limit, or otherwise.
3. `GetInvul()` checks where having Invulnerability keeps spells from landing on you or your target.
> [Messages] Add GM Status and Invulnerability Messages

- CHANGELOG.md
- common/version.h
- package.json
* Fix Message in #find task ([#4270](https://github.com/EQEmu/Server/pull/4270)) @Kinglykrab 2024-04-19
* Add rule to set stun duration.  Add rule to add stun messages. ([#4284](https://github.com/EQEmu/Server/pull/4284)) @noudess 2024-04-25
* Adjust #kill and #list Commands ([#4271](https://github.com/EQEmu/Server/pull/4271)) @Kinglykrab 2024-05-04
* Add profiler flag ([#4293](https://github.com/EQEmu/Server/pull/4293)) @xackery 2024-05-04
* Corpse searches for items did not search augs ([#4289](https://github.com/EQEmu/Server/pull/4289)) @noudess 2024-04-27
* Add Extra Haste to Bots/Character Tables ([#4286](https://github.com/EQEmu/Server/pull/4286)) @Kinglykrab 2024-05-04
* Break out changes to `npc_types` from parcels ([#4295](https://github.com/EQEmu/Server/pull/4295)) @joligario …
> [Release] 22.50.0

- zone/task_client_state.cpp
- Fully described [here](https://github.com/EQEmu/Server/issues/4247).
- Fixes #4247.
> [Bug Fix] Fix issue with KeepOneRecordPerCompletedTask

- common/database.cpp
- common/database.h
- common/repositories/character_data_repository.h
- world/console.cpp
- world/login_server.cpp
- world/main.cpp
- zone/api_service.cpp
- zone/client.cpp
- zone/gm_commands/suspend.cpp
- Described by Dracaena of EZ Server [here](https://discord.com/channels/212663220849213441/1240979738366054451).
> [Bug Fix] Fix issue with #suspend

- common/ruletypes.h
Mistakenly removed RULE_CATEGORY_END()
> [Bug Fix] Fix mistaken removed RULE_CATEGORY_END()

- CHANGELOG.md
- common/version.h
- package.json
* #npcspawn Changes ([#4311](https://github.com/EQEmu/Server/pull/4311)) @twincannon 2024-05-16
* Cleanup #resetaa Command ([#4310](https://github.com/EQEmu/Server/pull/4310)) @Kinglykrab 2024-05-22
* Add validation to RemoveXTarget ([#4324](https://github.com/EQEmu/Server/pull/4324)) @Akkadius 2024-05-25
* Fix Zone deconstructor crashes ([#4325](https://github.com/EQEmu/Server/pull/4325)) @Akkadius 2024-05-25
* Fix crash issue when dividing by zero in CalcHPRegen ([#4320](https://github.com/EQEmu/Server/pull/4320)) @Akkadius 2024-05-25
* Fix crash when map name is null ([#4322](https://github.com/EQEmu/Server/pull/4322)) @Akkadius 2024-05-25
* Fix player event crash in ITEM_DESTROY ([#4326](https://github.com/EQEmu/Server/pull/4326)) @Akkadius 2024-05-25
* Fix player events reload when …
> [Release] 22.51.0

- CHANGELOG.md
- common/version.h
- package.json
* Adjust return for perl release check  @Akkadius 2024-05-26
* Corrected issue with bazaar purchase via parcels where an incorrect quantity would be calculated. ([#4352](https://github.com/EQEmu/Server/pull/4352)) @neckkola 2024-05-27
* Improve SkillCaps::GetTrainLevel() Efficiency ([#4350](https://github.com/EQEmu/Server/pull/4350)) @Kinglykrab 2024-05-26
* Legacy Compute Defense against modern agi based defense. ([#4349](https://github.com/EQEmu/Server/pull/4349)) @fryguy503 2024-05-27
> [Release] 22.51.1

- zone/client.cpp
- zone/client.h
- zone/gm_commands/goto.cpp
- Resolves an issue with an un-escaped string making its way to `Client::GotoPlayer` mentioned [here](https://discord.com/channels/212663220849213441/1245124955226640384).
> [Bug Fix] Fix Unescaped String in Client::GotoPlayer

- common/deity.cpp
- common/deity.h
- common/inventory_profile.cpp
- common/inventory_profile.h
- world/worlddb.cpp
- zone/beacon.cpp
- zone/bot.cpp
- zone/client.cpp
- zone/embparser_api.cpp
- zone/encounter.cpp
- zone/gm_commands/find/deity.cpp
- zone/lua_client.cpp
- zone/lua_general.cpp
- zone/lua_mob.cpp
- zone/mob.h
- zone/perl_client.cpp
- zone/perl_mob.cpp
- zone/questmgr.cpp
- zone/questmgr.h
- Introduces `Deity` and `DeityBitmask` namespaces for methods like `EQ::deity::IsValidDeity`
- Cleans up a lot of the logic in finding a deity, checking for a valid deity, getting bitmask, etc.
- Logged in game, ran around, didn't notice any issues, can post screenshots or videos as necessary if there is specific functionality we need tested.
> [Cleanup] Cleanup Deity Code

- common/emu_constants.cpp
- common/emu_constants.h
- common/patches/sof.cpp
- common/patches/titanium.cpp
- common/repositories/command_subsettings_repository.h
- zone/client.cpp
- zone/gm_commands/find.cpp
- zone/gm_commands/find/bug_category.cpp
- Introduces `BugCategory` and `BugInformationFlag` namespaces.
- Adds `#find bug_category` subcommand.
- Logged in game, ran around, didn't notice any issues, can post screenshots or videos as necessary if there is specific functionality we need tested.
> [Cleanup] Cleanup Bug Category Code

- CHANGELOG.md
- common/version.h
- package.json
* Cleanup Bucket Comparison Code ([#4374](https://github.com/EQEmu/Server/pull/4374)) @Kinglykrab 2024-06-02
* Cleanup Bug Category Code ([#4367](https://github.com/EQEmu/Server/pull/4367)) @Kinglykrab 2024-06-01
* Cleanup Deity Code ([#4363](https://github.com/EQEmu/Server/pull/4363)) @Kinglykrab 2024-06-01
* Cleanup Special Ability Code ([#4365](https://github.com/EQEmu/Server/pull/4365)) @Kinglykrab 2024-06-01
* Remove unused code in common/eq_constants.h ([#4364](https://github.com/EQEmu/Server/pull/4364)) @Kinglykrab 2024-06-01
* Adjustments to Crippling Blows/Slay Undead and Confirmed Critical Code ([#4354](https://github.com/EQEmu/Server/pull/4354)) @fryguy503 2024-05-27
* Add protection to ensure adventure points award are only attempted on players …
> [Release] 22.52.0

- zone/spawn2.cpp
As seen [here](https://spire.akkadius.com/dev/release/22.52.0?id=24562), we need to check that the event actually exists before attempting to update it.
> [Bug Fix] Fix potential crash when updating spawn events

- CHANGELOG.md
- common/version.h
- package.json
* Anon players should not show in /who all ([#4392](https://github.com/EQEmu/Server/pull/4392)) @fryguy503 2024-06-14
* Escape should put player into SOS if owned. ([#4388](https://github.com/EQEmu/Server/pull/4388)) @fryguy503 2024-06-07
* Prevent Resurrection Spells from being resisted ([#4393](https://github.com/EQEmu/Server/pull/4393)) @fryguy503 2024-06-14
* Cleanup Account Status Code ([#4376](https://github.com/EQEmu/Server/pull/4376)) @Kinglykrab 2024-06-02
* Cleanup Body Type Code ([#4366](https://github.com/EQEmu/Server/pull/4366)) @Kinglykrab 2024-06-02
* Cleanup Object Type Code ([#4375](https://github.com/EQEmu/Server/pull/4375)) @Kinglykrab 2024-06-14
* Remove unused code in emu_constants.h ([#4384](https://github.com/EQEmu/Server/pull/4384)) @Kinglykrab 2024-06-14
* Fix …
> [Release] 22.53.0

- CHANGELOG.md
- common/version.h
- package.json
* Fix trader mode ([#4397](https://github.com/EQEmu/Server/pull/4397)) @joligario 2024-06-17
> [Release] 22.53.1

- zone/bonuses.cpp
> [Bug] AllowRaidTargetBlind logic backwards

- common/emu_constants.cpp
- common/emu_constants.h
- common/repositories/command_subsettings_repository.h
- zone/bot.cpp
- zone/bot.h
- zone/bot_commands/attack.cpp
- zone/bot_commands/bot.cpp
- zone/bot_commands/pull.cpp
- zone/bot_database.cpp
- zone/botspellsai.cpp
- zone/client_packet.cpp
- zone/gm_commands/find.cpp
- zone/gm_commands/find/stance.cpp
- zone/merc.cpp
- zone/merc.h
- Introduces `Stance` namespace for stuff like `IsValid`.
- Cleans up a lot of the logic in finding a stance, checking for a valid stance, etc.
- Adds `#find stance` subcommand.
- Logged in game, ran around, didn't notice any issues, can post screenshots or videos as necessary if there is specific functionality we need tested.
> [Cleanup] Cleanup Stance Code

- zone/bonuses.cpp
- zone/client.h
- zone/tribute.cpp
It was reported that the person tribute 'Harmony of Drums/Winds/etc' were not applying their modifications correctly.  I was able to reproduce.  This fix should resolve the issue.
https://www.youtube.com/watch?v=qscETMzr7Hs
RoF2
> [Bug Fix] Personal Tributes for bard items not being applied correctly

- zone/bonuses.cpp
- zone/client.h
- zone/tribute.cpp
Reverts EQEmu/Server#4414
I discovered an issue with Bots.  Reverting until I have a chance to correct it.
> Revert "[Bug Fix] Personal Tributes for bard items not being applied correctly"

- zone/client.h
- zone/client_process.cpp
- zone/special_attacks.cpp
Original Commit: 33fecd68d4eab36885eb7f8067102ba6bce95bac
Conditional ranged double attack
> [Bug Fix] Potential fix for some undesired ranged exploitative behavior.

- zone/bot.h
Fixes an issue described [here](https://discord.com/channels/212663220849213441/1263891012950954004).
> [Bug Fix] Fix Bot::SetBotStance

- CHANGELOG.md
- common/version.h
- package.json
* Cleanup Client File Exporting ([#4348](https://github.com/EQEmu/Server/pull/4348)) @Kinglykrab 2024-07-31
* Cleanup Stance Code ([#4368](https://github.com/EQEmu/Server/pull/4368)) @Kinglykrab 2024-07-03
* Mask GM Show Buff message behind EntityVariable ([#4419](https://github.com/EQEmu/Server/pull/4419)) @nytmyr 2024-07-22
* Extend #devtools Functionality ([#4425](https://github.com/EQEmu/Server/pull/4425)) @Kinglykrab 2024-07-23
* Remove memory reserve from bulk load ([#4427](https://github.com/EQEmu/Server/pull/4427)) @Akkadius 2024-07-23
* Add Barter/Buyer Features ([#4405](https://github.com/EQEmu/Server/pull/4405)) @neckkola 2024-07-30
* Add Parcel notification for online players when using the Quest API ([#4418](https://github.com/EQEmu/Server/pull/4418)) @neckkola 2024-07-22
* …
> [Release] 22.54.0

- zone/spell_effects.cpp
Imitate Death should also clear zone feign aggro
> [Bug Fix] Imitate Death should also clear zone feign aggro

- zone/tribute.cpp
Ensure proper return in the rare event that no item is found. Minor tweak to #4416.
> [Bug Fix] Ensure close of tribute item search

- common/database.cpp
- common/ruletypes.h
* [Feature] Add Character:DefaultGuildRank Rule
* Update ruletypes.h
* Update ruletypes.h
* Update database.cpp
> [Feature] Add Character:DefaultGuildRank Rule (#4438)

- CHANGELOG.md
- common/version.h
- loginserver/client.cpp
- package.json
* Remove unused methods ([#4449](https://github.com/EQEmu/Server/pull/4449)) @Kinglykrab 2024-08-22
* Add Character:DefaultGuildRank Rule ([#4438](https://github.com/EQEmu/Server/pull/4438)) @Kinglykrab 2024-08-04
* Add Optional Return to EVENT_DAMAGE_TAKEN ([#4454](https://github.com/EQEmu/Server/pull/4454)) @Kinglykrab 2024-08-27
* Extend Spell Buckets Functionality ([#4441](https://github.com/EQEmu/Server/pull/4441)) @Kinglykrab 2024-08-22
* Apply Race & Class restrictions to Auto-Combines ([#4452](https://github.com/EQEmu/Server/pull/4452)) @catapultam-habeo 2024-08-20
* Attune Augments when Equipped ([#4446](https://github.com/EQEmu/Server/pull/4446)) @fryguy503 2024-08-10
* Correct missed maxlevel reference in exp.cpp ([#4463](https://github.com/EQEmu/Server/pull/4463)) @N0ctrnl …
> [Release] 22.55.0

- zone/mob.cpp
- zone/mob.h
This is a very small PR that adds a helper method in assistance to another PR https://github.com/EQEmu/Server/pull/4453
> [Code] Add IsCloseToBanker method

- world/adventure.cpp
Fix infinite loop condition when bot encountered
SoF2
> [Bug Fix] Fix Infinite Loop in Adventure::Finished()

- CHANGELOG.md
- common/version.h
- package.json
* Fix Issue with Database::ReserveName ([#4477](https://github.com/EQEmu/Server/pull/4477)) @Kinglykrab 2024-09-20
* Add GrantAllAAPoints() Overload To Perl/Lua ([#4474](https://github.com/EQEmu/Server/pull/4474)) @Kinglykrab 2024-09-20
> [Release] 22.56.2

- zone/gm_commands/set/motd.cpp
- Fixes a bug described [here](https://discordapp.com/channels/212663220849213441/557677602706423982/1291920794011701260).
> [Bug Fix] Fix #set motd Crash

- common/ruletypes.h
- zone/client.cpp
- Adds a rule to disable PVP regions setting your PVP flag.
> [Rules] Add Rule to disable PVP Regions

- CHANGELOG.md
- common/version.h
- package.json
* Add "silent" option to ^spawn and mute raid spawn ([#4494](https://github.com/EQEmu/Server/pull/4494)) @nytmyr 2024-10-05
* Add attack flag when told to attack ([#4490](https://github.com/EQEmu/Server/pull/4490)) @nytmyr 2024-09-29
* Fix timers loading on spawn and zone ([#4516](https://github.com/EQEmu/Server/pull/4516)) @nytmyr 2024-10-20
* Fixed a typo in Zoning.cpp ([#4515](https://github.com/EQEmu/Server/pull/4515)) @carolus21rex 2024-10-20
* Optimization Code Cleanup ([#4489](https://github.com/EQEmu/Server/pull/4489)) @Akkadius 2024-09-30
* Remove Extra Skill in EQ::skills::GetExtraDamageSkills() ([#4486](https://github.com/EQEmu/Server/pull/4486)) @Kinglykrab 2024-10-03
* Fixes a crash when the faction_list db table is empty. ([#4511](https://github.com/EQEmu/Server/pull/4511)) …
> [Release] 22.57.0

- CHANGELOG.md
- common/version.h
- package.json
* Enable Bot Commands Only if Rule Enabled ([#4519](https://github.com/EQEmu/Server/pull/4519)) @Kinglykrab 2024-10-22
* Fix pet buffs from saving duplicates every save ([#4520](https://github.com/EQEmu/Server/pull/4520)) @nytmyr 2024-10-22
* Automatic Opcode File Creation ([#4521](https://github.com/EQEmu/Server/pull/4521)) @KimLS 2024-10-22
> [Release] 22.57.1

- CHANGELOG.md
- common/version.h
- package.json
* Add mysql prepared statement support ([#4530](https://github.com/EQEmu/Server/pull/4530)) @hgtw 2024-11-06
* Update perlbind to 1.1.0 ([#4529](https://github.com/EQEmu/Server/pull/4529)) @hgtw 2024-11-06
* Focus Skill Attack Spells ([#4528](https://github.com/EQEmu/Server/pull/4528)) @mmcgarvey 2024-10-31
* Add Missing Lua Registers ([#4525](https://github.com/EQEmu/Server/pull/4525)) @Kinglykrab 2024-10-24
* Fix cross_zone_set_entity_variable_by_char_id in Lua ([#4526](https://github.com/EQEmu/Server/pull/4526)) @Kinglykrab 2024-10-24
* Automatifc Opcode File Creation ([#4521](https://github.com/EQEmu/Server/pull/4521)) @KimLS 2024-10-22
* Add Spawn Circle/Grid Methods to Perl/Lua ([#4524](https://github.com/EQEmu/Server/pull/4524)) @Kinglykrab 2024-10-24
* Enable Bot Commands Only if …
> [Release] 22.58.0

- common/database/database_update_manifest.cpp
- common/version.h
This covers some queries that aren't covered by indexes. Observed performance issues on THJ.
Validated queries no longer hung for multiple seconds.
**Migration**
```
World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
World |    Info    | CheckVersionsUpToDate   Server | database [9284] binary [9285] checking updates 
World |    Info    | CheckVersionsUpToDate   Config | [server.auto_database_updates] [true] 
World |    Info    | CheckVersionsUpToDate ---------------------------------------------------------------------- 
World |    Info    | UpdateManifest [9285]       [ok] | [2024_11_08_data_buckets_indexes.sql] 
World |    Info    | UpdateManifest ---------------------------------------------------------------------- 
World …
```
> [Databuckets] Add database index to data_buckets

- zone/mob.cpp
- zone/npc.cpp
This fixes an issue found on THJ where NPC's when spawned would immediately disappear. After burning 12 hours on the issue we've figured out the mystery.
https://github.com/user-attachments/assets/b25128e7-ec45-4bca-8ac7-385bcbf36223
https://github.com/user-attachments/assets/6ad4d0bc-6efe-49d6-8804-20722f84dd57
> [Bug Fix] Fix issue where NPC's are being hidden as traders

- CHANGELOG.md
- common/version.h
- package.json
* Further refinements for instanced bazaar ([#4544](https://github.com/EQEmu/Server/pull/4544)) @neckkola 2024-11-16
* Fix build with older C++ libraries ([#4549](https://github.com/EQEmu/Server/pull/4549)) @hgtw 2024-11-24
* Fix World TCP Address Configuration Default ([#4551](https://github.com/EQEmu/Server/pull/4551)) @Akkadius 2024-11-24
* Fix Issue with Perl EVENT_PAYLOAD ([#4545](https://github.com/EQEmu/Server/pull/4545)) @Kinglykrab 2024-11-24
* Fix Possible Item Loss in Trades ([#4554](https://github.com/EQEmu/Server/pull/4554)) @Kinglykrab 2024-11-24
* Fix Strings::Commify bug with #mystats ([#4547](https://github.com/EQEmu/Server/pull/4547)) @carolus21rex 2024-11-22
* Fix an edge case with augmented items inside parceled containers …
> [Release] 22.60.0

- zone/gm_commands/find.cpp
- zone/gm_commands/find/bot.cpp
- Adds a `#find bot` subcommand.
> [Commands] Add #find bot Subcommand

- common/database.cpp
- world/cli/copy_character.cpp
Resolves an issue where several tables were erroring when copying a character.
* Adds validation to make sure that the destination player name doesn't already exist
* Adds logging to each table that is copied for the player and how many rows were copied
```
./bin/world character:copy-character Zerknotes Akkazerk schecterx
World |    Info    | CopyCharacter Attempting to copy character [Zerknotes] to [Akkazerk] via account [schecterx] 
World |    Info    | CopyCharacter Copying table [char_recipe_list] rows [9] 
World |    Info    | CopyCharacter Copying table [character_activities] rows [7] 
World |    Info    | CopyCharacter Copying table [character_alt_currency] rows [1] 
World |    Info    | CopyCharacter Copying table [character_alternate_abilities] rows [68] 
World |    Info    | …
```
> [Command] Fix #copycharacter

- CHANGELOG.md
- common/version.h
- package.json
* Fix AA ranks to account for level ([#4567](https://github.com/EQEmu/Server/pull/4567)) @nytmyr 2024-12-07
* Convert Event Parses to Single Line ([#4569](https://github.com/EQEmu/Server/pull/4569)) @Kinglykrab 2024-12-12
* Fix GM Flag Spell Restriction Bypasses ([#4571](https://github.com/EQEmu/Server/pull/4571)) @Kinglykrab 2025-01-06
* Remove Unused Group Methods ([#4559](https://github.com/EQEmu/Server/pull/4559)) @Kinglykrab 2024-12-12
* Add #find bot Subcommand ([#4563](https://github.com/EQEmu/Server/pull/4563)) @Kinglykrab 2024-12-12
* Add #find ldon_theme Subcommand ([#4564](https://github.com/EQEmu/Server/pull/4564)) @Kinglykrab 2024-12-12
* Fix #copycharacter ([#4582](https://github.com/EQEmu/Server/pull/4582)) @Akkadius 2025-01-06
* Improved Reliability and Performance of …
> [Release] 22.61.0

- CHANGELOG.md
- common/version.h
- package.json
* Improve Bazaar Search Performance ([#4615](https://github.com/EQEmu/Server/pull/4615)) @neckkola 2025-01-27
* Add --skip-backup to world database:updates ([#4605](https://github.com/EQEmu/Server/pull/4605)) @Akkadius 2025-01-22
* Change npc_types walkspeed to be of type float ([#4589](https://github.com/EQEmu/Server/pull/4589)) @Akkadius 2025-01-07
* Add Account Scoped Databuckets ([#4603](https://github.com/EQEmu/Server/pull/4603)) @Akkadius 2025-01-21
* Implement Nested Databuckets ([#4604](https://github.com/EQEmu/Server/pull/4604)) @Akkadius 2025-01-27
* Add Alternate Bazaar Search Approach ([#4600](https://github.com/EQEmu/Server/pull/4600)) @neckkola 2025-01-20
* Add Support for Item Previews ([#4599](https://github.com/EQEmu/Server/pull/4599)) @Kinglykrab 2025-01-20
* Evolving …
> [Release] 22.62.0

- zone/entity.cpp
Tested in game, repopped NPCs, NPC's findable.
> [Performance] Reuse OP_SendFindableNPCs packet memory

- CHANGELOG.md
- common/version.h
- package.json
* Add price change check to the Bazaar Search Window purchase mechanics ([#4632](https://github.com/EQEmu/Server/pull/4632)) @neckkola 2025-02-01
* NewBazaar Search Consumables ([#4631](https://github.com/EQEmu/Server/pull/4631)) @neckkola 2025-02-01
* Update the shard bazaar search feature ([#4630](https://github.com/EQEmu/Server/pull/4630)) @neckkola 2025-02-01
* Revert " Change raw pointer to unique_ptr to avoid potential leak in dbg stream " ([#4616](https://github.com/EQEmu/Server/pull/4616)) @Akkadius 2025-01-27
* Significantly Improve Client Network Resends ([#4629](https://github.com/EQEmu/Server/pull/4629)) @Akkadius 2025-02-01
> [Release] 22.62.2

- common/shareddb.cpp
Cleanup logic of cursor bag saving
Camps, logins, storing items from cursor and leaving some on bag between relogs to verify count was correct until all placed in inventory.
> [Cleanup] Cleanup logic in cursor bag check

- zone/zonedb.cpp
> [Fix] Big Bag additional fixes

- utils/scripts/build/linux-build.sh
- utils/scripts/build/source-db-build.sh
This ensures that the database is fully sourced instead of hoping that it is by the time we get to performing integration tests.
This also ensures that if there are errors in test output that the build fails. 
Properly failing build http://drone.akkadius.com/EQEmu/Server/16840/1/2
> [CI] Fix database race condition

- zone/bot.cpp
- zone/bot.h
- zone/bot_commands/bot.cpp
- zone/bot_commands/cast.cpp
- zone/bot_commands/depart.cpp
- zone/bot_commands/guard.cpp
- zone/bot_commands/hold.cpp
- zone/bot_commands/pet.cpp
- zone/bot_commands/pick_lock.cpp
- zone/bot_commands/taunt.cpp
- zone/bot_commands/track.cpp
- zone/botspellsai.cpp
- zone/lua_bot.cpp
- zone/perl_bot.cpp
- zone/special_attacks.cpp
- Cleans up the method for RaidGroupSay.
- Same functionality, just not as dirty.
- Still functions proper and as intended.
> [Bots] RaidGroupSay

- zone/bot.cpp
- This message had typos and didn't provide full information for why it was failing a check.
- Same functionality.
> [Bots] Correct helper message for forced casts

- zone/bot.cpp
- zone/bot_commands/spell_engaged_priority.cpp
- zone/bot_commands/spell_idle_priority.cpp
- zone/bot_commands/spell_pursue_priority.cpp
- Fix priority value check in spellpriority commands
- Fix list option
- Remove unnecessary temp vector on list grab
- Will move getter to cache in future PR
- Verified listing, setting and checking for commands.
> [Bots] Fix spell priority commands

- zone/client.cpp
- zone/client.h
- zone/client_evolving_items.cpp
- zone/client_packet.cpp
- zone/corpse.cpp
- zone/forage.cpp
- zone/object.cpp
- zone/task_client_state.cpp
- zone/tradeskills.cpp
- zone/zone.h
- Fixes an issue where items were not being properly discovered when picked up from the ground, evolved, fished, foraged, awarded by tasks, or as a result of a tradeskill recipe.
- Resolves https://github.com/EQEmu/Server/issues/4636.
- Adds caching to discovered items.
> [Bug Fix] Fix Item Discovery

- loginserver/client_manager.cpp
This fixes a regression caused by using modern remove_if paradigms, but causes issues because we manually manage the memory. This reverts to previous behavior.
Tested logging in and disconnecting client forcefully, logging in two of the same clients at the same time
```
Login |    Info    | ProcessDisconnect Client disconnected from the server, removing client 
```
```
Login |    Info    | RemoveExistingClient Client attempting to log in existing client already logged in, removing existing client 
```
> [Loginserver] Fix Iterator Crash

- common/bazaar.cpp
Change logging level for no items found in a bazaar search to reduce spam logs.
RoF2
> [Fix] Change logging level for no items found in a bazaar search

- common/database/database_update_manifest.cpp
- common/emu_constants.h
- common/eq_limits.cpp
- common/eq_limits.h
- common/eq_packet_structs.h
- common/events/player_events.h
- common/guild_base.cpp
- common/patches/rof.cpp
- common/patches/rof2.cpp
- common/patches/rof2_limits.h
- common/patches/rof2_structs.h
- common/patches/rof_structs.h
- common/repositories/base/base_guild_bank_repository.h
- common/version.h
- zone/client_packet.cpp
- zone/entity.cpp
- zone/entity.h
- zone/gm_commands/guild.cpp
- zone/guild_mgr.cpp
- zone/guild_mgr.h
This feature update provides additional RoF2 functionality for the Guild Bank.
- Updates the backend to allow for augmented items to be stored in the bank
- Allows for the max items with the RoF2 client.  200 in main area, 40 in deposit area
https://www.youtube.com/watch?v=kuryNi0p69Q
Tested with RoF2 as noted above.
RoF2
> [Feature] GuildBank Updates

- CHANGELOG.md
- common/database/database_update_manifest.cpp
- common/version.h
- package.json
* Add AEHateLine to HateLine ParentType ([#4678](https://github.com/EQEmu/Server/pull/4678)) @nytmyr 2025-02-15
* Add IsInRaidOrGroup checks to ^attack and ^pull ([#4654](https://github.com/EQEmu/Server/pull/4654)) @nytmyr 2025-02-07
* Add missing stance options ([#4681](https://github.com/EQEmu/Server/pull/4681)) @nytmyr 2025-02-15
* Bot Overhaul ([#4580](https://github.com/EQEmu/Server/pull/4580)) @nytmyr 2025-02-03
* Command Cleanup ([#4676](https://github.com/EQEmu/Server/pull/4676)) @nytmyr 2025-02-15
* Correct camp count on ^camp ([#4650](https://github.com/EQEmu/Server/pull/4650)) @nytmyr 2025-02-06
* Correct helper message for forced casts ([#4656](https://github.com/EQEmu/Server/pull/4656)) @nytmyr 2025-02-07
* Crash fixes related to GetNumberNeedingHealedInGroup …
> [Release] 23.0.0

- zone/client.cpp
- zone/client.h
- zone/lua_client.cpp
- zone/lua_client.h
- zone/perl_client.cpp
- Adds various keyring methods to Perl and Lua.
- Add `$client->KeyRingClear()`
- Add `$client->KeyRingList()`
- Add `$client->KeyRingRemove(item_id)`
```pl
my $item_one = 1001;
my $item_two = 1002;
$client->KeyRingList();
$client->KeyRingAdd($item_one);
$client->KeyRingAdd($item_two);
} elsif ($text=~/#c/i) {
my $has_item_one = $client->KeyRingCheck($item_one);
my $has_item_two = $client->KeyRingCheck($item_two);
$client->Message(315, "One: $has_item_one Two: $has_item_two");
} elsif ($text=~/#d/i) {
$client->KeyRingRemove($item_one);
$client->KeyRingRemove($item_two);
} elsif ($text=~/#e/i) {
$client->KeyRingClear();
}
}
```
- Add `client:KeyRingClear()`
- Add `client:KeyRingList()`
- Add `client:KeyRingRemove(item_id)`
```lua …
```
> [Quest API] Add Key Ring Methods to Perl and Lua

- common/database.cpp
- common/eq_packet_structs.h
- common/net/servertalk_server_connection.cpp
- common/servertalk.h
- loginserver/world_server.cpp
- loginserver/world_server_manager.cpp
- world/client.cpp
- world/cliententry.cpp
- world/cliententry.h
- world/clientlist.cpp
- world/clientlist.h
- world/login_server.cpp
- world/worlddb.cpp
This simply cleans up more code along the login path of a client. Not much else going on here.
* Member variable prefixing in client list entry `m_`
* fmt::format, remove numbered positions
* Single letter receivers
* Refactoring function signatures to be consistent with our current patterns
Tested logging in as per normal, no issues
> [Code Cleanup] More login <-> world code cleanup

- zone/zone_save_state.cpp
This fixes a minor edge case from https://github.com/EQEmu/Server/pull/4715 where in some cases a row may contain an empty entry and the JSON serialization throws an exception. The problem with this is if we don't catch every exception where it happens, it bubbles up way higher in the zoneserver stack and can actually keep the zone server from working at all.
Below are exceptions being caught and zone loaded normally
```
Zone | ZoneState  | LoadLootStateData Failed to load loot state data for NPC [29030] [JSON Parsing failed - provided NVP (copper) not found] 
Zone | ZoneState  | LoadNPCEntityVariables Failed to load entity variables for NPC [29030] [No more objects in input] 
Zone | ZoneState  | LoadNPCBuffs Failed to load entity variables for NPC [29030] [JSON Parsing failed - provided …
```
> [Zone State] Wrap all serialization/deserialization in try/catch

- loginserver/world_server.cpp
- loginserver/world_server.h
Minor loginserver code cleanup, change an error to an info, comments etc.
Not much testing to do here, boots, works
> [Loginserver] Minor cleanup

- zone/main.cpp
Check for directory existence before traversing in CheckForCompatibleQuestPlugins
Addresses crash https://spire.akkadius.com/dev/release/23.0.2?id=214221
On missing plugins dir
```
Zone |   Error    | CheckForCompatibleQuestPlugins Failed to find CheckHandin in plugins 
Zone |   Error    | main Incompatible quest plugins detected, please update your plugins to the latest version
```
> [Crash] Check for directory existence before traversing in CheckForCompatibleQuestPlugins

- common/file.cpp
Fixes (20+ occurrences) crash found here https://spire.akkadius.com/dev/release/23.0.2?id=214971
```
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\heap\throw_bad_alloc.cpp (35): __scrt_throw_std_bad_alloc 
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp (48): operator new 
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory (136): std::_Allocate_manually_vector_aligned<std::_Default_allocate_traits> 
C:\Windows\Temp\drone-hj5VEr5bfcU1gHs6\drone\src\common\file.cpp (108): File::GetContents 
C:\Windows\Temp\drone-hj5VEr5bfcU1gHs6\drone\src\common\database\database_dump_service.cpp (332): DatabaseDumpService::DatabaseDump 
C:\Windows\Temp\drone-hj5VEr5bfcU1gHs6\drone\src\common\database\database_update.cpp (187): …
```
> [Crash] Fix large file size crash in File::GetContents for windows

- CHANGELOG.md
- common/database/database_update_manifest.cpp
- common/version.h
- package.json
* Fix unresponsive bots in groups upon group wipe ([#4712](https://github.com/EQEmu/Server/pull/4712)) @nytmyr 2025-02-28
* More login <-> world code cleanup ([#4724](https://github.com/EQEmu/Server/pull/4724)) @Akkadius 2025-02-28
* Check for directory existence before traversing in CheckForCompatibleQuestPlugins ([#4730](https://github.com/EQEmu/Server/pull/4730)) @Akkadius 2025-03-02
* Fix filesystem crash / exception in DatabaseDumpService::RemoveCredentialsFile() ([#4731](https://github.com/EQEmu/Server/pull/4731)) @Akkadius 2025-03-01
* Fix large file size crash in File::GetContents for windows ([#4735](https://github.com/EQEmu/Server/pull/4735)) @Akkadius 2025-03-02
* Fix reload concurrency crash when ran from Spire ([#4733](https://github.com/EQEmu/Server/pull/4733)) @Akkadius …
> [Release] 23.1.0

- zone/parcels.cpp
This fix resolves two edge cases seen with parcel delivery.
- If the player had an item with charges, like a potion, within the item within the parcel delivery window, and then used a charge on the item, the delivered item would not be adjusted correctly.  This was fixed by preventing casting when sending a parcel.
- If the item being sent via parcel had 0 charges, the charge would not be respected when retrieved.
These issues are rarely seen and have been reported, mostly from server operators that allow normally no-drop items to be tradeable.
This was tested within THJ for some time.
RoF2
> [Fix] Parcel Delivery Updates for two edge cases

- zone/client_packet.cpp
- zone/corpse.cpp
- zone/gm_commands/parcels.cpp
- zone/inventory.cpp
- zone/trading.cpp
- zone/worldserver.cpp
There were crash reports on THJ for certain PlayerEventLogs and augments.  Added several checks.
Hotfix.  Could not reproduce.
> [Fix] Add crash checks for certain PlayerEventLogs

- CHANGELOG.md
- common/version.h
- package.json
* Add indexes for data_buckets and zone_state_spawns ([#4771](https://github.com/EQEmu/Server/pull/4771)) @Akkadius 2025-03-11
* Update GuildBank to correctly handle items with charges equal to zero ([#4774](https://github.com/EQEmu/Server/pull/4774)) @neckkola 2025-03-13
* Fix "port in use" error ([#4772](https://github.com/EQEmu/Server/pull/4772)) @Akkadius 2025-03-12
* Zone State Improvements Part 3 ([#4773](https://github.com/EQEmu/Server/pull/4773)) @Akkadius 2025-03-13
> [Release] 23.3.3

- world/eqemu_api_world_data_service.cpp
- world/zoneserver.h
This exposes zoneserver compile metadata to be used by tools such as Spire
See version column
> [API] Expose Zoneserver Compile Metadata

- CHANGELOG.md
- common/version.h
- package.json
* Expose Zoneserver Compile Metadata ([#4815](https://github.com/EQEmu/Server/pull/4815)) @Akkadius 2025-03-29
* Charmed Pets were breaking Mob respawns ([#4780](https://github.com/EQEmu/Server/pull/4780)) @nytmyr 2025-03-16
* Enraged positioning ([#4789](https://github.com/EQEmu/Server/pull/4789)) @nytmyr 2025-03-29
* Fix IsValidSpellTypeBySpellID to account for all types ([#4764](https://github.com/EQEmu/Server/pull/4764)) @nytmyr 2025-03-19
* Fix Rule ZonesWithSpawnLimits/ZonesWithForcedSpawnLimits errors ([#4791](https://github.com/EQEmu/Server/pull/4791)) @nytmyr 2025-03-29
* Fix rule Bots:FinishBuffing ([#4788](https://github.com/EQEmu/Server/pull/4788)) @nytmyr 2025-03-29
* Line of Sight and Mez optimizations and cleanup ([#4746](https://github.com/EQEmu/Server/pull/4746)) @nytmyr …
> [Release] 23.4.0

- zone/mob_movement_manager.cpp
Changes fix heading to use a less insane algorithm.
Downside: it loses a bit of granularity. 
Upside: It should no longer cause paw to hang in certain circumstances.
Tested locally by testing pathing in various ways.  Noticed no aberrations in the movement or heading changes.
Clients tested:  RoF2
> [Fix] FixHeading Infinite Loop Fix

- zone/gm_commands/task.cpp
- Addresses a crash reported [here](https://discord.com/channels/212663220849213441/557677602706423982/1366488964244050010).
> [Bug Fix] Fix Crash with #task

- CHANGELOG.md
- common/version.h
- package.json
* Correct ^pull logic and add checks for Enchanter pets ([#4827](https://github.com/EQEmu/Server/pull/4827)) @nytmyr 2025-05-15
* Fix creation limit, spawn limit, level requirement checks ([#4868](https://github.com/EQEmu/Server/pull/4868)) @nytmyr 2025-05-15
* Move all spell_id instances to uint16 ([#4876](https://github.com/EQEmu/Server/pull/4876)) @nytmyr 2025-05-15
* Prevent non-taunters from potentially fleeing mob on TargetReflection ([#4859](https://github.com/EQEmu/Server/pull/4859)) @nytmyr 2025-04-28
* ETL Settings Output ([#4873](https://github.com/EQEmu/Server/pull/4873)) @joligario 2025-05-15
* Fix typo in QueryNameAvailablity ([#4869](https://github.com/EQEmu/Server/pull/4869)) @nytmyr 2025-04-28
* Fix crash bug with pbae and quest scripts spawning mobs …
> [Release] 23.6.0

- zone/zone_save_state.cpp
Fixes a rarer scenario where when an NPC is added to a zone from a separate instance or through a content database transfer publish, zone state is missing new spawns that were added to the database that are a part of the base zone spawn data.
This change looks for any entries in the base spawn entries and compares them with zone state and adds them.
I manually inserted a spawn2 entry to the table for "halas" and it picked it up after initial zone restore
```
Zone | ZoneState  | AddLootTable NPC [bind trap] is resuming from zone suspend, skipping 
Zone | ZoneState  | AddLootTable NPC [Hasten Bootstrutter] is resuming from zone suspend, skipping 
Zone | ZoneState  | LoadZoneState Missing spawn2 [3266010] in zone state, this NPC spawn was newly created
Zone | ZoneState  | …
```
> [Zone State] Load New Spawn2 Data When Present

- zone/client.cpp
Undoes one change from https://github.com/EQEmu/Server/pull/4851 and pulls transaction out of client saves. 
Character saves work per normal
> [Database] Remove Transaction Wrapped Character Save

- common/events/player_event_logs.cpp
- common/events/player_event_logs.h
- world/console.cpp
- world/eqemu_api_world_data_service.cpp
- world/main.cpp
Adds some extra input validation incase args are empty
Tested hitting the client, no real issues.
> [World API] Input Validation

- world/adventure_manager.cpp
- world/cliententry.cpp
- world/clientlist.h
- world/dynamic_zone.cpp
- world/dynamic_zone_manager.cpp
- world/eqemu_api_world_data_service.cpp
- world/login_server.cpp
- world/shared_task_manager.cpp
- world/shared_task_world_messaging.cpp
- world/zonelist.cpp
TBD
- [] I have tested my changes
> [Code] ClientList Global to Singleton Cleanup

- zone/raids.cpp
- zone/raids.h
- Fixes possible crashes in `Raid::HealGroup`, `Raid::BalanceHP`, and `Raid::BalanceMana` as described [here](https://discord.com/channels/212663220849213441/557677602706423982/1387669462542712886).
> [Crash Fix] Fix Possible Crashes with Raid Methods

- common/item_instance.cpp
- Fixes an issue where Hero's Forge did not properly display on character select.
> [Bug Fix] Fix Hero's Forge on Character Select

- common/data_bucket.cpp
- zone/cli/tests/databuckets.cpp
Reverting #4917 for now until more test cases can be covered. I've identified some issues that need to be addressed and put into automated test coverage before full roll out.
This is how it worked before
> [Databuckets] Revert Caching Changes of #4917

- common/database/database_update_manifest.cpp
- common/version.h
Adds indexes to a few content tables that is used for newly developed database browser tooling.
Asked for by Rekka in Discord
Query plan before
After
> [Database] Add Indexes to NPC's Spawns Loot

- zone/client_packet.cpp
Clients send updates with their position whenever it's relevant and these position update packets include deltas which are used to animate the models.  There is a left and right turn animation that depends on getting heading delta values and jumping uses a delta Z value.  Due to some logic errors in the processing of client updates, these deltas were being squashed/filtered and the animations were not playing.  I fixed it up so all the animations get through and players can see each other jump and turn.  Since this isn't a packet encode problem, the fix is relevant to every client but I did my testing with only the titanium client.
Player jumping as viewed from another client.
Clients tested: Titanium
> fix player movement deltas (jumping, turning)

- common/repositories/command_subsettings_repository.h
- zone/gm_commands/find.cpp
- zone/gm_commands/find/account.cpp
Credit goes to https://github.com/The-Heroes-Journey-EQEMU/Server/pull/281
> [Commands] Add #find account Subcommand

- common/faction.cpp
- common/races.cpp
- common/races.h
- world/client.cpp
- world/clientlist.cpp
- zone/aa.cpp
- zone/attack.cpp
- zone/bot.cpp
- zone/bot_commands/appearance.cpp
- zone/bot_commands/bot.cpp
- zone/client.cpp
- zone/client_mods.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/entity.cpp
- zone/exp.cpp
- zone/gm_commands/feature.cpp
- zone/gm_commands/randomfeatures.cpp
- zone/mob.cpp
- zone/npc.cpp
- zone/special_attacks.cpp
- zone/tradeskills.cpp
- zone/worldserver.cpp
- Converts existing race constants to use `Race`, `RaceAppearance`, `RaceBitmask`, and `RaceIndex` namespaces.
> [Constants] Change Race Changes to Race Namespace

- common/shareddb.cpp
- common/shareddb.h
- zone/client_process.cpp
- Converts shared bank platinum to repositories.
> [Repositories] Convert Shared Bank Platinum to Repositories

- common/database/database_update_manifest.cpp
- common/evolving_items.cpp
- common/patches/rof2.cpp
- common/repositories/base/base_character_parcels_containers_repository.h
- common/repositories/base/base_character_parcels_repository.h
- common/version.h
- zone/parcels.cpp
Reports of a few issues with evolving items:
1. Evolving items can be mailed, but cannot be retrieved. It makes the sound like it's being delivered, but never detaches and goes into the inventory.
2. Evolving items cannot be placed on vendors for purchase. You can list one, but multiples will result in only the last entry being displayed.
3. When sold to a vendor, evolving items cannot be repurchased. The merchant UI crashes out and you must camp and come back or zone to buy or sell anything again.
4. Minor, but linking evolving items results in a number or letter prefixing the item name at all but the final evolution level.
Please include a summary of the changes and the related issue (Why is this change necessary). Please also include relevant motivation and context. List any …
> [Bug Fix] Fix Several Evolving Item Bugs
