luabind/luabind/object.hpp
Work-around for "strange ADL issues" not needed if using Boost 1.57.0 (was required through 1.56.0, thus test for less than 1.57.0).  Tested on VS2013 x64 and in-game appears to be working correctly; someone might want to check this on other compilers and/or OS.
=> Work-around for "strange ADL issues" not needed if using Boost 1.57.0

zone/special_attacks.cpp
Resolves those random 1 million damage hits that have been reported
=> Fix for spell projectiles (target type 1) being applied as melee damage.

zone/CMakeLists.txt, zone/client.h, zone/command.cpp, zone/command.h, zone/mob.h, zone/tune.cpp
Following command was implemented to assist developers in tuning content for difficult to approximate combat stats like AC/ATK , Accuracy/Avoidance on both clients and NPC.
It is very simple to use in game and will return recommended values as well as detailed information about the calculations.
This is NOT an efficient piece of code, it should only be used in a development setting NOT while players are actively fighting a raid event ect.
More features will be added in the future.
-- Tune System Commands --
-- Usage: Returning recommended combat statistical values based on a desired outcome.
-- Note: If targeted mob does not have a target (ie not engaged in combat, YOU will be considered the target.
-- Warning: The calculations done in this process are intense and can potentially cause …
=> Command #tune

zone/client.cpp
I'd like input on this change.
Wizard familiars were not persistent on zoning.  I checked live, and they are.  This one line change fixes that, but I am concerned as to why it is there to begin with.  My server doesn't support many new zones/expansions, so is the old code there to make something else work?
This does, in fact, fix the wizard familiars, so accept it if you think that's good.  If there are issues you need me to look into, let me know.
=> Made familiars persistent.

common/eq_stream.h, common/eq_stream_factory.cpp, common/eq_stream_factory.h, common/eq_stream_ident.cpp, common/eq_stream_ident.h, common/eq_stream_proxy.cpp, common/eq_stream_proxy.h, common/patches/ss_declare.h, common/patches/ss_define.h, common/struct_strategy.cpp, common/struct_strategy.h, loginserver/client.cpp, loginserver/client.h, loginserver/client_manager.cpp, ucs/clientlist.cpp, ucs/clientlist.h, world/client.cpp, world/client.h, world/net.cpp, zone/client.cpp, zone/client.h, zone/net.cpp
Found it addresses many seg faults found with the old eqstream code. PEQ went from 2-5 net related crashes a day to 0.
Still retains the sorta shared ptrish code that it had built into the stream, I plan to remove that in a future experiment but for now it's basically harmless.
Will merge it if I don't find any issue by tomorrow.
=> Change EQStream raw pointers to be std::shared_ptr

common/ruletypes.h, zone/attack.cpp
- New Rule: Character:UnmemSpellsOnDeath (default true)
=> Added new rule to make the UnmemSpellAll on death optional.

common/ruletypes.h, utils/sql/git/optional/2015_2_5_UseAdditiveFocusFromWornSlot.sql, zone/bonuses.cpp, zone/common.h, zone/mob.h, zone/spell_effects.cpp
Implemented non-live like feature to allow focus effects to be placed in worn slot
to provide an additive focus bonus that stacks with regular focus effects.
This is opposed to how regular focus effects work in which the highest
value is always taken. Please note, focus calculated from worn slot
will only use only the focuses base value (ie ignores all limit checks).
Example (Hypothetical).
Improved Heal I (10 pct focus) in Helm Worn Slot
Improved Heal I (10 pct focus) in Glove Worn Slot
Improved Heal V (50 pct focus) in Glove Focus Slot
Total Heal Focus would be 50 + 10 + 10
Added optional rule which is OFF by default.
UseAdditiveFocusFromWornSlot
=> Calc focus effects from worn slots, for an additive foci bonus [NOT LIVE LIKE]

common/ruletypes.h, utils/sql/git/optional/2015_2_6_AdditiveBonusWornType.sql, zone/bonuses.cpp, zone/bot.cpp, zone/client.h, zone/merc.cpp, zone/mob.h, zone/mob_ai.cpp
Implemented a better method for developers who want to have additive
worn bonuses than what was prior implemented.
Removed old rule RuleB(Spells, AdditiveBonusValues) [IF YOU USED SET NEW RULE = 2]
Replaced with new rule RuleI(AdditiveBonusWornType) 
The rule value denotes a specific 'worntype' that is to be
checked on items. If the items 'worntype' matches the rules worntype
then any worn effect on that item will be cacluated additively
instead of taking the highest value. This will also stack with
regular worn effects that take highest value. Unless the value
is set to (2) which is what all live items use. If set to 2 then
all worn effects will be calculated additively (same as what the old
rule did).
In laymans terms. You can take 3 Cleave I items and put them on a character
and they …
=> Optional additive worn effect bonus rule 

zone/attack.cpp
When a non magical weapon has an augment placed on it that is tagged as magic, the GUI shows the new adjusted weapon as magical but it still cannot hit a mob that requires a magic weapon.
This change makes the weapon behave as magical after an aug marked as magic is applied in combat.
Ex: It can now hit a willowisp.
I'm not 100% sure of this behavior on live (which augs are marked magical) but this seems quite reasonable.
=> A non magical weapon with an augment tagged as magic now hits as magic

common/ruletypes.h, zone/tradeskills.cpp
This allows for adjusting each individual skillup rate for a tradeskill without needing to recompile. Database rules added:
Character:TradeskillUpAlchemy
Character:TradeskillUpBaking
Character:TradeskillUpBlacksmithing
Character:TradeskillUpBrewing
Character:TradeskillUpFletching
Character:TradeskillUpJewelcrafting
Character:TradeskillUpMakePoison
Character:TradeskillUpPottery
Character:TradeskillUpResearch
Character:TradeskillUpTinkering
=> Added individual tradeskill skillup settings rules

loginserver/database_mysql.cpp
Avoid returning nulls when looking up if a row with the shortname is found. Nulls in the query results will cause the loginserver to crash.
=> Handle nulls in trusted server lookup(mysql)

zone/spells.cpp
There are only a couple of spells like this, at least in my db.  Flame lick was one of them.
Fixed to not expend the reagent as intended.  The code looked to work fine for bards, but not these cases.
=> Noexpend spells like flame lick were expending.

zone/attack.cpp
Previous to patch, magic gloves did not hit a mob when fighting hand to hand and MNK/BST.
=> Monk wearing magical gloves can hit creatures that need a magical weapon

zone/client.cpp
On live, if the NPC can't see you, he does not respond to hails.  Made eqemu match that and tested it.
=> Now Npcs won't respond to hails if they can't see you.

zone/mob.cpp
Kerran illusion was using 0 which didn't match models.
=> Allow Kerran race illusions to be either gender.

zone/spells.cpp
Bonethunder staff and other undead proces will have correct message when proc occurs against non-undead.
=> Fix proc messages for undead proc against non-undead.

loginserver/database_mysql.cpp
If the tblWorldServerRegistration is empty, max(ServerID) will return null when the loginserver tries to add an anonymous sever.  This null will crash the loginserver.
=> maxServerID null check (mysql)

zone/mob.h
Blinded mobs were being rolled into every use of IsFeared.  As I added the blind stuff into fear logic, that was an oversight.  I think this new macro makes more sense.  My testing looks good, but this is wide sweeping so I;d appreciate any feedback on impacts people think is wrong.  It should behave like it did before I added blind, so I feel ok.
=> Mobs that were blinded were being included in every use of IsFeared() 

zone/spells.cpp
When we update the duration on a spell (because of focus or AA, etc) we send a packet to the client with the intent of only changing the duration.
One of the fields, effect, is not completely understood.  Older code tried using caster_level, but that hosed up max HP on spells that had a max_hp effect.  I made changes to try other values.  255 seemed to be ok, so I used that for a time.  However, 255 does not work on some DOTS, in fact it makes them very erratic.
My testing has yielded this code, which starts to specifically address values for effect that work for various spell types.  I've tested this and it seems much better for the two types I listed in the routine.  I'll make a note to start looking for other problems this routine causes and map out what needs to be done.
This patch …
=> Beginnings of fix to SendBuffDuration.

zone/entity.cpp, zone/mob.cpp
First, the set function for mob _appearance optimized by not sending a message
if the new appearance was equal to the old.  This can't be done, as
the 1st time the zone runs there is no client when the set function is
called.  If we're combining set/send, as we are, better to always do both.  This fixes several of the cases.
Repop also did not work, as no code was being called reliably to set
appearance and update the client based on code path and various flags.  This is also fixed.
=> The mob AT_Anim (as set in spawn2) was not working in some cases.

zone/attack.cpp, zone/exp.cpp, zone/string_ids.h
* removed the double level gain messages to display once either the level gained or the level.
* implement the message "You will now lose experience when you die" and "Your items will no longer stay with you..." when reach a certain level already sets in the rule table.
=> * change the kill faction hits display before the xp message not after.

zone/spells.cpp
Utilizing the logging system to display an alert when a GM casts a blocked spell, giving some notification instead of silent successes on cast.
=> GM Output for Casting Blocked Spells via Logging System

zone/perl_npc.cpp
$npc->RemoveFromHateList is a mob function, not an NPC function. Castingto Mob to let it work.
=> Making $npc->RemoveFromHateList actually work

zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
- Uses memory (no database hits)
- Allows entity-based quest global checks
=> Added GetGlobal() support for all Mobs.

zone/CMakeLists.txt, zone/encounter.cpp, zone/encounter.h, zone/entity.cpp, zone/entity.h, zone/lua_general.cpp, zone/lua_parser.cpp, zone/lua_parser.h, zone/lua_parser_events.cpp, zone/lua_parser_events.h, zone/net.cpp, zone/quest_interface.h, zone/quest_parser_collection.cpp, zone/quest_parser_collection.h, zone/questmgr.cpp
This allows creation of quest timers that are tied to an encounter instead of a spawn. In particular, an encounter doesn't require a 'status' or 'trigger' spawn to exist in order to manage timers through the whole encounter.
It works by introducing a subclass of Mob called Encounter which gets instantiated any time an encounter is loaded, and timers get tied to that Encounter object. Then timers can be registered like other scripts, with eq.set_timer and that calls back to event_timer as usual.
It is possible I've overlooked something as this system is fairly complex, but my tests are working and I have run a couple existing encounters and they worked fine (but I only had a couple available to run!)
KLS has glanced over the code and I have fixed the only problem he saw.
=> Encounter timers

zone/CMakeLists.txt, zone/lua_encounter.cpp, zone/lua_encounter.h, zone/lua_general.cpp, zone/lua_parser.cpp, zone/lua_parser_events.cpp, zone/lua_parser_events.h
Encounter timers still needed a bit more to work properly.. these changes make it so a hooked function can create timers tied to the encounter even though the function is running in the context of an npc (or whatever you are hooking).
event_encounter_load(e) now passes e.encounter which should be saved and referenced when making/stopping timers.
Sample usage:
```lua
-- Saved encounter reference from event_load_encounter
local encounter;
function event_timer(e)
eq.zone_emote(15, "Timer: " .. e.timer);
end
function HookedSpawn(e)
-- create a timer in the encounter context
eq.set_timer("hooked_timer", 5000, encounter);
end
function HookedDeath(e)
eq.stop_timer("hooked_timer", encounter);
-- can also use:
eq.stop_all_timers(encounter);
end
function event_load_encounter(e)
encounter = …
```
=> More encounter timers support

common/opcode_dispatch.h, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/client_process.cpp, zone/command.cpp, zone/mob.cpp, zone/mob.h, zone/mob_ai.cpp, zone/npc.cpp, zone/waypoints.cpp
Fixed #modifynpcstat runspeed <value>, to work with new speed calculations.
Updated #showstats and #npcstats for new speed calcs to display speeds again in familiar float format.
Improved client movement while AI Controlled, such as feared and charmed.  Movement will be much smoother from clients perspective.
=> Updated additional support in code for new speed calculations.

common/guild_base.cpp
- Old column names timelaston and zoneid are no longer used, this was corrected to last_login and zone_id.
=> Fixed guild windows on bot-enabled servers.

changelog.txt, zone/client.h, zone/embparser_api.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/tasks.cpp, zone/tasks.h
Affected:
* quest::assigntask
* $client->AssignTask
This is to allow those task level requirements in DB to be used,
optionally. It defaults to do not enforce (translated: no change for
current servers), but can be set with an additional flag to both
commands (see below). The LUA bit was added thanks to help from demonstar55.
* quest::assigntask(703); # works
* quest::assigntask(703, 1); # denies user
* $client->AssignTask(701, $npc->GetID()); # works
* $client->AssignTask(701, $npc->GetID(), 1); # denies user
=> Add Optional Enforce Task Level Requirement on AssignTask

zone/client.cpp, zone/client.h, zone/perl_client.cpp
Added GetAccountAge() functionality to Perl so people can grant veteran AAs based on account age.
=> GetAccountAge() for Perl.

zone/zone.cpp
All packets to end weather should have the type.  The code in command.cpp knows this, the automated weather system did not.  Snow was not ending correctly.
=> Fix snow so it ends correctly.

zone/spells.cpp
In the same line as previous patches, the function to update buff durations has been fixed to not break see invis spells when it updates the duration.  I still don't see a clear explanation for the sbf->effect field, but like with the other spell types, trial and error got me to the value I am sending.  Using level was clearly breaking the buff at some levels.
=> Fix buffdurationpacket for seeinvis spells

common/shareddb.cpp, common/spdat.h, zone/effects.cpp
Determines the maximum chance this spell has to critical hit.
Ie. If set to 15, the spell will never critical more then 15% of the time
regardless of your characters innate chance to critcal from AAs.
=> Implemented spells_new field 217 override_crit_chance

common/shareddb.cpp, common/spdat.cpp, common/spdat.h, zone/aggro.cpp, zone/attack.cpp, zone/mob.h, zone/spells.cpp
Spells with this flag will not generate any aggro
Note: DOT portions of spells wilth this flag STILL generate aggro.
Example Harminous Arrow (Ranger AA) 16127
=> Implemented spells_new field 198 = no_detrimental_spell_aggro

changelog.txt, common/spdat.h, zone/bonuses.cpp, zone/client.h, zone/common.h, zone/spell_effects.cpp, zone/spells.cpp, zone/string_ids.h
Feign death will now break when hit by casted spells, consisted with live.
Implemented support for AA/spell effect which provides a chance to avoid FD breaking from spells.
=> FD break from spells

common/ruletypes.h, zone/exp.cpp
I wasn't sure if this was something that was wanted in the base code.  This created two rules (false by default) that control the old race and class experience penalties/bonuses, as the class penalties were removed in Velious while the race penalties weren't removed until much later.  The change is put in by increasing the character's required xp to level, as opposed to penalizing xp gains, as this is how it was originally implemented by SOE.  Ideally, they should be used separately from Character:UseRaceClassExpBonuses to avoid doubling up on bonuses.
Let me know if this style change isn't wanted in the base code and I'll refrain from future pull requests of this kind.
=> Old Race/Class Experience Mods

zone/client_packet.cpp, zone/tradeskills.cpp
RoF+ clients now support the built-in adding, swapping, destroying, and removing of augments in equipment, updating an equipped item's look in case of ornamentation changes. All clients will now verify that the proper distiller (or a perfected distiller for RoF+) is being sent for consumption for safely removing augments. Hard-coded item IDs for distillers have been replaced with checks on item types.
=> Augmentation Feature Patch

common/database.cpp
CheckNameFilter was enforcing given name as minimum length 4, but surnames were being limited to minimum length of 3.  Confirmed in the client that minimum length is 4.
Minor refactoring of CheckNameFilter to eliminate redundant code.  The check for null name and name min length 4 was duplicated (which is probably where the typo came from) so I eliminated the duplicate.
=> * CheckNameFilter minimum surname check incorrect

common/item.cpp
The case statement for lightLevelCandle should be comparing against lightTypeCandle as the check is on light types, not light levels.  Light levels are used for the return value.
The numerical value for lightLevelCandle and lightTypeCandle are the same (1) which is why this never broke anything, but it was still an incorrect comparision.
=> * LightProfile_Struct::TypeToLevel.  Incorrect comparision in case statement.

common/shareddb.cpp
If an error occurs (!results.Success()) in loadlootdrops the method continues processing instead of exiting.
=> Loadlootdrops (shareddb.cpp) not exiting on error

common/item_struct.h, common/patches/sod.cpp, common/patches/sof.cpp, common/patches/uf.cpp, common/shareddb.cpp
Item weight was being downcast to uint8 which impacted any item with weight over 255.  For SoD, SoF, and UF, prior to sending item info to the client we now cap weight at 255 to ensure the item remains heavy instead of being made (in most cases), super light.
=> Item weights being downcast to uint8

common/item_struct.h
Casttime was too small for the possible data values.  The Potion of Serious Healing has a cast time of 90.0 sec (90000) which exceeds the max value of uint16.  Updated Casttime from uint16 to uint32.  This change also makes CastTime have the same data type as Fulfilment which is notable as they are in a struct union and should have the same type.
=> Changed Item_Struct's CastTime member to uint32 (was uint16)

changelog.txt, common/ruletypes.h, zone/effects.cpp
Added FlatItemExtraSpellAmt rule (boolean) to allow SpellDmg on items to
be added as raw damage versus scaled.
=> FlatItemExtraSpellAmt Custom Rule Addition

changelog.txt, common/ruletypes.h, zone/effects.cpp
Added IgnoreSpellDmgLvlRestriction rule (boolean) to ignore the 5 level
spread when checking to add SpellDmg. Resubmitting due to the change
Natedog made ::shakefist::
=> IgnoreSpellDmgLvlRestriction Rule Added (re-resubmitted)

zone/special_attacks.cpp
Allow backstabs done with bane weapons to hit targets immune to all melee except bane.
Skill attacks will now give appropriate immune messages.
=> Backstab with bane weapons will now hit immune to all but bane targets

zone/spells.cpp
This fixes a case where spells with spell target ST_GroupClientAndPet (notably spirit of the panther, etc.. not many spells use this type) crash zone when Mob::IsRaidGrouped() returns true and Mob::GetRaid() returns null. Athrogate has sent me a few PEQ crash reports where this was the cause.
Also fixed a couple spots where the wrong mob was being cast to client when getting the target group id, but I don't think that was causing any real problems.
This doesn't address the underlying mismatch between those functions but that seems to be a pretty deep problem.
=> Zone crash fix

changelog.txt, zone/attack.cpp, zone/bot.cpp, zone/mob.cpp, zone/mob.h, zone/mob_ai.cpp
Fixed defensive procs so they now only trigger once per attack round like live.
Added live like proc chance modifer based on level difference to target.
"Anything above your level will receive full mod. Starting 6 levels below PC level there is a negative 10 % mod applied each level until it reaches 0 and will not proc on anything 15 levels below you or lower."
Thanks to Huffin from PEQ for the parse data
=> Defensive proc rate fix

zone/perl_mob.cpp
Exported the GetSpellIDFromSlot into Perl. Currently, there are numerous
Perl objections that can accept buff slot info, but nothing that can
return the buffs a mob/client currently has. This lets us iterate over
them with a loop, returning -1 if the slot requested doesn't exist.
Additionally: Tested this with valid buff slots and outrageous ones to ensure it doesn't cause a crash.
=> Exported GetSpellIDFromSlot into Perl

common/eq_packet.h, common/eq_stream.cpp, common/eq_stream.h, zone/bot.cpp, zone/client.cpp, zone/client_packet.cpp, zone/client_process.cpp, zone/entity.cpp, zone/mob.cpp, zone/mob.h
Changed where queued packets are sent while zoning.  Moved where zone inpacket_timer is started to assist in not dropping needed packets.
Added better netcode support for handling out of order acks, to preclude excessive resending of same packets.
Changed how timeout checks are performing on individual packets, for re-sends, so they do not happen more often than the client can respond.
Improved how the data rate limit for throttling packets for compressed stream, so the size reduction in packets are accounted for better.
=> Netcode and Zoning Improvements

zone/attack.cpp, zone/common.h, zone/mob.cpp, zone/mob.h
melee_damage_bonus_flat //(+/-) damage percent applied to out going damage
skilldmgtaken_bonus_flat //(+/-) mitigation percent applied to out going damage
*Note: These have not been applied to any ingame functions set.
=> ExtraAttackOptions (for npc special attacks) additions.

common/patches/rof.cpp, common/patches/rof2.cpp, common/patches/sod.cpp, common/patches/sof.cpp, common/patches/titanium.cpp, common/patches/uf.cpp
I get these errors without eqemu_config.h above eqemu_logsys.h
Unable to open opcodes file 'spells_us.txtpatch_SoF.conf'. Thats bad.
Unable to open opcodes file 'spells_us.txtpatch_SoD.conf'. Thats bad.
Unable to open opcodes file 'spells_us.txtpatch_UF.conf'. Thats bad.
Unable to open opcodes file 'spells_us.txtpatch_RoF.conf'. Thats bad.
Unable to open opcodes file 'spells_us.txtpatch_RoF2.conf'. Thats bad.
This fixes that.  I can't explain why this fixes it, so there might be a better solution.
=> reording includes fixes patch file location problem

zone/spells.cpp
Spells like listless power and dread touch should be taking down/blocking spells like augmentation and strenthen respectively.  The stacking code was being bypassed when a beneficial spell and a detrimental spell for the same effect were being compared.
With this code removed, the spells are compared and the stronger of the two spells wins and replaces or blocks the other.
Without this change, for example, dread touch takes down strengthen on the
client, but the server still things strength is up, causing a mismatch.
With this change, client/server match.  When a beneficial spell is stronger, it blocks/replaces the detrimental one.  When the beneficial spell is weaker, it is overwritten/blocked by the detrimental.  When they are equal, they can replace one another back and forth.
I am not …
=> Fix for detrimental/beneficial spell overwrite and/or block.

changelog.txt, common/features.h
As per some consensus, changing the min/max personal earned faction constants to -2000/2000.
There will be some autocorrection for people that are currently bottomed out.  Their new personal faction will end up being -2000 if they were already below that (as -2000 is the new low not counting modifiers).
See threads and issues:
[https://github.com/EQEmu/Server/issues/513](url)
[http://www.eqemulator.org/forums/showthread.php?p=249403&posted=1#post249403](url)
[http://www.peqtgc.com/phpBB3/viewtopic.php?f=17&t=15758&p=75196#p75196](url)
=> Changed personal faction earned min/max values to -2000/2000.

changelog.txt, common/ruletypes.h, zone/spells.cpp
Resurrection effects have always blocked some spells (like strength).  I took out the code that prevented this.
I also added a message to make us look like live as far as when spells are blocked.  Example:
_[Mon Jun 27 09:53:27 2016] Your Flawed Defiant Plate Boots shimmers briefly.
[Mon Jun 27 09:53:27 2016] You begin casting Frenzied Strength.
[Mon Jun 27 09:53:29 2016] Your Frenzied Strength spell did not take hold on Cendabik. (Blocked by Resurrection Sickness.)_
I'm not sure when live started showing this message.  Do you guys want me to add a RULE around this or is it good?
=> Res effects now block certain buffs like on live.  Blocked spells generate message like on live.

zone/spells.cpp
Another in the ongoing patches to fix the BuffDurationPacket which gets sent when an extended enhancement item is used to lengthen a buff that is cast.  In this patch, movement speed is fixed.  As you can see, I did trial and error and mapped the value to something that preserved the effect of the original spell.
=> Fix for BuffDurationPacket on movement speed buffs.

zone/spells.cpp
Prevent crash from race condition stuff, same band-aid fix as before with raids.
=> Prevent crash in spell casting when group doesn't exist

common/database.cpp, common/database.h, zone/command.cpp, zone/worldserver.cpp
Before #summon summoned the player to your zone, but if you were in an instance it would not account for that, so they would go to the non-instanced zone at your XYZ.
=> #summon will now work when you are in an instance.

web_interface/method_handler.cpp, world/remote_call.cpp, zone/remote_call.cpp
broadcast, zone shout, entity say and shout (both npc and pc).
Alpha'd the auth handler list so it is easier to read when/if we put more in.
=> Implemented some basic commands.

common/ruletypes.h, zone/npc.cpp
Added optional rule to enable quest globals on the zone controller NPC, as (sort of) requested [here](http://www.eqemulator.org/forums/showpost.php?p=251101&postcount=6),
=> Added quest global support for zone_controller.

common/ruletypes.h, zone/exp.cpp
Added new ruleset Character:ShowExpValues
If 0, default behavior will be set. (Default)
If 1, exp raw values will show.
If 2, exp raw values and % gains will show.
=> Exp Raw Value / % Gain

changelog.txt, zone/client_packet.cpp, zone/client_process.cpp
Rogue sneak was not taken into account while checking each of the merchants items against faction requirements, resulting in rogues only seeing temporary items on merchants when using sneak/buy.
=> Fix rogue merchant usage under sneak.

utils/sql/git/optional/2016_09_29_GroundSpawnsMaxZ.sql, zone/object.cpp, zone/zone.cpp
This fixes the random ground spawn z location on RoF2 clients, notably the Eastern Wastes skinning rocks, but also other occurrences. Titanium did not have an issue with this, and it is tested to still be functional.
I changed the max_z in the database to be equal to BEST_Z_INVALID (-99,999) to activate this code, and when ground spawns are generated, the Z value is set to the closest Z per the map file. To affect all ground spawns with variance in the X/Y location, use this query: `UPDATE ground_spawns SET max_z = -99999 WHERE max_x != min_x OR max_y != min_y`.
I also had to reorder the zone initialization code for this to work, as the zonemap is loaded after groundspawns, which prevented calculating the closestZ.
=> Fix Random Ground Spawn Z

common/database.cpp, common/ruletypes.h, utils/sql/git/optional/2016_10_17_GrantHoTTOnCharacterCreate.sql
This adds a rule - Character:GrantHoTTOnCreate - that if turned on will give all newly created characters the group leadership ability Health of Target's Target without the need to spend group ability points.
=> Optional rule to grant HoTT to newly created characters

loginserver/config.cpp
Some platforms define char to be unsigned by default (motivating example: Raspberry Pi / ARMv7) while GCC headers always define EOF as -1. This leads to an infinite loop when EOF values from fgetc() are stored as 255 and then checked against -1 as a stopping condition.
=> Fix potential infinite loop in loginserver's config file reader

loginserver/config.cpp
* use auto
* fix some questionable uses of string.append() that were broken by the use of int/auto (depending on endianness...)
There's no version of string.append() that just takes one character... because string+=(char) exists.
=> Additional LS config parser fixes:

zone/spells.cpp
I'm looking for help here to determine if I need more code for this fix.
Currently, chanters could not cast spells like Benevolence as a check was invalidating all PC->NPC benevolent spells.
I used an existing function (IsAllianceSpellLine()) to fix this.  I'm a little worried about other spells that increases faction ending up in something we don't want.  Any advice from  you guys on if this needs more bolting down, or if this is good enough?
Obviously this worked at some point, but seems broken in the current baseline, unless I am missing some setting.
=> Alliance spell line for chanters was not working.

common/eq_packet_structs.h, common/patches/rof2.cpp, common/patches/rof2_structs.h, common/shareddb.cpp, common/shareddb.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2017_01_10_book_languages.sql, zone/client.cpp
booktype in the items database contains language.  book contains type (scroll or book).  The OP to ReadBook did not contain enough information to implement the language for all clients in a common way.
Titanium only sends up book type (the 0, 1 and 2 field - relating to book in item) and the filename for the text. To get language we would have to do an item query and then pick one of multiple hits.  It made more sense to me to store language in the book table.
With newer clients that send slot, I could have used that to get the item id (in fact I did this until I saw what titanium was doing).  But to make one simple solution, I went with a new column in books.
On a separate issue that I discovered while in the code:
Newer clients send over slot (but this OP did not have all the new slot …
=> Use languages when reading books that are in a language other than common.

zone/bot.cpp, zone/bot_database.cpp, zone/bot_database.h
*  Fixes non-group leaders zoning with their bots.
*  Fixes non-bot owners attempting to load bots they don't own.
*  Sets bots that zone to follow owner not group leader.
*  Updates database call to only load bots client owns in group.
*  Tested on server 2 clients, 4 bots, all permutations of zoning.
Input/improvements encouraged.
=> ** Fix for groups with multiple players and bots.

zone/attack.cpp
Bots did not add XTargets, but add hate to client(). This ensures when bots generate hate for client() they also add the mob to the XTarget of the owning Client().
Tested with multi-player groups, with multi-bot owners, with each client initiating with bots, and with client.
=> Adding AutoXTarget for bot owner when hate is added to bot's owner.

utils/scripts/linux_installer/install.sh
Ubuntu 17 doesn't seem to have wget installed on a minimal installation. Added a line to install it.
=> Added wget to Debian/Ubuntu section

utils/scripts/linux_installer/install.sh
Split each package install out to its own line. This will cause the install to iterate though the package manager for each package installation. This will take a bit longer but will be less stringent. A package can be missing and not cause the others to fail.
=> Update Fedora package install method

zone/client.cpp, zone/embparser.cpp, zone/event_codes.h, zone/lua_general.cpp, zone/lua_parser.cpp, zone/lua_parser_events.cpp, zone/lua_parser_events.h
- Exports skill_id and skill_level in Perl/Lua whenever a skill is used (bash, kick, taunt, etc.)
=> Implement EVENT_USE_SKILL in Perl/Lua.

common/servertalk.h, world/zoneserver.cpp, zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/worldserver.cpp
Allow entity variables to be sent across zones to other clients.
=> Add CrossZoneSetEntityVariableByClientName

zone/npc.cpp
This allows pets to use the better value of oocregen or their db setting for hp_regen_rate (when out of combat).
This also allows you turn turn hp_regen way down in the db, and still get a speedy pet regen when out
of combat.
=> Allow pets to use the better of db/oocregen if oocregen rule on.

zone/fearpath.cpp, zone/waypoints.cpp
Ok this time the fix seems to work better.  Needed to fix common functions in waypoints to use FixZ when mobs are fleeing or feared.  Also, the original function needs to set currently_fleeing all the time.
If we want to set that to false and/or remove the fear spell again to avoid exploits, then I'm gonna need help fixing that function to find proper points, as now, without the help of fixz, it was always killing my fear spell on IceGiants - immediately at cast,.
=> Repair so that mobs that are fleeing or feared use FixZ.

zone/command.cpp, zone/fearpath.cpp, zone/mob.cpp, zone/waypoints.cpp
When GetGroundZ used GetBestZ, I have logs where 1028 turned into -489...
All the way down to the map grid.
Using ClosestZ grabs the more sane value.
=> Add fix for GetGroundZ and fix some constant references.

common/ruletypes.h, zone/client.cpp
The current code allows teaching yourself languages that are at least a 1 skill.
Some of us believe that in the past, you needed someone higher than you to teach.
This new rule defaults to current behaviour.
Set to false, it requires someone else to teach.
+RULE_BOOL(Skills, SelfLanguageLearning, true)
=> Rule to dictate if you can teach yourself lang.

zone/bot.cpp, zone/groups.cpp
Sorry if this isn't in the right format.  This is my first time opening a pr.  
The first commit addresses issue #657 by setting bots to be target-able in Bot::Spawn.  The second commit addresses a zone.exe crash when a client gets too far away from bots in their group.
=> Bot bugs - targeting after zoning and zone.exe crash

zone/mob_ai.cpp
Rooted casters would sometimes stand and do nothing.
=> Rooted mobs cast spells instead of doing nothing.

zone/mob_ai.cpp
The roam box code basically comes up with a new position to move to, and then keeps getting called until the mobs position is in the x/y location we aimed for.  The way it was however, it was possible to get into an endless cycle, as CalculateNewPosition2 could change out current location and the client could change it back due to Z issues... resulting in the roam box stalling.
In this patch I did two things:
1) Make debugging easier by spitting out the debugging once per new coordinate instead of smamming the same data.
2) Called MakeNewPositionAndSendUpdate directly, since thats what CalculateNewPosition2 did anyway.
3) Most importantly, every call to MakeNewPositionAndSendUpdate  uses the z for the mobs current progress so that we will get a result of false when the x and y match, …
=> Roam Box code was changing z every loop through.

zone/attack.cpp
The level restriction is not working correctly, the property Level returns 0 and allows procs to have no minimum level requirement. Using the Level2 property pulls the correct minimum level. 
Tested with level 10 warrior using http://lucy.allakhazam.com/itemraw.html?id=1154 min proc level 46
=> Change weapon proc req. level to Level2 property

zone/command.cpp, zone/command.h
For GMs that want to give players the ability to name only their own pets.
=> Added a #petname command for renaming only pets

zone/attack.cpp
The if statement was never evaluated since owner was added to hate list immediately before.
=> Fix for Xtargets not being populated when pet initiates aggro.

libs/format/fmt/format.h
This is a compile fix so that fmt can be build on Ubuntu 17.10.
Other notes: uuid-dev is also not included in Ubuntu 17.10 by default. You can apt-get install uuid-dev to get the required libraries.
=> Fixed Ubuntu 17.10 compile

zone/attack.cpp
+		// Death in levels with xp_mod (such as hell levels) was resulting
+		// in losing more that appropriate since the loss was the same but
+		// getting it back would take way longer.  This makes the death the
+		// same amount of time to recover.  Will also lose more if level is
+		// granting a bonus.
=> Adjust xp loss on death if using the level_based_mods.

zone/entity.cpp
To solve issue where a mob that is not engaged heals and pets witness and run off.
Discussed in discord with @mackal.
=> Removed pets from Witness Heal Aggro.

zone/spell_effects.cpp
Just a quick message fix.  Was coming out on client as %1.
=> Level was missing from Spell error message.

common/ruletypes.h, zone/loottables.cpp
This is the rule we talked about @mackal.  The other rule if for pet trades.  I'll commit that shortly as well.
=> Add rule to use ClassicBackstab (no mob fronttab)

zone/pets.cpp, zone/trading.cpp
This allows pets to take no drop items and use them if the new rule is set.
I believe I have it coded correctly (testing what I know to test) so that only PC summoned pets are eligible and none of the pet corpses that can get the drops will ever be looted.
I also modified the code that loads the pets - since it was subtracting these items.
=> Allow trading nodrop to pets via new rule.

zone/npc.cpp
On mobs where max_level is set,  AC and ATK were not being scaled.  This makes a large difference.  I had mobs that were level 7, max_level 9 and mobs that were just 9.  The level 9 mobs were a challenge for PCs around their level.  PCs could take 3 level 7 mobs scaled to 9 easily.
This makes them all the same based on scaled level.
=> Scaled AC and ATK if npc is scaling.

zone/command.cpp
If a person is gm, and uses /camp while a #hotfix was invoked, it will crash the zone as the hotfix takes a moment and doesn't verify the client still exists.
=> Added sanity check for #hotfix

common/ruletypes.h, zone/spells.cpp
A simple rule, enabled by default, where when disabled reagent costs check if the spell has SE_SummonPet as an effect in it. If it does, it bypasses the normal logic (for malachite, bone chips, tiny daggers, etc)
=> Added rule to remove pet reagent cost

utils/scripts/linux_installer/install.sh
If it's superseded or already installed, it just won't install it anyway.
=> Removed conditional for installing libsodium.

common/ruletypes.h, zone/client.cpp, zone/exp.cpp
This is for discord PvP, but sets a minimum level to automatically flag players as PVP. From what I could see, current code doesn't allow this.
This is a part of some other flags I am planning to add.
=> added minimum level to pvp flag.

zone/questmgr.cpp
The existing npcfeature() gets called per feature.  So you can:
npcfeature("face", 1);
npcfeature("gender", 2);
etc..
and all these would accumulate..
except for texture and helm.
These could be set:
npcfeature("texture", 2);
but a subsequent call to:
npcfeature("face", 1); 
would wipe it out.  
I am not sure why these two are singled out.  At first, I just said ok, always change texture last.  But then I saw the same issue with helm.  
This seems ok to me as a fix?
=> quest::npcfeature() could not set all features

zone/special_attacks.cpp
So if Harm Touch fails (line of sight issue for one) the old code still sets the reuse timer as if it was used.
Now, the mob will retry since it never actually fired.
=> Fix HT and LOH to retry after failure to cast

zone/spell_effects.cpp
Purify Body was removing Resurrection Effects and it should not.
Added a !IsResurrectionEffects check to the logic to make sure Purify Body does not remove Resurrection Effects.
=> Purfy Body Resurrection Effects fix

zone/mob_ai.cpp
Escape code only had hard coded HP ratio.  Added code so that custom ranges in spell list supersede.
=> Change spell logic to use min_hp from spell list.

common/ruletypes.h, zone/mob_ai.cpp, zone/zoning.cpp
RULE_INT(NPC, NPCGatePercent, 5) // % at which the NPC Will attempt to gate at.
RULE_BOOL(NPC, NPCGateNearBind, false) // Will NPC attempt to gate when near bind location?
RULE_INT(NPC, NPCGateDistanceBind, 75) // Distance from bind before NPC will attempt to gate
RULE_BOOL(NPC, NPCHealOnGate, true) // Will the NPC Heal on Gate.
RULE_REAL(NPC, NPCHealOnGateAmount, 25) // How much the npc will heal on gate if enabled.
=> Prevent Gate if near bind location (Rule) and Heal on Gate (Rule)

common/ruletypes.h, zone/aggro.cpp, zone/entity.h, zone/fearpath.cpp, zone/merc.cpp
Added following Rules:
Combat:FleeGray - If true FleeGrayHPRatio will be used.
Combat:FleeGrayHPRatio - HP % when a Gray NPC begins to flee.
=> Allow Separate CON_GRAY Flee rate.

zone/spells.cpp
Using low level mez to test if a mob is mezzable and NOT get aggro has been squashed. When you cast you will get 1 point of aggro on a Cannot mez with this spell.
=> [Exploit] Prevent low level mez testing without aggro.

zone/client_packet.cpp
Prevents players from /assist to see if a mob is up due to error or no error messages.
=> /assist exploit fix

common/ruletypes.h, zone/aggro.cpp
Want to make the level at which mobs aggro configurable.  The orcs in highpasshold still aggro a level 75.
=> Allow UseLevelAggro rule to be configurable.

zone/embparser_api.cpp, zone/lua_general.cpp
Last commit when I added this function I omitted these lines.
=> Fix omission for Perl/Lua binds for get_data_expires()

zone/zonedb.cpp
ZoneDatabase::GetCharacterCorpseID was always returning the 1st corpse, not the n-th corpse as requested.
=> Fix Get Corpse to fetch the corpse indicated.

zone/npc.cpp
This small change fixes a small issue.
NPCs that are on a faction, but have no faction hits and no npc_faction_entries whatsoever, do not
assist primary_assist by default, as they should.
This fixes that.
=> Small fix for an NPC on a faction but with no entries in npc_faction_entries

zone/command.cpp, zone/zone.cpp, zone/zone.h
LoadZoneCFG has a parameter that it never used.
LoadZoneCFG was called from command.cpp with true being passed as the instance id by mistake.
Refactored LoadZoneCFG to make a bit more sense.
=> Fix the LoadGFG function to no longer have the unused parameter.

zone/exp.cpp, zone/spells.cpp
"key" wasn't being escaped with `s, so the SQL queries were failing.
=> Properly escape key in SQL queries

zone/attack.cpp
This will allow Developers to disable/enable the stationary requirement.
=> Reimplemented pre-nerf Ranger stationary damage bonus.

zone/embparser_api.cpp, zone/lua_general.cpp
- quest::set_rule(string rule_name, string rule_value)
Example: quest::set_rule("Zone:UseZoneController", "false") - Sets the rule "Zone:UseZoneController" to "false" for the current zone.
- quest::get_rule(string rule_name)
Example: quest::get_rule("Zone:UseZoneController") - Returns true/false depending upon if it's enabled/disabled.
- Example NPC script here: https://pastebin.com/akKKN2NS
=> Adds dynamic rule capabilities to quests in LUA/Perl.

zone/attack.cpp
This function would cause defender's spell-based MeleeMitigationEffect to increase damage dealt and the attacker's item and aa-based MeleeMitigationEffect to increase damage dealt. New code should cause all three forms of defender MeleeMitigationEffect to reduce damage dealt.
=> Reference the defender melee mitigation, not attacker

utils/scripts/eqemu_server.pl
I believe the argument passed was wrong.  Am I correct?
I think exec is better here that system.  Exec will start over again with the new downloaded script and the current execution will terminate.
I believe this fixes the problem with quests updating automatically.  I tested as best I could with an alternate git fetch path for the script, but that of course updates the script!  Will retest immediately on main line if this is merged.
=> Fix issue with perl script not updating itself correctly

common/emu_constants.h, zone/mob_ai.cpp, zone/waypoints.cpp
The delay on roamboxes was inadvertently broken when new movement code was added to improve
pathing.  This corrects the delay issue.
I also have code that is a hack to fix underground stuck issues with roamboxes, but have conferred
with @KimLS  that I will hold that back, and wait for a navmesh based next roampoint instead of the 
current random location.
=> Fix issue with roambox wait time after switch to new movement code.

zone/mob.h
Needed to make new roambox constants (that were used instead of 666) actually work.
=> Fix SetCurrentWP to allow negatives

zone/client.cpp
Auto correct was not using the new client_base_data for min/max.
=> Fix the auto-correct mechanism on illegal faction

zone/lua_mob.cpp, zone/lua_mob.h, zone/perl_mob.cpp
By exposing RandomizeFeatures, the plugin::RandomFeatures is no longer needed.
Additionally, RandomizeFeatures has arguments for sending illusion and updating the mob instance.  This lets the quest caller decide if he wants an illusion (only visible to people in zone at the time) or if he wants this instance to retain the features even if a player zones out and back in, or new players zone in.
Also,this new exposed function works at EVENT_SPAWN, whereas the plugin::RandomFatures would not work until at least a second after spawn.
I also fixed a typo in a comment.
=> Expose RandomizeFeatures which supercedes plugin::RandomFeatures in functionality

zone/mob.cpp, zone/mob_ai.cpp, zone/pathfinder_nav_mesh.cpp
These changes result in 0 mobs underground in hilly zones with very large roamboxes,  Without them,
sooner or later the points chosen for next location end up with no route and the default code does a moveto which ends up underground.
KLS and I have discussed,  He has a plan for roamboxes picking destinations in a more correct manner.  This is a patch to get servers with this issue running in the meantime.
The pDontBuffMeBefore fix is a bonus :P  Mobs that could buff self with invis were doing it so early that the buff wasnt sent to the zone in time and they showed visible even though the invis buff was up.
=> Roambox patch for navmesh and large roamboxes in hilly zones

zone/inventory.cpp
OP_MoveItem causes a dysec if you try to move to -1 slot on client side, need to use OP_DeleteItem
=> fixed opcode for deleteing a item out of a player's inventory slot

zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.h, zone/perl_mob.cpp, zone/spells.cpp
- Mob::FindBuffBySlot(slot)
This allows you to find buffs by a specific slot.
Example: https://i.imgur.com/VG68cxs.png
Perl Example: https://pastebin.com/8HvMAC4h
- Mob::BuffCount()
This will find the active number of buffs an NPC/client has.
Example: https://i.imgur.com/jrLRBwV.png
Perl Example: https://pastebin.com/Wmg16wwp
=> New Perl/Lua buff functionality.

utils/scripts/linux_installer/install.sh
This brings the installer script up to date and changes a few logical problems. For example running apt 50 times is a ton slower than running it once, same with dnf.
the yum install for RHEL was also installing 1777 undeeded perl and lua modules for no reason. Now it installs 53.
=> Updating linux installer script

common/ruletypes.h, utils/sql/git/optional/2019_06_21_new_rule_gm_level_target.sql, zone/command.cpp
Add GM:MinStatusToLevelTarget rule, which determines the GM status needed to use the #level command on your target.
=> Convert constant check in level_command() to a Rule

zone/bonuses.cpp, zone/common.h, zone/lua_stat_bonuses.cpp, zone/lua_stat_bonuses.h, zone/spells.cpp
Dev quote is here:
https://forums.daybreakgames.com/eq/index.php?threads/enumerated-spa-list.206288/page-4#post-3655856
A couple ways to verify this on live
/testbuff with an Enchanter and self buff Intellectual Superiority. While buffed with Intellectual Superiority, casting a buff like Major Shielding doesn't change caster level that the client sees. Refreshing the existing buff also works after Intellectual Superiority is removed.
On emu, the client sees caster level+6 and the refresh attempt won't take hold. 
Another way to confirm this is via THO's Feeblemind debuff (-200 SPA112 value)
On emu, a shaman with this debuff will only have a ~9s duration on Balance of Discord
on live, the duration of Balance of Discord is the full 1m30s+
=> Make SPA 112 affect fizzle rate not effective caster level

common/ruletypes.h, zone/npc.cpp, zone/npc.h
This PR introduces a new rule, which is disabled by default, named Spells:CharmDisablesSpecialAbilities
I did not test this at all, really, other than ensure it compiles, as I wanted to have others review the implementation first..
When enabled, it will strip the special abilities of an NPC while charm is in effect.
So some debates with this PR:
* Charm even with the scaling features does not disable one of the biggest factors to the benefits of charm: Special abilities of an NPC.
* We could write a dynamic system so charmed NPCs have the special abilities to mirror what a pet gets at a given level?
* Should this be enabled by default?
=> Added Spells:CharmDisablesSpecialAbilities

zone/zone.cpp
Zone::IsSpellBlocked should correctly handle spellid 0 (all spells) blocked in a region (type 2).  This change has been tested and is live on the Flavortown EQEmu server (demos available).
Tested:
- specific spell, zone-wide (type 1)
- all spells (spellid 0), zone-wide (type 1)
- specific spell, region (type 2)
- all spells (spellid 0), region (type 2)
=> Support for blocked_spells entries for all spells in a region

utils/scripts/linux_installer/install.sh
RHEL/CentOS 6/7 are still on cmake version 2. Install cmake3 out of epel and set as primary alternative.
Note: Might break with RHEL/CentOS 8
=> RHEL/CentOS 6/7 cmake prerequisites

world/zonelist.cpp
this function is only used when a raw telnet ooc, auction, or tell is used. it needs to have the language skill set though otherwise it just comes out as garbled
=> fix for telnet's lack of language skill

zone/command.cpp, zone/mob.cpp, zone/mob.h
Earlier this year I added a model field to npc_types.  The use of this field is to allow servers to specify the actual race of all mobs in the race field, and the graphical model to be used in the model field.  This has the advantage that things like gnollbane can work on all gnolls, regardless of model. 
This PR fixes two bugs uncovered when this field (model) is used.
1) #texture command was not working, as it expected the model being used was in GetRace().  I added a new call GetModel() which returns race unless model is defined, in which case it uses model.
2) Illusiions fading would default back to race, rather than model in the cases where model was used.  This now fades back to model (if used) or GetBaseRace() as before.
=> Fix some bugs with the use of the model field in npc_types

common/ruletypes.h, zone/attack.cpp
The new rule defaults to live behavior of no corpse for merchants.
This is inspired as an option as a newly updated live quest "Noble Hunters" reveals that it was broken because the drops were on merchants before they implemented the no corpse rule.  Live fixed this by making these mobs non-merchants.  
I think this option for servers is a nice one to have .
=> This allows for merchants to drop corpses

zone/attack.cpp
This further changes the monk weight checks for the floating point aspect of weight.
I tested this with monks of the various levels at the edges of full pounds.  These changes bring us the closest I can come without full insight into the AC display on the client.  Without these changes, weights around the edge of 15, 16 and such showed places where the client AC went up, but our mitigation  stayed the same or went down.  No changes in AGI during the tests, so I don't think defense was involved.
I also removed some code that did some min/max places where the result was guaranteed without them.
=> Further refine monk weight checks for floating point

zone/waypoints.cpp
This fix only impacts those that use the model field in npc_types to override race on the client.
GetModel() returns model if set, otherwise race.
As a refresher, the model field is there so the server can still see a mob as its base race for things like bane, while the client can use a new model.
FixZ needs to know about this.
=> Fix FixZ regarding the use of model in npc_types

zone/client_packet.cpp, zone/string_ids.h
Message is same as what live uses in this scenario
=> Fix zone crash when a group member raid invites own group leader

common/emu_constants.h, common/servertalk.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_01_28_corpse_guild_consent_id.sql, world/zoneserver.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/corpse.cpp, zone/corpse.h, zone/string_ids.h, zone/worldserver.cpp, zone/zonedb.cpp, zone/zonedb.h
Refactors consent to be more live accurate
Message sent to owner and receiver for each zone a corpse is in
Corpses now store consent list instead of clients holding corpse list
Consent throttling added
Message strings and colors updated
Removed reporting invalid consent targets
=> Implement consent for group/raid/guild and add Auto Consent support

common/database.cpp, common/ruletypes.h
This allows server owners to assign all new characters created to a default guild of their choosing,
Default behavior is that the rule if off - as normal.
I see this good for:
- local servers where everyone is in same guild
- all servers that want new characters to be born into a community.
=> Implement DefaultGuild Rule

zone/mob.cpp
I actually believe this was some old cut-n-paste error.  aa_mod was being set to a total of all (3) caps - like the previous line.
#showstats now correctly displays movement rate for people with runspeed AAs.
=> _GetRunSpeed did not correctly report aa mods for Clients.

common/ruletypes.h, zone/npc.cpp
Without this change, Idle NPC casters get mana_regen from database which  happens all the time (non-idle) + the npc_sitting_regen_bonus variable (which was set for HP and only set when the NPC anim is actually sittting).
This current (existing) behavior means that if an NPC caster like a priest or shaman buffs his camp - he will eventually run out of mana and never have any again (depending on the db mana_regen).  It also means it gets no bonuses for being idle.
I don't think we want code to make our NPCs actually sit when out of battle.  I do think, a slow recovery rate when they are out of combat is reasonable, so that when A PC engages them after the zone has been up for hours, they have a chance of having mana and/or buffs.
Tested on my server before the changes, priests/shamans buff …
=> Idle NPC mana regen

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_02_06_globalloot.sql, zone/global_loot_manager.cpp, zone/global_loot_manager.h, zone/loottables.cpp
We do this in GlobalLootEntry::PassesRules since we want to check if the
hot zone status changes during run time
Value can be null, if null it's not checked. If the value is 0 the zone
must not be a hot zone (I guess one might want that) and if it's not 0,
the zone must be a hot zone
=> Add hot_zone filtering for global loot

common/patches/rof2_structs.h, common/patches/rof_structs.h, common/patches/sod_structs.h, common/patches/sof_structs.h, common/patches/uf_structs.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_02_06_aa_reset_on_death.sql, zone/aa.cpp, zone/aa_ability.h, zone/attack.cpp, zone/client.h
This is a field in the packet, live only uses this for Lay on Hands
Currently I didn't add this to the packet since it has 0 effect on the
client.
We could move this field to aa_ranks which would give more flexibility
for custom servers, but no one said they wanted it there.
=> Implement AA timers reset on death

common/ruletypes.h, zone/client.h
This makes "You are hungry" and "You are thirsty" messages squelched, emulating GM mode for custom servers that don't want people to get hungry.
=> Added EnableFoodRequirement Rule

zone/spells.cpp
The rule that was created does not include create undead pet spell effects, which have a different id than standard pets (magician, enchanter, shaman...) and therefore still require bone chips for Necromancers and Shadowknights. This will fix that functionality.
=> Add Necromancer pet spell effect id to pet spell reagent check

zone/lua_npc.cpp, zone/lua_npc.h, zone/npc.cpp, zone/npc.h, zone/perl_npc.cpp
When a level is changed on an NPC via Quest API, there is currently no way to recalculate skills. This function allows the ctor logic to be ran again, recalculating skills to ensure more accurate tohit, avoidance, and defense calculations.
=> Added NPC::RecalculateSkills

common/net/daybreak_connection.cpp
commit message has more information
script used for testing: https://gist.github.com/hgtw/8f0eac12dcaa9e86bb1f004f707d81f9
=> Send packet uncompressed if zlib deflates to a larger size than input

zone/client_packet.cpp, zone/lua_raid.cpp, zone/lua_raid.h, zone/perl_raids.cpp, zone/raids.cpp, zone/raids.h
This still doesn't add support for /autosplit in a raid, how should that
work?
This changes the Raid::SplitMoney to take a group ID and fails when
provided with RAID_GROUPLESS. This does change behavior, but I'm not
sure if it was ever used so ...
Reported here: http://www.projecteq.net/forums/index.php?threads/cant-split-when-raiding.16514/#post-78810
=> Fix /split while in a raid

common/event/event_loop.h, world/main.cpp, world/zonelist.cpp, world/zonelist.h, zone/main.cpp, zone/worldserver.cpp
Changes:
-World will no longer loop to find a port which should fix the situation where if you have more zones than your port range can handle your world server gets stuck in an infinite loop.
-Fixes the shutdown command in zone that was broken back when we changed how the zone loop behaves.
=> Rewrite how zone finds ports

zone/spells.cpp
This PR addresses a bug that causes clients other than the attacked and the attacker to receive double spell messages for damaging spells only.
This has been identified and diagnosed by @noudess and is highlighted in the (now deleted) comment that originated all the way back in the SVN repository (sorry can't git blame for credit)
=> Fix double damaging spell messages to non-attacked and non-attacker

common/ruletypes.h, zone/mob_ai.cpp
@Uleat made these changes so that a feared entity can still trigger proximity events.  I've tested this since 3/18 and its working great for me.
=> Added proximity check for feared clients

common/database.h, common/database_instances.cpp, common/ruletypes.h, common/timer.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/zone.cpp, zone/zone.h
General comments
Instance logic needs to be cleaned up and centralized, this PR is tailored towards fixing some things that cropped up on PEQ and wanted to get a solution in place quickly
Instead of purging immediately expired instances every 7.5 minutes, we will purge expired instances from the database table after they've been completely expired for an entire day every 7.5 minutes. The reason for this is that the code will still determine that an instance is expired when it needs to; but in order to not re-use the same instance ID not long after it had been freed while a zone is still online with the same instance ID, we're simply going to wait a grace period of 1 day to purge those entries as it will not harm anything
Client::SendToGuildHall() will send a client to a Guild Hall …
=> Implement SendToGuildHall and Improve Instance ID Cycling

ucs/chatchannel.cpp, ucs/clientlist.cpp, ucs/clientlist.h, ucs/database.cpp, ucs/ucs.cpp, ucs/worldserver.cpp, world/ucs.cpp, world/ucs.h, zone/client.cpp, zone/client.h, zone/entity.cpp, zone/raids.cpp, zone/worldserver.cpp, zone/zone.cpp
This PR addresses many things
**Raid::GetRaidByClient**
On PEQ we noticed via zone with high CPU footprint spending tons of time in in function `Raid::GetRaidByClient` where we excessively loop through all raids in zone, all members in the raid to return back a simple raid pointer. Now, we cache the pointer lookup instead of running the entire loop constantly. For perspective, with 100 toons in a zone all in a raid, you will easily see 4k/s calls to this function which adds up on a CPU profile (nuts)
**CPU Profile** https://gist.github.com/Akkadius/a5c55654d4b729697964f938c824030f
**Call Measurement Example**
```
eqemu@ce0931611614:~$ tail -f ~/server/logs/**/*.log | grep "returning cached raid" | pv -lr 2>&1 >/dev/null
[4.04k/s]
```
**UCS**
We also noticed UCS sucking up a lot of CPU …
=> UCS / Raid / Zone Fixes

zone/spells.cpp
* Addresses #1036
* Cleaned up if statement formatting
* Using Mob::GetOwnerOrSelf() now, which accounts for the edge case
NB: The Mob::SpellOnTarget() and Mob::CommonDamage() methods really
should be looked at and spell logic combined somehow.  Both have if
statements that dodge around the other's conditions to decide which
method sends the CombatDamage_Struct packet
=> Fix edge case with NPC pet owners charming PCs

world/client.cpp
The same check is being done right after this.  Having a duplicate check makes debugging harder, as the log message of the first one does not describe failing this check, while the second one does.
=> Removed redundant check during enter world

common/net/daybreak_connection.cpp
This randomly popped into my head that I meant to mention a while back when I was trying to fix the network issue on Windows server. When I was looking at the network code I noticed this switch statement missing a break for OP_AppCombined so some of those packets were spilling over into session request. I remember getting excited because I thought maybe that had something to do with the issue at the time, but it wasn't the case in the end. The missing break doesn't seem to have any major adverse affects but thought I'd quickly point it out with this pull request while I remember.
=> Add missing break for OP_AppCombined switch statement

zone/inventory.cpp, zone/zone.cpp, zone/zone.h
This change fixes cases where a merchant has at one point used slot 255 and slot 255 is still full but there are plenty of other slots open for use due to player buyback.  Without this fix, the code will throw an error saying the merchant is full.
This fix:
- Utilizes empty merchantlist_temp slots when available, regardless of where they are in the list
- Added LogInventory() statements throughout to aid in any later debugging that might be needed (though this has been running on my server for months)
- Added a DumpIt function which will dump the entire merchant inventory (currently unused) for later debugging if neeeded.
- Fixed a handful of if statements that were missing braces.
Obviously this fix is mainly for those that have rule:  World:ClearTempMerchantlist set to false.
=> Fix errant merchant full messages and add logging for later use

common/patches/rof2_structs.h, common/patches/rof_structs.h, common/patches/uf_structs.h
This maybe in older clients as well, but I couldn't verify it and those
clients never did anything with this field so it doesn't matter.
MQ2 calls this SubClass, but we call the field it's a "sub" of Type so I
figured we'd call it SubType.
We still need to rename the DB field and handle it server side etc
=> Identify SubType in Item structs in some clients

zone/npc.cpp
In this one code path, values could be added to an NPCs hp and max_dmg if they had been set to 0 with the intention of being dynamically scaled. This would cause those fields to be ignored when later scaling the enemy.
=> Don't scale 0 values

common/ruletypes.h, zone/entity.cpp
In static zones, if IDLE_WHILE_EMPTY is used (which is the default), when the last player leaves the zone, mobs cease to path immediately.
This PR adds code to allow these mobs to return to their spawn points before suspending mob::process.  In my testing 60 seconds is a good value for this rule, but servers might want more/less depending on preference.
This resolves issues like trains remaining at zone lines for the next unfortunate PC that zones in, days later.
=> Fix for static zone issue with mobs congregating after last player zones

zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
This exposes the client method NotifyNewTitlesAvailable for both perl and lua.
For what it's worth, I am exposing this to extend @KinglyKrab perl code that implements artisan titles, but it can be used anywhere you grant a title and want the popup.
His code was posted on this thread back in 2015.  In combination with quest::checktitle() quests can not use the TitlesAvailable popup at will.
=> Notify new titles

zone/command.cpp
Some zones like 'soldungb' are hard to search for because their long name isn't similar to their short name, this will make life a lot easier for people searching for zones.
=> Fix #findzone to allow you to search using part of a zone's short name.

zone/entity.cpp
This is a bit of an edge case which causes anguish doors on peq to sometimes be missing on clients
QueueClients in DespawnAllDoors() uses the CLIENT_CONNECTED flag but RespawnAllDoors()
uses default CLIENT_CONNECTINGALL
If a quest script calls a door function that calls these (amv 'close_door' timer calls SetOpenType()) while a character is zoning in the client receives the OP_SpawnDoor packets immediately but doesn't receive any of the OP_RemoveAllDoors packets until after zoning is complete
I don't know if using CLIENT_CONNECTED for RespawnAllDoors() instead is a better approach
=> Fix edge case with door packets that can cause missing doors on clients

common/string_util.cpp, common/string_util.h, zone/command.cpp, zone/npc.cpp, zone/npc.h
I had been trying to use #grid show in game to help debug some pathing issues.  I quickly noticed that in many cases, the node names did not match, or even come close to the grid nodes.
After investigation, the code was trying to spawn nodes named aaa_bbb where aaa is the grid # and bbb is the node number.  This was failing in a number of ways.  The creating of the NPC was stripping all numbers, leaving the node named '_'.  Then, the entity list code was making it unique, adding 000, 001, 002 on the end.  The resulting nodes were all _000, _001, _002 where the values were not guaranteed to match the node numbers, and in faction, when used in repetition, sometimes node 0 ended up being some arbitrary available number.  This is due to timing and the cleaning up of used values.
Also, if a …
=> Repair #grid show command

zone/mob_ai.cpp, zone/special_attacks.cpp
Mob_ai was using the engaged flag to decide when to start navigating toward a target.  This flag is a reflection of the hatelist being non-empty.  As is stood, the hatelist is added to early in the process, and calls for help have not yet been processed.  This resulted in the mob moving, sometimes a significant distance, before calls for help were sent out.
I changed mob_ai to only start moving toward the target after the CombatEvent has been set (which is done by all calls to AI_Event_Engaged).
This wasn't enough, as all special attacks were using callforhelp=false, which resulted in AI_Event_Engaged not calling for help, but setting the flag.
I changes all special attacks to use callforhelp=true and this seems to work.
Pulling via throwing or arrows now properly calls for help BEFORE …
=> Prevent mob from moving from point of aggro until after calls for help are issued.

zone/perl_npc.cpp
Currently you have to add an errant parameter (i.e. $npc->RecalculateSkills(1);) to make this function "properly". This fixes that.
=> Fix $npc->RecalculateSkills() in Perl.

zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/zoning.cpp
Add $client->MoveZone(zone_short_name) to Perl.
Add client:MoveZone(zone_short_name) to Lua.
Add $client->MoveZoneGroup(zone_short_name) to Perl.
Add client:MoveZoneGroup(zone_short_name) to Lua.
Add $client->MoveZoneRaid(zone_short_name) to Perl.
Add client:MoveZoneRaid(zone_short_name) to Lua.
=> Add MoveZone methods to Perl/Lua.

common/servertalk.h, world/zoneserver.cpp, zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/tasks.cpp, zone/worldserver.cpp
Removes extraneous error for non-NPC task assigns.
Add quest::crosszoneassigntaskbycharid(character_id, task_id, enforce_level_requirement) to Perl.
Add eq.cross_zone_assign_task_by_char_id(character_id, task_id, enforce_level_requirement) to Lua.
Add quest::crosszoneassigntaskbygroupid(group_id, task_id, enforce_level_requirement) to Perl.
Add eq.cross_zone_assign_task_by_group_id(group_id, task_id, enforce_level_requirement) to Lua.
Add quest::crosszoneassigntaskbyraidid(raid_id, task_id, enforce_level_requirement) to Perl.
Add eq.cross_zone_assign_task_by_raid_id(raid_id, task_id, enforce_level_requirement) to Lua.
Add quest::crosszoneassigntaskbyguildid(guild_id, task_id, enforce_level_requirement) to Perl.
Add eq.cross_zone_assign_task_by_guild_id(guild_id, task_id, …
=> Add cross-zone task assign methods to Perl/Lua.

zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/zoning.cpp
- Add $client->MoveZoneInstance(instance_id) to Perl.
- Add client:MoveZoneInstance(instance_id) to Lua.
- Add $client->MoveZoneInstanceGroup(instance_id) to Perl.
- Add client:MoveZoneInstanceGroup(instance_id) to Lua.
- Add $client->MoveZoneInstanceRaid(instance_id) to Perl.
- Add client:MoveZoneInstanceRaid(instance_id) to Lua.
=> Add MoveZoneInstance methods to Perl/Lua.

common/servertalk.h, world/zoneserver.cpp, zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/worldserver.cpp
Looping through the entity list is too expensive, using GetGroupByID() and GetRaidByID() is far more efficient.
- Add quest::crosszonemoveplayerbycharid(character_id, zone_short_name) to Perl.
- Add eq.cross_zone_move_player_by_char_id(character_id, zone_short_name) to Lua.
- Add quest::crosszonemoveplayerbygroupid(group_id, zone_short_name) to Perl.
- Add eq.cross_zone_move_player_by_group_id(group_id, zone_short_name) to Lua.
- Add quest::crosszonemoveplayerbyraidid(raid_id, zone_short_name) to Perl.
- Add eq.cross_zone_move_player_by_raid_id(raid_id, zone_short_name) to Lua.
- Add quest::crosszonemoveplayerbyguildid(guild_id, zone_short_name) to Perl.
- Add eq.cross_zone_move_player_by_guild_id(guild_id, zone_short_name) to Lua.
=> Optimize cross-zone utilities and add cross-zone player move utilities to Perl/Lua.

world/worlddb.cpp
This is a simple change to handle Titanium sending in player choice instead of a zone id.
=> Issue 743 - WorldDatabase::GetStartZone now checks isTitanium when creating the SQL

common/shareddb.cpp, zone/command.cpp
Fixes #hotfix command execution when trying to access the shared_memory binary in the `bin` folder
=> Windows #hotfix Fix

common/eq_packet_structs.h, common/eqemu_logsys.cpp, common/eqemu_logsys.h, common/eqemu_logsys_log_aliases.h, common/loottable.h, common/shareddb.cpp, common/shareddb.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_08_15_lootdrop_level_filtering.sql, zone/aa.cpp, zone/attack.cpp, zone/loottables.cpp, zone/npc.cpp, zone/npc.h, zone/pets.cpp, zone/trading.cpp, zone/zonedb.h
* Add new logging category "Loot"
* Adds fields `npc_min_level` and `npc_max_level` to `lootdrop_entries` which runs checks against the current NPC as long as the field values are non-zero
* Fields `minlevel` and `maxlevel` are renamed to `trivial_min_level` and `trivial_max_level` respectively for `lootdrop_entries` for item drops to be filtered based on the player level
* Before, `trivial_max_level` defaulted to `127` in the database, this became an issue on some servers and some scenarios, the default has been adjusted to simply be 0 and only check if the value is non-zero
=> Lootdrop Filtering Adjustments

common/repositories/base/base_zone_points_repository.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_08_16_virtual_zonepoints.sql, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/command.cpp, zone/command.h, zone/npc.cpp, zone/npc.h, zone/spells.cpp, zone/zone.cpp, zone/zone.h, zone/zoning.cpp
This PR adds support for virtual zonepoints
Because the zone points that are sent to the client use an internal index lookup, it does not really give us power over determining or creating zone points in some cases. While this works in most of the data we've collected, there are scenarios where we'd like to create zone points entirely server side
We've added 3 new fields to the `zone_points` table `is_virtual` `width` `height`
When a zone point is virtual it follows different rules, a box is created using the x, y, z with the width and the height into consideration
New command **#showzonepoints** will list all of the zone points in a zone whether they are client side driven or virtual. It will also show a physical representation of the zone points in game
DevTools menu now displays …
=> Add support for virtual zonepoints

zone/entity.cpp, zone/groups.cpp, zone/raids.cpp, zone/zone.cpp
Few fixes I've never put back upstream from classless involving deleted pointers that are not set to null. The codebase really needs a bigger review of "delete" usage vs "safe_delete" macro usage, but that could have complications that extend beyond just a mass find/replace, so don't do that (also not everything crashes that does that!)
First, fix null pointers in group/raid removal code. This is to avoid an instance where a group or raid is removed in that instance of the zone and then becomes a dangling pointer that could be later used in the same server tick.
Fix issue where npc_types could become null in the cache but remain referenced, causing a crash due to invalid memory accessed later in the code (IE; pets that are spawned by NPC Type ID, and mercenaries/bots are especially bad …
=> Null ptr fixes

zone/embparser_api.cpp, zone/entity.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/zone.cpp, zone/zone.h
This PR allows quest writers to write code that allows activities to take place in zones with no clients.
I'm adding this, so that periodic wars, or movement based on other changes in the world can take place in zones that have no population when the changes or activities are desired.
A quest that wants to make sure that mob movement and processing take place - rergardless of the zone being empty, enable the provessing via quest::processmobswhilezoneempty(1) or the lua counterpart eq.process_mobs_while_zone_empty(true).
Once the quest has completed the quest needs to return the processing to normal state with the same call passing 0 or false.
Or these quest routines could be used by local zone_controller or other spawns to enable processing for a zone permanently.
The default is of course …
=> Allow quests to turn on mob processing in empty zones

zone/aggro.cpp
Per January 15th 2003 Patch Notes:
"NPCs will now notice Druid and Shaman Percentage Heal spells in a manner similar to traditional healing spells."
Added SE_PercetalHeal to the same CheckHealAggroAmount as SE_CurrentHP to be similar to traditional healing spells.
=> [Aggro] PercentalHeal should be included in aggro generation

zone/mob_ai.cpp
As noted, I think we do this check incorrectly, but this should work
fine and matches other similar spells, let's get it good enough first.
=> Fix NPC AI casting of ST_AEClientV1

zone/spells.cpp
The pet affinity in this case was checking the caster's AAs not the
target's like it should
=> Fix issue where a group buff was casted on a solo player

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2020_09_02_pet_taunting.sql, zone/attack.cpp, zone/client.cpp, zone/client_packet.cpp, zone/pets.cpp, zone/spell_effects.cpp, zone/zonedb.cpp, zone/zonedb.h
The pet window sit button is often out of sync.  This PR fixes this issue.  Also pet's were frequently still marked as sitting internal to the server due to the owner being attacked, or other issues.  This is because the anim state was not being correctly updated.
I tested the behavior on live and made it match.  A pet on guard will always return to guard after a battle.  A pet sitting, will switch to follow mode after a battle.  This fix is here as well.
After 2 weeks of testing, I no longer see the pet sit button out of sync, and no longer see (harder to see, but can be done with a char in his teens) pet sitting regen while pet is actually standing.
After hearing from @Trust that the taunt button was also out of sync often, I looked into that as well.
The client stores the status of an …
=> Fix bugged pet sit button and taunt.

zone/mob_movement_manager.cpp
This PR is almost a direct parallel to my PR that was accepted for flying.
Without this PR, only water only mobs swim from path node to path node, or to a target without dropping to
the ground mesh.  Meaning you need to have flymode set to swimming and inwater set in the db.  For some mobs like crocodiles in guk, that start in water, this PR allows then to path between gird nodes that are both underwater, or path to a target that is also out of water without sinking to the bottom.
If LoS fails, the mob reverts to existing pathing hierarchy, just like the flying patch.
I think you'll find that mobs underwater in guk and places like oasis act much better.
If a path grid has a node that has no line of sight to the next path node (or any other path node depending on grid type), the mob will …
=> Allow amphibious mobs underwater to follow los and not fall to water bottom when pathing

zone/exp.cpp
Let's not confuse players with missing messages I guess
=> Only UF and earlier have the CORPSE_ITEM_LOST string

zone/command.cpp
Fixes an issue with command query not using content database connecter.
=> Fix for command '#editmassrespawn'

utils/mods/expansions_combat.lua, zone/lua_client.cpp, zone/lua_client.h, zone/lua_mod.cpp, zone/lua_mod.h, zone/lua_parser.cpp, zone/lua_parser.h, zone/spells.cpp
** PLEASE SQUASH COMMITS ON MERGE **
This PR adds Mob:GetSkill() to the Lua API, necessary for fizzle calculation.
The new combat code is in utils/mods/expansions_combat.lua.
This needs to be copied to eqemu/mods/expansions_combat.lua and in the same folder you will need a LoadOrder.txt file with the filename to load. eg:
LoadOrder.txt:
``
expansions_combat.lua
```
=> Spell Fizzle for < LDON expansions via lua_mod

zone/entity.cpp, zone/mob.cpp
Fix scenarios where quest calls to SendIllusion also update internal values so that new clients that zone in see the correct appearance
Lots of appearance calls ultimately end up using SendIllusion; this will allow appearance to stick dynamically in scripts
Example script
```perl
quest::settimer("set_appearance", 1);
}
sub EVENT_TIMER {
if ($timer eq "set_appearance") {
quest::stoptimer($timer);
my $texture = int(rand(4));
my $gender  = int(rand(2));
my $race    = int(rand(12));
$npc->RandomizeFeatures(1);
$npc->SendIllusion($race, $gender, $texture, 0);
$npc->WearChange(7, 97);
$npc->WearChange(8, 98);
}
}
=> SendIllusion Update Internal Values

zone/client.cpp
This should summon the item at max charges, if it has charges
=> Update the SummonItem call to default charges for QuestRewards

zone/mob_movement_manager.cpp
Under any teleport node with 0.0f for x/y, mobs will end up at 0,0,0 due to a bug that does not check teleport nodes in the else statement that prevents the mob from having that route added.
Ignore the Jan 13, 2019 commit, it's reverted in the merge commit. Only the two changes are in question here.
=> Add safeguard for issue with mobs pathing to 0,0,0 on teleport nodes with values 0,0,0

zone/mob_ai.cpp
On islands, the -15 to z for checks to see if destination was in water was not enough, resulting in destinations in water for land creatures to look like land.
@KimLS
=> Destination check needed to be actual ground z at loc.  -15 wasnt enough

zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/spells.cpp
I wanted to create an quest NPC to allow players to sort their spell book by level. Ended up creating a perl/lua client questAPI called GetSpellIDByBookSlot which uses the existing GetSpellByBookSlot function. This has allowed me to create a perl/lua script to retrieve the spells within the book, sort by various attributes (level, type, etc) and then repopulate the spellbook in whichever sorted order is required. Happy to share the scripts as well. Hope this is useful to others.
=> Added new Perl/LUA GetSpellIDByBookSlot

zone/spell_effects.cpp
I made some earlier fixes to the pet sit/stand window as well as the pet states.  Newly charmed pets need to be set as standing, or the clients old setting (if it was sit) will end up making new charmed pets do the poop-on-my-butt carpet rub when they attack.
=> Client tracks pet sit/stand - force new pets to stand.

common/ruletypes.h, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/command.cpp, zone/mob_info.cpp
This PR improves DevTools toggling options
DevTool Window toggling has been unified into simply "DevTools"
* When DevTools are toggled off at an account level, windows that display on target, messages that display on target and the zone-in menu will no longer show
* DevTools can optionally be shut off globally in rules for all GMs
=> [DevTools] Improve DevTools Toggling Options

zone/command.cpp, zone/corpse.cpp, zone/corpse.h, zone/entity.cpp, zone/entity.h, zone/zone.cpp, zone/zonedb.cpp, zone/zonedb.h
This is an existing issue that will be more common now since dynamic zones can be manipulated to shutdown early (mpg group trials expire in 5 minutes on failure)
Player corpses are moved to graveyard when an expired instance is shutting down in case the graveyard timers didn't have a chance to process them. Zones without a graveyard move the corpses to the non-instance version of the zone without changing their location.
Live moves corpses out early instead of waiting for the graveyard timer when a dz shuts down like this (confirmed via an mpg group trial). Corpses moved to the non-instance version I observed via freeport sewers instances during anniversary last year.
=> Move player corpses on instance shutdown

common/eqemu_logsys.h, common/eqemu_logsys_log_aliases.h, common/servertalk.h, world/zoneserver.cpp, zone/entity.cpp, zone/entity.h, zone/groups.cpp, zone/groups.h, zone/worldserver.cpp
Added public/private class for oldleadername so we can save the previous leader name when the entity is destroyed then allow us to transfer leadership.
Adjusted DelmemberOOZ and in zone functions to include removal of the old leader when disbanding.
=> [Bug] Fix for Group Leader Disband Issue

zone/inventory.cpp
Bug Fix:
This prevents where a bard has a 2hand only instrument in secondary which prevents anything from being equipped in primary, it is possible to autoloot a main hand weapon and equip it with a 2-hand instrument, this will prevent that scenario from happening.
=> [Bug] Prevent Bards from auto equip loot when using instrument

zone/entity.cpp, zone/npc.cpp
When mobs are being pulled to Guards; they lag in their awareness to their surrounding because they are idle and not scanning aggressively (Every tic) whereas idle NPCs only do full scans once a minute
Flipped the flag for NPC's to add themselves to others close list when they are moving. This will ensure that any moving entity always updates those around them
Also added in-source comments around the "close mob" system
=> [Bugfix] Very edge case Guard awareness latency

zone/expedition.cpp, zone/expedition_database.cpp, zone/expedition_database.h
Fixes an exploit where multiple accepted cross zone invites could race with cache updates and allow an expedition to exceed its max members
=> Fix bug that could allow expeditions to exceed max members

zone/command.cpp
Preferential changes to #finditem, doesn't show stack options if item isn't stackable. Only shows "X" to summon one and/or max stack size of the item for summoning items. Resolves the issues some people were having where this command would summon an item with 1 charge instead of max charges because 1 was supplied as charges. Also shows name first instead of ID so the formatting is better.
In my experience most people who summon items like this want either one item or a full stack of an item and the summon size here is relative to the current item's stack size.
=> #finditem Changes

zone/exp.cpp, zone/string_ids.h
Basically just allows you to see if you're gaining multiple AAs at a time rather than just seeing "You have gained an ability point! You now have %1 ability point%2." every time regardless of amount gained and your current amount.
=> Add AA gain messages.

zone/npc.cpp
The NPC (npcthis) pointer held by Spawn2 wasn't reset if the npc was depopped without a respawn timer by #depop commands or depop(false) quest apis. If the NPC was part of a spawn condition then the condition would try to dereference that pointer (which gets deleted) on condition change.
STR with current peq db/quests:
- #zone fearplane
- #depopzone or #depop some trash mobs that exist on condition 1
- #dbspawn 72003 to repop Cazic_Thule (he toggles condition 1 5s after spawn and should crash zone)
- crash in Spawn2::SpawnConditionChanged
=> [Bugfix] Fix zone crash on spawn condition change

zone/entity.cpp
Fixes regression from b08dc02a (PR #1051)
The normal door list sent on zone entry caused unopenable double doors on clients if an api respawned them while the client was zoning. This waits until the client finishes zoning and has received the initial door list before sending any despawn/respawn packets.
Example packet order for one of the door APIs if called while a client is zoning:
```cpp
void Doors::SetOpenType(uint8 in) {
entity_list.DespawnAllDoors();
open_type = in;
entity_list.RespawnAllDoors();
}
```
before patch b08dc02a:
```
OP_SpawnDoor      -- part 2 (RespawnAllDoors) of api call (CLIENT_CONNECTINGALL)
OP_SpawnDoor      -- normal zone entry door list packet
OP_RemoveAllDoors -- part 1 (DespawnAllDoors) of api call, deferred until now (CLIENT_CONNECTED)
*all doors missing*
``` …
=> [Bugfix] Don't respawn doors while clients are zoning

zone/mob.cpp, zone/npc.cpp
Some boats (like race 533) line up better with some docs when they are not "levitating".
Before this patch, the flymode from the db could not override the code, because the check for IsBoat() in Mob::FillSpawnStruct happens after npc/mob creation has already been forced to turn the db field into the GravityBehavior enum which means it can no longer tell what to do.  I moved the check to inside the npc constructor, where this check against -1 can be made.
I also think that the old boat override only addressed the levitation mode in the packet being sent, and not in the mob itself.  I think this is what may be leading to some people seeing a floating boat and others seeing it underwater.  @thalix1337  and this may fix that.
=> Allow boats flymode to be overridden by local db

zone/perl_client.cpp
Noticed the Gitbook documentation listed SendFullPopup not Popup2 due to parsing the Perl croaks in the files, causing people not to be able to find the proper way to send a full popup window.
=> Fix Popup2 Perl croak.

zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
- Add quest::message(color, message) to Perl.
- Add eq.message(color, message) to Lua.
- Add quest::whisper(message) to Perl.
- Add eq.whisper(message) to Lua.
These methods allow you to use implied client references.
The whisper method also converts a widely used plugin in Perl to a Perl and Lua method that works on both Clients and NPCs.
=> Add message(color, message) and whisper(message) to Perl/Lua.

common/say_link.cpp
Fixes zone crash when this is logged
=> Replace unescaped braces in format string

common/database/database_dump_service.cpp
Fix issue where sometimes under certain circumstances when issuing a database dump with large data over a network with extended inserts we hit a buffer threshold that kills a MySQL dump with Error 2013
This occurs when using world cli command `database:dump`
This is seen specifically during http://db.projecteq.net/ 's dump operation when sourcing data both from the content database and local database simultaneously. This resulted in fragmented dumps on a very intermittent occasion
Tested fix 30x manually on PEQ
```
mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `items` at row: 82810
```
=> [Bugfix] Fix MySQL Dump Buffer Allocation

zone/mob.cpp
Mob::GMMove was ignoring heading.  Fixed to set it.
If a server allows boats to be targetted (so you can see boat name), any hail of the boat was turning the boat.  Disabled this for boats.
=> Use heading in GMMove and change FaceTarget not to turn boat

zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/questmgr.cpp
- Add $client->GetLearnableDisciplines(min_level, max_level) to Perl.
- Add client:GetLearnableDisciplines(min_level, max_level) to Lua.
- Add $client->GetLearnedDisciplines() to Perl.
- Add client:GetLearnedDisciplines() to Lua.
- Add $client->GetMemmedSpells() to Perl.
- Add client:GetMemmedSpells() to Lua.
- Add $client->GetScribeableSpells(min_level, max_level) to Perl.
- Add client:GetScribeableSpells(min_level, max_level) to Lua.
- Add $client->GetScribedSpells() to Perl. 
- Add client:GetScribedSpells() to Lua. 
This also fixes an oversight where CHAScribeHack wasn't able to be turned off for quest::scribespells.
Converts the methodology of traindiscs and scribespells to methods that are exported to Perl and Lua for both convenience and the customization options it offers.
From my …
=> Add new Spell methods to Perl and Lua.

zone/expedition.cpp
Fixes an edge case where a member could accept a pending invite into an
empty expedition before world could invalidate it
=> Verify expedition is not empty on invites

zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
- Add $client->SetAnon(anon_flag) to Perl.
- Add client:SetAnon(anon_flag) to Lua.
- Add $client->GetAFK() to Perl.
- Add client:GetAFK() to Lua.
- Add $client->SetAFK(afk_flag) to Perl.
- Add client:SetAFK(afk_flag) to Lua.
Converted GetAnon from bool to int for Lua because it can return 0 for Non-Anon, 1 for Anon, and 2 for Roleplaying.
Probably a little hacky, wasn't sure of a better way to get around some of the timer checks and stuff that some of the spawn appearance methods do.
=> [Quest API] Add Anon/AFK methods to Perl and Lua.

cmake/FindLua51.cmake
The include folder on my system is /usr/include/luajit-2.0, added some
extra library names since mine was /usr/lib64/libluajit-5.1.so
=> [Lua] Provide more search paths for luajit

common/ruletypes.h, zone/entity.cpp, zone/mob.cpp, zone/mob.h, zone/mob_ai.cpp, zone/mob_info.cpp, zone/npc.cpp, zone/npc.h
This PR allows a server operator to turn off animals opening doors if they want
Default live behavior is for animals to open doors when in proximity
```
RULE_BOOL(NPC, AnimalsOpenDoors, true, "Determines or not whether animals open doors or not when they approach them")
```
**Show your Work**
**Default Value** (Animals can open doors)
Rodent opened door
**Rule Disabled** (Animals can't open doors)
Rodent warped through door
=> [Door Opening] Rule to let configure Animal Door Opening

zone/data_bucket.cpp, zone/data_bucket.h, zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
Adds mob-based data bucket methods to Perl and Lua.
These methods use implied keys to shorten the process when creating and indexing unique data buckets.
For example $mob->SetBucket("a", 1) will set a bucket for "NPCID-a" if NPC or "CharacterID-a" to 1 automatically without something having to key it or think anymore about it.
- Add $mob->DeleteBucket(bucket_name) to Perl.
- Add mob:DeleteBucket(bucket_name) to Lua.
- Add $mob->GetBucket(bucket_name) to Perl.
- Add mob:GetBucket(bucket_name) to Lua.
- Add $mob->GetBucketExpires(bucket_name) to Perl.
- Add mob:GetBucketExpires(bucket_name) to Lua.
- Add $mob->GetBucketKey() to Perl.
- Add mob:GetBucketKey() to Lua.
- Add $mob->GetBucketRemaining(bucket_name) to Perl.
- Add mob:GetBucketRemaining(bucket_name) to Lua.
- Add …
=> [Quest API] Add Mob-based data bucket methods to Perl/Lua.

zone/lua_npc.cpp, zone/lua_npc.h, zone/npc.cpp, zone/npc.h, zone/npc_scale_manager.cpp, zone/npc_scale_manager.h, zone/perl_npc.cpp
- Add $npc->ScaleNPC(npc_level) to Perl.
- Add npc:ScaleNPC(npc_level) to Lua.
=> [Quest API] Add ScaleNPC(npc_level) to Perl and Lua.

zone/perl_client.cpp
Add category tags to new client methods.
=> Add category tags to new client methods.

common/ruletypes.h, zone/npc.cpp
Sneak pulling is a technique I used for years with my rogue on live, dating way back to 1999.
There are many different interpretations of how this works.  This thread covers alot of the ideas within the thread and with references to Monkly Business and The Safehouse.
https://www.project1999.com/forums/showthread.php?t=260642
For my server and from my memory, this implementation gets me close to my experience from live.
This is behind a rule, so no base behavior will change unless you enable it.
If it is enabled, then  successful sneaking reduces the assist range.  If behind the mob, it negates it - but you must remain sneaking while pulling.  I spent many years hurling throwing weapons while peddling backwards with sneak/hide on with sow. If I peddled back out of aggro range before the …
=> [Game Play Mechanic] Very simple implementation of Sneak Pull

zone/client.cpp, zone/questmgr.cpp
These functions were returning the size of the array of spells, not the amount of spells or disciplines learned.
Was also missing a couple logic checks.
Condensed messages as well and added a count in a message with scribespells similar to traindiscs.
=> [Quest API] Resolves traindiscs and scribespells issues in Perl/Lua.

common/string_util.cpp, common/string_util.h, tests/string_util_test.h
This function takes a string of deliminated an see if another string is
one of those
This function also verifies it's not finding a substring
The motivational example for this function is the hotzone checking in PR #1257 
Currently our easiest way of doing this task is to split the string, this is rather needlessly expensive, so I wrote this.
Benchmarks: (on 8700k, stock, governor set to performance, optimization level 2 an march not set)
```----------------------------------------------------
Benchmark             Time           CPU Iterations
----------------------------------------------------
bench_split         871 ns        871 ns     796901
bench_search         38 ns         38 ns   18419186
```
=> Add string util search_deliminated_string

zone/main.cpp
It should be fine to init further down after the early returns.
This wasn't really a leak that affected performance, but mainly moving
to shutup valgrind
=> [Leak] Fix NPC Scale Manager leaking

zone/entity.cpp, zone/lua_parser.cpp, zone/lua_parser.h, zone/quest_interface.h, zone/quest_parser_collection.cpp, zone/quest_parser_collection.h
Basically, EntityList::RemoveAllEncounters is called before ReloadQuests
resulting in stale pointers in the lua_encounters map.
We just have to remove the entry from the map.
=> [Crash] Fix ReloadQuest on Shutdown crash related to encounters

zone/zoning.cpp
This is in response to the discussion in eqemu-coders:
https://discord.com/channels/212663220849213441/557677602706423982/814234259845283870
The "fix" is simple.  From what I read, the pet does not switch from guard to follow on live.  I did not check live myself, I'm relying on the information in the thread.
If the pet should stay on guard, this should fix the issue.
=> [Bug Fix] Do not summon pet or set new pet state when PC summoned by a mob

zone/worldserver.cpp
```
==1674==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffb47f3068 at pc 0x7f64ee1f531e bp 0x7fffb47f2f50 sp 0x7fffb47f2700
READ of size 432 at 0x7fffb47f3068 thread T0
#0 0x7f64ee1f531d  (/lib/x86_64-linux-gnu/libasan.so.5+0x3f31d)
#1 0x55c78e8d002e in WorldServer::UpdateLFP(unsigned int, unsigned char, unsigned char, unsigned int, unsigned int, unsigned int, char const*, GroupLFPMemberEntry*) ../zone/worldserver.cpp:3166
#2 0x55c78e8d01d9 in WorldServer::StopLFP(unsigned int) ../zone/worldserver.cpp:3180
=> [ASan] Fix stack-buffer-overflow thanks to StopLFP

common/event/timer.h, common/net/tcp_connection.cpp, common/net/tcp_server.cpp
I don't think these are actually causing any real problems, ASan
complains about them though since it's kind of a code smell I guess and
a potential source of problems. But our case is fine, so cast to silence
them.
=> [ASan] Use casts to silence ASan complaints

world/client.cpp, world/zoneserver.cpp, zone/bot.cpp, zone/client.cpp, zone/command.cpp, zone/main.cpp, zone/merc.cpp, zone/npc.cpp
Skill caps is classed as a content database table; the database pointer that accesses and mutates should be consistent with that all the way across
Issue was observed on character creation
**Before**
**After**
=> [Bugfix] Fix Skill Caps Loading References

zone/groups.cpp
```
==2317==ERROR: AddressSanitizer: heap-use-after-free on address 0x6170000633c0 at pc 0x55ed1d8e8d8b bp 0x7ffda4bef580 sp 0x7ffda4bef578
WRITE of size 8 at 0x6170000633c0 thread T0
#0 0x55ed1d8e8d8a in Group::SetLeader(Mob*) ../zone/groups.h:80
#1 0x55ed1d8e8d8a in Group::DisbandGroup(bool) ../zone/groups.cpp:1016
```
ASan didn't like this
=> [ASan] Fix heap-use-after-free issue with groups

zone/spawngroup.cpp, zone/spawngroup.h
This was leaking on #repop, unsure of other cases, smart pointers should
cover us though.
```
Direct leak of 3600 byte(s) in 18 object(s) allocated from:
#0 0x7f2b3dbe0d30 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
#1 0x5645dc7c9dff in ZoneDatabase::LoadSpawnGroups(char const*, unsigned short, SpawnGroupList*) ../zone/spawngroup.cpp:241
#2 0x5645dc9db3f5 in Zone::Depop(bool) ../zone/zone.cpp:1746
#3 0x5645dca1ba6b in Zone::Repop(unsigned int) ../zone/zone.cpp:1777
#4 0x5645db4624b7 in command_repop(Client*, Seperator const*) ../zone/command.cpp:5683
```
```
Indirect leak of 6552 byte(s) in 273 object(s) allocated from:
#0 0x7f26f2ff8d30 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
#1 0x558d00490bc6 in …
```
=> [Leak] Port SpawnGroup stuff to unique_ptr to fix leak

common/database_instances.cpp, zone/client_packet.cpp, zone/worldserver.cpp
```
==1810==ERROR: AddressSanitizer: strcpy-param-overlap: memory ranges [0x7ffef04baf90,0x7ffef04baf98) and [0x7ffef04baf90, 0x7ffef04baf98) overlap
#0 0x7f163bb9509e  (/lib/x86_64-linux-gnu/libasan.so.5+0x4f09e)
#1 0x5652caed27b3 in Client::Handle_Connect_OP_ZoneEntry(EQApplicationPacket const*) ../zone/client_packet.cpp:1535
```
```
==1918==ERROR: AddressSanitizer: strcpy-param-overlap: memory ranges [0x7ffddc8057c0,0x7ffddc8057c8) and [0x7ffddc8057c0, 0x7ffddc8057c8) overlap
#0 0x7fc61ee0e09e  (/lib/x86_64-linux-gnu/libasan.so.5+0x4f09e)
#1 0x56023c149698 in WorldServer::HandleMessage(unsigned short, EQ::Net::Packet const&) ../zone/worldserver.cpp:1055
```
=> [ASan] Fix strcpy-param-overlap with GetGroupLeadershipInfo calls

zone/command.cpp
Fixed typo in the command description.
=> Fixed typo in description of #list command. [skip ci]

zone/spells.cpp
I found that disciplines like "Focused Will" were causing our characters to stand up on the client, while on the server their sit/stand status was unchanged.  This got us out of sync with the GUI the next time sit/stand was pressed.
Testing Focused Will on live, it does not require the character to stand up, nor does the character do any animation aside from some glowing.  Testing non spell disciplines, both our server and live stand up first.
The change in this PR makes our server behave live like for Disciplines that cast spells for the disciplines I tested.  We still get the glowing effect, but the character sit/stand does not change.
=> Remove unneeded calls to DoAnim() for spells/bardsong

zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
Converts time in seconds to human readable string.
- Add quest::secondstotime(duration) to Perl.
- Add eq.seconds_to_time(duration) to Lua.
=> [Quest API] Add secondstotime(duration) to Perl and Lua.

zone/spawngroup.cpp
setting spawn2.version to -1 will now properly spawn mobs in all zone versions
=> [Bugfix] Fix for spawn2.version

zone/embparser_api.cpp
I needed this for a spell scriber I am making.. Figured I'd put it here in case someone else finds it useful in the future. I searched for something that does this already but couldn't find anything.
This uses the already existing GetSpellLevel from spdat.cpp. Generally I would copy the naming scheme of similar methods (getspellname, getskillname) but the triple L made it quite ugly.
If the class provided cannot use the spell, the spell level is greater than the max level of the server, or an invalid spell is provided it will return 0.
=> [Quest API] Add quest::get_spell_level(uint16 spell_id, uint8 class_id)

zone/CMakeLists.txt, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/dynamic_zone.cpp, zone/dynamic_zone.h, zone/entity.cpp, zone/expedition.cpp, zone/expedition.h, zone/lua_client.cpp, zone/zone.h
Removes the DynamicZoneInfo struct used for switch list window. This data can be stored on DynamicZone and kept updated by its owning system.
Beginning to cherry pick stuff from my current dz decoupling dev branch. This also renames zone dynamic_zone source files for consistency with dz repository headers and other new files added later. Also sneaking in a small cleanup to MarkSingleCompassLoc with this since it's touching the compass methods.
=> [Expeditions] Store description and leader name on dz

common/ruletypes.h, world/expedition.cpp, world/expedition.h, world/expedition_state.cpp
This fixes unnecessary leader processing on mass dzquits
Also marks leader dirty for empty expeditions in case something goes
wrong (shouldn't be possible after 62e480fe)
=> [Expeditions] Throttle auto expedition leader changes

zone/client.cpp, zone/client.h, zone/entity.cpp, zone/zone.cpp, zone/zone.h
This changes Zone::GetDynamicZone to return a pointer instead of a copy
and also lets DynamicZone be forward declared in zone.h
=> [Expeditions] Cleanup client dz safe return methods

common/CMakeLists.txt, common/expedition_lockout_timer.cpp, common/expedition_lockout_timer.h, common/repositories/base/base_character_expedition_lockouts_repository.h, common/repositories/character_expedition_lockouts_repository.h, common/repositories/expeditions_repository.h, zone/CMakeLists.txt, zone/client.cpp, zone/expedition.cpp, zone/expedition.h, zone/expedition_database.cpp, zone/expedition_database.h, zone/expedition_request.cpp, zone/expedition_request.h, zone/lua_client.cpp
Move ExpeditionLockoutTimer to common
This simplifies expedition request conflict checks and uses repository
for the queries instead of processing the query result directly.
=> [Expeditions] Refactor expedition requests

zone/client_packet.cpp
Theoretically this could be used to corrupt memory, but they would have
to get extremely lucky to actually execute a successful attack
=> [Bug Fix] Add Bounds Checking to OP_LFGCommand Comment Processing

common/eq_constants.h, common/repositories/instance_list_repository.h, common/servertalk.h, world/CMakeLists.txt, world/dynamic_zone.cpp, world/dynamic_zone.h, world/expedition.cpp, world/expedition.h, world/expedition_database.cpp, world/expedition_database.h, world/expedition_message.cpp, world/expedition_state.cpp, world/expedition_state.h, world/zoneserver.cpp, zone/dynamic_zone.cpp, zone/dynamic_zone.h, zone/expedition.cpp, zone/expedition.h, zone/lua_expedition.cpp, zone/perl_expedition.cpp, zone/worldserver.cpp
Use internal dz messages to process duration and location changes
Add world DynamicZone class (later this will inherit from a base)
Add FindDynamicZoneByID to get dz from zone and world system caches
This starts the main decoupling process and precedes some more changes that will make dynamic zones more usable by other systems
=> [Expeditions] Decouple dz updates from expeditions

zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
- Add quest::GetZoneLongNameByID(zone_id) to Perl.
- Add quest::GetZoneShortName(zone_id) to Perl.
- Add eq.get_zone_id_by_name(zone_name) to Lua.
- Add eq.get_zone_long_name_by_id(zone_id) to Lua.
- Add eq.get_zone_long_name_by_name(zone_name) to Lua.
- Add eq.get_zone_short_name_by_id(zone_id) to Lua.
=> [Quest API] Add new zone name methods to Perl and Lua.

common/ruletypes.h, world/dynamic_zone.cpp, world/dynamic_zone.h, world/expedition.cpp, world/expedition.h, world/expedition_state.cpp, world/expedition_state.h
Move early empty shutdown and process rate rules to DynamicZone scope
This decouples the expired status check from expeditions into an
internal dz method that can be called by its owning system
=> [Expeditions] Let dz process its expired state

common/CMakeLists.txt, common/dynamic_zone_base.cpp, common/dynamic_zone_base.h, common/repositories/dynamic_zones_repository.h, common/servertalk.h, world/dynamic_zone.cpp, world/dynamic_zone.h, world/expedition.cpp, world/zoneserver.cpp, zone/client.cpp, zone/command.cpp, zone/dynamic_zone.cpp, zone/dynamic_zone.h, zone/expedition.cpp, zone/expedition.h, zone/worldserver.cpp
This creates an abstract class in common so zone and world can share
most of the implementation. World now has access to the same dz data and
api as zone.
Rename CharacterChange to AddRemoveCharacter for clarity
Rename GetRemainingDuration to GetDurationRemaining for consistency
Move dynamic zone queries to custom repository methods
=> [Expeditions] Create common dz abstract class

zone/spells.cpp
This isn't the exactly the right way, but it's behavior is much closer
to live than current for Solon's Song of the Sirens (725), the other
bard charms don't repulse due to mana cost
=> [Bug Fix] Hack to fix repulsable bard charms

zone/zone_event_scheduler.cpp
Using search_deliminated_string here is significantly faster than
splitting, most likely because of dynamic memory management
Some tests on my system:
```
----------------------------------------------------
Benchmark             Time           CPU Iterations
----------------------------------------------------
bench_split         864 ns        864 ns     807922
bench_search         35 ns         35 ns   20265205
```
This test was a case where the string was present somewhere in the
middle which gave a ~96% speed up
```
----------------------------------------------------
Benchmark             Time           CPU Iterations
----------------------------------------------------
bench_split         936 ns        936 ns     725518
bench_search         61 ns         61 ns   11156359
```
This …
=> [Performance] Switch scheduled hot zone check to search instead of split

zone/npc.cpp
Any values in the npc_spells table that set these variables were being ignored because the rules are being applied after AI_AddNPCSpells is called, so moved the AISpellVar assignments before the call.
=> [Fix] Moved assigning of AISpellVar variables before AI_Start()

common/ruletypes.h, world/login_server.cpp
Rule Name: GM:MinStatusToBypassLockedServer
Default Status: 100
Description: Players >= this status can log in to the server even when it is locked
Believe you used to be able to change this via the old config? Either way should be very useful as the current requirement is 101 to get through a Locked server. Since our default is 100 now you will be able to get in at status 100 but nothing below that obviously.
The plan for me specifically is to create a new field in the accounts table and disconnect this whole thing from GM status entirely (field would be named ignoreLockedServer or bypassLockedServer or something). Don't know if that's too custom for Master source but will provide that as well when I am done with it if anyone wants it.
=> [Rules] Add rule 'GM:MinStatusToBypassLockedServer'

zone/npc.cpp
If you set ignore_primary_assist in npc_faction, then mobs of the same primary faction should not assist each other.  The code to handle this was broken, in that it checked for this, but also always did this check regardless:
sender->GetReverseFactionCon(mob) <= FACTION_AMIABLE
That call always returns AMIABLE if the mob requesting assistance and the mob being checked are on the same primary faction.
So, the ignore_primary_assist  was essentially doing nothing.
The fix is easy, we simply coninue when we find this condition in call for help.  No need to proceed with the mob being checked if they are on the same faction and ignore primary is true.
=> [Bug] Fix ignore_primary_assist.

common/database.cpp, world/worlddb.cpp, zone/zoning.cpp
GetSafePoints  was causing a crash on character creation on Ubuntu due to a null_ptr being sent to GetSafePoints when bindid was 0 in start_zones.
I can't identify why this has cropped up in the last few weeks of changes, but it is 100% repeatable now.  Maybe changes to string utils?
Regardless, passing null_ptr to GetSafePoints isn't good, and this change will simple end up passing "UNKNOWN" which fixes the crash.
I changed all (4) spots for safety, but only in the case of bindid=0 do I expect ZoneName() to be returning a 0.
This was the dump created by the unsafe calls:
terminate called after throwing an instance of 'fmt::v5::format_error'
what():  string pointer is null
[sudo] password for drool:
29      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
[World] [Crash] …
=> Fix calls to GetSafePoints to not pass null_ptr as zonename

common/dynamic_zone_base.h, common/expedition_base.cpp, common/expedition_base.h, common/servertalk.h, world/expedition.cpp, world/expedition.h, world/expedition_message.cpp, world/expedition_message.h, world/expedition_state.cpp, world/zoneserver.cpp, zone/expedition.cpp, zone/expedition.h, zone/worldserver.cpp
World now caches and tracks member statuses so it can send them to zones
that request them on startup. Prior to this the cle would be searched in
world for every zone startup caching request, now it's only searched once
when a new expedition is created.
Bulk loading statuses removed since it would only be needed on world
startup now and likely have no clients in the client list anyway.
This also lets world choose non-linkdead members on expedition leader
changes and better detect when a leader change needs to occur
=> [Expeditions] Track DZ member status in world

zone/npc.cpp
If a mob is pulled with a spell like flash of light, the mob_ai never sets a target until the flee portion of the spell wears off.
On live, these fleeing mobs still cause other mobs to help, even while the mob keeps fleeing.
This PR assigns a target in these cases to YellForHelp functions properly.
It also adds additional logging for YellForHelp debugging.
=> [Bug Fix] Add debugging and fix edge case where no target for aggro mob

utils/scripts/eqemu_server.pl
Some improvements to the installer script to help make a streamlined, simplified docker setup that leverages the same installer as suggested on the wiki.  In particular:
- Support for using environment variables for everything in installation_variables.txt (as well as some of the SKIP steps)
- Added support for specifying a db host other than localhost in above
- Added support for specifying the db root password for use when we DROP/CREATE database in new_server
- Added some of the existing additional options to the menus (like the linux start_server_with_login.sh)
- Removed a redundant build step (we were building the source twice in new_server)
- Added an option to deploy a new_server_with_bots, since the processes is all the same, just with different options on build
- Merged the …
=> [Installer] $ENV support, formatting, and optimizations

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2021_04_28_idle_pathing.sql, zone/entity.cpp, zone/lua_general.cpp, zone/spawn2.cpp, zone/spawn2.h
This PR simplifies and expands the capability to allow mobs to continue to process even when a zone is idle.
In a PR 4 years ago, I submitted the following PR so that mobs like Fippy, that spawn and then run to the end of a grid and despawn would continue to do this on the set timing regardless of zone status.  This made these spawns more realistic and less hinky (ie,. they used to start there run as soon as the 1st player ran in).
That PR, while helpful, attached the mobs mode of moving while the zone was idle to grid types 4 and 6.  These happened to be the most glaring cases of mobs being too predictable based on the IDLE zone optimizations.
This PR removes that code, and now ANY spawn2 can be set to always process regardless of zone status.  I find this especially useful for named …
=> [Feature] Allow any spawn2 spawned mob to path while zone is idle if new flag is set.

zone/command.cpp
Makes using #list npcs and using the goto button more useful when NPC is a boat, as normal Z will put you in the water.
=> [GM Command] #list npcs Goto option now goes to higher Z if selected NPC is a boat.

common/dynamic_zone_base.h, common/expedition_base.cpp, common/expedition_base.h, world/expedition_state.cpp, zone/expedition.cpp, zone/expedition.h
This starts some changes that move storage of things from expeditions to
dynamic zone class so other systems can possibly use them. This will also
make it easier to move window packet creation methods to DynamicZone.
For now these will remain on the expeditions table in the database. This
can be re-evaluated once other components are moved and seeing how other
systems may want to handle their player requirements.
=> [Dynamic Zones] Store min and max players on dz

common/ruletypes.h, zone/effects.cpp
this fixes AE pacify / Mez spells only landing on 4 when it shouldn't have a cap
=>  [Bug Fix] EntityList::AESpell fix for Pacify / Mez

zone/attack.cpp
This also scales up to 280 skill, so under that, you don't get as high
of a bonus
=> This skill bonus was suppose to only apply to monks with epics

zone/client_process.cpp
Add additional popup to shared bank warning message, as client-side filters can cause the message to be unseen.
=> [Shared Bank] Shared Bank Disabled Warning Popup

common/ruletypes.h, zone/bot.cpp, zone/client.h, zone/effects.cpp, zone/merc.cpp, zone/merc.h, zone/mob.cpp
Remove the overloads that don't make sense (bots probably doesn't make
sense either, but too lazy)
Fix the formulas
Removed the Spells:MaxCastTimeReduction rule since this is HARDCODED in
the client so it doesn't really make sense to have it as a customization
point. If you want to hack the client, change the hardcode as well I
guess.
=> [Fix] Fix Spell Cast Time reduction issues

common/servertalk.h, world/zoneserver.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/command.cpp, zone/embparser_api.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/lua_general.cpp, zone/perl_client.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/worldserver.cpp
- Swapped parameters in mostly unused functions to be theme_id first and points second. (No examples in PEQ quests.)
- Removed UpdateLDoNLosses/UpdateLDonWins source methods in favor of AddLDoNLoss/AddLDoNWin as you can only add 1 at a time.
- Add $client->AddLDoNLoss(theme_id) to Perl.
- Add $client->AddLDoNWin(theme_id) to Perl.
- Add quest::crosszoneaddldonlossbycharid(character_id, theme_id) to Perl.
- Add quest::crosszoneaddldonlossbygroupid(group_id, theme_id) to Perl.
- Add quest::crosszoneaddldonlossbyraidid(raid_id, theme_id) to Perl.
- Add quest::crosszoneaddldonlossbyguildid(guild_id, theme_id) to Perl.
- Add quest::crosszoneaddldonlossbyexpeditionid(expedition_id, theme_id) to Perl.
- Add quest::crosszoneaddldonpointsbycharid(character_id, theme_id, points) to Perl.
- Add …
=> [Quest API] Add several methods to Perl/Lua API for LDoN stuff.

zone/client_packet.cpp
When using aggrozone to test certain things if you have any mobs that cast fear in the zone you get stunlocked without being able to use any GM commands.
Tied to green name, not status.
=> [Bug Fix] Allow GMs to chat when AIControlled (feared, mezzed?)

world/expedition.cpp
This fixes an edge case where a player could be made leader when added
to an expedition that only had a single member previously.
If a leader in a two-member expedition quit (forcing a leader change)
and the new leader went offline while throttled, a leader change flag
would be set until a non-leader was available. The first added member
would then be made the new leader.
This could also potentially occur on world startup due to the initial
throttle timer state but member statuses aren't processed there yet
=> Avoid expedition leader change if only member

common/ruletypes.h, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/effects.cpp
Uses similar logic to disciplines with the hardcoded `Tome:` check and stuff, but with `Spell:` items here instead. Locked it behind a rule in case people don't want to use it.
=> [Spells] Adds a rule to allow right-click memorize from spell scrolls.

common/database_schema.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2021_06_06_beastlord_pets.sql, zone/pets.cpp, zone/zonedb.h
- Create a Beastlord pets table to allow server operators to easily customize Beastlord pets without a source modification.
- Defaults to similar values as the original switch inside the struct and database table.
=> [Pets] Unhardcode Beastlord pet values.

common/database.cpp, common/database.h, common/string_util.h, zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
- Allows Server Operators to grab the clean name without having to clean it up in their Perl/Lua.
=> [Quest API] Add getcleannpcnamebyid(npc_id) to Perl/Lua.

zone/command.cpp, zone/command.h, zone/npc.h
- Allows GMs to search for a specific item across all the loot currently available on the spawned NPCs in the zone.
- Specifying item ID 0 will allow GMs to see all the droppable items, I tested in Sanctus Seru (a huge zone) and it sent approximately 1,200 messages, which didn't lag or desync my client.
=> [Commands] Add #viewzoneloot [item id] command.

zone/command.cpp, zone/command.h
- Allows GMs to find a class by name or ID.
- Modify some verbiage in command messages that were improper.
=> [Commands] Add #findclass [search criteria] command.

zone/mob.cpp
Fix an issue originally reported by @RoT-PvP  where armor appearance does not look correct after an illusion fades
**Before Illusion**
**Illusion**
**After Illusion**
Issue caused by my PR back in Oct 2020 https://github.com/EQEmu/Server/pull/1130
The original PR will have to have functionality split into a separate function
=> [Bug Fix] Fix illusions

zone/spells.cpp
Stack Trace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f04bc75a0ca in __waitpid (pid=14948, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
[Current thread is 1 (Thread 0x7f04bba80140 (LWP 12099))]
#0  0x00007f04bc75a0ca in __waitpid (pid=14948, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x000055e6afebfcae in print_trace () at /home/eqemu/code/common/crash.cpp:154
#2  <signal handler called>
#3  std::_Hashtable<unsigned short, std::pair<unsigned short const, Mob*>, std::allocator<std::pair<unsigned short const, Mob*> >, std::__detail::_Select1st, std::equal_to<unsigned short>, std::hash<unsigned …
```
=> [Hotfix] Fix crash pertaining to new PVPEnableGuardFactionAssist code

common/eq_packet_structs.h, zone/mob.cpp, zone/mob_appearance.cpp, zone/spell_effects.cpp
Reverts a revert https://github.com/EQEmu/Server/pull/1389
Tested this and this is working fine. The previous revert was hurting more than it was helping so it makes sense to keep what I had patched in from last October for now unless there is something that warrants taking a closer look
Time boxing investing time in this but for the most part we should be good and should get this merged back in to fix previous regressions on master
* #size (Camped character, re-zone etc.)
* Illusion (Camp other player, re-zone back in)
* Click off Illusion, returns to normal (Camp other player and re-zone back-in)
This also fixes an issue where Illusions were improperly setting size for a specific Illusion. The Illusion would update properly for one client but would not set the size properly. We're not …
=> [Hotfix] Illusion Revert

zone/bonuses.cpp, zone/trading.cpp
Most commonly this would allow the different color satchels to be used in Trader mode.
PEQ database has 1 item (Yellow Trader's Satchel Token - 35037) marked as type 51, but otherwise only the proper bags are already set in that DB.
Bonus of removing the hard-coded ID from source.
=> [Items] Allow any bag type 51 to be used for Trader

zone/command.cpp, zone/entity.cpp, zone/entity.h, zone/npc.cpp, zone/npc.h, zone/waypoints.cpp, zone/zonedb.h
- #grid add will no longer let you put in a duplicate grid.
- Grid nodes now spawn with invul/immune to damage so they cannot be damage accidentally.
- Grid nodes now set an entity variable "grid_id" on spawn.
- This allows grid nodes to be specifically despawned by "grid_id" entity variable, meaning you can view multiple grids at once and not despawn them all accidentally.
- #grid hide will despawn your targeted NPC's Grid nodes.
- #grid add, #grid show, #grid delete, and #grid hide send messages to let GM know what's going on.
- #wp add and #wp delete now send messages to let the GM know what's going on.
- #wpadd now send messages to let the GM know what's going on.
=> [Commands] Modify #grid and #wp.

zone/command.cpp
- #summonitem will now properly take item augments from an item link when used as a link for summoning.
- #summonitem help message and command message will now list proper argument list.
- #giveitem will now allow item links like #summonitem with the same functionality level.
- #giveitem help message and command message will now list proper argument list.
- #giveitem small fix where there were 2 checks for argument count at 7, meaning final argument count (8) did not work.
=> [Commands] Modify #summonitem and #giveitem.

common/ruletypes.h, zone/mob.cpp, zone/spell_effects.cpp
This directly addresses https://github.com/EQEmu/Server/issues/904
Apparently the Livelike functionality is ANY invis breaks charm  -- even if you have say a regular mob charmed and you cast IVU. Setting the rule to false will only break charm if your pet cannot see you. (ex. You have a skeleton charmed and cast IVU). Rule description is very clear.
At the current time after the charm breaks the pet starts attacking you which I am told is Livelike behavior.
=> [Bug Fix] Fixed Invis vs Undead / Invis Vs Animals not breaking charm + Added rule for custom capabilities

zone/mob.cpp, zone/spell_effects.cpp
Revert the rest of the code that was changed back to October until further deeper testing. This function does too many things and is interwoven in spaghetti code
This should address https://github.com/EQEmu/Server/issues/1436 and bring us back to our original zero state but the issues originally reported by @RoT-PvP will still remain which at this point are far smaller than the side effects produced by what's currently there
=> [Hotfix] SendIllusion revert to October

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/common.h, zone/lua_stat_bonuses.cpp, zone/mob.cpp, zone/mob.h, zone/special_attacks.cpp, zone/spell_effects.cpp, zone/spells.cpp
Implemented various new spell effects. (7/13/21)
SE_DS_Mitigation_Amount		467 
Modify incoming damage shield damage by flat amount. 
Note: Negative value is used to decrease DS (ie. -500 will reduce flat 500 pts of DS)
SE_DS_Mitigation_Percentage		468
Modify incoming damage shield damage by percentage. 
Note: Negative value is used to decrease DS (ie. -50 will reduce incoming DS by 50%)
SE_Double_Backstab_Front		        473  - Chance to double backstab from front
SE_Critical_Melee_Damage_Mod_Max	496 - increase or decrease by percent critical damage (not stackable)
SE_Melee_Damage_Position_Mod	503 
increase/decreases melee damage by percent base1 based on your position base2 0=back 1=front (not stackable)
SE_Damage_Taken_Position_Mod	505
increase/decreases melee damage taken by percent …
=> [Feature] New SPAs pass 1

zone/special_attacks.cpp, zone/spell_effects.cpp
Fixed bug with spell projectiles causing angle to not be calculated correctly. Spell projectiles will now fire straight instead of from the side.
Significantly improved all projectile timings. At least up to range of 300 should see more accurate timings for damage/effects occurring upon projectile impact.
Will be noticed most significantly for all spell projectiles and for longer range archery.
=> Projectiles Update

common/spdat.h, zone/bonuses.cpp, zone/common.h, zone/mob.cpp, zone/spell_effects.cpp
Implemented new spell affect
SPA 482 SE_Skill_Base_Damage_Mod
Modifies base melee damage by skill 
Base: pct Limit: skill(-1=ALL), max: none
Stacks with SPA 189 and 482
=> Implemented SPA 482 SE_Skill_Base_Damage_Mod

zone/mob.cpp, zone/spell_effects.cpp
Improvement to SE_TwinCastBlocker SPA 399 implementation to catch all cases where twincast is used. 
Will now ensure both spell casted and weapon proced twincasts can be effectively blocked.
=> Fix SE_TwinCastBlocker SPA 399 to also block twinproc

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/common.h, zone/lua_stat_bonuses.cpp, zone/merc.cpp, zone/spell_effects.cpp
Implemented
SE_AddExtraAttackPct_1h_Primary	498 , gives your double attacks a percent chance to perform an extra attack with 1-handed primary weapon, base: chance, limit: amt attacks, max: none
SE_AddExtraAttackPct_1h_Secondary	499  gives your double attacks a percent chance to perform an extra attack with 1-handed secondary weapon, base: chance, limit: amt attacks, max: none
Added limit field functionality (can have more than 1 extra attack) to similar effect SPA 266 which gives extra attack chance to perform an extra attack with a 2-handed weapon.
SPA 266 (and new ones) will now be calculated to take highest percent value when applying bonus. (was additive, which seems obviously in error based on AA data values in our tables and live descriptions of AAs that use these)
=> Implemented SPA 498 and 499 (extra attack chance effects)

zone/bonuses.cpp, zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
Fixed bug with SPA 30 SE_SE_ChangeFrenzyRad and SPA 86 SE_Harmony allowing those spells to affect NPC's above their level restrictions when cast as a 'Targeted AE' spell (ie. Harmony, Wake of Tranquility) when the targeted NPC was bellow level restricted range, but the NPC's next to them were above it.
Implemented the live like behavior, if this case occurs on live, the buff is not applied to the targets over the level limit and "Your target looks unaffected" message is given. 
Also added additional layer of protection, even if somehow the buff does get on the target, the actual effect will not be applied to an NPC over the level limit.
This bug was originally reported by: Isaaru (7/26/21)
=> [Spells] Bug fix for AOE Harmony/Lull

zone/client.h, zone/merc.cpp, zone/merc.h, zone/mob.h, zone/npc.h, zone/spell_effects.cpp
Need to increase from int16 to int32 when calculating focus in CalcAAFocus and CalcFocusEffect due it causing issues with returning spell ids for some effects which can easily be over the int16 limit. GetFocusEffect which gets its values from CalcAAEffect and CalcFocusEffect function was doing all math in int16, therefore if increasing the above,  makes sense to do the calculations GetFocusEffect with int32 as well. No downside I can see.
=> [Spells] Focus related functions to use int32 instead of int16

zone/bonuses.cpp, zone/common.h, zone/lua_stat_bonuses.cpp, zone/mob.h
Update to SPA 335 SE_BlockNextSpellFocus code.
Minor code changes to make the focus be checked consistent with how all other focuses are checked. No change in functionality.
Reminder functionality, Focus checks on caste for a chance to block next incoming spell if conditions are met. 
base: chance limit: none max: none
You specify which spells are to be blocked using focus limiters.
=> [Spells] Update to SPA 335 SE_BlockNextSpellFocus

common/spdat.cpp, common/spdat.h, zone/bonuses.cpp, zone/command.cpp, zone/command.h, zone/mob.cpp, zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
Rewrote the functions that handle the focus effect SPA 339 SE_TriggerOnCast
As reminder, the effect works as a focus that gives a chance to cast an additional spell whenever a spell is cast is conditions are met. Base1: Chance Base2:  spell_id
This focus was not coded consistently to how other focus effects are checked. There is no longer an arbitrary max number focuses with this effect that a player can have. Overall it works well now, fits with rest of foci code, and is easier to manage.
Also added #command resetdisc_timer
usage: #resetdisc_timer [all | timer_id]
=> [Spells] Update SPA 339 SE_TriggerOnCast

common/shareddb.cpp, common/spdat.h, zone/mob.h, zone/spell_effects.cpp
Update to focus limiter
SPA SE_LimitSpellClass: 403
SPA SE_LimitSpellSubclass: 404
Now use spell table values from column 221 and 222 respectively. 'spell_class' and 'spell_subclass'
Base: spell category id (positive value include spells with this category, negative value excludes them)
Note: Values in these fields correlate to specific groups/types of spells, but I do not know what most of them correlate to.
Either way, live spells will now properly work that have these effects. Removed old function that is no longer relevant.
Added FocusLImitInclude Enum to improved GetFocusEffect functions readability.
=> [Spells] Update for SPA 403 and 404

zone/mob.h, zone/spell_effects.cpp
Live like updates.
Update to SPA 130 SE_SpellHateMod: To allow focus calculation to check a random range if indicated by spell file data.
Reminder, focus allows to increase or decrease hatred generated from spell damage.
Update to SPA 131 SE_ReduceReagentCost: To allow focus calculation to check a random range if indicated by spell file data.
Reminder, focus gives a chance not to consume a reagent.
For both, and any focus that uses random effectiveness formula.
If Base and Limit values both are defined. Then Base = min value Limit = max value
If you don't want random range, then Base = value Limit = 0, or set Limit to same as Base value
Added a standard function to do all the random effectiveness calculations in source.
#USE THIS INSTEAD OF PR 1483
=>  [Spells] Update to SPA 130 and SPA 131 focus calculation, focus code improvements (version2)

common/spdat.h, zone/attack.cpp
SPIndex fix for mislabeled spell
All other SPIndex consts were checked again without any additional errors found.
=> [Spells] SPIndex fix for wrong const in variable

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/common.h, zone/mob.cpp, zone/mob.h, zone/spell_effects.cpp
Implemented
SE_Melee_Damage_Position_Amt	504  - Modify melee damage by flat amount if done from Front or Behind opponent, base: amt, limit: 0=back 1=front, max: none
SE_Damage_Taken_Position_Amt	506  - Modify melee damage by flat amount if dmg taken from your Front or Behind, base: amt, limit: 0=back 1=front, max: none
=> [Spells] Implemented SPA 504 and 506

common/spdat.h, zone/bonuses.cpp, zone/client_mods.cpp, zone/common.h, zone/spell_effects.cpp
Implemented
SE_Worn_Endurance_Regen_Cap	489
modify worn item regen cap
base: amt, limit: none, max: none
Also added support to allow item mana regen cap to check item and spell bonuses.
=> [Spells] Implemented SPA 489 SE_Worn_Endurance_Regen_Cap

common/spdat.h, zone/bonuses.cpp, zone/common.h, zone/spell_effects.cpp
Implemented
SPA 390 SE_FcTimerLockout
This focus limited effect sets any spell in the spell bar that meets the criteria of the of the focus limits to be a on recast timer.
Base value: recast duration in milliseconds.
Example spell: Suppression of Fire ID 16973.
Sets any fire spell in the clients spell bar to a 2 second recast when the client is affect by the spell.
Note: This focus can only be applied from spells (not item or AA)
Note: Although reinforced by the server, to appear visually correct both server side and client side spell values need to match (ie. need to matching database and spells_us.txt values).
=> [Spells] Implemented SPA 390 SE_FcTimerLockout

common/net/servertalk_client_connection.cpp, common/net/servertalk_client_connection.h, common/net/servertalk_common.h, common/net/servertalk_server.cpp, common/net/servertalk_server.h, common/net/servertalk_server_connection.cpp, common/net/servertalk_server_connection.h
Remove server talk security code for the following reasons:
- Security code actually slows down the servertalk connections quite a bit.
- Most the data going across these connections isn't ***that*** sensitive and usually they're talking to servers that are on the same machine.
- It isn't a standardized security method and lacks basic things like mitm attack protection and forward secrecy limiting its usefulness anyway in an environment that warrants it.
- Because it's not standardized it makes writing a server in another language hard (not a real benefit but perhaps one day someone will and was a problem I ran into in the past with the webinterface stuff)
- TLS exists and if we feel we need security on these we should look at implementing that on the underlying server connection.
=> [Netcode] Remove security from servertalk connections

common/ruletypes.h, world/main.cpp
Also work peeled from #1451 
This enables world GM say logging and relays all messages to all zoneservers.
This was especially helpful during Shared Tasks work where we need / want to see real live communication of packets being sent back and forth between world and zone
**Example**
This also adds the following rule which is enabled by default
```
RULE_BOOL(Logging, WorldGMSayLogging, true, "Relay worldserver logging to zone processes via GM say output")
```
Of course operators will need to be mindful of not turning on excessive logging but should be fine performance wise under normal conditions
=> [Logging] Implement World GMSay Logging

common/net/servertalk_client_connection.cpp, common/net/servertalk_server_connection.cpp
We have several packets throughout the code base that are server to server that are zero size to simply send messages which stopped working with #1464 
PR #1464 removed some of this functionality in the sense that encrypted connections padded zero length packets
This restores the padding for unencrypted packets
=> [Networking] Pad Zero Size Server to Server Packets

loginserver/world_server.cpp, world/login_server.cpp, world/zonelist.cpp, zone/worldserver.cpp
This is carry over from Shared Tasks work in #1451 
This brings down inter-process keep alive pings to 1 second (1000ms); this results in faster disconnects and reconnects and the overhead is very minimal
=> [Server] Tweak inter-process keepalive timers

common/spdat.h, zone/bonuses.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/common.h, zone/spell_effects.cpp
Suspend Minion and related effects were still hardcoded using old AA system.
No actual change in functionality besides that is now more flexible and can be applied like any other spell/bonus, therefore can
give any class at any level these abilities if desired.
SPA 151 SuspendPet updated to use actual spell values from spells_new table.
```
/*
SPA 151 Allows an extra pet to be saved and resummoned later.
Casting with a pet but without a suspended pet will suspend the pet
Casting without a pet and with a suspended pet will unsuspend the pet
effect value 0 = save pet with no buffs or equipment
effect value 1 = save pet with buffs and equipment
effect value 2 = unknown
Note: SPA 308 allows for suspended pets to be resummoned after zoning.
*/
```
Renamed SPA 308 SE_SuspendedMinion to …
=> [Spells] Updated pet suspend code to use spell effect data and bonuses

common/shareddb.cpp
- Shared bank charges were being set to int8 on select, meaning any item that stacks over 127 would break if put in shared bank, causing loss of items.
=> [Bug Fix] Shared Bank Charges Fix

zone/corpse.cpp, zone/corpse.h, zone/lua_corpse.cpp, zone/lua_corpse.h, zone/lua_npc.cpp, zone/lua_npc.h, zone/npc.cpp, zone/npc.h, zone/perl_npc.cpp, zone/perl_player_corpse.cpp
- Add $npc->HasItem(item_id) to Perl.
- Add $npc->CountItem(item_id) to Perl.
- Add $npc->GetItemIDBySlot(loot_slot) to Perl.
- Add $npc->GetFirstSlotByItemID(item_id) to Perl.
- Add $corpse->HasItem(item_id) to Perl.
- Add $corpse->CountItem(item_id) to Perl.
- Add $corpse->GetItemIDBySlot(loot_slot) to Perl.
- Add $corpse->GetFirstSlotByItemID(item_id) to Perl.
- Add npc:HasItem(item_id) to Lua.
- Add npc:CountItem(item_id) to Lua.
- Add npc:GetItemIDBySlot(loot_slot) to Lua.
- Add npc:GetFirstSlotByItemID(item_id) to Lua.
- Add corpse:HasItem(item_id) to Lua.
- Add corpse:CountItem(item_id) to Lua.
- Add corpse:GetItemIDBySlot(loot_slot) to Lua.
- Add corpse:GetFirstSlotByItemID(item_id) to Lua.
These methods will allow server operators to view the loot a current has in a slot, the …
=> [Quest API] Adds new methods to NPCs and Corpses.

zone/bonuses.cpp, zone/client.cpp, zone/common.h
Allow SE_SecondaryForte 248 to be calculated as a bonus instead of hardcoded AA
This affect allows you to have a secondary specialization that goes above the cap.
No change in functionality.
=> [Spells] Allow SE_SecondaryForte 248 to be calculated as a bonus instead of hardcoded AA

common/spdat.h, zone/bonuses.cpp, zone/mob.h
Updated SE_NegateSpellEffect SPA 382 to now use the base1 value which allows you to limit specific types of bonuses for a spell effect type (ie AA, Item or from Spell buffs).
Base 1 values allowed
NEGATE_SPA_ALL_BONUSES                               = 0,
NEGATE_SPA_SPELLBONUS                                  = 1,
NEGATE_SPA_ITEMBONUS                                   = 2,
NEGATE_SPA_SPELLBONUS_AND_ITEMBONUS   = 3,
NEGATE_SPA_AABONUS                                     = 4,
NEGATE_SPA_SPELLBONUS_AND_AABONUS     = 5,
NEGATE_SPA_ITEMBONUS_AND_AABONUS      = 6,
Reminder: This spell effect allows you to completely negate any benefits from a specific spell effect.
Base: Bonus type
Limit: Spell Effect id
Example: Add this to a spell debuff where, Base = 4 and Limit: 3 (SE_MovementSpeed)
The …
=> [Spells] Updated SE_NegateSpellEffect SPA 382, new functionality

common/ruletypes.h, zone/client_mods.cpp, zone/mob.cpp
=> [Mods] Added Hastev3Cap

zone/aggro.cpp
Just about everyone has seen the "mob is too far away" while chasing fleeing mobs.  Perhaps more so on servers that use a higher percentage for flee ratio.  Upon looking at this, the client updates for client position come in too slowly to accurately compare against a mobs location when fleeing, the earlier a mob flees (and thus the faster the mob is running).
This has been a gripe of melee players for years on my server, and myself.
This patch is a hack, but I don't see a reasonable, or realistic way to fix it any better.  This come from trial and error and looking at the difference in distances that the math is showing, vs. what I see on the screen while chasing.
It dramatically reduces the frustration and looks far more realistic.  Far fewer "you are too far away" despite being right …
=> Hack to fix melee chasing fleeing mobs "too far" issues.

zone/zone.cpp
There is currently a bug when you buy (1) item like a_giant_snake_fang from a vendor that has say, 10 of these.  The 1st one you buy works.  But when you go to buy a second, the server spits a "display purposes only" message and you end up having to log off.
Test case.  Find a vendor with more than 1 of a non-stackable item.  Buy one.  Attempt to buy another one.  This crashes if you are more recent than about 4 months ago.
This is because the code changed in the PR does not retain the item in the merchant list.
I talked this over with @dencelle.  These changes were made as part of a scheme to preserve item charges, not # of items on the merchants.  He has told me he plans to revisit that and make it more comprehensive.
That said, the below only has to do with the merchantlist_temp and …
=> Fix bug where stacks of non-stackable items are removed when you buy 1.

common/CMakeLists.txt, common/database.cpp, common/database.h, common/eqemu_logsys.cpp, common/eqemu_logsys.h, common/eqemu_logsys_log_aliases.h, common/http/uri.h, common/repositories/base/base_tool_game_objects_repository.h, common/repositories/tool_game_objects_repository.h, utils/scripts/generators/repository-generator.pl, zone/CMakeLists.txt, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/command.cpp, zone/command.h, zone/doors.cpp, zone/doors.h, zone/gm_commands/door_manipulation.cpp, zone/gm_commands/door_manipulation.h, zone/npc.cpp, zone/npc.h
This PR ports Perl plugin from https://docs.eqemu.io/quest-api/perl/plugins/doors-manipluation to native GM command #door 
This plugin has been used widely by lots of folks over the years. Parts of the plugin have gone stale and it has deserved a port into the source with some improvements and zero-touch installation
Props to @Kinglykrab for the coordinate saylink menus as he was backseat driving during the stream porting this plugin over <3 
**Notes**
* Functionality is 1:1 - no net new commands
* Helper NPC's are created "on-the-fly" and no longer require fixed `npc_type` data as did the original plugin
* Uses data from table `tool_game_objects` sourced from https://github.com/EQEmu/database-tool-sqls
* First invocation of the GM command automatically fetches the table data from the …
=> [GM Command] Door Manipulation Command Port

common/ruletypes.h, common/say_link.cpp, common/say_link.h, zone/embparser_api.cpp, zone/entity.cpp, zone/lua_mob.cpp, zone/mob.cpp, zone/perl_mob.cpp
This PR adds the ability to automatically inject saylinks into "say" dialogue and client messages that are only invoked through the Quest API
If there is a saylink that already exists in the message, the injector will leave it alone
The reason we don't inject saylinks at the edge (Inside Client::Message) because we would end up with logs and a ton of other message related things with saylinks that have no need to be and adds quite a bit of overhead adding extra saylinks and extra overhead generating them in the process
**Two New Rules**
```cpp
RULE_BOOL(Chat, AutoInjectSaylinksToSay, true, "Automatically injects saylinks into dialogue that has [brackets in them]")
RULE_BOOL(Chat, AutoInjectSaylinksToClientMessage, true, "Automatically injects saylinks into dialogue that has [brackets in …
```
=> [Saylinks] Implement Auto Saylink Injection

zone/bot_command.cpp
Currently bot pets will taunt and there's no way to turn it off. This makes it so pets follow their owner's taunt settings.
=> [Bots] Fix for Bot Pets Taunting

zone/corpse.cpp, zone/corpse.h, zone/lua_corpse.cpp, zone/lua_corpse.h, zone/lua_npc.cpp, zone/lua_npc.h, zone/lua_parser.cpp, zone/npc.cpp, zone/npc.h, zone/perl_npc.cpp, zone/perl_player_corpse.cpp
- Add $corpse->GetLootList() to Perl.
- Add $npc->GetLootList() to Perl.
- Add corpse:GetLootList() to Lua.
- Add npc:GetLootList() to Lua.
Returns an array of item IDs for use with corpse and NPC methods such as HasItem(item_id), CountItem(item_id), and GetFirstSlotByItemID(item_id).
=> [Quest API] Add corpse->GetLootList() and npc->GetLootList() to Perl and Lua.

zone/client_packet.cpp, zone/embparser.cpp, zone/event_codes.h, zone/lua_general.cpp, zone/lua_parser.cpp, zone/lua_parser_events.cpp, zone/lua_parser_events.h
- Exports $corpse_entity_id in Perl.
- Exports e.corpse_entity_id in Lua.
Allows you to perform events on corpse consider for server operators.
=> [Quest API] Add EVENT_CONSIDER_CORPSE to Perl and Lua.

zone/mob.cpp, zone/spell_effects.cpp
Spells will now properly understand their expected gender, texture, and size.
Logic is based on what I saw in a stock PEQ database, can be adjusted if need be.
Any feedback is helpful.
=> [Bug Fix] Resolves issues with improper genders and textures on spells.

common/ruletypes.h, zone/command.cpp, zone/command.h
Adds dye command for going beyond darkness limits that client has when using the Dye UI Window.
#dye help
#dye [slot] [red] [green] [blue]
Dyes the armor at the specified slot to the Red, Green, and Blue values specified.
There is a rule that is disabled by default that makes the command require Vials of Prismatic Dye for use for servers interested in providing this command to players.
=> [Commands] Adds #dye command.

zone/bonuses.cpp
Small fix that will now allow for this spell effect also correctly apply to spells that have a negative effect of Decreasing your Offhand Damage shield mitigation. Ie. causing you to take more damage than normal. (There are a few spells on live that do this).
=> [Spells] Minor fix SPA 305 SE_MitigateDamageShield

zone/bonuses.cpp, zone/common.h, zone/spell_effects.cpp, zone/spells.cpp
This is the effect on the Kunark Cleric Breastplates that had a clicky complete heal.
Once the CH is applied it also applied a buff that prevented any additional clicky CH from a BP from healing that target again
until the buffed faded.
From my testing it didn't even seem like the buff was blocking anything, further even if it was working the way it was coded caused the buff duration to be refreshed if it would block it. Regardless, this fixes the issue completely and now if you have the CH blocking buff on you, it just blocks any new incoming CH's correctly
=> [Spells] Fix for  SE_CompleteHeal SPA 101 buff blocker

zone/client_process.cpp
/quit and /exit will now properly parse to EVENT_DISCONNECT so operators can do things on disconnect to these players, previously it only functioned for /camp.
=> [Bug Fix] Fixes EVENT_DISCONNECT for /quit and /exit.

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/client_process.cpp, zone/common.h, zone/lua_stat_bonuses.cpp, zone/mob.cpp, zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
These effects trigger a spell when specific requirement is met, these requirements mimic values used the Caster and Target requirement  field from spell table. Updated these effects to utilize all the same code pathways. Overall this just now allows you to use all the possible options in the SpellRestriction enum from spdat.h. 
Note, to trigger this effect you need to use SpellRestrictions that affect HP, Mana, Endurance or Pet count. 
Ie. Trigger Completel heal if HP < 50% ... Where your base would be spell ID 13 and limit value would be 510 (SpellRestriction ID)
```
#define SE_TriggerOnReqTarget			442 // implemented, @SpellTrigger, triggers a spell when Target Requirement conditions are met (see enum SpellRestriction for IDs), base: spellid, limit: SpellRestriction ID, max: none, Note: …
```
=> [Spells] Update to SPA 442 and 443 (SE_TriggerOnReqTarget, SE_TriggerOnReqCaster)

zone/client.h, zone/client_packet.cpp, zone/dialogue_window.cpp
- Syntax is button_one:button_one_name and button_two:button_two_name, similar to wintype and popupid.
- Add support for negativeid, syntax is negativeid:id. 
- Also changes "mysterious" identifier to "{mysterious}".
- Both button names are required for anything to show up, otherwise it defaults to Yes/No similar to Client::SendFullPopup.
Example:
```pl
if ($text=~/Hail/i) {
$client->DialogueWindow("Testing! {mysterious} wintype:1 button_one:Update button_two:Close");
}
}
```
=> [Dialogue] Add support for Dialogue Window buttons.

common/races.cpp, common/races.h, zone/command.cpp, zone/questmgr.cpp
- Added missing columns like untargetable, show_name, exp_mod, etc.
- Put stats in order of column appearance in table within help message and within code.
- Converted StringFormat to fmt::format.
- Added a GetGenderName() helper method.
- Prettified response messages of nearly every #npcedit option.
All tested and ready to go.
Would like input about possibly changing some of the command arguments to match the table column names more closely, example being "spell" should be "npc_spells_id".
=> [Commands] Overhauled #npcedit.

zone/spell_effects.cpp
This issue was introduced by:
[Bug Fix] Fixed Invis vs Undead / Invis Vs Animals not breaking charm + Added rule for custom capabilities #1374
if you look at the code: https://github.com/EQEmu/Server/pull/1374/files I think you'll see that the two lines added to spell_effects.cpp are not needed for this PR and actually break the feature of one char casting invis and IVU *in that order* on a group member.
I don't think SetInvisible(0) is needed in the two spots it was added.
Do you agree @splose?
Tested and fixes my issue, and I don't see how it breaks the original PR intent.
=> [Bug Fix] Fix bug where IVU could not be cast on char with Invis

common/spdat.cpp
- GetSpellStat() converts identifiers to lowercase and they were being checked against mixed case strings, causing certain identifiers to always fail.
=> [Bug Fix] GetSpellStat() Identifiers were comparing improperly.

zone/zone.cpp
The changes about a month back to the world/zone connection sequence moved the call from world to OnConnect in the timing sequence. 
https://github.com/EQEmu/Server/commit/1c8231eb9ef2093613ab7791a991e9d0b089ea97
Specifically calling OnConnect before the flag gets cleared.
Current code:
World calls zone::Bootup()
zone::Bootup calls Zone::GetTimeSync
Zone::GetTimeSync won't request TimeSync unless worldserver.Connected() is true.
World calls zone::OnConnect()
On Connect() calls Zone::GetTimeSync
Zone::GetTimeSync won't request TimeSync unless worldserver.Connected() is true.
World sets m_connecting = false - But now GetTimeSync is no longer called.
After this PR:
- removed call to Zone::GetTimeSync in zone:Bootup as it will fail anyway (worldserver.Connected() is false)
- No longer check …
=> [Bug Fix] Zones no longer syncing time to world

common/spdat.h, zone/mob.h, zone/spell_effects.cpp
Memory blur spell effect should be calculated as below. I personally checked on live to confirm this is accurate. These changes will allow memory blur chances to be significantly higher than how we have them now, which for most effects makes almost useless at 1% to 10% chances.
Memory Blur mechanic for SPA 62
Chance formula is effect chance + charisma modifier + caster level modifier
Effect chance is base value of spell
Charisma modifier is CHA/10 = %, with MAX of 15% (thus 150 cha gives you max bonus)
Caster level modifier. +100% if caster < level 17 which scales down to 25% at > 53. **
(Yes the above gets worse as you level. Behavior was confirmed on live.)
Memory blur is applied to mez on initial cast using same formula. However, recasting on a target that
is already mezed will not …
=> [Spells] Updated Memory Blur SPA 63 - Implemented Live Mechanics

zone/spells.cpp
Fix for Spell Buff Max Hits not displaying when initially cast. This the little number in the left bottom corner of buffs that can be counted down if conditions are met. Example spell Mana Flare 8032.
Not entirely sure why this broke, but noticed it.
The update that sends the packet needs to occur at the first buff tick so it may be slightly delayed, not ideal but best I could do to make it work again.
=> [Spells] Fix for Spell Buff Max Hits not displaying when initially cast

common/spdat.h, zone/mob.h, zone/spell_effects.cpp
Found examples of this effect also being applied to non-duration effects, such Call of Hero or Dispel ect...
Expanded implementation to now apply to all non-duration effects as well.
Ie. If you use Call of the Hero SPA 82 on a player with a debuff with NegateSpellEfffect with limit set to 82, you will not be able to COH that player.
Few edge cases remaining. Can be seen Negating resurrection effects. This likely blocks the client from accepting a rez request if they have the debuff. Will look into more at a later time.
SE_NegateSpellEffect 382 Debuff, negates specific spell effect benefits for the duration of the debuff and prevent non-duration spell effect from working, base: see NegateSpellEffecttype Enum, limit: SPA id, max: none
=> [Spells] More updates for SPA 382 SE_NegateSpellEffect

zone/perl_entity.cpp
This causes the wrong name to show up on Spire.
=> [Quest API] Typo in Perl $entity_list->IsMobSpawnedByNpcTypeID().

common/ruletypes.h, zone/client_packet.cpp, zone/dialogue_window.cpp, zone/entity.cpp, zone/lua_mob.cpp, zone/mob.cpp, zone/perl_mob.cpp
For some reason there were some changes that got merged into this branch that didn't make it into master. Creating this PR to reconcile
Originally parts from #1526 that only got merged into another branch
This PR is a completely optional feature that server operators may like to use for a richer dialogue experience
It utilizes the Dialogue Window from https://docs.eqemu.io/quest-api/perl/plugins/diawind
It intercepts the default behavior for `quest::say` and pipes it to a popup dialogue window for richer interaction if server operators choose to do so
**Rules**
```
RULE_BOOL(Chat, QuestDialogueUsesDialogueWindow, false, "Pipes all quest dialogue to dialogue window")
RULE_BOOL(Chat, DialogueWindowAnimatesNPCsIfNoneSet, true, "If there is no animation specified in the dialogue window …
```
=> [Dialogue Window / Saylinks] Missing Changes

zone/task_client_state.cpp
Shared tasks start replay timers based on accept time but solo tasks
should start from completion time. Solo tasks on live that have a
non-unlimited duration may require further investigation
=> [Shared Tasks] Start solo task replay timers from completion time

zone/dialogue_window.cpp
- Syntax is `title:popup_title`
- Custom title allows defaults to be overridden where necessary, like a leaderboard or something.
- Default target to client in case people want to send Dialogue Windows from current client.
- Fix possible issue with markdown.
- Example: Using the word "title" or using any identifier and forgetting the colon.
=> [Dialogue] Add support for Dialogue Window titles.

zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
Alternative apis using arrays of hash items for EQEmu/Server#1575
Perl usage:
```perl
my @bag_items = (
{ item_id => 1001, charges => 1 },
{ item_id => 1002, charges => 1 },
{ item_id => 10037, charges => 10 },
);
$client->SummonBaggedItems(17403, \@bag_items);
```
```perl
my $bag_items = [
{ item_id => 1001, charges => 1 },
{ item_id => 1002, charges => 1 },
{ item_id => 10037, charges => 10 },
];
$client->SummonBaggedItems(17403, $bag_items);
```
Lua Usage:
```lua
local bag_items = {
{ item_id = 1001, charges = 1 },
{ item_id = 1002, charges = 1 },
{ item_id = 10037, charges = 10 }
}
e.other:SummonBaggedItems(17403, bag_items);
```
=> [Quest API] Add client->SummonBaggedItems(bag_item_id, bag_items_ref) to Perl/Lua.

zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
- Add $client->ReadBookByName(book_name, book_type) to Perl.
- Add client:ReadBookByName(book_name, book_type) to Lua.
- Allows server operators to put books in to their database and read from their database instead of storing the values in a script, also allows them to read pre-existing books using a script.
=> [Quest API] Add client->ReadBookByName(book_name, book_type) to Perl/Lua.

common/database.cpp, common/database.h, zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
- Add $client->GetIPExemption() to Perl.
- Add $client->GetIPString() to Perl.
- Add $client->SetIPExemption(exemption_amount) to Perl.
- Add client:GetIPExemption() to Lua.
- Add client:GetIPString() to Lua.
- Add client:SetIPExemption(exemption_amount) to Lua.
Will make plugin::IP unnecessary and allow people to get readable IP string easier, as well as set/get IP exemptions from Perl and Lua.
=> [Quest API] Add GetIPExemption(), GetIPString(), and SetIPExemption(exemption_amount) to Perl/Lua.

zone/client.cpp, zone/lua_client.cpp, zone/perl_client.cpp
Allows operators to spawn bagged items that are already attuned and/or have augments in them.
Perl Example:
```pl
my @bag_items = (
{ item_id => 33649, charges => 1, attuned => 1, augment_one => 32940 },
);
```
Lua Example:
```lua
local bag_items = {
{ item_id = 33649, charges = 1, attuned = 1, augment_one = 32940 }
}
=> [Quest API] Add attuned/augment support to client->SummonBaggedItems() in Perl/Lua.

zone/dialogue_window.cpp
{name} was being replaced with the string "$name" because Perl would parse it properly, but when used here it doesn't return the client's name.
=> [Bug Fix] Dialogue Window Name replace.

zone/dialogue_window.cpp
Allows operators to hide responses.
Syntax is `hiddenresponse`.
=> [Dialogue] Add hidden response support.

zone/doors.h
The include order here was causing a compile error when building with
perl 5.12 due to a bad interaction with the older fmt submodule version
being used
This should fix the Win32 CI build which is built with perl 5.12
=> [Bug Fix] Remove unnecessary includes

common/inventory_profile.cpp, zone/client_packet.cpp
A few spelling corrections.
A few variables that were not used.
=> [Bug Fix] Minor corrections

zone/spells.cpp
Fix the Z in relation to model and size when we send resurrection coordinates to the player during confirmation
=> [Rez] Fix Z during Resurrection

zone/entity.cpp, zone/mob.cpp, zone/spell_effects.cpp
Bug fix for clients losing target server side when charming
Reported: https://github.com/EQEmu/Server/issues/1652
Bug fix for failed charms due to things like already having a pet causing NPC to have hate list wiped and lose aggro.
Likely need to be checking fail check else where, but for now just moved the check to avoid this issue.
=> [BugFix] Charm Targeting and other issues.

common/say_link.cpp, common/say_link.h, zone/main.cpp
We've been using saylinks forever. Every single time a saylink appears in a message its a database hit. This adds up substantially especially with heavy saylink usage and even more with automatic saylink injection.
This change keeps a static global bucket to store cached saylinks and loads them on zone bootup. This works fine for now; I'd like to see this get centralized to an instance and store it there rather than using a global but the saylink class is almost purely static right now
* When a saylink is not in the database, its stored in the database and cached
* When a saylink is in the database but not in the cache, its fetched from the database and then cached in the zone (Think a saylink was created in another zone)
* When zone boots, saylinks are cached into memory from the …
=> [Saylinks] In-Memory Saylink Lookups

zone/client_packet.cpp
This logic should be gated behind a rule for servers who have task system disabled
=> [Hotfix] Gate some new shared task logic behind task rule

common/eqemu_config.cpp, common/string_util.cpp, common/string_util.h, loginserver/account_management.cpp, loginserver/account_management.h, loginserver/client.cpp, loginserver/client.h, loginserver/client_manager.cpp, loginserver/client_manager.h, loginserver/database.cpp, loginserver/database.h, loginserver/encryption.h, loginserver/eq_crypto_api.h, loginserver/login_server.h, loginserver/login_structures.h, loginserver/loginserver_command_handler.cpp, loginserver/loginserver_command_handler.h, loginserver/loginserver_webserver.cpp, loginserver/loginserver_webserver.h, loginserver/main.cpp, loginserver/options.h, loginserver/server_manager.cpp, loginserver/server_manager.h, loginserver/world_server.cpp, loginserver/world_server.h, world/login_server.cpp, world/login_server.h
**Changes**
* [Code Cleanup] Change member variables to be `m_` prefixed
* [Code Cleanup] Remove licensing information from loginserver related files
* Add human readable addresses to client login log statements
* Sanitize world server names so only a specific allowed set of characters can show up in the server list
* Force legacy mode for `login.eqemulator.net` to avoid user mistakes
* Add more logging information for World when Loginserver::SendInfo is triggered
* Set a remote address for World if it is not sent to the Loginserver based on a non-empty local address field
* Key worldserver lookups by both long name and short name instead of just short name. Probably move this to closer to memory lookups later
* Move validation constants
* Set servers to be authorized in all unregistered …
=> [Loginserver] Code Cleanup and Tweaks

loginserver/account_management.cpp, loginserver/account_management.h, loginserver/client.cpp, loginserver/client.h, loginserver/loginserver_command_handler.cpp, loginserver/loginserver_command_handler.h, loginserver/loginserver_webserver.cpp, loginserver/main.cpp
This implements an internal health check system where a fake system user logs into the Loginserver a returns the login response code. 
In this test everything is in memory and returns response code 105 (Failed login) which informs the health check that the Loginserver is up and is responding to requests. 
It simulates a game client and requesting login.
Added endpoint `/probes/healthcheck` which simply returns the status. When this returns a 0 status; the loginserver process will then exit and allow its process manager to revive it
```curl
curl -s loginserver:6000/probes/healthcheck | jq
{
"status": 105
}
```
Added some other resiliency checks to prevent hangs. This code is running on **login.projecteq.net** now
=> [Loginserver] Health Checks

zone/client.cpp, zone/client.h, zone/command.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/questmgr.cpp, zone/spells.cpp
- Add $client->GetFreeDisciplineSlot(starting_slot) to Perl.
- Add $client->ScribeSpells(min_level, max_level) to Perl.
- Add $client->LearnDisciplines(min_level, max_level) to Perl.
- Add client:GetNextAvailableDisciplineSlot(starting_slot) to Lua.
- Add client:ScribeSpells(min_level, max_level) to Lua.
- Add client:LearnDisciplines(min_level, max_level) to Lua.
- Convert quest::scribespells() and quest::traindisc() to use new ScribeSpells and LearnDisciplines methods for consistency.
- Convert #scribespells and #traindisc to use new ScribeSpells and LearnDisciplines methods for consistency.
=> [Quest API] Simplify bulk Scribe and Train logic.

zone/spell_effects.cpp
Bug fix for clients losing target server side when charming
Reported: #1652
Original fix last week was causing a ton of crashes and had to be reverted. Targeting issue arises from function  entity_list.RemoveFromTargets(this) which we were calling to remove the charmed NPC from other npc hatelists, which also had side effect messing with client targeting. While I did make a safe fix for that. Ultimately, I realized it was irrelevant because what we should be using is the function entity_list.RemoveFromHateLists(this). Achieves the goal without the targeting side effects.
=> [BugFix] Charm Targeting Fix

zone/spell_effects.cpp
Fixed issue with it unintentionally negating instant healing effects.
When checking from instant effects will now also make sure the base1 limiter is applied.
=> [Spells] Update and fix for SPA382 SE_NegateEffect

zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
When casting charm the check for if charm could be applied for specific target restriction was not being done at the correct location in the code. This was causing issues due to having to remove the buff after it was applied if target checks failed.
As verified on live,  it should be checking restrictions as soon as you start casting and then it quickly cancels the cast.
Also, updated the fail messages to reflect live messages.
*This does not solve the other charm bug involving targeting.
=> [Spells] Update to Charm target restriction code

zone/client_packet.cpp, zone/spells.cpp
SOF+ client's were not checking Item Click Recast timers until after the click spell had completed casting. It should be checked upon initial click and not start casting if the recast timer is active. Titanium does this by default with no code checks needed., though we enforce it server side at end of cast for Titanium. Keeping the end of cast check for both, Titanium doesn't play as nice when I tried to move it up to be done on click.
=> [Bug Fix] SOF+ clients item click recast timer not met check

common/spdat.cpp, common/spdat.h, zone/spell_effects.cpp, zone/spells.cpp
Implemented SPA 415 SE_FFItemClass **Limits focuses to check if cast from item clicks. Can be used to INCLUDE or EXCLUDE items by ItemType and/or SubType and/or Slots**
This is a very powerful effect that can have a lot of creative uses. Most simply, if you don't want a specific focus effect being applied to items you can add this to it. But, interestingly if you want a focus effect that say ONLY applies to Shield slot click effect, or weapon slot click effects. For example you have a Custom warrior Breastplate with a click effect that gives 90 pct damage mitigation for 3 tics. You can make a custom focus on another item that extends ONLY that breastplates click focus to last 6 tics, by setting the SubType on your item to say the Item ID, and then setting focus limit to that same Item ID …
=> [Spells]  Implemented SPA 415 SE_FFItemClass

common/skills.cpp, common/skills.h, zone/command.cpp, zone/npc.cpp, zone/npc.h, zone/questmgr.cpp, zone/zonedb.cpp, zone/zonedb.h
- Cleanup menu and add stats that were not there before.
- Only display some data if necessary (i.e only show loot/money if they have loot/money)
- Add skill name helper method.
- Add faction name helper method.
- Add Charmed stats and other getter methods.
- Cleanup npc->QueryLoot() method.
=> [Commands] Cleanup #npcstats Command.

zone/command.cpp
- Add #worldwide remove [Spell ID] - Removes a spell from player buffs worldwide.
- Add #worldwide message [Message] - Sends a worldwide message in Chat::Yellow.
- Add #worldwide move [Zone ID] or #worldwide move [Zone Short Name] - Moves every player in the game to the specified zone.
- Add #worldwide moveinstance [Instance ID] - Moves every player in the game to the specified instance.
- All but `#worldwide message` send a message to sender client.
=> [Commands] Further implement #worldwide functionality.

common/ruletypes.h, zone/bot.cpp, zone/client_process.cpp
- Add RULE_BOOL(Character, UseResurrectionSickness, true, "Use Resurrection Sickness based on Resurrection spell cast, set to false to disable Resurrection Sickness.")
- Add RULE_INT(Character, OldResurrectionSicknessSpellID, 757, "757 is Default Old Resurrection Sickness Spell ID")
- Add RULE_INT(Character, ResurrectionSicknessSpellID, 756, "756 is Default Resurrection Sickness Spell ID")
- Add RULE_BOOL(Bots, OldRaceRezEffects, false, "Older clients had ID 757 for races with high starting STR, but it doesn't seem used anymore")
- Add RULE_BOOL(Bots, ResurrectionSickness, true, "Use Resurrection Sickness based on Resurrection spell cast, set to false to disable Resurrection Sickness.")
- Add RULE_INT(Bots, OldResurrectionSicknessSpell, 757, "757 is Default Old Resurrection Sickness …
=> [Rules] Add Resurrection Sickness rules for Characters/Bots.

zone/command.cpp, zone/mob_ai.cpp
- Cleanup messages and display.
- Only shows time can cast, resist adjust, and min/max health if that's used.
=> [Commands] Cleanup #showspellslist Command.

zone/attack.cpp, zone/mob.cpp, zone/mob.h
Resolves an issue where if you start auto attacking with two weapons with the same delay the offhand animation will never fire due to the throttle timer, the primary would always go first. This solution checks when the timers are set if both attack and dw timers are the same, if so it will ensure an equal chance of primary and secondary animations.
=> [Bug Fix] Fix for dual wield animation when same delay weapons.

zone/effects.cpp
As far as I can tell on live, damage over time critical hits do not apply to beneficial DOT effects like necromancer Lich spell line.
=> [Bug Fix] Prevent critical DOTs from affecting beneficial damage over time

zone/attack.cpp
Ranged procs were receiving a 50 pct reduction in proc rate chance due to what I think was an oversite when ranged procs were implemented. It was getting the reduction meant for offhand attacks which checked for anything that wasn't primary slot, which is probably how the code was before the ranged procs went in.
I took the time to parse this on live and found no significant difference between primary hand melee spell proc rate and ranged spell proc rate. Thus confident this is correct.
Conclusion: Ranged Procs should proc 2x as often now.
=> [Spells] Fixed proc rate for Ranged procs

loginserver/client.cpp, loginserver/client.h, loginserver/login_structures.h, loginserver/server_manager.cpp, loginserver/server_manager.h, loginserver/world_server.cpp, loginserver/world_server.h
=> [Loginserver] Identify unknown login client packet fields

zone/command.h
=> [Commands] Remove #testspawn and #testspawnkill Commands.

zone/command.cpp, zone/mob.cpp
- Create a temporary NPC to use ShowStats() instead.
- Cleanup message.
- Cleanup spawn/emote/textures logic in ShowStats() when unused.
=> [Commands] Cleanup #viewnpctype Command.

zone/spells.cpp
Defensive procs and all AA procs added to IsCombatProc check to allow them to be exclude from focusing.
Forgot to add the new AA procs when recently implemented.
=> [Spells] Update to IsCombatProc checks

loginserver/login_util/login_schema.sql
Since m_remote_ip_address does not resolve IP address, world server may still use host name.
=> [Bug Fix] Make room for host names.

common/emu_constants.h, world/world_store.cpp, world/world_store.h, world/zonelist.cpp, world/zoneserver.cpp, world/zoneserver.h, zone/command.cpp
- Add support for Zone IDs.
- Cleanup messages and display.
- Fix dangling pointer in ZoneLongName() helper method so name is displayed properly.
=> [Commands] Cleanup #zonelock Command.

zone/mob.cpp
Adjusted calculation in MeleeLifeTap function to prevent the multiplier from overflowing and causing damage instead of healing when numbers go to high.
=> [Bug Fix] Melee Life tap overflowing and causing damage

zone/special_attacks.cpp
Frenzy is supposed to use 1HS/1HB animation not 2H.
=> [Bug Fix] Frenzy Animation

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp
Added support to SPA 161 and SPA 450 to provide spell or dot shielding respectively, when put on as an Item worn effect or as AA's. There was no easy way to provide percentage spell or dot mitigation via AA's so this solves that problem in a straightforward way. This will stack with item mod2 spellshielding or dotshielding.
SE_MitigateSpellDamage 161	// implemented, Runes, mitigate incoming spell damage by percentage until rune fades, base: percent mitigation, limit: max dmg absorbed per hit, max: rune amt, Note: If placed on item or AA, will provide stackable percent mitigation.
SE_MitigateDotDamage	450 // implemented, Runes, mitigate incoming dot damage by percentage until rune fades, base: percent mitigation, limit: max dmg absorbed per hit, max: rune amt, Note: If placed on item or …
=> [Spells] Support for SPA 161 and 450 to give  percent spell or dot mitigation from Items or AA's.

zone/command.cpp, zone/gm_commands/nukebuffs.cpp, zone/mob.h, zone/spells.cpp
- #nukebuffs now allows you to nuke all, beneficial, or detrimental buffs, also added a help menu.
- Add BuffFadeBeneficial().
- Cleanup logic in some buff fade methods.
- Fix several spots where we were using CalcBonuses() when it was unnecessary, i.e when you fade no buffs you do not need to recalculate bonuses.
=> [Commands] Cleanup #nukebuffs Command.

zone/command.cpp, zone/gm_commands/zheader.cpp, zone/zone.cpp, zone/zone.h, zone/zonedb.cpp, zone/zonedb.h
- Add parameter to allow versions to be loaded.
- Cleanup parameter name in CFG methods from instance_id to instance_version.
=> [Commands] Cleanup #zheader Command.

zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
Usage: Mob::SpellEffect(THIS, uint32 effect, [uint32 duration = 5000], [uint32 finish_delay = 0], [bool zone_wide = false], [uint32 unk20 = 3000], [bool perm_effect = false], [Client* single_client]), [caster_id = 0], [target_id = 0]")
This function is used for affects like Nimbuses but it also has a large variety of spell casting graphics that are not self only. The way the function was coded it was always setting the target of the effect as the caster. So if you tried to use it to simulate say a "nuke" it would do the casting animation on the target and then spell landing animation. I added a way using optional parameters at the end to set the caster and target.
```
#put on an npc  and hail it
sub EVENT_SAY
{
$client->SpellEffect(68, 5000,0, 0, 3000, 0, $client, $client->GetID(), …
```
=> [API] mob->SpellEffect can now properly display spell effect that are used on a target.

zone/perl_mob.cpp
Update to recent PR https://github.com/EQEmu/Server/pull/1785
Usage: Mob::SpellEffect(THIS, uint32 effect, [uint32 duration = 5000], [uint32 finish_delay = 0], [bool zone_wide = false], [uint32 unk20 = 3000], [bool perm_effect = false], [Client* single_client]), [caster_id = 0], [target_id = 0]"); 
Needed to now allow perl to pass nullptr or 0 for [Client* single_client] parameter otherwise wouldn't work unless you set $client
to send to only a single client.
=> [API] mob->SpellEffect small perl fix

zone/client_mods.cpp
Confirmed on live that AA clicks that use song skills do not benefit from bard song modifiers.
Evident by using Quick Time and Fierce Eye AA, neither benefit from having a song modifier. While similar effects in regular songs do.
=> [Spells] Bard AA clicks should not receive song modifiers.

zone/spells.cpp
Resolves the issue with buff hit counters not displaying the counters instantly when buff is applied to client.
Hit counters are that little number on the buffs that tells you how many times something can happen till it fades.
=> [Bug Fix] Buff hit counter will now display instantly on cast.

common/spdat.cpp, common/spdat.h, zone/client_packet.cpp, zone/spells.cpp
Fixed issue where Bind Sight effects would not display the buff on your character when initially cast
Fixed issue where you could not click off the buff on your character (preventing you from restoring your own vision)
Fixed issue where the effect was hard coded to only two spells
SE_BindSight	73 see through the eyes of your target, click off buff to end effect, base: 1, limit: none, max: none
=> [Bug Fix] Bind Sight will now function properly 

zone/CMakeLists.txt, zone/command.cpp, zone/command.h, zone/gm_commands/npcstats.cpp, zone/gm_commands/petitems.cpp, zone/npc.cpp, zone/npc.h
- Add #petitems command to show a person's pet items if they have access to the command.
- Adds a default false parameter to QueryLoot for NPCs that keeps messages and logic from being ran on pets for no reason.
- Cleaned up message a bit for loot and stuff.
- Remove check for loottable ID when using #npcstats for NPCs that get items from a script or otherwise.
=> [Commands] Add #petitems Command.

zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
Credit to Natedog who figured out what extra parameters actually did!
SendAppearanceEffect  packet has 3 different parameters, with up to 5 different effects per packet 
parm1 = graphic animation
parm1slot (formerly parm1a) = location on body of the graphic animation
0 = pelvis1
1 = pelvis2
2 = helm
3 = Offhand
4 = Mainhand
5 = left foot
6 = right foot
9 = Face
parm1ground (formerly parm1b) = place graphic on the ground.  If this is set and and slot > 0, it will follow the mob and be removed upon zoning/death, if slot set to zero it will be perma set to be on ground in that location
Original Perl function Mob->SendAppearanceEffect has been expanded to accept slot and ground parameters
`Usage: Mob::SendAppearanceEffect(THIS, int32 param_1, [int32 param_2 = 0], [int32 param_3 = 0], [int32 …
=> [API] mob->AppearanceEffects improved functionality.

zone/command.cpp, zone/gm_commands/movechar.cpp
- Add support for Zone ID versus Zone Short Name.
- Add support for Character ID versus Character Name.
=> [Commands] Cleanup #movechar Command.

zone/CMakeLists.txt, zone/command.cpp, zone/command.h, zone/gm_commands/endurance.cpp, zone/gm_commands/setendurance.cpp
- Add #setendurance [Endurance] command to set an NPC or player's endurance to a specified amount, or to max if the amount is greater than their max.
- Cleanup #endurance command message and logic.
=> [Commands] Add #setendurance Command.

zone/entity.cpp
Players / npcs need this set otherwise trying to scale NPCs AGI / AC will cause them to depop
Also any NPC pets with items will despawn if this is not set here as well.
=> [Bug fix] SetPetID after we assign the new NPC an ID

common/spdat.h, zone/client.cpp, zone/client.h, zone/mob.cpp, zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
Special credit and thanks to Natedog for helping figure out how to reduce recast reduction with memorizespell_struct!
SPA 310 can now be used to reduced the recast timers on spells (previously only worked on discipline timers).
SE_ReduceReuseTimer	310 Focus Effect, On Caster, spell and disc reuse time mod by amount, base: milliseconds
Note: Use positive values for amount of reduction, IE. 10000 = 10 second reduction.
If you try and reduce lower than the spells recast timer, it will set the spell to be instant refresh.
Also, fixed a bug with Forceful Rejuvenation (resets recast timers) where spells with linked timers were not getting there recast timers reset server side.
=> [Spells] SPA 310 SE_ReduceReuseTimer	will now work on spell recast time

common/emu_constants.h, zone/client.cpp, zone/mob.cpp, zone/spell_effects.cpp
- Invisibility vs. Undead and Invisibility vs. Animals were not breaking charm.
- Add Invisibility enumerator.
- Add special identifier for Invisibility vs. Undead and Invisibility vs. Animals.
=> [Bug Fix] Charm Break Invisibility Fix.

zone/attack.cpp, zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.h, zone/spell_effects.cpp
Added support for modify incoming spell damage amount focus effects, SPA 296 and 483 to work on items and AA's.
These effects can be used to modify incoming spell damage by flat on a target with the buff containing the focus.
If you put it on an AA or an item you can cause your client to have an innate increase or decrease in spell damage taken by amount.
Example, your client gains an AA that makes them take 100 less damage from Fire Spells.
Positive value increases damage taken, negative value reduces damage taken by amount
These two foci do same thing and will stack with each other.
Also, removed some out dated uses of the spell that are no longer applicable.
SE_FcDamageAmtIncoming			297, Focus Effect,, On Target, damage taken flat amt, base: amt
SE_Fc_Spell_Damage_Amt_IncomingPC	484, …
=> [Spells] Update to mod incoming Spell Damage amount focus, SPA 297 and 484 to support focus from  AA and items.

zone/mob.cpp, zone/spells.cpp
Added support for spell vulnerability focus effects, SPA 296 and 483 to work on items and AA's.
These effects can be used to modify incoming spell damage by percent on a target.
If you put it on an AA or an item you can cause your client to have an innate increase or decrease in spell damage taken.
Example, your client gains an AA that makes them take 5% less damage from Fire Spells.
Positive value increases damage taken, negative value reduces damage taken by percent.
These two foci do same thing and will stack with each other.
SE_FcSpellVulnerability 296	     Focus Effect , On Target, spell damage taken mod pct, base: min pct, limit: max pct
SE_Fc_Spell_Damage_Pct_IncomingPC 483 Focus Effect On Target, spell damage taken mod pct, base: min pct, limit: max pct
=> [Spells] Update to Spell Vulnerability effects, SPA 296 and 483 item and AA support

zone/gm_commands/wpinfo.cpp, zone/lua_npc.cpp, zone/lua_npc.h, zone/npc.h, zone/perl_npc.cpp, zone/waypoints.cpp
- Only display grid/waypoints if NPC has a grid.
=> [Commands] Cleanup #wpinfo Command.

zone/CMakeLists.txt, zone/client.h, zone/command.cpp, zone/command.h, zone/gm_commands/unmemspell.cpp, zone/gm_commands/unmemspells.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/spells.cpp
- Add #unmemspell [Spell ID] command to unmemorize a spell by ID from you or your target.
- Add #unmemspells command to unmemorize all spells from you or your target.
- Cleanup #memspell command and change arguments from #memspell [Slot] [Spell ID] to #memspell [Spell ID] [Spell Gem] for easier use.
- Add #memspell [Spell ID] functionality to memorize to first open spell gem if there are any using FindEmptyMemSlot helper method.
- Rename client->FindMemmedSpellByID(spell_id) to FindMemmedSpellBySpellID(spell_id).
- Add client->FindEmptyMemSlot() helper method.
- Add $client->FindEmptyMemSlot() to Perl.
- Add client:FindEmptyMemSlot() to Lua.
- Add $client->FindMemmedSpellBySpellID(spell_id) to Perl.
- Add client:FindMemmedSpellBySpellID(spell_id) to Lua.
=> [Commands] Add #unmemspell and #unmemspells Commands.

zone/CMakeLists.txt, zone/client.cpp, zone/client_packet.cpp, zone/command.cpp, zone/command.h, zone/embparser_api.cpp, zone/gm_commands/setaltcurrency.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/zone.cpp, zone/zone.h
- Add #setaltcurrency [Currency ID] [Amount] command to allow you to set a specific alternate currency to a value.
- Add Zone::GetCurrencyID() and Zone::GetCurrencyItemID() helper methods.
- Cleanup loops through zone->AlternateCurrencies.
- Utilize helper methods where necessary.
- Convert old methods parameters and return values from int to uint32 where necessary.
=> [Commands] Add #setaltcurrency Command.

zone/client_packet.cpp, zone/spell_effects.cpp
Levitate spells that have a limit value are used for Flying mounts. If set it seems like it should be using Flymode 5 LevitateWhileRunning. Add support for that.
=> [Spells] Update to SPA 58 SE_Levitate to support limit value

zone/spell_effects.cpp
SPA 89 SE_ChangeSize is classically used to shrink or grow. Newer spells have the option to directly set model size using limit value, which is often seen on illusion spells. In these cases the base value is either 0 or 100 (which would not change model size normally). Of note, max value also likely does something but unknown at this time.
=> [Spells] Update to SPA 89 SE_ChangeSize to support directly limit value that sets model size

zone/bonuses.cpp, zone/common.h, zone/mob.h, zone/spell_effects.cpp, zone/spells.cpp
Update to SPA 238 SE_IllusionPersistence to allow at higher rank to persist through death. Newer AA's on live have this feature.
Baseline AA ability allows illusions to persist through zones. Set base value to 2 to gain persist through death attribute.
=> [Spells] Update SPA 238 SE_IllusionPersistence allow illusions to persist through deaths at higher AA ranks.

common/spdat.h, zone/client_process.cpp, zone/effects.cpp, zone/entity.h, zone/spell_effects.cpp
Updated the hard coded rampage range from 30 to 40 which is how live describes it in every spell.
This effect performs a single primary slot combat rounds on all creatures within a 40 foot radius. On live if you want more than one round of melee you need to use an additional effectid slot.
Added some additional functionality.
**base value** which is normally 1, can be set to do allow for additional combat rounds from same slot (ie set to 15 to do 15 melee swings)
**limit value** can set to limit the number of NPCs that can be hit by the AE (ie set to 5 to make it so no more than 5 different NPC can take damage)
**max value** can be set to override the 40 default range
`#define SE_Rampage						205	// implemented, @Combat Instant, Perform a primary slot combat rounds on all creatures within …
=> [Spells] Update to SPA 205 SE_Rampage

common/spdat.h, zone/bonuses.cpp, zone/client_packet.cpp, zone/common.h, zone/spell_effects.cpp
Implemented functionality to the rogue AA Trap Circumvention.
SE_TrapCircumvention	245
decreases the chance that you will set off a trap when opening a chest or other similar container by percentage, 
base: chance modifier
limit: none
max: none
=> [Spells] Implemented SPA 245 SE_TrapCircumvention 

zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/client_process.cpp, zone/inventory.cpp, zone/mob.cpp, zone/mob.h, zone/mob_appearance.cpp
This update provides fixes to a couple of issues regarding Hero Forge Armor not displaying to other clients in zone under certain conditions. 
1- Resolved Issue: When a client wearing the hero forge armor zones into a new zone, other clients in that zone could not see hero forge armor on that client.
2- Resolved Issue: When a client wearing hero forge armor in the helmet removed the helmet, the hero forge graphic would not be reapplied if the item was equipped, until the client zoned. (For some reason we were excluding helmets from wear change, I can see no real reason why, I verified on both titanium AND ROF2 that it has no impact on clients show helm option.)
3- Resolved Issue: When a client wearing hero forge armor removes the item and then re-equipped it in zone, for helmet slot it …
=> [Bug Fix] Hero Forge armor graphics not displaying properly to other clients in zone.

zone/spell_effects.cpp
Max level calculation updated to match lives.
max_value determines max level of target to be affected.
If max_value > 1000, formula is value - 1000 = max level. Example 1080 = max level of 80
If max_value < 1000 formula is value = casters level + value = max level of target, if 3, then target must be no more than 3 levels higher.
=> [Spells] Minor update to SPA 502 Fearstuns max calculation.

common/ruletypes.h, zone/doors.cpp
Classic locked doors with keys that do not add to the key ring required the player to have the key on their cursor.
Added a new rule that allows this functionality to work correctly.  The default is the functionality before this patch, which is to just require it to be anywhere in their inventory.
=> [Doors] Add new rule enabling classic "key on cursor" for pre keyring keys

zone/attack.cpp, zone/bonuses.cpp, zone/common.h
SPA 440 sets what the max level a target needs to be for it to be affected by a finishing blow. The limit value determines what the maximum hp ratio required for it to be affected. Was hardcoded at 10 pct, which is what the AA sets it at. You can now edit the limit value to change this.
=> [Spells] Update to SPA 440 SE_FinishingBlowMaxLevel limit value sets HP ratio for FB

zone/attack.cpp
Likely a result of an accidental deletion when I added the SBIndex defines few months ago.
IsDetrimental was checking a buff slot instead of the spell id. Obviously, no good.
=> [Bug Fix] Root code error passing wrong variable into IsDetrimental check

common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/common.h, zone/mob.cpp, zone/mob.h, zone/special_attacks.cpp
I originally had this implemented in a much narrower scope where you could have a max of one of this effect as an AA. Current live AA make use of this SPA multiple times in same AA, thus was time to recode this appropriately. Example of an effect that uses this is the monk Dragon Punch AA.
This update, 
-Adds support for up to 12 effects from AA. 
-Adds support also for this effect to place on items and spell buffs, up to 12 each.
SPA 288  SE_SkillAttackProc, chance to cast a spell when using a skill
base: chance (set 1000 for 100% chance)
limit: skill
max: spellid, (custom for emu, no live spells use this effect only AA)
note: if used in AA the spell id is set in aa_ranks table 'spell' field to the spellid (this is how the AA works).
Note, this differs from SPA 427 and 429 SkillProcs, in …
=> [Spells] Rework of SPA 288 SE_SkillAttackProc

common/guild_base.cpp, common/guild_base.h, zone/client.cpp, zone/gm_commands/guild.cpp, zone/guild_mgr.cpp
- Adds GetGuildNameByID, GetGuildRankName, GetGuildIDByCharacterID, and IsCharacterInGuild helper methods for guild stuff.
- Convert #guild info message to a popup display to tidy it up and make it more legible.
Before:
After:
=> [Commands] Cleanup #guild Command.

utils/sql/git/optional/2021_11_28_pot_pick_locks_book.sql, zone/client.cpp, zone/client.h, zone/doors.cpp
This PR fixes picking locks as follows:
- Skilling up class pick lock skill should only happen on a door that can be opened by the PC.  This is now true after this PR.
- Skilling up, as well as messages only happen when you open the door.  Closing the door is quiet.
- A small 1 second spam timer was added to prevent door/sync issues.
=> [Bug Fix] Pick Lock was allowing skillups on doors above player skill

zone/special_attacks.cpp
NPCs and Pets below the rule values allowing damage vs mobs requiring magic weapons can now kick successfully if wearing magical booties.
=> [Combat] Allow npcs/pets to kick vs opponents requiring magic weapons if wearing magic booties.

common/ruletypes.h, zone/attack.cpp
Rule disables live like feature that if you have SPA 173 SE_RiposteChance it makes the player immune to NPC enrage.
True by default, set to false to disable.
=> [Rule] Added rule to disable SPA 173 from making player immune to enrage.

zone/effects.cpp
Why:
Heal Over Time spells honor the Spells:IgnoreSpellDmgLvlRestriction rule,
shouldn't instant heals honor this rule too?
The fix:
Added a check for Spells:IgnoreSpellDmgLvlRestriction in the GetActSpellHealing
method.
=> [Spells] Instant Heals honor IgnoreSpellDmgLvlRestriction

zone/mob_ai.cpp
For @noudess 
Additional context for readers.
When NPC's in Faydark are walking by the platform and platform triggers both the trigger and the platform would get triggered.
This would ignore cases mentioned above as NPC's should not be manipulating these types of doors on an automatic basis.
If NPC's need to manipulate these types of doors in pathing they can be handled via script.
=> [Doors] Ignore Doors that Have Non-Zero Trigger or Door Param

common/spdat.h, zone/aggro.cpp, zone/attack.cpp, zone/bonuses.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/entity.cpp, zone/entity.h, zone/mob.cpp, zone/mob.h, zone/mob_ai.cpp, zone/spell_effects.cpp
Implemented SPA 281 SE_PetFeignMinion which will allow you to command your pet to FD using /pet feign
Requires purchasing the the AA ability for it to work.
`#define SE_FeignedMinion				281	// implemented, ability allows you to instruct your pet to feign death via the '/pet feign' command, base: succeed chance, limit: none, max: none, Note: Only implemented as an AA.`
Note: This required a little bit of changes to the feign death code in general to let it support non clients. I don't think there should be any unintended changes to regular FD.
=> [Spells] Implemented SPA 281 SE_PetFeignMinion

zone/gm_commands/guild.cpp, zone/gm_commands/killallnpcs.cpp, zone/gm_commands/worldwide.cpp
- #guild rename was checking argument count and not allowing you to rename guilds to names that had spaces.
- #killallnpcs was crashing zones when used sometimes due to getting a nullptr somewhere in the loop.
- #worldwide message was using just the first word of the message sent using the command, not all of them.
=> [Bug Fix] Fix #guild rename, #killallnpcs, and #worldwide message errors.

zone/client_packet.cpp
Seeds of Destruction and higher clients allow GMs to right click any target's buffs and remove them with no client-side restrictions. This PR adds server-side support for this feature.
=> [Spells] Allow GMs to remove buffs from any target

zone/attack.cpp, zone/client.cpp, zone/mob.cpp, zone/mob.h
The problem:
There existed a state where a mob's corpse would remain indefinitely in an auto XTarget slot if Auto Haters was on.
In order to get to this state, a combination of pet attacks and a timely feign death without feign memory was required.
My fix:
Added an IsValidXTarget method to the Mob class. which includes filtering out corpses.  Just in case this logic needs referenced elsewhere, at some other point in the future.
Call IsValidXTarget from the IsXTarget method in client class.
Added call to ProcessXTargetAutoHaters() inside Death methods for both NPC and Client
Inside AddAutoXTarget, moved autohate increment call to after the IsXTarget check.
=> [XTarget] Disallow Corpses in XTarget Auto Slots

common/database_schema.h
Titles is a hybrid table which needs to be split up. It stores both record of content and character level persistence data. Until these are split out I am going to reclassify this table until we have split titles out
=> [Database] Mark titles as a server table so it at least shows up in dumps

zone/gm_commands/guild.cpp
- Names with spaces were breaking command.
=> [Commands] #guild create argument count bug fix.

zone/attack.cpp, zone/client.cpp
Removed a conditional that was rendered obsolete by moving the addition of a
mob to the auto haters list to fire after an IsValidXTarget check.  This
made an entity_list call unnecessary.  [zone/client.cpp]
Removed said unnecessary entity_list call.  [zone/client.cpp]
Removed a superfluous call to ProcessXTargetAutoHaters [zone/attack.cpp]
I spent a few hours today, testing to ensure that corpses still won't get stuck in the XTarget window, with these modifications.  I was unable to get a corpse to stay in the XTarget window, which is good.  This is the desired behavior.
=> [XTarget] Performance Improvement After Corpse Change

zone/aa.cpp
Problem: Hasten AA (spa 246) would not stack with itself if multiple AA are available that hasten the same hotkey cool down.
For example Beastlord 'Bite of the Asp' AA can be reduced by both 'Haste Feral Attacks' and 'Hasten Bite of the Asp', due to how it was coded it could not properly calculate the total cool down reduction if both cool down reduction AA's were purchased. However, client would display it properly.
This now resolved.
=> [Bug Fix] Hasten AA will now reduce time properly if multiple Hasten AA's affect same cool down.

common/ruletypes.h, zone/attack.cpp, zone/bot.cpp, zone/mob.h
Replaced recent rule I made (Combat, ImmuneToEnrageFromRiposteSpellEffect) with
(Combat, UseLiveRiposteMechanics, false, "Set to true to disable SPA 173 SE_RiposteChance from making those with the effect on them immune to enrage, can longer riposte from a riposte.")
This update resolves crash issues associated with original rule and refines the mechanics based on how live currently handles riposte and spell effect 173 (SE_RiposteChance).
Below describes the different mechanics. 
Rule is set to use Legacy mechanics by default so no action is needed to keep things how they are.
```
/*
Live Riposte Mechanics (~Kayen updated 1/22)
-Ripostes can not trigger another riposte. (Ie. Riposte from defender can't then trigger the attacker to riposte)
-Ripostes can not be 'avoided', only hit or miss. …
```
=> [Combat] Implemented rule for live like Riposte mechanics

common/inventory_profile.cpp, common/inventory_profile.h, common/item_instance.cpp, common/item_instance.h, zone/lua_inventory.cpp, zone/lua_inventory.h, zone/lua_iteminst.cpp, zone/lua_iteminst.h, zone/perl_inventory.cpp, zone/perl_questitem.cpp
- Add $inventory->CountAugmentEquippedByID(item_id) to Perl.
- Add $inventory->HasAugmentEquippedByID(item_id) to Perl.
- Add $item->ContainsAugmentByID(item_id) to Perl.
- Add $item->CountAugmentByID(item_id) to Perl.
- Add inventory:CountAugmentEquippedByID(item_id) to Perl.
- Add inventory:HasAugmentEquippedByID(item_id) to Perl.
- Add item:ContainsAugmentByID(item_id) to Perl.
- Add item:CountAugmentByID(item_id) to Perl.
=> [Quest API] Add multiple augment related methods to Perl/Lua.

zone/client.cpp
Fixes Enchanter AA Doppleganger crash issue. 
This will also give like behavior where the Doppleganger will not despawn after its target dies, can continue to fight other targets.
=> [Bug Fix] Fixes Enchanter AA Doppleganger crash issue

shared_memory/main.cpp
Content flags are not load during the shared memory loading process. This results in any loot with a content flag being omitted from shared memory.
=> [Content Flags] Load the content flags before loading shared data.

zone/effects.cpp, zone/mob.h, zone/spells.cpp
Bards on live can use disciplines while casting a song or using /melody. This update provides support for that.
Also added  live like support for spell field 'cast not standing' to allowing allow when divine aura is present on the character.
=> [Spells] Support for bards using Disciplines while casting or /melody.

zone/spells.cpp
On live spells will knock back a rooted NPC. Correct code to allow for that.
Need to have RuleB(Spells, NPCSpellPush) = true.
Will not work on permarooted and pseudorooted mobs, these are typically raid encounters.
=> [Spells] NPC spell push should work on rooted mobs.

zone/client.h, zone/client_packet.cpp, zone/spells.cpp
This update resolves the problem on ROF2 where if you died with an item with an active recast timer, then looted that item and clicked it before recast timer was up it would lock the clients spell bar. In addition looted items don't show the graphical cool down timer. I was able to get to redisplay but only when attempting to use the item. So clicking it after you loot it will redisplay the count down timer at its current time remaining.
=> [Bug Fix] Stop spellbar from locking after looting item with recast timer and clicking it.

zone/mob.cpp
clean_name is cached by the 1st use of GetCleanName().  Any use of TempName() did not cause that cache to be invalidated.
One resulting bug is that #petname would change the pets name, but would not alter some messages that used GetCleanName() until a zone or a camp.
Simply setting *clean_name to NULL forces a recache on the next call to GetCleanName().
=> [Bug Fix] Any use of TempName left old clean_name.

zone/attack.cpp, zone/client.cpp, zone/questmgr.cpp
@nilbog told me that faction isn't awarded for quests if the quest npc is charmed.  He knew this was classic but wasn't sure about live.  I logged onto live and tested.  Sure enough, no faction for bone chips turn in to Lashun when she was charmed.  The rest worked (she cast cure disease) and I got a ding.
=> [Bug Fix (faction)] Do not award faction if NPC is charmed.

zone/mob.h, zone/spells.cpp
Bug fix https://github.com/EQEmu/Server/pull/1941
Was checking perma and pseudo root on caster instead of target.
=> [Bug Fix] Correction to properly disable spell push to perma rooted NPC's.

zone/special_attacks.cpp
Bards on live can throw while casting songs or using /melody. This updated adds support for that.
=> [Combat] Bards can now throw while casting songs or using /melody

utils/mods/legacy_combat.lua
After a few hours of chasing our tails (Kayen, Drac and I) during upgrading EZ's code; NPC scaling was heavily out of whack. After digging through tons of logs and narrowing things down it looks like it is related to a function being bound to Lua that now has a signature change. Because this signature has changed the middleware needs to change. Since the function really isn't needed to begin with it has been removed entirely.
Affected by PR #1858
=> [Combat] Legacy Combat Middleware Affected by PR #1858

zone/client_packet.cpp
Do not allow /open to be used on traps or auras, causes zone crash.
=> [Bug Fix] Do not allow /open to be used on traps or auras, causes crash

zone/mob.cpp, zone/waypoints.cpp
This has been in production for a few weeks on my server now and has completely eliminated the summon issue that cropped up when the summon code was changed a couple of months ago.
Talking with @mackal I believe he feels we need something more comprehensive than this, ala checking ceiling or something similar.
However, I believe this correct the issue for all cases I have seen.  I can't say if it will solve everyone's issue, but the change is small and makes sense.
=> [Bug Fix] Fix issue with mobs summoning PCs into ceilings

zone/client_packet.cpp, zone/titles.cpp, zone/titles.h
- Fixes exploit where you can use titles that are in the database regardless of if you have it.
- Add TitleManager::HasTitle(client, title_id) help method.
- Cleanup entire titles.cpp/titles.h logic, loops, and formatting.
=> [Bug Fix] Fix issue where you can set your title to titles you don't have.

zone/aggro.cpp
spell field 'HateAdded' which overrides spell hate amount will now allow negative values to override which can be used to reduce hate. There are many examples of live spells that use this in our spell file. Previously it would only override if positive.
=> [Spells] Support for 'HateAdded' spell field to apply negative values to reduce hate.

zone/attack.cpp, zone/entity.cpp, zone/entity.h, zone/mob_ai.cpp
Swarm pet aggro after initial target died was broken in various ways.
Correct behavior is once the initial swarm pets target dies, the swarm pet until it despawns will follow you and if you take damage/detrimental spell cast on you from an npc, the pet will attack that NPC. Similar to an enchanter animations AI.
This update will make the pets function like they do on live.
=> [Spells] Swarm pet aggro logic fix

zone/bonuses.cpp, zone/client_packet.cpp, zone/common.h, zone/entity.cpp, zone/entity.h, zone/mob.h, zone/spell_effects.cpp
This update resolves an issue where if a mob already has an illusion on them, when a new client zones in, the armor would not display properly on the mob with the illusion to that client who just zoned in.
=> [Bug Fix] Illusions will now properly display armor to other clients when they zone in.

zone/corpse.cpp, zone/npc.cpp
- Fixes an issue where 0 charged or out of charge items do not count towards the return value.
=> [Bug Fix] NPC::CountItem and Corpse::CountItem 0 Charge Item Fix.

zone/attack.cpp, zone/bonuses.cpp, zone/common.h, zone/mob.h, zone/spell_effects.cpp
Implemented live like mechanic of when a mob dies while having an illusion on them, the corpse will retain that illusion.
=> [Spells] Illusions will now persist onto the corpse when mob is killed.

common/spdat.h, zone/spells.cpp
Update affects SPA 311 SE_LimitCombatSkills which prevents procs from being focused. The way it was coded was incorrectly excluding 'casted' spells that were put as procs.  Where casted spells refers to a spell that can be memorized and casted by a class. Confirmed on live 'casted' spells that are on proc weapons do not receive any focusing.
=> [Spells] SPA 311 SE_LimitCombatSkills should prevent focusing of procs even if proc is a 'casted' spell.

zone/spell_effects.cpp
This update resolves issue of SPA 194 SE_FadingMemories not working correctly for target types other than self only, because it was hard coded to only apply to caster regardless of target type. Relevant when using summon companion AA that triggers spell 27405  Pet Fade  which applies fade to pet.
=> [Bug Fix] SPA 194 SE_FadingMemories not working correctly for target types other than self only.

zone/aa.cpp, zone/client.h, zone/effects.cpp, zone/mob.h, zone/spells.cpp
Recoded how we set AA and Discipline recast timers to finally resolve issues involving recast timers on abilities being set even though the ability failed. As a result, all casting timers (Spell, AA, item, discipline) will now be set at the same location in the code when spell is finished and no further failures can occur, resolving any possibility of the timers not being reset correctly in the event of failure. This also optimizes some of the changes regarding bards casting while using disciplines or AA.
=> [Spells] Fix for AA and Discipline recast timers being set on spell casting failure.

zone/mob.cpp, zone/spell_effects.cpp
This restores functionality I must have accidently removed at some point. With quest added spell mitigation, if you set the mitigation to lower than -100, it would allow your damage spells to heal,  thus providing lots of fun options for developers. This only applies to quest derived spell mitigation using $npc->ModVulnerability(resist type, mitigation amount).
Example add these to an npc and all fire nukes will heal the npc for 1000% of damage done.
```
$npc->SetAllowBeneficial(1);
$npc->ModVulnerability(2, -1000);
```
=> [Spells] Allow damage spells to heal if quest based spell mitigation is over 100 pct.

zone/mob_ai.cpp, zone/npc.h, zone/perl_npc.cpp
These functions are extension of the 'npc_spells_effects' table which allow you to directly apply spell effect bonuses to NPC's without requiring actual spell buffs. You apply the buff as if you were designing a custom spell with a single effect. These buffs work just like regular spell buffs, can be overwritten by more powerful real buffs, or block weaker ones.
```
$npc->AddAISpellEffect(spell_effect id , base_value, limit_value, max_value)
```
Example: $npc->AddAISpellEffect(5 , 100, 0, 0);
This uses SPA 5 that increase strength stat, so this will increase your npcs STR by 100
```
$npc->RemoveAISpellEffect(spelleffect_id)
```
Example: $npc->RemoveAISpellEffect(5);
This will remove all quest or table applied STR buffs.
Using this obviously requires knowledge of how to make spell effects. …
=> [API] Perl functions added to apply spell effects directly to NPCs without requiring buffs.

zone/lua_npc.cpp, zone/lua_npc.h, zone/mob_ai.cpp, zone/npc.h, zone/perl_npc.cpp
- Add $npc->HasAISpellEffect(spell_effect_id) to Perl.
- Add npc:AddAISpellEffect(spell_effect_id, base_value, limit_value, max_value) to Lua.
- Add npc:HasAISpellEffect(spell_effect_id) to Lua.
- Add npc:RemoveAISpellEffect(spell_effect_id) to Lua.
=> [Quest API] Add AI Spell Effect methods to Perl/Lua.

common/emu_constants.cpp, common/emu_constants.h, common/eq_packet_structs.h, common/patches/rof2_structs.h, common/patches/rof_structs.h, common/patches/sod_structs.h, common/patches/sof_structs.h, zone/client_packet.cpp, zone/embparser_api.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
- Add EQ::constants::GetEnvironmentalDamageMap() and EQ::constants::GetEnvironmentalDamageName().
- Add quest::getenvironmentaldamagename(damage_type) to Perl.
- Add eq.get_environmental_damage_name(damage_type) to Lua.
- Cleanup GM messages for avoiding environmental damage.
```perl
sub EVENT_ENVIRONMENTAL_DAMAGE {
my $damage_type_name = quest::getenvironmentaldamagename($env_damage_type);
quest::message(315, "$env_damage $env_damage_type $damage_type_name $final_damage");
}
```
```lua
function event_environmental_damage(e)
local damage_type_name = eq.get_environmental_damage_name(e.env_damage_type);
eq.message(315, string.format("%s %s %s %s", e.env_damage, e.env_damage_type, damage_type_name, e.env_final_damage));
end
```
=> [Quest API] Add GetEnvironmentalDamageName() to Perl/Lua.

zone/gm_commands/timers.cpp
- Utilize popup instead of chat messages.
- Utilize ConvertSecondsToTime() helper method.
=> [Commands] Cleanup #timers Command.

zone/command.cpp, zone/gm_commands/undye.cpp, zone/gm_commands/undyeme.cpp
- Fix #undye command as its method was not being used in command.cpp.
- Cleanup messages and logic for both #undye and #undyeme.
=> [Commands] Cleanup #undye and #undyeme Commands.

zone/command.cpp, zone/gm_commands/flagedit.cpp
- Cleanup and fix messages and logic.
- Utilized popup for listing zones that have required flags.
=> [Commands] Cleanup #flagedit Command.

zone/gm_commands/logs.cpp
- Utilize popup for list and applying settings.
- #logs reload_all is now #logs reload
- #logs list_settings is now #logs list
- #logs list has option starting category ID for listing purposes.
=> [Commands] Cleanup #logs Command.

common/ruletypes.h, zone/client_packet.cpp, zone/string_ids.h
When trying to invite a client into your group who is already in a group, if you have the rule enabled you will receive a message informing you that the player is already in a group.
RULE_BOOL(Character, OnInviteReceiveAlreadyinGroupMessage)
*Note string id was not displaying properly so didn't use it.
=> [Feature] Send message when trying to invite player already in group.

zone/aa.cpp, zone/client.h, zone/effects.cpp, zone/mob.h, zone/spells.cpp
This update has proved to be problematic causing unforeseen inconsistent issues with discipline timers. Creating more problems to solve another is not a good strategy. The goal of this PR can be better addressed in a different way.
=> [Spells] Revert for PR1971 Recast Timer updates.

common/emu_constants.cpp, common/emu_constants.h, zone/embparser_api.cpp, zone/gm_commands/ai.cpp, zone/lua_general.cpp, zone/questmgr.cpp, zone/questmgr.h
- Remove #ai start/#ai stop as they can crash zones and are mostly useless.
- Add EQ::constants::GetConsiderLevelMap() and EQ::constants::GetConsiderLevelName().
- Add quest::getconsiderlevelname(consider_level) to Perl.
- Add eq.get_consider_level_name(consider_level) to Lua.
=> [Commands] Cleanup #ai Command.

zone/spells.cpp
Thanks to Neckkola for figuring this out.
Resolves crash loop with BOT bards occurring after bard rework.
=> [Bug Fix] Bard BOT crash fix

zone/command.cpp, zone/gm_commands/showskills.cpp
- Utilize popup over messages.
- Usage: #showskills [Start Skill ID] [All] - shows skills starting from skill ID and if "all" is specified it will show skills the player does not have normally (no max/cannot have skill).
=> [Commands] Cleanup #showskills Command.

common/ruletypes.h, common/spdat.h, zone/attack.cpp, zone/bonuses.cpp, zone/bot.cpp, zone/bot_command.h, zone/client.cpp, zone/client_packet.cpp, zone/client_process.cpp, zone/common.h, zone/gm_commands/tune.cpp, zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp, zone/spell_effects.cpp, zone/spells.cpp, zone/zonedump.h
This update improves the way we handle invisibility related spells to allow better implementation of invisibility levels and support for live like having multiple different invisibility buffs on a character at same time.
Live invisible mechanic allows for multiple different invisibles spells to applied to same client. For example you can have self only Improved Invisible, have bard invisible and have a regular targeted invisible cast on you. Thus giving you all 3 buffs at same time. If you cast or attack all three will fade. Therefore the below rule, should be true by default. This update provides full support for multiple invisible spells.
`RULE_BOOL(Spells, AllowDoubleInvis, true, "Allows you to cast invisibility spells on a player that is already invisible, live like behavior.")` …
=> [Spells] Invisibility updates and rework

zone/spells.cpp
Bards casting from items with cast times with melody wasn't displaying timer. Looks like I didn't need to be locking the spell bar for the casting to work. Everything seems fine for melody while clicking and regular song casting while clicking.
From https://github.com/EQEmu/Server/pull/1954)
=> [Bug Fix] Bards casting from items with cast times with melody wasn't displaying timer.

zone/client.h, zone/command.cpp, zone/gm_commands/unscribespell.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/spells.cpp
- Add Client::UnscribeSpellBySpellID(spell_id, update_client).
- Add $client->UnscribeSpellBySpellID(spell_id, update_client) to Perl.
- Add client:UnscribeSpellBySpellID(spell_id, update_client) to Lua.
=> [Commands] Cleanup #unscribespell Command.

common/ruletypes.h, common/spdat.cpp, zone/beacon.cpp, zone/beacon.h, zone/spells.cpp
Spells with AE Duration effects can be applied to Target Ring cast spells and PBAE spells. This update provides support for both of those.
=> [Spells] AE Duration effect (Rains) will now work with Target Ring and PBAE spells.

queryserv/database.cpp
LogPlayerHandin was not recording the item details of the trade. It should be inserting the trade details into `qs_player_handin_record_entries` but it was not running the query because of missing QueryDatabase function.
=> [Bug] Fixed trade items record log

zone/entity.cpp, zone/entity.h, zone/lua_entity_list.cpp, zone/lua_entity_list.h, zone/perl_entity.cpp
- Add $entity_list->GetRandomMob(x, y, z, distance, exclude_mob) to Perl.
- Add $entity_list->GetRandomNPC(x, y, z, distance, exclude_npc) to Perl.
- Add eq.get_entity_list():GetRandomMob(x, y, z, distance, exclude_mob) to Lua.
- Add eq.get_entity_list():GetRandomNPC(x, y, z, distance, exclude_npc) to Lua.
=> [Quest API] Add GetRandomMob() and GetRandomNPC() to Perl/Lua.

zone/spells.cpp
Fix for using castspell command with parameter 0.
We weren't checking for not having an item slot correctly.
=> [Bug Fix] Fix for castspell command failing using parameter 0

zone/aa.cpp, zone/effects.cpp, zone/mob.h, zone/spells.cpp
This is from the bard update. Was trying to check casting_spell_slot before it was defined, causing some spells to fail when they shouldn't. Explains the mysterious discipline fail issues that were occurring , likely not related to the recast timer changes that I reverted in hindsight.
=> [Bug Fix] Fix for issue why some disciplines were randomly failing.

zone/lua_mob.cpp, zone/mob.h, zone/worldserver.cpp
- Spell casting was using SpellFinished which casts the spell, and if the spell was a group spell each member of the group would cast it on all the other members, causing a chain reaction.
- This fix utilizes ApplySpellBuff(spell_id, duration) so that it only casts the spell on the target, as with the crosszone and worldwide methods you will be affecting your target based on identifiers regardless.
- This should alleviate some of the crosszone/worldwide casting crashes on larger servers such as Lazarus.
=> [Bug Fix] Alleviate some lag with crosszone/worldwide spell casting.

zone/gm_commands/zclip.cpp
This fixes an issue where `#zclip` crashes when ran with 0 or 2 args.
Help command should return otherwise execution falls through other logic and crashes. This also adds requirements for 4 args
=> [GM Command] Fix Crash Issue and Validation with #zclip

zone/spell_effects.cpp
Implemented missing mechanic for SPA 79 SE_CurrentHPOnce so it will now appropriately apply focus/critical and partial resists. Currently we do not try to apply any of that.
Was able to confirm on live for healing using SPA 79 as long as it is NOT in a buff spell (defined as using SPA 69), then it can critical and be focused.
Was able to confirm on live for damage using SPA 79 is can critical and can be partially resisted. Was unable to test focus because just about every live focus for damage specifically limits the focus to only apply to SPA 0, however by that logic then if you removed that limitation it should apply to SPA 79, and further it does apply to healing, and it applies all other behaviors of regular damage. So it is reasonable to conclude it can be focused.
=> [Spells] SPA 79 SE_CurrentHPOnce now will check for focus, critical and partial resist checks, except for buffs.

zone/embparser_api.cpp
- Logic made the method return an "error" when not using last parameter.
- Example of using all but last parameter.
```pl
quest::MovePCInstance($zone_id, $hardcore_instance_id, $npc_x, $npc_y, $npc_z);
```
=> [Bug Fix] quest::MovePCInstance() Arguments Fix.

common/ruletypes.h, zone/effects.cpp
Rule to apply Spell Dmg and Heal Amount stats as a percentage instead of flat value.
This was useful for my server. Each point of these stats is reflected as a 1% increase in spell effectiveness, subject to the 5-level spread and recalculation around casting time, etc (unless the rules to disable those are in effect).
=> Rule to apply Spell Dmg and Heal Amount stats as a percentage instead of flat value.

zone/gm_commands/worldwide.cpp
- Command usages would not display when using commands improperly, this will fix that.
- Added a return for invalid spells on cast and remove so they cannot be accidentally used.
=> [Commands] Cleanup #worldwide command.

zone/lua_parser.cpp
Fix accidental removal of argument dispatch for EVENT_CONSIDER_CORPSE in https://github.com/EQEmu/Server/pull/2015
=> [Bug Fix] Removed Lua Event Argument Dispatch.

zone/bot.cpp, zone/bot.h, zone/client.h, zone/effects.cpp, zone/merc.cpp, zone/merc.h, zone/mob.cpp, zone/mob.h, zone/npc.h, zone/spell_effects.cpp, zone/spells.cpp
This update addresses an issue where if your using buffs with numhits type 7 which would tic down the hits counter every time a spell was focused, subsequent spell casts or item clicks of unrelated spells would incorrectly tic down that hit counter.
Also this update fixes an issue where focus that apply to dots or hots specifically would not properly tic down the hit counter,  was broken in various ways. The correct behavior is that they tic down on initial cast.
=> [Spells] Fixes for numhits type 7 counter incrementing incorrectly.

zone/perl_doors.cpp
- Typo was causing GetIncline() to show twice on Spire and causing GetSize() not to show at all on Spire.
=> [Bug Fix] Doors::GetSize() Perl Croak Typo.

zone/bot.cpp
Bots use a different method to calculate final spell damage and healing amounts, for which the version for players and bots are out of sync in several ways. This corrects one difference.
=> [Bots] Apply Spells:IgnoreSpellDmgLvlRestriction to bots

zone/inventory.cpp
There are multiple places in this file where the following is done:
(a & b == 0)
== has higher precedence than &
The correct way to check is
(a&b) == 0
Many lines in the same file doing the same thing are correct already.
Bad line:
if (((uint64)1 << i) & GetInv().GetLookup()->PossessionsBitmask == 0)
Good Line:
if ((((uint64)1 << slot_id) & GetInv().GetLookup()->PossessionsBitmask) == 0)
=> [Bug Fix] Fixed several instances of incorrect comparison - & executes after ==

zone/inventory.cpp
If you activated a bandolier set and one of the source weapons was on your cursor, the code didn't see it.
For whatever reason, m_inv.GetItem(EQ::invslot::slotCursor)->GetCharges() was returning 0 when the source weapon was on the cursor, bypassing the code that was written to handle this case.
=> [Bug Fix] Bandolier didn't recognize source weapon on cursor

zone/mob_ai.cpp
The AI code for spell casting (engaged):
- two forms of innate/priority0 spells
- in combat buffs
- heals/bene
- everything else
The first spell to get a sucess roll wins for that trip through the loop.
InCombatBuffs is 50% per spell to be chosen.  Hopwever, the code did not have a CanStack check.  So mobs with a spell list that included InCombatBuffs is severely compromised due to one spell getting cast over and over, on top if itself, 50% of the loops through if the spell list has no innates/priority0 spells.
Added a simple CanStack check and these mobs behave much better.
(Also changed the brace style to match the surrounding code)
=> [AI] Spell Type (1024) InCombatBuff were spam casting

common/ruletypes.h, zone/spells.cpp
I always thought that this was one of the better features of EQ2. I think implied targeting melee would be more tricky to implement, and is pretty opaque to me (not a C++ guru by any stretch of the imagination), so skipping that for now, but spells are pretty easy and a pretty nice QOL feature.
=> [Feature] EQ2-style implied targeting for spells.

common/content/world_content_service.cpp, common/content/world_content_service.h, common/loottable.h, common/shareddb.cpp, common/string_util.cpp, common/string_util.h, shared_memory/main.cpp, zone/loottables.cpp
This helps remove the need to restart server when changing content flags. If you change a flag from enabled to disabled or back, all it requires is a `#reloadcontentflags` and then a `#repop`. If you change the flags on a loottable or lootdrop, then you have to also do a `#hotfix` before `#repop`.
=> [Content Filtering] Updates contents flags to be checked at runtime.

zone/gm_commands/killallnpcs.cpp
This is another command that was crashing from recent cleanups.
Using NPC List is not great for this because it has book keeping issues, I moved it back to using MobList. Using the NPC list was causing crashes in it of itself. It's not a good idea to be iterating over a list that is being manipulated (entries being removed) so in this case using a copy of the mob list works better.
```
[03-06-2022 :: 20:19:43] [Zone] [Crash] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[03-06-2022 :: 20:19:43] [Zone] [Crash] 0x00007f472aeae0ca in __waitpid (pid=26569, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
[03-06-2022 :: 20:19:43] [Zone] [Crash] [Current thread is 1 (Thread 0x7f472a1d3140 (LWP 25943))]
[03-06-2022 :: …
```
=> [Command] Fix #killallnpcs from crashing

zone/spell_effects.cpp
Bug from recent invisible update. Fixes display issue where NPC's would not drop invisible appearance when attacking.
=> [Bug Fix] Invisible (name) appearance will now correctly drop from NPC's when attacking.

zone/embparser.cpp, zone/lua_parser_events.cpp, zone/spells.cpp
- Add $caster_id and $caster_level to EVENT_CAST_ON in Perl.
- Add e.caster_id and e.caster_level to EVENT_CAST_ON in Lua.
=> [Quest API] Add caster_id and caster_level export to EVENT_CAST_ON in Perl/Lua.

zone/npc.cpp
For $npc->GetNPCStat(identified)
Useful for scripts that use scaling.
```
"default_ac"
"default_min_dmg"
"default_max_dmg"
"default_attack_delay"
"default_accuracy_rating"
"default_avoidance_rating"
"default_atk"
```
=> [API] GetNPCStat can now return default stat values.

zone/attack.cpp, zone/mob.h, zone/tune.cpp
Fix issue with client AC not calculating properly due to overrides.
tune stats will now display NPC raw stats for AC/ATK/Avoid/Accuracy
Fixed issue where if client had critical hit chance it would spam critical hit messages.
For more info on tune command see
https://github.com/EQEmu/Server/pull/1677
=> [Bug Fix] #tune command various fixes

zone/attack.cpp, zone/bot.cpp
- Fixed Bots Spell Damage being negative under some circumstances (heal target)
- Allow Bots to send non-melee damage reports in the same manner as Clients
- Refactor\Update Bots Spell Damage & Heal calculations to match current state of Clients.
- Allow Bots to actually utilize Spell Damage and Heal Amount stats
This is mostly just copy\paste from the methods in effects.cpp, with IsClient() checks and sections that only apply to NPCs removed. I tried simply calling the Mob methods, but there are some incompatibilities in regard to determining spell Foci that will require some more significant refactoring than I'm capable of right now.
A few foci that I don't believe apply to any relevant vanilla content (boost received healing) are not handled by the Heal method, because resolving the …
=> [Bots] Update Bot Heal & Damage methods to more closely match Clients + Bugfixes

zone/attack.cpp, zone/embparser.cpp, zone/entity.cpp, zone/mob.cpp, zone/mob_ai.cpp, zone/spell_effects.cpp, zone/task_client_state.cpp, zone/tradeskills.cpp, zone/waypoints.cpp
- Export $killed_x, $killed_y, $killed_z, and $killed_h to EVENT_DEATH_ZONE in Perl.
- Cleanup export strings and unnecessary .c_str() calls on event exports.
=> [Quest API] Export killed XYZH to EVENT_DEATH_ZONE in Perl.

zone/spells.cpp
- Export $caster_id and $caster_level to EVENT_CAST and EVENT_CAST_BEGIN in Perl.
- Export e.caster_id and e.caster_level to EVENT_CAST and EVENT_CAST_BEGIN in Lua.
=> [Quest API] Add EVENT_CAST_ON exports to EVENT_CAST and EVENT_CAST_BEGIN.

zone/embparser.cpp, zone/lua_parser_events.cpp, zone/zoning.cpp
- This will allow server operators to prevent zoning to or from a specific zone based on whatever criteria they want.
=> [Quest API] Allow EVENT_ZONE to be parsed as non-zero to prevent zoning.

zone/npc.cpp
Update to this recent PR: https://github.com/EQEmu/Server/pull/2048
Realized the names should match the regular version names.
"default_ac"
"default_min_hit"
"default_max_hit"
"default_attack_delay"
"default_accuracy"
"default_avoidance"
"default_atk"
=> [API] GetNPCStat default better naming

zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
- Add $client->AddItem(item_data) to Perl.
- Add client:AddItem(item_table) to Lua.
- This will allow server operators to add items without needless parameters.
Perl Example:
```pl
my %item_data = (
"item_id" => 1200,
"charges" => 1,
"augment_one" => 49656,
"augment_two" => 49656,
"augment_three" => 49656,
"augment_four" => 49656,
"augment_five" => 49656,
"augment_six" => 49656,
"attuned" => 1,
"slot_id" => quest::getinventoryslotid("general1")
);
$client->AddItem(\%item_data);
```
Lua Example:
```lua
local item_data = {
item_id = 1200,
charges = 1,
augment_one = 49656,
augment_two = 49656,
augment_three = 49656,
augment_four = 49656,
augment_five = 49656,
augment_six = 49656,
attuned = true,
slot_id = Slot.General1
};
e.self:AddItem(item_data);
```
=> [Quest API] Add AddItem() to Perl/Lua.

zone/lua_general.cpp, zone/questmgr.cpp
- ZoneLongName and ZoneName were returning nullptr in places when given invalid data that were then attempting to use that nullptr value, causing zone crashes.
=> [Bug Fix] Fix possible crash with zone name methods.

zone/client_packet.cpp
Handle_OP_EnvDamage log messages were logging the input damage base, not the actual adjusted damage that was being mitigated by invulnerability.
=> [Logging] Fix log messages to final damage values

utils/sql/db_update_manifest.txt
Field name in version 9176 doesn't match field created.
=> [Bug Fix] manifest for db version 9176 had incorrect field name

zone/entity.cpp, zone/entity.h, zone/lua_entity_list.cpp, zone/lua_entity_list.h, zone/perl_entity.cpp
- Add $entity_list->GetBotListByClientName(client_name) to Perl.
- Add eq.get_entity_list():GetBotListByClientName(client_name) to Lua.
- Allows you to get a bot list comprised solely of a specific character's bots.
=> [Quest API] Add GetBotListByClientName(client_name) to Perl/Lua.

common/spdat.cpp, zone/bonuses.cpp
Error occurring due to bard modifiers being applied to invisible spell effect value when it should not.
=> [Bug Fix] Bard Invisible causing display issues.

zone/client_packet.cpp
- Clearing uses title ID 0, so need to make sure title ID is valid when setting and based on that, either check and set, or just clear.
=> [Bug Fix] Clear title/suffix bug fix.

zone/worldserver.cpp
Voice tells for non-player races (like skeleton illusions, etc.) are incorrectly playing human sounds on recipient clients.
This is because the code isn't checking the return value for GetPlayerRaceValue().  
This patch makes recipient play BaseRace in these cases, to match what sending client plays.
=> [Bug Fix] Fix recipient sound (vtell) on non-player races

common/spdat.cpp
Bard Instrument Mods should not affect spells that change model size. SPA 89 and SPA 298
=> [Bug Fix] Bard Instrument Mods should not affect spells that change model size.

zone/client.h
Blocked spell id should be checking int32 not int16
=> [Bug Fix] Blocked spells max spell id increased

zone/gm_commands/task.cpp, zone/task_client_state.cpp
- Cleanup messages.
- Add #task uncomplete [Task ID] to uncomplete a completed task without having to go in the database manually.
=> [Commands] Cleanup #task Command.

common/spdat.cpp, zone/spells.cpp
I noticed that when an npc (spectre) cast lifetap on a PC that the "feel your life drain away" message was missing.
This PR fixes this, and some other missing messages.  It also uses the proper message Filters.  This function had conflicting filters.
Been tested on Rolath for about a week.  Have not seen any extra messages and missing messages are restored.
=> [Bug Fix] Restore missing messages for lifetap and dmg spells.

zone/worldserver.cpp
WorldServer::HandleMessage wasn't working correctly on else if statement thus preventing cross zone signals from working for quests using lua_cross_zone_signal_npc_by_npctype_id.
=> Bug Fix for WorldServer::HandleMessage, CZUpdateType_NPC

zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/corpse.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/trading.cpp
- Allows for easier NPC interactions.
- GetCarriedPlatinum() adds together all currencies in inventory based on conversion amounts so it works easily with removals/checks.
- Add $client->AddPlatinum(platinum, update_client) to Perl.
- Add $client->GetCarriedPlatinum() to Perl.
- Add $client->TakePlatinum(platinum, update_client) to Perl.
- Add client:AddPlatinum(platinum, update_client) to Lua.
- Add client:GetCarriedPlatinum() to Lua.
- Add client:TakePlatinum(platinum, update_client) to Lua.
- Remove unused Client::SendClientMoneyUpdate.
=> [Quest API] Add AddPlatinum(), GetCarriedPlatinum() and TakePlatinum() to Perl/Lua.

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_04_30_hp_regen_per_second.sql, zone/gm_commands/npcedit.cpp, zone/merc.cpp, zone/mob.cpp, zone/mob.h, zone/npc.cpp, zone/zonedb.cpp, zone/zonedump.h
This PR implements an additional and optional per second HP regen to offset DPS. (HPRS vs DPS) 
Per second HP regen makes it easier for operators to build content against projected DPS rates and makes it easier to tune encounters based on baseline DPS rates for a given content tier.
* Implemented new field `hp_regen_per_second` at the `npc_types` table level
* Implemented #npcedit hp_regen_per_second
* Implemented modifier to ModifyNPCStat / GetNPCStat `hp_regen_per_second`
This does not change in anyway the existing `hp_regen_rate` functionality or intended Live functionality is completely optional. Default value is 0
=> [Regen] Implement Per Second HP Regen for NPCs

zone/entity.cpp, zone/spells.cpp
AOE target types for Beam and Cone type spells were attempting to hit targets incorrectly like pets and aura's.
=> [Bug Fix] Update to target types Beam and Cone to ignore invalid targets.

common/eqemu_logsys.cpp, common/eqemu_logsys.h, common/eqemu_logsys_log_aliases.h, zone/CMakeLists.txt, zone/attack.cpp, zone/combat_record.cpp, zone/combat_record.h, zone/mob.h, zone/mob_ai.cpp, zone/spells.cpp
This PR implements a basic combat recording mechanism for operators to see very simple DPS / Heal/s stats at the end of a combat encounter. 
This helps when making assessments on scaling content at a very basic level and can help with pulling analytics on the kind of DPS players are pushing in content by also logging to a file.
This can eventually extend out to include more complicated metrics, realtime popup window watching, tracking multiple entities but only gets a basic implementation for this PR.
**Changes**
* Adds class `CombatRecord`
* Adds logging category `CombatRecord`
* Hooks SetHP for increment / decrement events
* Hooks engaged and death events to properly start and stop Combat Record
=> [Combat] Basic Combat Recording

common/repositories/grid_entries_repository.h
This is in the custom repository method file so the generator doesn't
need modified for it
=> [Repository] Cast floats to avoid grid repository warnings

zone/special_attacks.cpp
I believe that frenzy should fail against opponents that are immune to non-magical weapons, when not wielding one. This PR fixes that.
NOTE: It seems live has removed this invulnerability from wisps and ghouls...  Not sure if it's just gone, or only on selected mobs.
Also note, this fixes the issue for clients.  Very similar code exists in Client::DoClassAttacks for Frenzy.  Does this need to be changed also?  I don't know where that code is called from??  Changing that code had no effect on this bug.  Maybe I need to put the same fix there for cases when client is AI controlled?
=> [Combat] Fix Frenzy vs opponents immune to non-magic

common/string_util.cpp, common/string_util.h, zone/embparser_api.cpp, zone/lua_general.cpp, zone/mob_info.cpp
- Add quest::commify(number) to Perl.
- Add eq.commify(number) to Lua.
=> [Quest API] Add commify to Perl/Lua.

zone/perl_client.cpp
- Fixes `$client->GetAllMoney()` to use `uint64` and not overflow int value.
- Fixes `$client->GetCarriedMoney()` to use `uint64` and not overflow int value.
=> [Quest API] Perl Money Fixes.

zone/client_packet.cpp, zone/command.cpp, zone/gm_commands/summon.cpp, zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/worldserver.cpp
- Command will now tell you if the specified character name does not exist instead of incorrectly telling you it's summoning a non-existent character.
- Add glm::vec4 overload for GMMove.
- Remove unused parameter from GMMove.
- Remove unnecessary Lua GMMove now that parameter is gone.
=> [Commands] Cleanup #summon Command.

zone/client.cpp, zone/client.h, zone/gm_commands/serverrules.cpp
- Change separator from new line to pipe separator, as new line was non-functional.
=> [Commands] Cleanup #serverrules Command.

common/servertalk.h, world/zoneserver.cpp, zone/command.cpp, zone/gm_commands/reloadstatic.cpp, zone/worldserver.cpp
- Make reloading of static zone data global instead of zone specific.
=> [Commands] Cleanup #reloadstatic Command.

common/emu_constants.h, common/servertalk.h, world/console.cpp, world/console.old.cpp, world/world_event_scheduler.cpp, zone/command.cpp, zone/gm_commands/reloadworld.cpp, zone/gm_commands/repop.cpp, zone/questmgr.cpp, zone/spawn2.cpp, zone/worldserver.cpp, zone/zone.cpp, zone/zone.h, zone/zone_reload.cpp, zone/zonedb.h
- Add #reloadworld 2 option to forcefully repop all mobs globally as well as reset quest timers and reload quests.
- Add zone->ClearSpawnTimers() for a shorthand to clear all spawn timers instead of it being stuck in the quest method.
- Add enum for reloadworld types to avoid magic numbers.
=> [Commands] Cleanup #reloadworld and #repop Command.

zone/bot.cpp, zone/bot.h, zone/lua_bot.cpp, zone/lua_bot.h, zone/perl_bot.cpp
Resolves an issue where the methods have the same name as other methods.
=> [Bug Fix] Resolve subroutine redefinition due to bot methods.

zone/command.cpp, zone/gm_commands/qglobal.cpp
=> [Commands] Cleanup #qglobal Command.

zone/lua_stat_bonuses.cpp
```
/drone/src/zone/lua_stat_bonuses.cpp: In member function 'bool Lua_StatBonuses::GetBlockNextSpell() const':
/drone/src/zone/lua_stat_bonuses.cpp:681:1: warning: control reaches end of non-void function [-Wreturn-type]
```
=> [Bug Fix] Lua GetBlockNextSpell() no return.

zone/npc.cpp
```
In member function 'float NPC::GetNPCStat(const char*)': /drone/src/zone/npc.cpp:2810:1: warning: control reaches end of non-void function [-Wreturn-type]```
=> [Bug Fix] NPC::GetNPCStat has no default return.

common/repositories/base/base_task_activities_repository.h, common/tasks.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_05_03_task_activity_goal_match_list.sql, zone/attack.cpp, zone/task_client_state.cpp, zone/task_goal_list_manager.cpp, zone/task_goal_list_manager.h, zone/task_manager.cpp, zone/task_manager.h
This PR implements a separate, far more ergonomic way of driving task activity goal list update targets.
For example when using a goal list, instead of maintaining individual ID's in a goal list table for every single NPC type ID that you want to be in a task, its far easier to just grep by the name of the NPC's within the context of the zone that you want to provide your update for.
For example; in Tutorial there is a Task called **Arachnia**
**Kill 12 Gloom Spiders 0/12 The Mines of Gloomingdeep**
You can provide a `goal_match_list` of `gloomingdeep grunt|rat|goblin` and you will get activity updates from pipe delimited partial matches. This would give updates from any NPC with the partial matches within the pipes. This works together with other filters, such as zoneids to filter …
=> [Tasks] Implement Task Goal Match List

ucs/ucs.cpp, zone/client.cpp, zone/client.h, zone/worldserver.cpp
* Hooking program signals when UCS crashes or is killed by the OS
* Handling proper UCS shutdown when crashed or killed (Closing connections)
* Informing the client the connection is closed when UCS is terminated either gracefully or ungracefully
* Informing the client of the UCS server connection after the UCS server has become available again
=> [UCS] Auto Client Reconnection

world/clientlist.cpp, zone/gm_commands/cvs.cpp
- std::find was using .begin() in both comparisons, so it wasn't working and unique IPS always returned 1.
=> [Commands] Cleanup #cvs Command.

zone/gm_commands/repop.cpp
If you use no arguments, the command does not repop.
=> [Bug Fix] Fix #repop Command.

zone/common.h
GCC warning messages were complaining, turns out they had a good reason to
=> [Bug Fix] Out of bounds issues with SPA 288

common/emu_constants.h, common/eq_packet_structs.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_05_07_merchant_data_buckets.sql, zone/client.cpp, zone/client.h, zone/client_process.cpp, zone/zone.cpp
- Allows server operators to limit merchant items based on data bucket values and comparisons.
- Adds 3 columns, bucket_name, bucket_value, and bucket_comparison to merchantlist table.
- Bucket is checked based on GetBucketKey()-bucket_name.
- Buckets are mass loaded when using the merchant so it's not a database call per item, just a grouping of all their buckets from the start.
- This is a nearly year old pull request redone for master.
- bucket_comparison Values are as follows:
```
0: bucket_name == bucket_value
1: bucket_name != bucket_value
2: bucket_name >= bucket_value
3: bucket_name <= bucket_value
4: bucket_name > bucket_value
5: bucket_name < bucket_value
6: bucket_name is any of pipe(|)-separated bucket_value
7: bucket_name is not any of pipe(|)-separated bucket_value
8: …
```
=> [Merchants] Add Merchant Data Bucket capability.

zone/client.h, zone/embparser_api.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
- Add $client->TaskSelector(task_list) to Perl.
- Add client:TaskSelector({task_list}) to Lua.
- Allow $client->AssignTask(task_id) in Perl.
- Allow client:AssignTask(task_id) in Lua.
- Can now assign tasks in scripts without the NPC ID parameter.
=> [Quest API] Add TaskSelector to Perl/Lua.

common/content/world_content_service.h, common/perl_eqdb.cpp, common/perl_eqdb_res.cpp, zone/embparser_api.cpp, zone/lua_general.cpp, zone/perl_client.cpp, zone/perl_entity.cpp, zone/perl_groups.cpp, zone/perl_inventory.cpp, zone/perl_mob.cpp, zone/perl_npc.cpp, zone/perl_object.cpp, zone/perl_perlpacket.cpp, zone/perl_player_corpse.cpp, zone/perl_questitem.cpp, zone/perl_raids.cpp
- Some push methods were pushing integers as unsigned integers or unsigned integer as integers, this fixes all of that.
- Some methods were using integer returns instead of bool returns.
- Also cleans up some lines that had multiple function calls on them.
=> [Cleanup] Quest API push methods using invalid types.

common/database.cpp, common/database.h, zone/bot_database.cpp, zone/client_packet.cpp, zone/embparser_api.cpp, zone/lua_general.cpp
- Add quest::checknamefilter(name) to Perl.
- Add eq.check_name_filter(name) to Lua.
- Allows operators to check strings against the name filter for stuff like setting custom pet names, titles, suffixes, etc in scripts.
=> [Quest API] Add CheckNameFilter to Perl/Lua.

zone/attack.cpp, zone/spells.cpp
The fact that some spells use skill_id 52 (innate) has caused confusion and multiple attempts at understanding why some messages are missing and some are duplicated.
This PR fixes spells that use skill_id 52 to send (2) messages to the person being damaged (attack.cpp)
1) The strike message
2) The actual spell effect (life drains away, you have been poisoned, etc).
Some of the above were being send by spells.cpp because attack.cpp was missing them.
This has been tested using lifetaps, DD, DD+DOT, DOT, root w/damage,etc.
It has been tested in PVP,, and npcs procing as well as casting,
I think more messages come out now (that we were missing) and all duplicates are gone.
Fingers crossed.
@nytmyr This fixes canni also..
=> [Bug Fix] Fix duplicate and missing messages due to innate in spells

zone/zonedb.cpp
`hp_regen_rate` was being used for `hp_regen_per_second` incorrectly.
=> [Bug Fix] Fix HP Regen Per Second.

zone/aggro.cpp
So the following scenario seemed wrong to me so I tested on live, and I was correct.
Before this PR:
- Pull a mob and root it next to your group.
-  Back up.
- The mob just stands there.  No one else is added to the hate list.
I tested this on live.  If the current target is out of combat range, it will attack anyone else it hates that is in range.
This is even true of unrooted mobs, but I wasn't sure the community was ready for that big of a change, so I didn't include that.
This PR simply lets other targets to be added to the hatelist if they are close enough and the mob can't reach its currently engaged target due to root.
Feedback appreciated..
=> [Aggro] Rooted mobs will add other hated targets to Hate list

zone/client_mods.cpp
Math was using an integer and then multiplying, so if you set the rule value to `2,000,000,000` it would overflow almost every time causing you to have negative regen and endlessly die.
=> [Regen] Fix possible overflow in CalcHPRegenCap().

common/ruletypes.h, zone/spell_effects.cpp, zone/spells.cpp
- Allows illusions to always persist beyond death or zoning.
=> [Rules] Add Spells:IllusionsAlwaysPersist.

common/database.cpp, common/database.h, world/client.cpp, world/clientlist.cpp, world/clientlist.h, world/main.cpp, zone/main.cpp
- IP Exemptions were broken due to GetAccountID() returning 0 in logic somehow, resolved this by setting a variable to GetAccountID() at the beginning of the method.
- Fixed weird IP messages where the long form of IP was displayed instead of the string form.
- Fixes edge case where IP rule may be set to -1 and this will make anyone get instantly kicked if IP Exemptions were enabled as their IP Count would always be greater than -1.
=> [Bug Fix] Fix IP Exemptions.

zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/embparser_api.cpp, zone/exp.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/spells.cpp
- Spell buckets will now allow new mob->SetBucket() buckets since most people use these now.
- Max level bucket will now allow new mob->SetBucket() bucket since most people use these now.
- Buckets check new naming first then old, returns based on which it finds or if it doesn't find any.
- Clean up GetScribeableSpells() and GetLearnableDisciplines() logic and magic numbers.
- Make GetClientMaxLevel() uint8 instead of int since it can only be 0-255.
=> [Cleanup] Cleanup spell and max level bucket logic.

common/string_util.cpp, zone/corpse.cpp, zone/embparser_api.cpp, zone/gm_commands/givemoney.cpp, zone/groups.cpp, zone/npc.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/raids.cpp, zone/string_ids.h, zone/task_client_state.cpp
- Cleans up all the money messages using ConvertMoneyToString().
- Allows quest::givecash() to have optional parameters other than copper.
=> [Money Messages] Cleanup quest::givecash(), split, and task reward messages.

zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.h, zone/npc.cpp, zone/perl_mob.cpp
- These all had int64 values and were overflowing, returning garbage data.
=> [INT64] Fix int64 for OOC Regen and GetHP(), GetMaxHP(), GetItemHPBonuses() in Perl/Lua.

zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
- Setter was using int, causing any value over 2 billion to overflow.
- Stat bonuses HP is int64, so getter for Spell HP Bonuses should be, too.
=> [INT64] Further int64 cleanup in Perl SetHP() and GetSpellHPBonuses() in Perl/Lua.

zone/groups.cpp, zone/questmgr.cpp
- Not sure how Windows compiles, but Linux fails.
Not sure if we need this, as AppVeyor build succeeded this time, it had just said YOU_RECEIVE and YOU_RECEIVE_AS_SPLIT were undefined before, so I assumed it was this.
=> [Hot Fix] Fix Linux compile due to missing include.

zone/zone.cpp
Fix null pointer crash via GetZoneDescription when #reload commands are calls and zones aren't actually booted
=> [Crash] Fix Null Pointer Crash via GetZoneDescription

zone/zone.cpp, zone/zonedb.cpp
Corrects an issue where Merchantlists and NPC types loaded at a zone level do not also consider -1 (all)
=> [Loading] Zone Version Loading Fixes

common/item_data.h, common/ruletypes.h, common/shareddb.cpp, zone/inventory.cpp
- Noticed some data types were `uint32` when they should be `int32` based on Live items having these stats as negatives.
- Loregroup was `uint32` and should be `int32` for Loregroup -1, fixed any references to -1 as 0xFFFFFFFF.
- Attack was `uint32` and should be `int32`.
- DamageShield was `uint32` and should be `int32`.
- DotShielding was `uint32` and should be `int32`.
- Endurance was `uint32` and should be `int32`.
- EnduranceRegen was `uint32` and should be `int32`.
- Haste was `uint32` and should be `int32`.
- ManaRegen was `uint32` and should be `int32`.
- Regen was `uint32` and should be `int32`.
```cpp
RULE_BOOL(Items, DisableAttuneable, false, "Enable this to disable Attuneable Items")
RULE_BOOL(Items, DisableBardFocusEffects, false, "Enable this to disable Bard Focus Effects on …
```
=> [Rules] Add Rules to disable various item functionalities and cleanup data types.

zone/mob.cpp
Original condition `IsClient() & spells[spell_id].effect_id[effect_slot] == SE_Chance_Best_in_Spell_Grp` will evaluate `spells[spell_id].effect_id[effect_slot] == SE_Chance_Best_in_Spell_Grp` first, then `IsClient() & <bool>` will evaluate.
New condition will evaluate in expected left to right order. Results are expected to be the same (`bool & bool` should equal `bool && bool`)
=> [Bug Fix] Correct (probably) unintended bitwise AND instead of logical AND

zone/command.cpp, zone/gm_commands/spawneditmass.cpp
- Split command into its own file.
=> [Commands] Cleanup #spawneditmass Command.

common/shareddb.cpp
- `combateffects` and `charmfileid` were varchar and have no default value, so if you passed '' shared memory would fail, default these to 0 to prevent this.
=> [Cleanup] Add Validation to varchar number item fields.

common/classes.cpp, common/classes.h, common/ruletypes.h, zone/attack.cpp, zone/client_packet.cpp, zone/gm_commands/findclass.cpp, zone/gm_commands/npcedit.cpp, zone/lua_general.cpp, zone/mob.cpp, zone/mob.h, zone/npc.cpp, zone/zonedb.cpp, zone/zonedump.h
- Add NPC:DisableLastNames to disable NPC Last Names.
- Fix #npcedit lastname to allow you to use an empty string.
=> [Rules] Add Rule to Disable NPC Last Names.

zone/command.cpp
Quicker than porting to std::unique_ptr since we do fun stuff with
commandlist ...
=> [Memory Leak] Fix leak of CommandRecords in commandlist

common/ruletypes.h, zone/attack.cpp, zone/mob.cpp
- Add Combat:FrontalStunImmunityClasses rule for determining Frontal Stun Immunity by class bitmasks
- Add Combat:FrontalStunImmunityRaces rule for determining Frontal Stun Immunity by race bitmasks
- Add Combat:NPCsUseFrontalStunImmunityClasses rule for determining if NPCs use Frontal Stun Immunity by class bitmasks
- Add Combat:NPCsUseFrontalStunImmunityRaces rule for determining if NPCs uses Frontal Stun Immunity by race bitmasks
- Cleanup GetDefaultGender() as best as possible with the globalload I have.
- Combat:NPCsUseFrontalStunImmunityRaces defaults to true as NPCs currently use Frontal Stun Immunity.
- Added **all** Ogre races to the check for Frontal Stun Immunity.
=> [Rules] Add Frontal Stun Immunity Rules.

zone/trading.cpp
Corrected fields that the bazaar search function is using to prevent mysql error due to non-existant field items.spellid.
=> [Bug Fix] Bazaar Search MYSQL Error

zone/lua_mod.cpp, zone/lua_parser.cpp
EventItem was leaving the package table on the stack in successful
(non-encounter) calls and only popping the return. All events were
also leaking the full stack on lua_pcall errors. Lua mod callbacks
were popping error returns but leaking the table.
=> [Bug Fix] Fix stack leaks in Lua events

zone/tradeskills.cpp
When trying to fully script a combine so the tradeskill itself does not return an item (Item 0) and handling all items through quests, the source will provide an error regardless that "Item 0 does not exist". This change will move the item summon after the validity check thus preventing the error to the client.
=> [Bug Fix] Tradeskill Item 0 Error

common/eq_packet_structs.h, zone/client_packet.cpp
- These messages are only sent when you loot a corpse that is mid-decay (i.e. no items and you go to loot it immediately) or if you try to loot a non-corpse entity.
- The ent != 0 shows up a lot if you're trying to loot too quickly and really isn't an error, the server just hasn't caught up to decay the corpse before you try to loot.
- Add LootItem_Struct to give more verbosity to Handle_OP_LootItem.
=> [Loot] Remove unnecessary loot error messages.

zone/trading.cpp
More leakage fixes. This time return values of ZoneDatabase functions were checked for leaks.
=> [Bug Fix] Free return value of ZoneDatabase::LoadTraderItemWithCharges()

common/ruletypes.h, zone/spells.cpp
Adds a rule to disable combat range requirement for spell target type "Target's Target".
=> [Spells] Target's Target Combat Range Rule

zone/mob.cpp, zone/mob.h, zone/mob_movement_manager.cpp, zone/npc.cpp, zone/waypoints.cpp
If a boat spawn point or waypoint had a Z value that caused the code to no longer see the boat in water, even though a great deal of the boat was below water. FixZ would kick in.  This can cause massive issues to clients viewpoints of the boat (other than the client riding the boat) - causing some people that zone in after the FixZ to see the boat and rider underwater.
This is a tiny patch to avoid the issue in general - but I'll be looking to touch up my Boat navigation in movement_manager to be more in sync with how the client deals with Z for boats.
=> [Fix] Boats should never get FixZ'd

common/net/console_server_connection.cpp, world/console.cpp, world/zoneserver.cpp
- Will allow you to send guild-specific messages from things like Discord EQ.
- Add Guild support in `EQ::Net::ConsoleServerConnection::SendChannelMessage` so guild ID can be parsed out.
- Fix Auction messages not sending to telnet (thanks @xackery).
=> [Telnet] Add guildsay to console commands and Guild Channel to QueueMessage.

common/ruletypes.h, zone/client_packet.cpp, zone/string_ids.h
During some point in the eras you were not able to Bind Wound or Forage when mounted. I am not sure if Live is still like this, so I added a rule with it disabled by default.
=> [Feature] Bind Wound and Forage while mounted.

zone/client_packet.cpp, zone/npc.cpp, zone/string_ids.h
The pick pocket skill should only work on certain body types.
The pick pocket skill should not allow picking items that are wielded.
Verified on live (though some mobs are marked as humanoid on live that are questionable - this will be a db issue).
=> [Feature] Add humanoid and non-wielded restrictions to pick pocket

zone/loottables.cpp
NPCs and pets that wield a weapon with a proc were getting the proc added twice to the in memory tables.  
This also caused pets to sometimes proc weapons that should not proc for their level, while sometimes yielding the "not able to command this weapon" other times.
Tested thoroughly with the fix.
=> [Bug Fix] NPCs were getting weapon proc added twice

common/eqemu_config.cpp, common/eqemu_config.h, common/ip_util.cpp, common/ip_util.h, world/main.cpp, world/world_config.cpp, world/world_config.h
**What**
This PR implements a mechanism in which informs new server operators that they may have a misconfiguration in their server config.
This is by far one of the most common issues of setting up a new server that are not immediately obvious to new operators and this is a way to help them before they reach support channels
* Resolves world `address` DNS when DNS record present to prevent from creating warnings from mismatch
* Detects when using meta-address `0.0.0.0` for `address`
* Detects when using meta-address `0.0.0.0` for `localaddress`
* Detects when in a Docker environment and configuration for `localaddress` or `address` is not correct
* Detects when UCS `host` addresses are different from `address`
* Detects when World `address` differs from publicly auto-detected address
* …
=> [Server] Configuration Issues Checker (LAN Detection)

world/main.cpp
**What**
* Move **eqemu_server.pl** download responsibilities to be handled natively in World using `httplib` versus using Perl LWP
* No longer write `eqemu_server.pl` if we do not get a status `200` from Github
* Force a re-download of the utility script if the file is zero size or has less than 100 bytes (Replace file checks with C++17 native checks when we migrate)
=> [Server Maintenance Script] Improvements to Downloading - Empty File Detection

zone/zoning.cpp
=> [Bug Fix] String comparison issues in Client::SendZoneFlagInfo

common/eqemu_logsys.cpp
This PR fixes a GMSay Log regression caused by https://github.com/EQEmu/Server/pull/2140
**Before**
**After**
=> [Logs] Fix GMSay Log Regression

zone/task_client_state.cpp
Live places item rewards into the first free inventory slot and only
places it on the cursor if inventory is full
This was more of a pet peeve than a critical fix, but it's parity with live
=> [Tasks] Place task item rewards in free slots

common/crash.cpp
**What**
Linux crash dumps used to be a lot of work to get working and configured even for those experienced with Linux. 
Several years ago we automated running `GDB` and automatically parsing the `core` file but it requires elevated access and also requires `GDB` to analyze the dump. 
Both requirements are not obvious to operators still and this PR makes it clear to the user
This PR adds validation when a crash dump occurs and informs the user during the event of a crash in the crash log
**Passwordless Sudo Validation**
This validates when not running as root (not recommended to run as root)
```
[World] [Crash] [Error] Current user does not have passwordless sudo installed. It is required to automatically process crash dumps with GDB as non-root.
```
**GDB Installation Validation**
This …
=> [Crash] Linux Crash Dump Improvements

world/login_server.cpp
Today we have terrible, vague messages for when a new operator installs a new server and tries to connect it to the Legacy EQEmulator Loginserver. Users simply get the error message
This error comes from the loginserver itself, it's not super descriptive and doesn't tell the user hardly anything and usually it is ambiguous until someone on Discord informs a user what the cause of the error is.
This PR adds more descriptive erroring so its more clear to users what action should be taken to remediate. Including the source loginserver address and reason for the error with a link to where to remediate
**Before**
```
[World] [Error] Error [Worldserver Account / Password INVALID.]
```
**After**
```
[World] [Info] Login server [login.eqemulator.net:5998] responded with fatal error [Worldserver …
```
=> [World] Add More Descriptive LS Auth Error Message

zone/gm_commands/logs.cpp
This PR adds improvements to the `#logs list` command that adds clickable saylinks for each log category.
If the logging level is already active, it is shown without a saylink as a white number, otherwise it is printed as a clickable saylink to activate the logging category for that category.
This does remove the popup as your focus will remain in the chat window for listings options. This still keeps paging as it was
**In-Game Example**
=> [Logs] #logs list Improvements

common/repositories/base/base_zone_repository.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_09_zone_expansion_deprecate.sql, zone/zoning.cpp
We historically had a cosmetic `expansion` field in the `zone` table used to show what expansion zones were associated with. This had been used in some tools like the PEQ editor and was used very early in the source for expansion zoning validation before we had introduced content filter fields `min_expansion` `max_expansion` `content_flags` `content_flags_disabled` at the `zone` level.
This PR deprecates `expansion` and sets all values of `expansion` to `min_expansion` and drops the `expansion` field to reduce confusion and duplication.
Tested cross-expansion zoning after changes.
Related issue https://github.com/EQEmu/Server/issues/2280
=> [Zone] Deprecate Zone `expansion` Field

common/repositories/base/base_task_activities_repository.h, common/tasks.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_09_task_zone_version_matching.sql, zone/task_client_state.cpp, zone/task_client_state.h, zone/task_manager.cpp
This PR allows a server operator to filter task activity updates to a specific zone version if desired. Default behavior is to have the field set to `-1` so no behavior change by default. 
For example, if I have a kill goal match list of `gloomingdeep grunt|rat|goblin` and I only want instance version `1` to provide updates on those matches, I would set `zone_version` on the activity row to `1`
To further this explanation for this, you need this to prevent a name match from being exploitable in different versions of the same zone. While this very edge case, its still possible and gives operators the ability to more specifically target and filter down not just at the zone level, but zone version level as well.
**Possible Concern**
One consideration is that zones can have many entries for …
=> [Tasks] Zone Version Matching

tests/string_util_test.h
This was testing the old std::string EscapeString(const char *src,
size_t sz) which was removed since it's not used anywhere else.
=> [Bug Fix] Remove StringUtilTest::EscapeStringMemoryTest

common/repositories/base/base_character_tasks_repository.h, common/tasks.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_10_character_task_rewarded.sql, zone/task_client_state.cpp, zone/task_client_state.h, zone/task_manager.cpp, zone/task_manager.h
If a member is offline (or possibly during a race while zoning?) when
the shared task is completed they will not receive the reward. On live
the character receives their reward (with an updated replay timer) if
they enter back into game while the shared task is still active. They
keep the original replay timer if the shared task is no longer active
and do not receive a reward.
This makes it so clients are issued rewards (and a task completed
event is dispatch) if the client's task state was out of sync with a
completed shared task. To prevent characters being rewarded more than
once in case of bad sync checks, a 'was_rewarded' field has been added
to the character_tasks table and updated when rewards are assigned.
This fixes a couple bugs so the character_activities table is correctly …
=> [Tasks] Reward clients on shared task completion sync

zone/gm_commands/loc.cpp
I do have a question:
why the bme variable that was never used?  Should it have been used instead of me?
=> Fix bestz to work on client or target.

common/content/world_content_service.cpp
Fixes regression caused by https://github.com/EQEmu/Server/pull/1940 where when set to expansion `-1` (All) runtime filtering was preventing `min_expansion` 8 in the reported case from dropping
**Example**
Huffin reported from PEQ that Ailing Walrus was not dropping Savage Lord Totem Epic drop https://everquest.allakhazam.com/db/item.html?item=30533
Validated fixed
=> [Content Filter] Fix Runtime Filtering When Set to -1 (All)

common/say_link.cpp
If a message was longer than 50 characters with "00000" somewhere in the
message (such as messages with hex numbers) then the saylink injection
method was sending a blank message to the chat window.
This refactors the saylink injection method using a crude state machine
to build the output. It should function the same:
- Inner-most brackets generate saylinks when nested
- Saylinks are not generated in brackets that already have a saylink
- Existing saylinks are preserved
- Existing saylinks that contain text with brackets do not attempt to
generate saylinks
- Saylinks are not generated if brackets contains leading or trailing
spaces (e.g. [ spaces ])
---
Original bug:
```lua
e.other:Message(MT.White, "following message broken:")
e.other:Message(MT.White, "This message is over 50 …
```
=> Refactor saylink injection

zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/client_process.cpp
Consolidates "moving" tracker member variables and fixes `IsMoving` Mob export for Client instead of just NPC
**Testing**
=> [Client] Fix IsMoving for Client

common/net/daybreak_connection.cpp
When a packet was over max_raw_size and zlib failed to compress the
first packet chunk then the final output would be 513 bytes which
exceeded m_max_packet_size of 512.
This occured because the first packet chunk used sublen without
adjusting for the new_length + 1 compression flag added in Compress().
When the packet failed to compress then it was already at its max.
After the first packet, chunk sizes are calculated using max_raw_size
which already accounted for the compress flag. (From #979)
This should fix #2325
Kinda surprised this hasn't caused issues before this, it must be a really rare edge case
=> Adjust first packet for compress flag

zone/client_packet.cpp
Returning non-zero from EVENT_CLICK_DOOR will prevent the default
handler.
This should have been implemented when expeditions were put in to
allow scripts to prevent zoning out of vxed and tipt without flags.
Some upcoming changes may need this to allow scripts to prevent
automatic dz entry.
=> Allow scripts to prevent door click

common/repositories/base/base_tasks_repository.h, common/tasks.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_13_task_reward_points.sql, zone/task_client_state.cpp, zone/task_manager.cpp
This replaces the separate DoN crystal reward fields with points and
point_type fields. This will make it easier to import data from
packet/client captures and possibly better support any future clients
or tasks that don't reward through the newer reward window.
=> [Tasks] Add Task Reward Points Field

common/ruletypes.h, zone/forage.cpp
- Added rule to allow the adjustment of zone foraging %
=> [Rules] Add adjustment for zone forage.

zone/mob_ai.cpp
While debugging roam boxes under water, I found the log messages were not populating the data fields.  Fixed this.
I also found that the calls to FindPath were very often not finding tiles from start/end when mob started in a water position, causing them to never move and just spew logging errors.
Looking into this, the calls in the mob_ai roambox call to FindPath() are really unneeded and do not take into account terrain.  Simply allowing the Movement Manager code to handle this fixed all my issues, and movement manager has the stuck behavior code as well, which was being bypassed by this pre-emptive check in the roambox code.
=> [Roambox] Improve Path Finding

zone/task_client_state.cpp
Live sends the task updated message for every solo quest and task
increment (not just goal completed).
Also changed color to what live uses now. There are some other color
changes with shared task messages but they correspond with colors
changed in client generated messages but probably not worth chasing
down and causing inconsistency.
=> Send message for all solo task updates

common/eq_packet_structs.h, common/servertalk.h, zone/entity.cpp, zone/entity.h, zone/lua_mob.cpp, zone/lua_mob.h, zone/mob.cpp, zone/mob.h, zone/perl_mob.cpp
This was implemented in a very odd way. The intensity is just a float.
This is a breaking api change but low-impact (intensity will be
different).
To convert old values to new values with same intensity:
0: 0.03125
1: 0.05625
2: 0.1
3: 0.175
4: 0.3
5: 0.5
6: 0.9
7: 1.6
8: 2.8
9: 4.8
10: 8.0
=> [Quest API] Use Floating Point for CameraEffect Intensity

common/repositories/base/base_account_repository.h, common/shareddb.cpp, common/shareddb.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_28_gm_state_changes.sql, world/zoneserver.cpp, zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/command.cpp, zone/command.h, zone/gm_commands/flymode.cpp, zone/gm_commands/godmode.cpp, zone/gm_commands/invul.cpp, zone/inventory.cpp
- Flymode and Invulnerable will now persist over zoning.
- Appended GMSpeed, Flymode and Invulnerable to the hideme message GMs see when they first login.
- Added #godmode [on/off] command to turn on or off hideme, flymode, gmspeed and invulnerable all in one shot.
- /becomenpc will now disable tells to the target player. It will also automatically disable GM States that interfere with its functionality.
- GM Command /toggle will not properly turn tells on/off
- GMs will now be notified if they are ignoring tells when they first zone-in, provided their GM flag is up.
- Added TellsOff variable to the output to #showstats
=> [Feature] GM State Change Persistance

common/repositories/base/base_tasks_repository.h, common/shared_tasks.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_13_task_lock_activity.sql, world/shared_task_manager.cpp, world/shared_task_manager.h, world/shared_task_world_messaging.cpp, world/zoneserver.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/task_client_state.cpp, zone/task_client_state.h
This adds the `lock_activity_id` field to the tasks table which will
automatically lock a shared task when that element becomes active.
A method was added to world analogous to zone's UnlockActivities to
determine when an activity is active with respect to task steps.
Also adds quest apis to manually lock or unlock a client's shared task
=> [Shared Tasks] Implement Activity Locking

common/repositories/base/base_character_task_timers_repository.h, common/repositories/base/base_tasks_repository.h, common/tasks.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_16_task_timer_groups.sql, world/shared_task_manager.cpp, world/shared_task_manager.h, zone/task_client_state.cpp, zone/task_manager.cpp
This adds task replay and request timer groups (an arbitrary id) which
allows for different tasks to share lockouts
=> [Shared Tasks] Implement task timer groups

common/shared_tasks.cpp, common/shared_tasks.h, common/tasks.h, world/shared_task_manager.cpp, world/shared_task_manager.h, world/shared_task_world_messaging.cpp, world/zoneserver.cpp, zone/client_packet.cpp, zone/shared_task_zone_messaging.cpp, zone/task_client_state.cpp, zone/task_manager.cpp, zone/worldserver.cpp
Functionally nothing should change in this patch. This refactors a lot
of formatting and code duplication in requests and member removals.
The long SharedTaskMessage namespace and its constants were contributing
to a lot of formatting that was difficult to read. These were shortened
since they're not all shared task specific anyway (though they should
probably just be moved to string_ids.h with other eqstrs now)
Shared task requests were refactored a little to remove an unnecessary
function that filled potential members. The separate functions used for
/taskquit and /taskremove were also combined into a single function to
remove a member while preserving live message differences.
=> [Shared Tasks] Cleanup shared task request and remove

common/ruletypes.h, common/shared_tasks.h, common/tasks.h, world/main.cpp, world/shared_task_manager.cpp, world/shared_task_manager.h
This verifies a shared task's minimum players requirement is still met
when a member is removed and schedules it for termination if not
=> [Shared Tasks] Enforce task reqs on player removal

common/tasks.h, zone/client.h, zone/doors.cpp, zone/task_client_state.cpp, zone/task_client_state.h
This changes task touch elements to use the dz_switch_id as the goal id
instead of checking if a player zoned. It will remove the need to script
door clicks or modify task element zone field since task packet data can
just be imported.
=> [Tasks] Use dz switch id for task touch events

common/CMakeLists.txt, common/database_schema.h, common/dynamic_zone_base.cpp, common/dynamic_zone_base.h, common/repositories/base/base_dynamic_zone_templates_repository.h, common/repositories/base/base_tasks_repository.h, common/repositories/dynamic_zone_templates_repository.h, common/servertalk.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_23_dz_templates.sql, world/dynamic_zone_manager.cpp, world/dynamic_zone_manager.h, world/shared_task_manager.cpp, world/shared_task_manager.h, world/world_boot.cpp, world/zoneserver.cpp, zone/client.cpp, zone/client.h, zone/gm_commands/reload.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp, zone/worldserver.cpp, zone/zone.cpp, zone/zone.h
This allows shared tasks to create dz instances automatically through
the `dz_template_id` field instead of using quest scripts. Quest apis
were also added to create expeditions from template ids.
=> [Dynamic Zones] Implement dz templates

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_07_30_merchantlist_temp.sql, zone/zone.cpp, zone/zonedb.cpp, zone/zonedb.h
This prevents issues with a merchant being in more than one zone as well
as guild hall merchants sharing a list of temp items
=> [Bug Fix] Limit merchant temp item list to zone and instance

common/ruletypes.h, common/shared_tasks.cpp, common/shared_tasks.h, world/shared_task_manager.cpp, world/shared_task_manager.h
This wasn't safe since the erase would invalidate iterators used
internally by the range loops.
Shared tasks with no members are now also cleaned up
Make GetMembers return reference instead of copy (this is used a lot)
Add rule for shared task terminate time for easier debugging
=> [Shared Tasks] Avoid erasing shared tasks while iterating

zone/task_client_state.cpp
This was causing #task reloadall to desync state for shared tasks.
Characters were removed from the shared task but remained in the
character_tasks table. This CancelTask is cosmetic only to reload
the client window.
=> [Tasks] Make #task reloadall not quit shared tasks

zone/lua_general.cpp
This was leaving the task count at 0 if called with more than the max
number of tasks (40)
Noticed this because one of the DoN missions on live is assigned to the wrong npc which makes it offer up to 41 tasks
=> [Quest API] Fix lua task selector count when over max

common/repositories/base/base_account_repository.h, common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_08_01_drop_expansion_account.sql
PEQ has this in the accounts table for some reason, it's not actually used, therefore repositories are being generated for a column that some people don't have.
This fixes consistency issues
=> [Hotfix] Remove expansion field from account for those who have it

common/ruletypes.h, zone/client.cpp
With the recent changes to #hideme as of #2328, tells are disabled to hidden GMs, meaning a GM must show themselves in order to receive tells.
=> [Rules] Add Rule to Enable Tells with #hideme

zone/perl_mob.cpp
- Add $mob->GetSkillDmgAmt(skill_id) to Perl.
- This already exists in Lua, but not Perl.
- Perl Test Script:
```perl
if ($text=~/#b/i) {
foreach my $skill_id (0..77) {
my $extra_skill_damage = $client->GetSkillDmgAmt($skill_id);
if ($extra_skill_damage > 0) {
my $skill_name = quest::getskillname($skill_id);
quest::message(315, "$skill_name: $extra_skill_damage");
}
}
}
}
```
=> [Quest API] Add GetSkillDmgAmt() to Perl.

zone/client.cpp, zone/client_packet.cpp, zone/doors.cpp, zone/doors.h, zone/gm_commands/door_manipulation.cpp, zone/npc_scale_manager.cpp
This PR is in response to https://github.com/EQEmu/Server/issues/2367
**Changes**
* Simplified the saylink menu building
* Fixed a bug where `Doors` scoped variables were the same as variables being passed in so member variables were not being set and creating uninitialized behavior - resulting in created objects being incredibly small or large
* Refactored private member variables to be `m_` prefixed for readability and addressing / preventing the above issue from happening again
* Silent saylinks now pipe to commands (So when a saylink is clicked it doesn't result in. "You say, "message"")
* NPC Scale Manager now skips the door helpers because they have no NPC type ID assigned
* The door menu no longer prints every time a command is clicked (because silent saylinks now work)
* All door …
=> [Doors] Improvements to door manipulation

zone/attack.cpp, zone/client.cpp, zone/entity.cpp, zone/gm_commands/emotesearch.cpp, zone/mob.h, zone/mob_ai.cpp, zone/npc.cpp, zone/npc.h
emoteid packet structure is UINT32 but a number of references are in UINT16.
=> [Bug] UINT32 EmoteID

utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_08_14_exp_modifier_instance_versions.sql, zone/client.h, zone/embparser_api.cpp, zone/exp.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/lua_general.cpp, zone/perl_client.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/zonedb.cpp, zone/zonedb.h
Allows Operators to set experience modifiers to be instance version specific so that you can have different versions of the same zone have different modifiers.
If there is not one found, it defaults to `zone_id` 0 for global and `instance_version` -1 for global.
=> [Feature] Instance Version Specific Experience Modifiers

zone/client.cpp, zone/client.h, zone/lua_client.cpp, zone/lua_client.h, zone/perl_client.cpp
These methods will allow server operators to teleport players directly to other players via the quest API using the #goto command's functionality.
- Add $client->TeleportToPlayerByCharID(character_id) to Perl.
- Add $client->TeleportToPlayerByName(player_name) to Perl.
- Add $client->TeleportGroupToPlayerByCharID(character_id) to Perl.
- Add $client->TeleportGroupToPlayerByName(player_name) to Perl.
- Add $client->TeleportRaidToPlayerByCharID(character_id) to Perl.
- Add $client->TeleportRaidToPlayerByName(player_name) to Perl.
- Add client:TeleportToPlayerByCharID(character_id) to Lua.
- Add client:TeleportToPlayerByName(player_name) to Lua.
- Add client:TeleportGroupToPlayerByCharID(character_id) to Lua.
- Add client:TeleportGroupToPlayerByName(player_name) to Lua.
- Add …
=> [Quest API] Add Goto Player Teleport Methods.

common/spdat.h, zone/effects.cpp, zone/merc.cpp, zone/mob.h, zone/perl_mob.cpp, zone/perl_npc.cpp
Changed Spell Mana Costs from Unsigned Int16 to Signed Int32.
=> [Feature] Change Mana Costs to use Signed Int

zone/client_packet.cpp
Clicking silent saylinks was sending the message twice if you had an NPC targeted due to duplicate code within ChannelMessageReceived.
=> [Bug Fix] Fix Duplicate Silent Saylink Messages

common/repositories/base/base_task_activities_repository.h, common/shared_tasks.h, common/tasks.h, common/version.h, tests/CMakeLists.txt, tests/main.cpp, tests/task_state_test.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_08_08_task_req_activity_id.sql, world/shared_task_manager.cpp, zone/task_client_state.cpp, zone/task_client_state.h, zone/task_manager.cpp, zone/task_manager.h
Some live tasks make new elements available without requiring all
currently active ones to be completed first.
This adds the `req_activity_id` field to task activities which will mark
an element active if its required activity id is completed. If a valid
value is set then it's used instead of checking the current step.
The `step` field may still be set on rows with a valid `req_activity_id`
to specify its logical step and prevent later steps from becoming active
until completed. It's only ignored when deciding if the current element
is active.
The legacy task logic for unlocking activities was completely refactored
for this. A common method has been added so both zone and world can make
use of it to determine which elements are currently active. The previous
step system should remain …
=> [Tasks] Implement Task Activity Prerequisites

zone/client.cpp, zone/client.h, zone/client_packet.cpp, zone/perl_client.cpp
Silent saylinks wouldn't send to sender, but to everyone else, so they could see what your saylinks were.
Added an optional `is_silent` bool to ChannelMessageReceived to account for this where necessary.
=> [Bug Fix] Fix Silent Saylinks Sending Message to Others.

zone/client.cpp, zone/client.h, zone/embparser_api.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/lua_general.cpp, zone/perl_client.cpp, zone/questmgr.cpp, zone/questmgr.h
- Add $client->GetRecipeMadeCount(recipe_id) to Perl.
- Add $client->HasRecipeLearned(recipe_id) to Perl.
- Add quest::getrecipemadecount(recipe_id) to Perl.
- Add quest::getrecipename(recipe_id) to Perl.
- Add quest::hasrecipelearned(recipe_id) to Perl.
- Add client:GetRecipeMadeCount(recipe_id) to Lua.
- Add client:HasRecipeLearned(recipe_id) to Lua.
- Add eq.get_recipe_made_count(recipe_id) to Lua.
- Add eq.get_recipe_name(recipe_id) to Lua.
- Add eq.has_recipe_learned(recipe_id) to Lua.
=> [Quest API] Add Recipe Methods

zone/questmgr.cpp, zone/questmgr.h
Currently, you have to create the instance with a client initiator, whether that's in an NPC's EVENT_SAY /EVENT_ITEM or in a player script.
This will allow you to create instances without needing a client, but if there is one and there are errors, the messages will be sent to the client.
=> [Quest API] Allow CreateInstance to be used without a Client initiator.

world/shared_task_manager.cpp
The default for this field is -1 not 0, so on world restarts this was
marking all elements completed
=> [Bug Fix] Fix loading world shared task state

common/strings_legacy.cpp
Windows and Linux use different data models on 64 bit systems so "%lld"
isn't the same on them.
=> [Bug Fix] Use macro to generate correct format specifier

common/strings.cpp, common/strings.h, tests/string_util_test.h
std::from_chars floating point support is still pour, so we provide some
fall backs. These fall backs currently lack error handling.
(since GCC 11 and MSVC 2019 16.4 FP support is added, clang with libc++
still doesn't support FP)
GCC's floating point support is still rather pour (performance) and
probably shouldn't be used, but we have support to if people want to
now.
Probably need more test cases ...
=> [Utility] Add std::string_view overloads for std::from_chars

zone/loottables.cpp
Loot Table currently favors the first item in the loot drop. This should help remove that condition.
Code by Ailia.
=> [Bug] Loot Drop Randomization adjustment

zone/client.cpp, zone/client.h
Arg was shadowing the member variable and we weren't updating the member
variable
=> [Bug Fix] Resolve issues with Client::SetHideMe

zone/raids.cpp
We're checking if they're groupless here, so this should be correct now
=> [Bug Fix] Resolve logic error in Raid::QueueClients

common/discord_manager.cpp
Erasing from the map inside the range loop invalidated the iterator used
internally by the loop. This caused ucs access violations under msvc
debug builds when a discord logging category was enabled.
=> [Bug Fix] Avoid erase in discord queue range loop

common/zone_store.cpp, world/zoneserver.cpp, zone/client_packet.cpp, zone/zoning.cpp
This PR addresses both issues that I introduced from https://github.com/EQEmu/Server/pull/2388 and furthermore cleans up around the originally refactored areas
**Issue**
Zone flags were getting corrupted in c-string format, usage of those c-strings have been removed for the more modern std::string container and related checks have been adjusted accordingly. Because it was corrupted, zones always thought they had zone flags to check and clients always did not meet zone requirements. This coupled with another long time issue addressed in this PR was causing clients to go an infinite loop, looping between arena and the zone they didn't meet requirements for.
**Resolution**
This infinite loop was caused by a race condition of world not entirely being up to date on where the client has …
=> [Zoning] Fix zoning logic issues

zone/lua_npc.cpp, zone/lua_npc.h, zone/npc.cpp, zone/npc.h, zone/perl_npc.cpp
- Add $npc->ReloadSpells() to Perl.
- Add npc:ReloadSpells() to Lua.
Example of using ScaleNPC method with various levels on an NPC with spells.
**Level 62 Rytan**
**Level 20 Rytan**
**Level 1 Rytan**
Previously, you would you have to manually call RecalculateSkills() after you scale the NPC, now the call is built in to the scaling.
Spells did not reload when NPCs were scaled, causing them to continue to use their low/high level spells depending upon which way their level had been scaled, this has been adding to the scaling method. This will make NPCs properly use their level-based spells.
RecalculateSkills() and ReloadSpells() can still be used manually if people scale using something other than the source scaling method. Having this functionality built in to the scaling itself just …
=> [NPC Scaling] Recalculate Skills and Reload Spells on Level Change

zone/client.h, zone/embparser_api.cpp, zone/lua_client.cpp, zone/lua_client.h, zone/lua_general.cpp, zone/perl_client.cpp, zone/questmgr.cpp, zone/questmgr.h, zone/task_manager.cpp, zone/task_manager.h
Some live npcs ignore the request cooldown timer (tutorialb)
A separate function had to be used for perl because the apis use an
array instead of array reference which won't allow a bool overload
This also replaces the fixed array and count args with a vector
=> [Tasks] Make Task Selector Cooldown Optional

world/shared_task_manager.cpp
This prevents re-triggering completion when a shared task contains
optional elements
=> [Tasks] Only allow shared task completion once

common/ruletypes.h, zone/task_client_state.cpp
On live if a task update would affect multiple elements, only the first
one gets updated. This was added as part of the changes in 7482cfc0.
Setting `UpdateOneElementPerTask` to false will restore the old behavior
that increments all active elements matching the task update criteria.
=> [Tasks] Add rule to update multiple task elements

zone/npc.cpp, zone/waypoints.cpp
Issue originally reported in #support-pathing (Discord) by Symetrix.
**Reproduction**
Pull Xygoz in Veeshan's Peek up/down steep hill from spawn and he will clip in and out of the floor
**Problem(s)**
1. Xygoz is a fixed race model (5 size is default) but the server data has him set to 1
2. Dragon race 49 is missing proper Z offsets for its model
**Solution(s)**
* Updated GetZOffset to include remaining models from `Resources/SPOffsets.ini`
* Set static race dragon (49) to always be size 5 regardless of what is set in the database
Both of these solutions combined result in a dragon that does not clip through the floor under steep terrain and calculates Z positioning correctly with the server
=> [Pathing] Fix pathing z-correctness for certain models

common/spdat.h, zone/spell_effects.cpp
Type 49545 - endurance or mana drops below 10%
Used in live spell Reaver's Bargain, doesn't appear to have any corresponding message in live dbstr.
=> [Feature] Add Type 49545 to Spell Resistrictions

zone/lua_parser.cpp, zone/lua_parser.h, zone/quest_interface.h, zone/quest_parser_collection.cpp, zone/quest_parser_collection.h, zone/trading.cpp
This fixes an edge case where trading would not detect the npc had a quest handler if it was registered inside a Lua encounter.
=> [Quest API] Let HasQuestSub check encounters

zone/mob_ai.cpp
Flurry & Rampage messages will now filter to proper chat window (Pet Flurry/Rampage filter) instead of using NPC Flurry/Rampage chat window filtering.
=> [Bug Fix] Fix Swarm Pet Flurry/Rampages Messages

common/CMakeLists.txt, common/stacktrace/backward.hpp, common/zone_store.cpp, world/cli/test.cpp, world/zoneserver.cpp, world/zoneserver.h
**Issue**
Folks are seeing 
```
[World] [Info] [GetZoneName] Failed to get zone name by zone_id [0] error_unknown [false]
[World] [Info] [GetZoneName] Failed to get zone name by zone_id [0] error_unknown [false]
[World] [Info] [GetZoneName] Failed to get zone name by zone_id [0] error_unknown [false]
[World] [Info] [GetZoneName] Failed to get zone name by zone_id [0] error_unknown [false]
```
Which are logs added recently to trap logic that shouldn't be occuring in the first place. We should not see this function get called with a `zone_id` of 0
Since this is called everywhere, we need to be able to see the stack, caller. Added https://github.com/bombela/backward-cpp cross-platform header library to print the stack when this log is produced to give more meaningful information.
Also fixed …
=> [Logging] Add stack trace in code paths that shouldn't occur

common/version.h, utils/sql/db_update_manifest.txt, utils/sql/git/required/2022_09_28_discord_webhooks.sql
There's been instances where this has been repeatedly getting missed even though a CREATE and an ALTER runs together in the same file. The CREATE has been running without the ALTER. This is a no-op for folks who have the columns and catches it for those who aren't getting the update in the earlier migration
=> [Database] Add fallback migration for logsys columns

zone/api_service.cpp
**Trace**
```
[09-28-2022 20:38:31] [Zone] [Crash] C:\Code\Server\zone\zone.h (173): Zone::GetZoneID 
[09-28-2022 20:38:31] [Zone] [Crash] C:\Code\Server\zone\api_service.cpp (832): ApiGetLogsysCategories 
[09-28-2022 20:38:31] [Zone] [Crash] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\type_traits (1558): std::invoke<Json::Value (__cdecl*&)(EQ::Net::WebsocketServerConnection *,Json::Value),EQ::Net::WebsocketServerConnection *,Json::Value const &> 
[09-28-2022 20:38:31] [Zone] [Crash] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\functional (670): std::_Invoker_ret<Json::Value>::_Call<Json::Value (__cdecl*&)(EQ::Net::WebsocketServerConnection *,Json::Value),EQ::Net::WebsocketServerConnection …
```
=> [Crash] Websocket Crash fix race when fetching log categories

loginserver/client.cpp
Remove error log that largely confuses people anyways because its not really an error. This is captured in the new Client -> Server logging if the server operator or developer chooses to use it
=> [Logging] Remove loginserver unhandled error

zone/worldserver.cpp, zone/zone.cpp
**Issue** 
Global reload commands are crashing zone processes that are not booted. While this doesn't affect players, it still is killing all standby processes needlessly every time for several different reload types. Fixed by adding zone checks to most reload commands
**Stack Example (One of them)**
```
[Zone] [Crash] stack trace for /home/eqemu/code/build/bin/zone pid=1684
[Zone] [Crash] [New LWP 1685]
[Zone] [Crash] [New LWP 1686]
[Zone] [Crash] [New LWP 1687]
[Zone] [Crash] [New LWP 1688]
[Zone] [Crash] [Thread debugging using libthread_db enabled]
[Zone] [Crash] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Zone] [Crash] 0x00007fe79fce1207 in __GI___wait4 (pid=1754, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
[Zone] …
```
=> [Crash] Fix reload crashes

zone/spells.cpp
Death Touch targets the pet owner instead of the pet when said pet is tanking. via the rule CazicTouchTargetsPetOwner. 
Touch Of Vinitras was ignoring this rule.
=> [Bug Fix] Touch Of Vinitras was ignoring ignore Pets as target of Death Touch rule 

eqlaunch/eqlaunch.cpp, loginserver/main.cpp, queryserv/queryserv.cpp, world/main.cpp
Akkadius wanted me to change the executables that still were using event loop process to instead use event loop run because event loop process causes issues on windows under high load.
I ran through getting into a zone from login->world->zone and everything appears to work but could probably use some outside verification.
=> Change all executables to use the default event loop run

zone/client_packet.cpp
Force resending of position after client actually connects since the issue appears to be related to a race condition of packets and the client puts itself under the world, lets bring it back to where it should be (hopefully)
This might need additional investigation but is worth testing on PEQ test server
=> [Zoning] Possible zoning under world fix

zone/client.cpp, zone/client.h, zone/worldserver.cpp, zone/zone.cpp, zone/zoning.cpp
**Problem**
Players end up in seemingly random locations in the destination zone
This is a race condition that can occur on all servers, but shows itself more prevalent on servers like PEQ where folks are running 30-60 box armies.
When a player crosses a zone line, a save is issued in `character_data` representing the destination `zone_id` `zone_instance` and `x` `y` `z` etc. The receiving zone then loads this to place the character properly on the other side.
The race condition is that when players cross a zone line, while x/y/z gets saved, there is a small chance that the players current X,Y,Z in the zone prior to the actual zoning gets updated when the client sends its client position update one last time before the client gets deconstructed (Where save is called again, saving the …
=> [Zoning] Fix zone race condition

zone/effects.cpp, zone/questmgr.cpp, zone/questmgr.h
Songs weren't capable of being scribed from scrolls because we didn't check for `Song:` in the name.
Converted old logic to substrings, can probably do it cleaner, but it's better than it was.
Removed extraneous `initiator->IsClient()` calls as `initiator` is **always** a client.
=> [Bug Fix] Allow Songs to be scribed from scrolls

zone/botspellsai.cpp
This was preventing Nukes from using more complex spells such as the Wizard Claw Line, or any instant cast nuke with an additional trigger/effect.
=> [Bug Fix] Fixed Spell Logic for Bot Nukes

common/ruletypes.h, zone/exp.cpp, zone/string_ids.h
Will force unused AA points to the cap if they exceed the cap. Will also force AA Percentage to 0%. NOTE: The variable, UnusedAAPointCap, should NOT be lowered once implemented without first checking the DB for how many Unused AAs people have.  The next time they gain any EXP, it WILL drop them to cap.  Also, PCs should be given warning prior to this patch going to Live, to ensure they have a chance to spend any AAs above the cap, else they will lose them.
=> [Feature] AA Cap Limit

common/eq_constants.h, zone/attack.cpp, zone/client.cpp, zone/effects.cpp
Had to close old PR #2463, and resubmit due to deleted branch head. 
This adds support for the "Show Only Mine" Filter to function properly with the following Filter Types:
Spell Damage/Non-Melee Hits
Critical Melee Hits
Spell Crits.
Heal over Time.
Tested commits by setting up two characters, and going through all possible filters for the above fields.
=> [Feature] Add Support for "Show Mine Only" Filters

zone/aggro.cpp
Fixed formatting, and moved around statements.
Some Healing spells on live make use of both the Hate Override and Bonus Hate mod. This adds support for this.
This resolves https://github.com/EQEmu/Server/issues/874
=> [Feature] Add Hate Override for Heals

common/zone_store.cpp, common/zone_store.h, world/cli/test.cpp, world/clientlist.cpp, zone/gm_commands/zone.cpp
This PR addresses a few things from working with operators to get their servers fixed
* #zone command has extra validation to no longer crash on bad inputs. Also keeps zone from sending bad zone requests to world
* Zone store log helpers no longer print warnings that have become noise, making operators think there is a problem when certain logic safely uses some of the cases
* Remove stack trace debugging for zone store methods
=> [Crash] Stability Fixes

common/ruletypes.h, zone/client_packet.cpp
This adds a toggle to disable the Warrior shielding ability. This will not stop the client-side message from sending when you do not have a target, but it will keep the ability from doing anything.
This message will not be disabled, but when you have a target and use it, it will tell you it's disabled.
=> [Rules] Add Toggle for Warrior Shielding

common/emu_constants.h, common/eqemu_logsys_log_aliases.h, zone/bot.cpp, zone/bot.h, zone/botspellsai.cpp, zone/merc.cpp, zone/mob_ai.cpp, zone/npc.cpp, zone/npc.h, zone/zone.cpp, zone/zonedb.h
In Preparation of adding new Spell fields to Bot_Spells_Entries, I figured it would be easiest to separate the Spell functions Bots use.
This will reduce the chance of any issues popping up with NPC casting by splitting these off now.
Eventually I'd like to look into fully splitting off Bots.
=> [Bots] Cleanup Bot Spell Functions, reduce reliance on NPC Functions/Attributes

zone/client.cpp, zone/common.h, zone/lua_mob.cpp
This adds the IMMUNE_OPEN (53) special ability to prevent /open on LDON_TREASURE classes.
=> [Feature] Add special ability to block /open

zone/task_client_state.cpp, zone/task_client_state.h
Returning non-zero from EVENT_TASK_COMPLETE will prevent task rewards and completion emote. This is necessary for a DoN mission which scripts a mission failure but still gives the lockout.
=> [Tasks] Let task completion event block task rewards

common/emu_constants.cpp, common/emu_constants.h, zone/attack.cpp, zone/client.cpp, zone/command.cpp, zone/entity.cpp, zone/gm_commands/emotesearch.cpp, zone/gm_commands/emoteview.cpp, zone/mob_ai.cpp, zone/npc.cpp, zone/npc.h
Cleanup command messages and logic.
Add constants for Emote Events and Emote Types and replace all the old constants with the new constants.
**#emoteview**
**#emotesearch**
=> [Commands] Cleanup #emotesearch and #emoteview Command.

zone/perl_groups.cpp
- Add `$group->GetLowestLevel()` to Perl.
- This exists in Lua, but not Perl.
=> [Quest API] Add GetLowestLevel() to Perl.
