EQEmu/Server

zone/position.cpp

VS2013 wants <algorithm> included also, to be able to find std::min and std::max.  Enclosed test for MS in #ifdef if is not required by other toolchains.
(Note: came back & edited totally incoherent wee-hours subject line)

MS Visual Studio vs. position.cpp

---

zone/bot.cpp
zone/botspellsai.cpp
zone/client.cpp
zone/client_packet.cpp
zone/command.cpp
zone/corpse.cpp
zone/effects.cpp
zone/entity.cpp
zone/hate_list.cpp
zone/merc.cpp
zone/mob.cpp
zone/mob.h
zone/mob_ai.cpp
zone/perl_client.cpp
zone/position.cpp
zone/position.h
zone/raids.cpp
zone/special_attacks.cpp
zone/spells.cpp

removing the mob member functions for distance and using the position based ones.

Data bundling2

---

common/mysql_request_result.h
common/mysql_request_row.cpp
common/mysql_request_row.h

now we should be able to do
for (auto row : results)
{
row[4];
}
as well as:
auto row = results.begin();
row[0];

modified mysql results/row to be ready for range based for

---

zone/client_process.cpp

RoF+ can send 200 items to the client at a merchant. I've tested this with RoF, RoF2, and UF.

Rof merchantlist

---

zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp

Returns a bool if can equip or not.

Added perl function function: CanClassEquipItem(item_id)

---

zone/client.cpp
zone/client_packet.cpp
zone/client_process.cpp

Bind Wound/ShopPlayerBuy sanity checking to prevent exploits.

Sanity checking

---

zone/hate_list.cpp
zone/spells.cpp

Added additional check to prevent recourse spells from recoursing themselves and crashing.

Fix for taunt.

---

zone/perl_npc.cpp
zone/special_attacks.cpp

Minor fix to NPC ranged attack.

Fix for perl defensive/ranged proc function

---

zone/npc.cpp
zone/npc.h
zone/perl_npc.cpp

perl $npc->ChangeLastName(name)
perl $npc->ClearLastName()
Modifies NPC last names.

perl npc last name related functions.

---

common/skills.h
zone/bonuses.cpp
zone/mob.cpp
zone/perl_mob.cpp

Fix for perl GetModSkillDmgTaken

Fix for ModSkillDmgTaken to once again work with (-1 = ALL skills)

---

zone/perl_npc.cpp

$npc->RemoveMeleeProc(spell_id)
$npc->RemoveDefensiveProc(spell_id)
$npc->RemoveDefensiveProc(spell_id)

PERL remove proc functions

---

zone/client.cpp

Vendors sometime reject based on deity.  Added two possible messages that seemed to fit when that happened.  Previously had a human saying "don't humans like you"...  lol

Vendor message for rejection based on Deity

---

zone/attack.cpp

Quick patch to previous PR for safety.

Check to make sure we're a client before a CastToClient(). 

---

zone/embparser_api.cpp
zone/questmgr.cpp
zone/questmgr.h

Exporting ConnectNodeToNode and AddNode from Pathing to Perl so devs can more quickly build pathing with Perl script(s).

Exporting ConnectNodeToNode and AddNode (from Pathing) to Perl

---

zone/perl_npc.cpp

Revert "Making $npc->RemoveFromHateList actually work"

---

common/eq_stream.cpp

This directly addresses the root cause of issue #418.
I'd like someone to review it and/or have some more testing done on it before merging since it's in an area that I have little experience in.

Application packet size fix for high byte opcodes

---

zone/exp.cpp

Simple fix, but still tested and verified on my server.

Full group was being excluded from group exp bonus

---

zone/bot.cpp
zone/bot.h

- Added support for Powersource.
- Changed all messages to group messages (Defaults to say if they are not in a group)

Bot changes.

---

common/ruletypes.h
zone/bot.cpp
zone/special_attacks.cpp

- Values (% damage mod): 0 = 0%, 5 = 5%, 50 = 50%, 200 = 200%

Added Combat:BackstabBonus rule.

---

zone/command.cpp
zone/questmgr.cpp

- Added command aliases: #findzone -> #fz, #reloadquest -> #rq
- Added instance ID to $client->GoToSafeCoords() in quest::safemove();

Files changed: command.cpp, questmgr.cpp

---

zone/bot.cpp
zone/bot.h
zone/botspellsai.cpp

- #bot ai mez is now #bot mez
- #bot bindme is now #bot bind
- #bot runeme is now #bot rune
- #bot augmentitem now has an alias of #bot ai
- #bot giveitem now has an alias of #bot gi
- Removed unused #bot groupmessages
- Removed useless additional parameters (c->GetName()/sep->arg[2])
- Formatted loops and conditionals.

Bot command changes.

---

zone/command.cpp
zone/command.h

- #untraindisc [spellid] - Untrains specified discipline.
- #untraindiscs - Untrains all disciplines.

New commands.

---

zone/client.h
zone/tasks.cpp
zone/tasks.h
zone/trading.cpp

Added support for handing in stacked items and getting task credit for
those items.

Hand in stacked items

---

common/ruletypes.h
utils/sql/git/optional/2015_07_22_CommonTongue.sql
world/client.cpp

Files added: 2015_07_22_CommonTongue.sql
Adds new rules so you can change the start Common Tongue value for Iksars, Ogres, and Trolls.

Files changed: ruletypes.h, client.cpp

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

Types:
- 0: Copper
- 1: Silver
- 2: Gold
- 3: Platinum
Sub Types (if applicable):
- 0: On Character
- 1: In Bank
- 2: On Cursor
- 3: Shared Bank (only applies to Type 3/Platinum)

Added $client->GetMoney(type, subtype) to Perl/Lua.

---

zone/bot.cpp

Saylinks had #bot invis instead of #bot resist.

Fixed #bot resist commands.

---

common/spdat.h
zone/bonuses.cpp
zone/common.h
zone/mob_ai.cpp

464 - Base1 % chance to do rampage for base2 % of damage each melee round

Implemented SE_PC_Pet_Rampage

---

common/spdat.h
zone/bonuses.cpp
zone/common.h
zone/effects.cpp
zone/mob_ai.cpp
zone/spell_effects.cpp

Implemented SE_ImprovedDamage2				461 // Increase spell damage by percent (SE_Fc_Damage_%2)
Implemented SE_FcDamageAmt2     		462 // Increase spell damage by flat amount (SE_Fc_Damage_Amt2)

Implemented a few new stackable spell damage focus effects from live.

---

common/ruletypesx.h
common/shareddb.cpp
common/spdat.h
zone/aggro.cpp
zone/client_packet.cpp
zone/effects.cpp
zone/lua_spell.cpp
zone/mob.cpp
zone/spell_effects.cpp
zone/spells.cpp

219 not_extendable - > not_focusable - No focus are applied to these spells
217 maxtargets -> no_heal_damage_item_mod - Not applied to these spells.
232 -> no_remove -> Can not click off these spells even if beneficial
209 powerful_flag -> no_resist -> Unresistable spell

Update/Implementation of various fields in spells_new

---

common/spdat.h
zone/attack.cpp
zone/bonuses.cpp
zone/common.h

466 // PC Pet only - Base1 % chance to do flurry from double attack hit.

Implemented SE_PC_Pet_Flurry_Chance			

---

common/dbcore.cpp

Reports records affected by inserts, updates, and deletes as well as the records returned by selects.

Quick query logging addition

---

changelog.txt
zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

Check changelog.txt for changes.

Exported several Mob-based methods to Perl and Lua.

---

changelog.txt
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Example script included: http://wiki.eqemulator.org/i?Module=Pastebin&Paste=iqh70Lxq

Added GetInstanceTimer to Perl and Lua.

---

zone/client.cpp

Just added runspeed to #mystats window.

Added runspeed to #mystats window

---

zone/client_packet.cpp

table schema for character_corpses is zone_id, not zoneid.

---

zone/special_attacks.cpp

Was only broken if using (RuleB(Combat, ProjectileDmgOnImpact))

Fix for ammo weapon damage not calculating when launching projectiles

---

changelog.txt
zone/effects.cpp
zone/entity.h
zone/mob.h
zone/special_attacks.cpp
zone/spell_effects.cpp

Fix for AE taunt to use correct range and hate modifier.
Fix for spell effect version of taunt to use correct range.

AE Taunt range fix

---

zone/mob.h
zone/special_attacks.cpp

Fix for special attacks that was causing most of them do to do the HitChance roll twice.

Special attacks hit chance fix

---

common/mysql_request_result.h
common/useperl.h
zone/embperl.h

FreeBSD Compile Fixes

---

zone/lua_parser.cpp

This allows one to use the lua_modules folder as their luarocks tree
ex (from the server folder with lua_modules using default location)
luarocks --tree=lua_modules install luasql-mysql MYSQL_INCDIR=/usr/include
This will install the luasql mysql module so you can now do queries from lua

Add luarocks support

---

zone/client.cpp

Per what I recall, and a few comments on the spell on Zam, you can still speak yourself if you target yourself.
Fixed to allow this.

Fix Voice Graft to work only when targetting pet.

---

changelog.txt
common/database.cpp
common/database.h
common/eq_packet_structs.h
common/eqemu_logsys.h
common/patches/sod_structs.h
common/patches/sof_structs.h
common/patches/titanium_structs.h
common/patches/uf_structs.h
common/ruletypes.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2016_08_27_ip_exemptions.sql
world/client.cpp
world/clientlist.cpp

Modified quantity in Merchant_Sell_Struct to be uint32 in accordance with Merchant_Purchase_Struct. This will allow you to buy stacks of items beyond 255. (Tested with a stack of 1,000 Arrows.)

Fixed quantity in merchant purchase.

---

zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

Allows you to see what percent of experience is going to AAs.

Added GetAAPercent() to Perl and Lua.

---

common/servertalk.h
world/zoneserver.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/worldserver.cpp

Requested in [this](http://www.eqemulator.org/forums/showthread.php?t=40885) thread.

Added support for server-wide marquee messages.

---

zone/loottables.cpp
zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.h
zone/perl_npc.cpp
zone/questmgr.cpp
zone/questmgr.h

Added augment support for NPC AddItem() and quest::addloot in Perl/Lua. This will allow you to add items to NPCs with scripts that already have augments in them.

Augment support for adding items to NPCs in quests.

---

zone/attack.cpp
zone/forage.cpp
zone/string_ids.h

Just a quick change to add fish names to fishing.  Please excuse the # of commits.  Not great with git and had to backout some commits.

Add fish names to fishing messages as per live for non junk items,

---

zone/client_process.cpp

Better solution thx to demonstar55.

Add check for mob spell based defensive procs.

---

utils/scripts/linux_installer/install.sh

This should be fully working with Ubuntu 16.04 Server.

Update for Ubuntu 16.04

---

world/client.cpp
world/cliententry.h

Just for more detailed logs and clarity.

Change message from always saying Logging (In) to Logging in or Logging Out.

---

common/eqemu_config.cpp
common/eqemu_config.h

Fixes an issue with loginserver# array

eqemu_config is now persistent after first load.

---

zone/fearpath.cpp
zone/spell_effects.cpp

Repair fear pathing issues with Z and FEar resists now apply cha adjustments as they should.

---

zone/fearpath.cpp

Undid all changes except the one about dropping fear when no pathing could be found.

My "fix" for the fear spell getting dropped caused many fleeing errors

---

zone/client_packet.cpp

Level 1-7 chars were skilling up like mad.  I never caught it.  I was wrong when I put this in
initially.

This change way back when actually totally hosed skillups.

---

zone/mob_ai.cpp

Seems pretty silly for mobs to fear an enemy, and then root them.

Mobs no longer root feared enemies.

---

zone/waypoints.cpp

This fixes issues where feared clients go Z crazy.
@Akkadius we talked about this.

Exclude clients from FixZ to fix fear issues.

---

zone/mob_ai.cpp

While not sophisticated, this corrects every underworld pet issue I have seen so far due to following 
owners through walls, etc and landing underworld.

This patches gross pet errors in Z.

---

common/ruletypes.h

Just some cleanup to reduce confusion.

Cleanup some rules that are no longer used anywhere.

---

common/ruletypes.h
zone/aggro.cpp
zone/attack.cpp
zone/bot.cpp
zone/client.cpp
zone/client.h
zone/client_packet.cpp

This is adding PVP changes to a new branch, PVP

Add PVP changes to pvp branch

---

common/ruletypes.h
zone/attack.cpp
zone/client_process.cpp
zone/spells.cpp

This is my last PR from eqcodex->pvp branch, i'll use the pvp branch from now on and push directly.

Added PVP Root chance to break and PVP respawn mana rules

---

zone/mob.cpp

Quick change to make the spell work.,

Kerran illusion spell uses 562 not 23.

---

common/spdat.cpp

Changes to make the spell harmony work.
Taken from :  
http://www.eqemulator.org/forums/archive/index.php/t-40331.html

Changes to make Harmony work.

---

zone/lua_general.cpp

Added the get_instance_timer to lua quest thingie in lua_general.cpp

Exposing get_instance_timer to lua

---

zone/client_packet.cpp

My zones like tox no longer get arbitrarily dark.  I tested and I could see that sometimes the zoneheader (OP_NewZone) was not getting processed.  I moved it back after weather and it works again.  Also cleaned up an unused variable that was passed and never used.

Zone header was getting ignored by RoF2 client.

---

utils/sql/db_update_manifest.txt

Fix previous error in manifest.

Fix typo in manifest.

---

loginserver/options.h

Couple of comments were copy/pasted/duplicated wrong..

Tidied Comments

---

common/base_packet.h
common/eq_constants.h
common/eq_packet_structs.h
common/patches/rof.cpp
common/patches/rof2.cpp
common/patches/sod.cpp
common/patches/sof.cpp
common/patches/titanium.cpp
common/patches/uf.cpp
zone/client.cpp
zone/client.h
zone/common.h
zone/embparser_api.cpp
zone/entity.cpp
zone/entity.h
zone/lua_general.cpp
zone/lua_general.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/lua_parser.cpp
zone/mob.cpp
zone/mob.h
zone/questmgr.cpp
zone/questmgr.h

This should prevent any optimizations being done on the "1 char string"
This also fully documents the packet and expands the uses of
quest::say/QuestSay
Looking for comments on quest API changes before pushing to master.

Fix issues with OP_SpecialMesg handling

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- GetAlternateCurrencyValue(currency_id) - Returns the amount of the alternate currency you have.
- SetAlternateCurrencyValue(currency_id, amount) - Allows you to directly set the amount of an alternate currency.

Export Getter/Setter alternate currency methods to Perl and Lua.

---

zone/embparser_api.cpp
zone/perl_client.cpp
zone/perl_entity.cpp
zone/perl_groups.cpp
zone/perl_mob.cpp
zone/perl_npc.cpp
zone/perl_raids.cpp

Fixes multi-line Perl croaks, allowing the quest API reader to function properly.

Remove multi-line Perl croaks

---

utils/scripts/eqemu_server.pl

Has a matching pull request in Akkadius/EQEmuInstall
* Error was found by Maze

Modified eqemu_server.pl to use new login server schema

---

utils/scripts/eqemu_server.pl

* Pulls login.json from repo
* updates variables from variables file

Added automated initialization of login.json [ci skip]

---

zone/attack.cpp

Spell procs were not firing due to bad conditional.

Fix damage done by poison proc changes

---

zone/client.cpp
zone/client.h
zone/command.cpp
zone/command.h

#faction -- Displays Target NPC's Primary faction
#faction Find [criteria | all] -- Displays factions name & id
#faction Review [criteria | all] -- Review Targeted Players faction hits
#faction Reset [id] -- Reset Targeted Players specified faction to base ( mimic /clearfaction from live )

#Faction command

---

zone/client_packet.cpp

This commit should address the second bullet-point in issue #932

Mobs will not trade anymore if they are currently in combat.

---

zone/client_packet.cpp
zone/mob.cpp
zone/mob.h

This is a collaboration between myself and @Uleat.   I added code to reflect client updates (incremental) correctly once a client enters a boat.  @Uleat made it fit in much more elegantly.

Advance client position while on boat

---

zone/client_mods.cpp

There were errors in the old formula for wis/int values over 201.

Fix formula for mana

---

common/eqemu_logsys.cpp
common/eqemu_logsys.h
common/eqemu_logsys_log_aliases.h
common/ruletypes.h
common/servertalk.h
world/console.cpp
zone/CMakeLists.txt
zone/worldserver.cpp
zone/zone.cpp
zone/zone.h
zone/zone_reload.cpp
zone/zone_reload.h

This only is implemented for quests to start, can easily be extended to many other data types
HRM client CLI utility is in another codebase that will be available for download and documented soon

Feature - Hot Reload

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/c_cpp_properties.json
.vscode/tasks.json

This is my dev environment I use, I hop between osx/linux/windows often. May need improvements, but shouldn't impact any other tooling of efforts, but be helpful for those interested in getting a free cross-platform IDE together to build linux binaries.
If PR gets accepted, I'll write a step by step how to on gitbook of how to configure it.

Added vscode environment files

---

zone/pathfinder_nav_mesh.cpp

restore some code unintentionally removed

---

common/version.h

Update version for always_aggros_foes db change.

---

utils/scripts/eqemu_server.pl

* Also added an escape to skip pulling Maps (tighter feedback loop if
developing)

Modified eqemu_server.pl to pull latest PEQ

---

common/database/database_dump_service.cpp

Clean branch with only relevant fixes..

Tweaked compression arguments for 7-Zip cli command invocation

---

.gitignore

* Removes the generated files from both CMake and VS
---
Got tired of having to dodge all those files in git add :)

Enhanced .gitignore

---

zone/command.cpp
zone/command.h

Another 'mass editing' command

Added command 'editmassrespawn' for mass editing of respawn times

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getitemname(item_id);
Lua: eq.get_item_name(item_id);

Add getitemname(item_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getspellname(spell_id);
Lua: eq.get_spell_name(spell_id);

Add getspellname(spell_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/tasks.cpp
zone/tasks.h

Perl: quest::gettaskname(task_id);
Lua: eq.get_task_name(task_id);

Add gettaskname(task_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::CheckInstanceByCharID(instance_id, char_id);
Lua: eq.check_instance_by_char_id(instance_id, char_id);

Add CheckInstanceByCharID(instance_id, char_id) to Perl/Lua.

---

zone/client_packet.cpp

This fixes the problem, but I believe someone with better knowledge of the client than I can find a more "correct" solution.
Posted as a PR per @joligario  to solve it for now.  Was also asked to put SE_Invisibility in there so that this "hack" is a catch all.
https://github.com/EQEmu/Server/issues/998

Hack to fix RoF2 perma IVU/IVA bug after zoning.

---

common/CMakeLists.txt
common/namegenerator/namegen.cpp
common/namegenerator/namegen.h
world/client.cpp

While testing character creation; I got tired of unreliable name generation. This has shown to be more consistent, clean, re-usable and gives us options to use it elsewhere easily
Use name generator here: https://github.com/skeeto/fantasyname
http://rinkworks.com/namegen/

Improved Random Name Generator

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getcharidbyname(name);
Lua: eq.get_char_id_by_name(name);

Add getcharidbyname(name) to Perl/Lua.

---

common/database.cpp
common/database.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getcharnamebyid(char_id);
Lua: eq.get_char_name_by_id(char_id);

Added getcharnamebyid(char_id) to Perl/Lua.

---

common/database.cpp
common/database.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getnpcnamebyid(npc_id);
Lua: eq.get_npc_name_by_id(npc_id);

Add getnpcnamebyid(npc_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getcurrencyid(item_id);
Lua: eq.get_currency_id(item_id);

Add getcurrencyid(item_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getskillname(skill_id);
Lua: eq.get_skill_name(skill_id);

Add getskillname(skill_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Perl: quest::getracename(race_id);
Lua: eq.get_race_name(race_id);

Add getracename(race_id) to Perl/Lua.

---

.gitignore

Added .gitignore for the VS generated folder x64

Added a VS ignore for x64 compiles

---

zone/entity.cpp
zone/entity.h
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/perl_entity.cpp

Perl: $entity_list->GetNPCBySpawnID(spawn_id);
Lua: eq.get_entity_list():GetNPCBySpawnID(spawn_id);

Add GetNPCBySpawnID() to Perl/Lua.

---

common/servertalk.h
world/zoneserver.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/worldserver.cpp

Perl: quest::crosszonemessageplayerbyguildid(type, guild_id, message);
Lua: eq.cross_zone_message_player_by_guild_id(type, guild_id, message);

Add CrossZoneMessagePlayerByGuildID() to Perl/Lua.

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/perl_npc.cpp

Perl: $npc->IsTaunting();
Lua: e.self:IsTaunting();

Add IsTaunting() to Perl/Lua.

---

utils/scripts/eqemu_server.pl

Changed binaries to x64 and got rid of wget.exe for windows, switched to
native WebClient
Uses zipped binaries at Akkadius/EQEmuInstall until appveyor is sorted

Win64 eqemu_server.pl

---

utils/scripts/eqemu_server.pl

Requires change to the zip on eqemu.gitbook.io

Revert back to using wget.exe for windows installs

---

utils/scripts/eqemu_server.pl

Switched the powershell command to a more compatible one

Updated installer to support powershell older than 3.0

---

zone/command.cpp
zone/command.h

Adds #findrace [race_name|race_id].

Add #findrace command.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

Add eq.zone(short_name) to Lua.
Add eq.zone_group(short_name) to Lua.
Add eq.zone_raid(short_name) to Lua.
Add quest::zonegroup(short_name) to Perl.
Add quest::zoneraid(short_name) to Perl.

Add new zone methods to Perl/Lua.

---

zone/command.cpp

Add zone ID to #findzone.

---

zone/client.h
zone/effects.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

Add $client->GetDisciplineTimer(timer_id) to Perl.
Add client:GetDisciplineTimer(timer_id) to Lua.
Add $client->ResetDisciplineTimer(timer_id) to Perl.
Add client:ResetDisciplineTimer(timer_id) to Lua.

Add GetDisciplineTimer() and ResetDisciplineTimer() to Perl/Lua.

---

zone/attack.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.h
zone/perl_mob.cpp

Pulled from a [Gist](https://gist.github.com/fe1c0e77a5f9c40d6ce037c8efe2cf9a) by Mackal.

Add GetDisplayAC() to Perl/Lua.

---

zone/client.h
zone/inventory.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->DyeArmorBySlot(slot, red, green, blue, use_tint) to Perl.
- Add client:DyeArmorBySlot(slot, red, green, blue, use_tint) to Lua.

Add DyeArmorBySlot(slot, red, green, blue, use_tint) to Perl/Lua.

---

world/main.cpp

The code already exists, guarded by a rule.

Removed duplicate code for pruning merhantlist_temp

---

.vscode/tasks.json

Did tweaks to the .vscode file for the new peq dump snapshots, and changed from /build/bin to /bin

changed build dir to /bin, updated peq db dump

---

utils/mods/expansions_combat.lua
zone/lua_client.cpp
zone/lua_client.h
zone/lua_mod.cpp
zone/lua_mod.h
zone/lua_parser.cpp
zone/lua_parser.h
zone/spells.cpp

* [expansions] Create a Lua mod hook into Client::CheckFizzle()
* Added expansions_combat.lua mod stub
* Spell  Fizzle as per TAKP formula

Spell Fizzle for < LDON expansions via lua_mod (#1118)

---

zone/client.cpp

We need to save the remaining time sooner to prevent circumstances
described here:
http://www.projecteq.net/forums/index.php?threads/raid-out-of-combat-regen-timers-resetting-on-non-raid-mobs.16114/

Save the rest_timer sooner to prevent issues

---

.drone.yml
.travis.yml
zone/mob_ai.cpp

Runs Linux server build pipeline on Drone, runs @ 4 cores on a Ryzen chip at about 4 minute builds which should be plenty
http://drone.akkadius.com/EQEmu/Server/6/1/2

Drone Build Pipeline

---

.drone.yml
zone/mob_ai.cpp

* Create drone config
* Tweak config
* Update .drone.yml
* Garbage commit to run another build
* Bring cores down
* Fix formatting from https://github.com/EQEmu/Server/pull/1142
* Add tests line
* Change directory to build before running the unit tests
* Remove tests dir
* Avoid double build on PR's
* Testing build settings

Drone Build Pipeline (#1144)

---

zone/mob.cpp

Added 533 so we can use it for boats and IsBoat() will work.

Added RACE_BOAT_533 to IsBoat()

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Perl: quest::removeitem(item_id, quantity);
- Lua: eq.remove_item(item_id, quantity);

Add removeitem(item_id, quantity) to Perl/Lua.

---

zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/command.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->SetRadiantCrystals(value) to Perl.
- Add $client->SetEbonCrystals(value) to Perl.
- Add client:SetRadiantCrystals(value) to Lua.
- Add client:SetEbonCrystals(value) to Lua.

Add SetRadiantCrystals() and SetEbonCrystals() to Perl/Lua.

---

common/classes.cpp
common/classes.h
common/spdat.cpp
common/spdat.h

- Update GetSpellName() to uint16.
- Add more classes to GetClassIDName().

quest::getspellname() and quest::getclassname() fixes/additions.

---

zone/command.cpp
zone/command.h

#endurance

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- $client->Fling(value, target_x, target_y, target_z, ignore_los, clipping) in Perl.
- client:Fling(value, target_x, target_y, target_z, 1ignore_los, clipping) in Lua.

Add client->Fling() to Perl/Lua.

---

zone/lua_client.cpp
zone/lua_client.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_client.cpp
zone/perl_mob.cpp

Adds GetClassBitmask(), GetClassName(), GetRaceBitmask(), and GetRaceName() to Perl/Lua.

Add Race/Class Name and Bitmask Methods.

---

zone/mob_ai.cpp
zone/object.cpp
zone/zone.cpp

Just a minor inconvenience when developing without maps installed, shouldn't affect normal servers

Fix zone startup crash if maps not installed

---

zone/command.cpp
zone/command.h

This PR addresses naming suggestions in https://github.com/EQEmu/Server/pull/1170

[Command] Naming suggestions from https://github.com/EQEmu/Server/pull/1170

---

zone/client.h
zone/effects.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->HasDisciplineLearned(spell_id) to Perl.
- Add client:HasDisciplineLearned(spell_id) to Lua.

Add HasDisciplineLearned() to Perl/Lua.

---

zone/perl_raids.cpp

Add validation macro to all raid methods.

[Quest API] Perl Raid Validation Macro

---

zone/perl_questitem.cpp

Add validation macro to all item methods.

[Quest API] Perl Item Validation Macro

---

zone/perl_player_corpse.cpp

Add validation macro to all corpse methods.

[Quest API] Perl Corpse Validation Macro

---

zone/perl_perlpacket.cpp

Add validation macro to all packet methods.

[Quest API] Perl Packet Validation Macro

---

zone/perl_object.cpp

Add validation macro to all object methods.

[Quest API] Perl Object Validation Macro

---

zone/perl_npc.cpp

Add validation macro to all NPC methods.

[Quest API] Perl NPC Validation Macro

---

zone/perl_mob.cpp

Add validation macro to all mob methods.

[Quest API] Perl Mob Validation Macro

---

zone/perl_hateentry.cpp

Add validation macro to all hate methods.

[Quest API] Perl Hate Validation Macro

---

zone/perl_groups.cpp

Add validation macro to all group methods.

[Quest API] Perl Group Validation Macro

---

zone/perl_entity.cpp

Add validation macro to all entitylist methods.

[Quest API] Perl Entity Validation Macro

---

zone/perl_doors.cpp

Add validation macro to all door methods.

[Quest API] Perl Doors Validation Macro

---

zone/perl_client.cpp

Converts all the methods that were not using this macro to use this macro instead of reusing the same code over and over.

[Quest API] Perl Client Validation Macro

---

zone/perl_questitem.cpp

Add category tags for quest_item methods.

[Quest API] Item annotations

---

zone/perl_raids.cpp

Added categories tags for raid methods.

[Quest API] Perl Raid Annotations

---

zone/perl_client.cpp

Added category tags for client methods.

[Quest API] Perl Client Annotations

---

zone/perl_player_corpse.cpp

Add category tags for corpse methods.

[Quest API] Perl Corpse Annotations

---

zone/perl_object.cpp

Add category tags for Object methods.

[Quest API] Perl Object Annotations

---

common/string_util.cpp

Slowly leaking memory for ages!
clang-tidy complained about it

[Memory Leak] Fix va_list leaks in MakeAnyLenString/AppendAnyLenString

---

zone/bot.cpp
zone/client_packet.cpp
zone/worldserver.cpp

These cases probably are exceedingly rare, but they still need to be
accounted for. (As in, I don't think anyone has run into these cases too
often to cause problems)

[Memory Leak] Fix some leaks of groups/raids

---

common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2021_02_14_npc_exp_mod.sql
zone/exp.cpp
zone/mob.h
zone/npc.h
zone/zonedb.cpp
zone/zonedump.h

Mostly envisioned to be useful for custom content without having a really hacky mod script involved.

[Experience] Add exp mod to npc types to let a server op change the exp modifier

---

zone/perl_groups.cpp

Added category tag annotations for group methods.

[Quest API] Perl Group Annotations

---

zone/perl_mob.cpp

Added category tag annotations for mob methods.

[Quest API] Perl Mob Annotations

---

zone/perl_npc.cpp

Added category tag annotations for NPC methods.

[Quest API] Perl NPC Annotations

---

zone/perl_doors.cpp

Add category type annotations to door methods.

[Quest API] Perl Door Annotations

---

zone/perl_hateentry.cpp

Added category tag annotations for Hate Entry methods.

[Quest API] Perl Hate Entry Annotations

---

zone/perl_entity.cpp

Added category tag annotations for perl entity list methods.

[Quest API] Perl Entity List Annotations

---

common/database.cpp
common/database.h
common/string_util.cpp
common/string_util.h
ucs/clientlist.cpp
world/clientlist.cpp
world/zonelist.cpp
zone/client_packet.cpp
zone/client_process.cpp
zone/embparser.cpp
zone/inventory.cpp
zone/merc.cpp

These functions were fine back in the day, but we got better more modern things.
Either use bounded safe c-string stuff or fmtlib.

[Cleanup] Nuke Make/AppendAnyLenString

---

zone/entity.cpp
zone/horse.cpp
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp

- Add $mob->IsHorse() to Perl.
- Add mob:IsHorse() to Lua.

[Quest API] Add IsHorse() to Perl and Lua.

---

common/dbcore.cpp

Fix deletes in DBcore::Open

---

world/client.cpp

It's still pretty gross, but the bits ASan really hated are less gross

[ASan] Make Client::Clearance less gross

---

common/database.h
zone/merc.cpp
zone/npc.cpp
zone/worldserver.cpp
zone/zonedb.cpp
zone/zonedb.h

I got bored and decided to start working through some of the warnings enabled by -Wall, this one does have potential for finding buffer overflows, so I started there.

[Cleanup] Make code -Wformat-overflow safe

---

common/eq_packet_structs.h
zone/client.cpp

This solves the OOB issue pointed out in #1304 and cleans up the code a
bit so it should be less error prone

[Fix] Clean up Filtered/MessageString functions

---

zone/spells.cpp

Bard songs with a mana cost and Vet AAs were repulsing when they shouldn't have.

[Bug Fix] Misc Bard Song Fixes

---

zone/lua_client.cpp
zone/lua_client.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_client.cpp
zone/perl_mob.cpp

Changes Perl and Lua GetLastName() method from client only to mob.
Lua
- mob:GetLastName();
Perl
- $mob->GetLastName();

[Quest API] Convert Client GetLastName() method export to Mob export.

---

common/string_util.cpp
common/string_util.h
tests/string_util_test.h
zone/mob_info.cpp
zone/zone_event_scheduler.cpp

Some clean up since we had duplicate functions and optimizations
This is on a VERY long SpecialAbilities (taken from the PEQ's DB)
```
--------------------------------------------------------------
Benchmark                       Time           CPU Iterations
--------------------------------------------------------------
bench_oldsplit               5201 ns       5201 ns     129500
bench_split                  1269 ns       1269 ns     548906
```

[Strings] Split String Optimizations

---

common/ruletypes.h
zone/spells.cpp

Spells:July242002PetResists defaults to true

Add a rule to disable the Pet Resist buff

---

common/database.cpp
common/database.h
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

https://gist.githubusercontent.com/mackal/3ecf78f8467e97631f7de36762803fc1/raw/ae3f084b3fcde67e2f4c6ed8b5a0c1ba4bb02030/notsafe.txt
This code should be fine with NRVO maybe, unsure if that works nested, but hey, no more corruption.

[Bug Fix] use-after-free corruption with some DB calls

---

zone/waypoints.cpp

Fix to only delete correct zone grid.

[Bug Fix] #grid delete was deleting the grids everywhere

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/perl_npc.cpp

- Add $npc->IsRaidTarget() to Perl.
- Add npc:IsRaidTarget() to Lua.

[Quest API] Add IsRaidTarget() to Perl and Lua.

---

world/clientlist.cpp

Secrets suggested this a long time ago and I just remembered it.
Not sure if this has ever caused anyone issues.

[CLE] Reset iterator in IsAccountInGame()

---

zone/effects.cpp

We need to do the spell effect first, then check the limits

[Bug Fix] EntityList::AESpell was off by one

---

utils/scripts/generators/repository-generator.pl

[Repository Generator] Fix repository generator on windows

---

common/ruletypes.h
zone/spells.cpp

https://discord.com/channels/212663220849213441/447944570580238376/844018209984348180
For Symetrix.. discussion in link above.

[Rules] Add rule to allow you to cast invis on already invis'd players

---

zone/client_packet.cpp
zone/zone.cpp

https://github.com/EQEmu/Server/issues/1350 this fixes this issue

[Bug Fix] Fix for charges not being sold correctly

---

common/eq_constants.h
common/races.cpp
common/races.h
common/ruletypes.h
zone/attack.cpp
zone/npc.cpp
zone/npc.h
zone/spells.cpp

feel free to look this over, will only affect client vs. client and client's pet vs client. Rule must be true to work as well.

[PVP] Pvp guard assist code. (Guards will assist in PvP based on faction)

---

zone/lua_mob.cpp
zone/lua_mob.h

This returns the hate list but in a random order. This is useful to
prevent repeated (potentially infinite ...) calls to GetHateRandom()

[Lua/Feature] Add Lua_Mob::GetShuffledHateList

---

zone/dynamic_zone.cpp
zone/dynamic_zone.h
zone/expedition.cpp
zone/expedition.h

This method can be moved now that members are on dz

Move member compass updates to dz

---

common/ruletypes.h
zone/spawn2.cpp

This should fixed the eqtime spawn condition from falling behind.

strict spawn_events now take into account EQ minute.

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->SetHideMe(hide_me_state) to Perl.
- Add client:SetHideMe(hide_me_state) to Lua.

[Quest API] Add SetHideMe() to Perl/Lua.

---

zone/client.h
zone/effects.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->ResetAllDisciplineTimers() to Perl.
- Add client:ResetAllDisciplineTimers() to Lua.

[Quest API] Add ResetAllDisciplineTimers() to Perl/Lua.

---

common/http/httplib.h
loginserver/main.cpp

Bumped `httplib` with about 2 years worth of updates. Updated the API's accordingly and also did some testing against the Loginserver API to make sure there were no regressions using `curl` and the php example client https://github.com/Akkadius/eqemu-loginserver-php-api-client
* Loginserver API Web interface now runs on its own thread
* Add API Web logging
```
[Login] [Info] [API] Request [/v1/servers/list] via [127.0.0.1:40614]
[Login] [Info] [API] Request [/v1/servers/list] via [127.0.0.1:40632]
[Login] [Info] [API] Request [/v1/servers/list] via [127.0.0.1:40634]
[Login] [Info] [API] Request [/v1/servers/list] via [127.0.0.1:40636]
[Login] [Info] [API] Request [/v1/servers/list] via [192.168.65.229:42352]
[Login] [Info] CheckLoginUserCredentials account [something] source_loginserver …
```

[Library] Update httplib

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::rename(name) to Perl.
- Add eq.rename(name) to Lua.

[Quest API] Add rename(name) to Perl/Lua.

---

loginserver/main.cpp
world/world_server_command_handler.cpp
zone/command.cpp

**Description**
When using the #gearup command; it would originally instruct you to install the table yourself if it did not exist. Now the command will automatically reach out to Github and install the table for you via HTTPS client request
Gearup is a command to easily add era-contextual equipment to a character. See original commit if interested: https://github.com/EQEmu/Server/pull/1094/commits/cfa3e88bb29f164751e147eca9a57ff128c5316a
Referenced SQL https://raw.githubusercontent.com/EQEmu/Server/master/utils/sql/git/optional/2020_07_20_tool_gearup_armor_sets.sql
**Demo Video**
https://www.youtube.com/watch?v=baPBZhNiGZ8

[Command] #gearup Table Auto-Install

---

zone/perl_mob.cpp

- Add $client->AddNimbusEffect(effect_id) to Perl.

[Quest API] Add AddNimbusEffect(effect_id) to Perl.

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp
zone/questmgr.cpp

- Add $client->CountItem(item_id) to Perl.
- Add $client->RemoveItem(item_id, quantity) to Perl.
- Add client:CountItem(item_id) to Lua.
- Add client:RemoveItem(item_id, quantity) to Lua.

[Quest API] Add CountItem(item_id) and RemoveItem(item_id, quantity) to Perl/Lua.

---

zone/spell_effects.cpp

[Bug Fix] Fix for unknown spell effect message with spell effect 459 (DamageMod2)

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::getinventoryslotname(slot_id) to Perl.
- Add eq.get_inventory_slot_name(slot_id) to Lua.

[Quest API] Add getinventoryslotname(slot_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::getdeityname(deity_id) to Perl.
- Add eq.get_deity_name(deity_id) to Lua.

[Quest API] Add getdeityname(deity_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::getgendername(gender_id) to Perl.
- Add eq.get_gender_name(gender_id) to Lua.

[Quest API] Add getgendername(gender_id) to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp

- Add quest::get_data_remaining(bucket_name) to Perl.
- Add eq.get_data_remaining(bucket_name) to Lua.

[Quest API] Add get_data_remaining(bucket_name) to Perl/Lua.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/mob.h
zone/perl_mob.cpp

- Add $client->RemoveAllNimbusEffects() to Perl.
- Add client:RemoveAllNimbusEffects() to Lua.

[Quest API] Add RemoveAllNimbusEffects() to Perl/Lua.

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Converts [this](https://github.com/ProjectEQ/projecteqquests/blob/master/plugins/Instances.pl#L4) script to a C++ method and adds Raid functionality.
- Add $client->SendToInstance(instance_type, zone_short_name, instance_version, x, y, z, heading, instance_identifier, duration) to Perl.
- Add client:SendToInstance(instance_type, zone_short_name, instance_version, x, y, z, heading, instance_identifier, duration) to Lua.

[Quest API] Add SendToInstance(instance_type, zone_short_name, instance_version, x, y, z, heading, instance_identifier, duration) to Perl/Lua.

---

zone/bot.cpp
zone/mob.cpp

[Bug Fix] spell cast time cap issue introduced in e5b9d72b81

---

zone/inventory.cpp

Not sure if this is the right way to do this, but seems to work...

[Inventory] Remove Trader's Satchel ID from inventory.cpp

---

common/spdat.h

Added as comments since that appears what we were doing. This just gets
us caught up to dev post.

Add defines (commented) for further known SPAs

---

zone/command.cpp

original PR https://github.com/EQEmu/Server/pull/1424

[Commands] Make #maxskills work on target.

---

common/ruletypes.h
zone/aggro.cpp

…nd new rule AggroPlayerPets set to true

[Pets] Allow NPCs to aggro player pets with NPCAggro field set in database and new rule AggroPlayerPets set to true

---

zone/attack.cpp
zone/spells.cpp

Without this change guards will assist npcs if you have lower than indifferent faction and attack npcs near them

Fixs guards assisting mobs against players

---

utils/scripts/generators/repository-generator.pl

**Description**
* Adds Int64 / BigInt type support
* Adds reserved word support so that database fields do not collide with reserved words (cpp)

[Repository Generator] Int64/BigInt Support, Reserved Word Support

---

zone/npc_scale_manager.cpp

In effort of repository usage adoption; quickly migrated the scale manager code to use repositories

[Repository Usage] Migrate NPC Scale Manager to use repositories

---

zone/client_packet.cpp

[Merchants] Fixes issues with 1 charge items purchased with 0

---

zone/bot.cpp

This should probably be updated to match everything in client, but this
will at least fix compile

Fix bots with ExtraAttackChance changes

---

common/ruletypes.h
common/spdat.cpp
common/spdat.h
zone/spells.cpp

[Spells] IsInvisSpell() Method + InvisRequireGroup Rule

---

zone/aggro.cpp

Fix SPA 209 SE_DispelBeneficial not causing aggro.

[Spells] Fix SPA 209 SE_DispelBeneficial not causing aggro

---

common/repositories/template/base_repository.template
utils/scripts/generators/repository-generator.pl

From work in PR #1451 
This PR adds `datetime` support for repositories; @hgtw co-authored and wrote most of the base work

[Repositories] Add datetime support to repositories

---

zone/cheat_manager.cpp

Fixes a crash related to missed FMT bindings

[Hotfix] Fixing FMT Format Crash

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/perl_npc.cpp

- Add $npc->GetHealScale() to Perl.
- Add $npc->GetSpellScale() to Perl.
- Add npc:GetHealScale() to Lua.
- Add npc:GetSpellScale() to Lua.

[Quest API] Add GetHealScale() and GetSpellScale()  to Perl and Lua.

---

common/repositories/base/base_spells_new_repository.h
common/shareddb.cpp
common/spdat.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2021_08_31_pvp_duration.sql
zone/lua_spell.cpp
zone/lua_spell.h
zone/spells.cpp

Make use of the spell fields. If you don't want these enabled, I recommend just setting the data equal to normal rather than bothering with a rule.

[Spells] Implement PVP resist and duration overrides

---

zone/attack.cpp
zone/client_mods.cpp
zone/mob.cpp
zone/mob.h

Addition to https://github.com/EQEmu/Server/pull/1517
It appears to just be the if statement here.. I upped the throttling numbers 3x and it was still updating much faster than before. 
With the if statement:
https://i.gyazo.com/74f0e6301340412f67fb12c371ac1853.mp4
without:
https://i.gyazo.com/58c791576d268155073a8f1bb0fc70a7.mp4

[Hitpoints] Fix HP update throttling

---

zone/zone.cpp

[Bug Fix] Resolves issue where loading temporary merchant list "fails" because there aren't any to load.

---

zone/mob.cpp
zone/mob.h
zone/waypoints.cpp

Pretty sure the distance should probably be melee range / 2 but ahh
yeah. Can't do that. Hopefully 5 units isn't too far.

[Summoning] Make Summon a bit more live like

---

zone/perl_client.cpp

[Quest API] Fix freeze formatting for Quest API parsing (Spire)

---

common/eq_packet_structs.h
common/patches/rof.cpp
common/patches/rof2.cpp
common/patches/rof_structs.h
common/patches/sod.cpp
common/patches/sod_structs.h
common/patches/sof.cpp
common/patches/sof_structs.h
common/patches/uf.cpp
common/patches/uf_structs.h
common/repositories/base/base_zone_repository.h
common/version.h
utils/sql/db_update_manifest.txt
utils/sql/git/required/2021_09_14_zone_lava_damage.sql
zone/zonedb.cpp

`
/*Add lava damage variables to zone table*/
ALTER TABLE `zone` ADD `lava_damage` INT(11) NULL DEFAULT '50' AFTER `underworld_teleport_index`, ADD `min_lava_damage` INT(11) NOT NULL DEFAULT '10' AFTER `lava_damage`;
`

[Zone] Add LavaDamage and MinLavaDamage support to ZoneHeader

---

zone/command.cpp
zone/doors.cpp
zone/doors.h
zone/zone.cpp
zone/zonedb.h
zone/zonedump.h

This is prep for some door (switch) refactoring and missing functionality additions I want to do

[Repositories] Use repositories to load doors

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

Will be required for tutoriala script and other similar events

[Quest API] Add mob->SetPet(pet_mob) and mob->RemovePet(pet_mob) to Perl/Lua.

---

zone/perl_client.cpp

Add hash overload to perl CreateExpedition api
This adds an api to perl similar to the Lua api that accepts a reference
to a hash table with expedition creation info
Usage example:
```
my $expedition_info = {
expedition => { name => "Perl expedition", min_players => 2, max_players => 6 },
instance   => { zone => "crushbone", version => 0, duration => 3600 },
compass    => { zone => "gfaydark", x => 238, y => 987, z => -24.90 },
safereturn => { zone => "gfaydark", x => 245.84, y => 987.93, z => -27.6, h => 484.0 },
zonein     => { x => 479.44, y => -500.18, z => 5.75, h => 421.8 }
};
$client->CreateExpedition($expedition_info);
```
Syntax for passing directly from a hash:
```
my %expedition_info = (...);
$client->CreateExpedition(\%expedition_info);
```
Add CreateTaskDynamicZone api to …

[Quest API] Add perl hash apis for dz creation

---

zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp
zone/spells.cpp

- Add $client->UntrainDiscBySpellID(spell_id, update_client) to Perl.
- Add client:UntrainDiscBySpellID(spell_id, update_client) to Lua.

[Quest API] Add client->UntrainDiscBySpellID(spell_id, update_client) to Perl/Lua.

---

zone/embparser_api.cpp
zone/entity.cpp
zone/entity.h
zone/lua_general.cpp

- Add quest::isnpcspawned(npc_ids) to Perl.
- Add quest::countspawnednpcs(npc_ids) to Perl.
- Add eq.is_npc_spawned(npc_ids) to Lua.
- Add eq.count_spawned_npcs(npc_ids) to Lua.

[Quest API] Add IsNPCSpawned(npc_ids) and CountSpawnedNPCs(npc_ids) to Perl/Lua.

---

zone/questmgr.cpp

Allows operators to modify lava damage dynamically.

[Quest API] Add LavaDamage and MinLavaDamage to UpdateZoneHeader in Perl/Lua.

---

zone/command.cpp

Spawnfix was using the client's Z to spawnfix
It should use the model size and model offsets to determine Z in relation to the ground

[Commands] Fix Z on #spawnfix

---

zone/spell_effects.cpp

Math error with multiplying int by uint by mistake.

[BugFix] Fix for bard song instrument mod formula from recent update

---

common/string_util.cpp

[Hotfix] Add include to fix windows build

---

zone/entity.cpp
zone/spell_effects.cpp

Remove potential nullptrs in Virus Code.

[BugFix] Remove potential nullptrs in Virus Code

---

loginserver/account_management.cpp
loginserver/client.cpp

This should address some crashing, concurrency and hangs

[Loginserver] Add some resiliency to LS requests

---

common/ruletypes.h
zone/effects.cpp

[Rules] Add optional rules for HealAmt and SpellAmt to scale DoTs/HoTs.

---

zone/command.cpp
zone/command.h

- Allows you to search for Tasks by ID or partial name.

[Commands] Add #findtask [search criteria] Command.

---

zone/command.cpp
zone/command.h

- Allows you to search for skills by ID or partial name.

[Commands] Add #findskill [search criteria] Command.

---

zone/command.cpp

- Add new data from NewZone_Struct to command and clean up display.

[Commands] Cleanup #zstats Command.

---

world/console.cpp
world/console.old.cpp
world/zonelist.cpp
zone/command.cpp

- Cleanup system messages and magic numbers.

[Commands] Cleanup #worldshutdown Command.

---

zone/command.cpp
zone/command.h

[Commands] Remove #listnpcs Command.

---

world/zoneserver.cpp

These were missed switching them to TellEcho from a previous change

[Bug Fix] Channel TellEcho issues

---

zone/command.cpp

- Cleanup messages and display.

[Commands] Cleanup #npccast Command.

---

zone/command.cpp

[Commands] Cleanup #fov Command.

---

zone/command.cpp

[Commands] Cleanup #viewzoneloot Command.

---

zone/command.cpp

- Cleanup display and use GetSkillName() helper method.
- Only shows skills Client can have and that also have a current max of greater than 0.

[Commands] Cleanup #showskills Command.

---

common/skills.cpp
zone/command.cpp

[Commands] Cleanup #setskill Command.

---

common/emu_constants.cpp
common/emu_constants.h
zone/command.cpp

- Add GetLanguageName() helper and GetLanguageMap() for future use.

[Commands] Cleanup #setlanguage Command.

---

zone/command.cpp

[Commands] Cleanup #distance Command.

---

zone/command.cpp

[Commands] Cleanup #cast Command.

---

world/clientlist.cpp
zone/command.cpp

- Cleanup message and display.
- Add Total Clients to message.
- Add Unique IPs to message.

[Commands] Cleanup #cvs Command.

---

common/net/servertalk_server_connection.cpp
common/net/servertalk_server_connection.h
loginserver/world_server.cpp

A set of changes to allow legacy connections to work on a modern loginserver.
I haven't tested it with pre-revamp code yet cause I literally can't get it to compile and run anymore.  So will probably have to talk to Jumbers about testing it on the login.

[Networking] Servertalk Legacy World Connections for Login

---

zone/command.h

[Commands] Remove #sendop Command.

---

zone/command.h

[Commands] Remove #synctod Command.

---

zone/command.h

[Commands] Remove #qtest Command.

---

zone/command.h

[Commands] Remove #refundaa Command.

---

zone/command.h

[Commands] Remove #optest Command.

---

zone/command.h

[Commands] Remove #numauths Command.

---

zone/command.cpp
zone/command.h

- Removed unused/deprecated command.

[Commands] Remove #mysqltest Command.

---

zone/command.h

[Commands] Remove #manastat Command.

---

zone/command.h

[Commands] Remove #ipc Command.

---

zone/command.h

[Commands] Remove #d1 Command.

---

zone/command.h

[Commands] Remove #connectworldserver Command.

---

zone/command.cpp

[Commands] Cleanup #reloadquest Command.

---

zone/command.cpp

[Commands] Cleanup #heal Command.

---

zone/command.cpp

[Commands] Cleanup #mana Command.

---

zone/command.cpp

[Commands] Cleanup #endurance Command.

---

zone/command.cpp
zone/command.h

- Remove unused/deprecated command.

[Commands] Remove #crashtest Command.

---

zone/command.h

[Commands] Remove #bug Command.

---

zone/command.cpp

[Commands] Cleanup #findnpctype Command.

---

zone/command.cpp

- Remove find subcommand as we have #findfaction now.
- Cleanup message.

[Commands] Cleanup #faction Command.

---

zone/lua_iteminst.cpp
zone/lua_packet.cpp
zone/lua_raid.cpp
zone/lua_spawn.cpp
zone/lua_spell.cpp

Fixes regression from 7b6decae

[Quest API] Add back removed lua class properties

---

common/ruletypes.h
zone/special_attacks.cpp

- Add RULE_BOOL(Combat, ArcheryConsumesAmmo, true, "Set to false to disable Archery Ammo Consumption")
- Add RULE_BOOL(Combat, ThrowingConsumesAmmo, true, "Set to false to disable Throwing Ammo Consumption")

[Rules] Add Archery/Throwing Ammo Consumption Rules.

---

loginserver/login_types.h
loginserver/world_server.cpp

- Constant was named after Windows macro.

[Bug Fix] Loginserver Error String Constants.

---

zone/command.cpp

[Commands] Cleanup #checklos Command.

---

common/string_util.cpp
common/string_util.h
zone/command.cpp
zone/questmgr.cpp

- Cleanup message.
- Add ConvertSecondsToTime() to string_util.h and convert Quest API Methods to use helper.

[Commands] Cleanup #stun Command.

---

zone/command.cpp

- Increase cap from 5,000 to 2,000,000,000.

[Commands] Cleanup #setaapts Command.

---

zone/command.cpp

[Commands] Cleanup #loc Command.

---

zone/command.cpp

- Add message.
- Cleanup logic.

[Commands] Cleanup #setaaxp Command.

---

zone/command.cpp

[Commands] Cleanup #setpvppoints Command.

---

zone/command.cpp

- Add message.
- Increase cap from 100,000 to 2,000,000,000.

[Commands] Cleanup #setcrystals Command.

---

zone/command.cpp
zone/zonedb.h

- Add RaidLootTypes enum and map for names.

[Commands] Cleanup #raidloot Command.

---

zone/command.cpp
zone/gm_commands/permaclass.cpp

[Commands] Cleanup #permaclass Command.

---

zone/command.cpp
zone/gm_commands/permarace.cpp

[Commands] Cleanup #permarace Command.

---

zone/command.cpp
zone/gm_commands/invul.cpp

[Commands] Cleanup #invul Command.

---

zone/command.cpp
zone/gm_commands/givemoney.cpp

[Commands] Cleanup #givemoney Command.

---

zone/command.cpp
zone/gm_commands/nukeitem.cpp

[Commands] Cleanup #nukeitem Command.

---

zone/gm_commands/flags.cpp
zone/zoning.cpp

[Commands] Cleanup #flags Command.

---

common/string_util.cpp
common/string_util.h
world/zonelist.cpp
zone/command.cpp
zone/gm_commands/camerashake.cpp
zone/gm_commands/stun.cpp
zone/worldserver.cpp

- Fix ConvertSecondsToTime logic for milliseconds.
- Add ConvertMillisecondsToTime inline function.

[Commands] Cleanup #camerashake Command.

---

zone/gm_commands/ginfo.cpp

[Commands] Cleanup #ginfo Command.

---

zone/command.cpp
zone/gm_commands/damage.cpp

[Commands] Cleanup #damage Command.

---

zone/command.cpp
zone/gm_commands/setanim.cpp
zone/mob.cpp

- SetAppearance was not sending to self, so if you modified your own appearance, you wouldn't be able to see it.

[Commands] Cleanup #setanim Command.

---

zone/command.cpp
zone/gm_commands/setfaction.cpp

- Doesn't allow you to use invalid faction IDs anymore.

[Commands] Cleanup #setfaction Command.

---

zone/client.cpp

- Cleanup popup window display and logic.

[Commands] Cleanup #myskills Command.

---

zone/gm_commands/killallnpcs.cpp

- Modified Damage portion to use NPC's health in case the NPC's health is somehow greater than 1,000,000,000.

[Commands] Cleanup #killallnpcs Command.

---

zone/gm_commands/aggrozone.cpp

- Add the ability to aggro the zone on your target if you have one.

[Commands] Cleanup #aggrozone Command.

---

common/faction.cpp
common/faction.h
common/features.h
zone/aggro.cpp
zone/client.cpp
zone/client_packet.cpp
zone/command.cpp
zone/effects.cpp
zone/entity.cpp
zone/gm_commands/aggro.cpp
zone/lua_general.cpp
zone/mob.cpp
zone/mob.h
zone/npc.cpp
zone/questmgr.cpp
zone/spells.cpp

- Cleanup constant names and references.
- Cleanup aggro description methods.

[Commands] Cleanup #aggro Command.

---

zone/client.cpp
zone/command.cpp
zone/gm_commands/pvp.cpp

[Commands] Cleanup #pvp Command.

---

zone/command.cpp
zone/gm_commands/memspell.cpp

- Add support for memorizing spell to target if you have GM enabled.

[Commands] Cleanup #memspell Command.

---

zone/command.cpp
zone/gm_commands/lastname.cpp

[Commands] Cleanup #lastname Command.

---

zone/special_attacks.cpp

Monk AA Spirit of Master Wu sends message even if it grants 0 extra attacks.

[Bug Fix] - Monk AA Spirit of Master Wu

---

zone/client_packet.cpp
zone/client_process.cpp
zone/special_attacks.cpp

Fix being able to attack yourself with autofire if Combat:MinRangedAttackDist == 0

[Bug Fix] - Autofire attacking yourself

---

zone/command.cpp
zone/gm_commands/permagender.cpp

[Commands] Cleanup #permagender Command.

---

common/string_util.cpp
common/string_util.h
zone/corpse.cpp
zone/entity.cpp
zone/entity.h
zone/gm_commands/corpse.cpp
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/npc.cpp
zone/perl_entity.cpp

- Add ConvertMoneyToString(platinum, gold, silver, copper) helper method.
- Cleanup NPC::QueryLoot() and Corpse::QueryLoot().
- Convert DeletePlayerCorpses() to uint32.
- Convert DeleteNPCCorpses() to uint32.
- Cleanup Quest API stuff to use uint32.

[Commands] Cleanup #corpse Command.

---

zone/command.cpp
zone/gm_commands/zunderworld.cpp

- Add parameter to allow data to be saved to database.

[Commands] Cleanup #zunderworld Command.

---

zone/gm_commands/zsave.cpp

[Commands] Cleanup #zsave Command.

---

zone/command.cpp
zone/gm_commands/zsky.cpp

- Add parameter to allow data to be saved to database.

[Commands] Cleanup #zsky Command.

---

zone/command.cpp
zone/gm_commands/zclip.cpp

- Add parameter to allow data to be saved to database.

[Commands] Cleanup #zclip Command.

---

zone/command.cpp
zone/gm_commands/zsafecoords.cpp

- Add parameter to allow data to be saved to database.

[Commands] Cleanup #zsafecoords Command.

---

zone/command.cpp
zone/gm_commands/enablerecipe.cpp

[Commands] Cleanup #enablerecipe Command.

---

zone/command.cpp
zone/gm_commands/disablerecipe.cpp

[Commands] Cleanup #disablerecipe Command.

---

zone/spell_effects.cpp

Fixed issue where targeted bard songs were able to bypass restricted effects check. This was making Harmony type spells not work properly.

[Bug Fix] Bard instrument modifiers applying to effects when it shouldn't under certain conditions.

---

zone/command.cpp
zone/gm_commands/getplayerburiedcorpsecount.cpp

[Commands] Cleanup #getplayerburiedcorpsecount Command.

---

zone/gm_commands/bind.cpp

- Add message and cleanup logic.

[Commands] Cleanup #bind Command.

---

zone/client.cpp
zone/command.cpp
zone/gm_commands/gm.cpp

[Commands] Cleanup #gm Command.

---

zone/command.cpp
zone/gm_commands/castspell.cpp
zone/gm_commands/gender.cpp
zone/gm_commands/getplayerburiedcorpsecount.cpp
zone/gm_commands/ginfo.cpp
zone/gm_commands/givemoney.cpp
zone/gm_commands/loc.cpp
zone/gm_commands/nukeitem.cpp
zone/gm_commands/permagender.cpp
zone/gm_commands/permarace.cpp
zone/gm_commands/scribespells.cpp
zone/gm_commands/setaapts.cpp
zone/gm_commands/setaaxp.cpp
zone/gm_commands/setcrystals.cpp
zone/gm_commands/setpvppoints.cpp
zone/gm_commands/stun.cpp
zone/gm_commands/traindisc.cpp

- Cleanup other spots using similar logic so they're all uniform.

[Commands] Cleanup #gender Command.

---

zone/command.cpp
zone/gm_commands/gmspeed.cpp

[Commands] Cleanup #gmspeed Command.

---

zone/command.cpp
zone/gm_commands/title.cpp

[Commands] Cleanup #title Command.

---

zone/command.cpp
zone/gm_commands/gmzone.cpp

[Commands] Cleanup #gmzone Command.

---

zone/CMakeLists.txt
zone/command.cpp
zone/command.h
zone/gm_commands/mana.cpp
zone/gm_commands/setmana.cpp

- Add #setmana [Mana] command to set an NPC or player's mana to a specified amount, or to max if the amount is greater than their max.
- Cleanup #mana command message and logic.

[Commands] Add #setmana Command.

---

zone/CMakeLists.txt
zone/command.cpp
zone/command.h
zone/gm_commands/heal.cpp
zone/gm_commands/sethp.cpp

- Add #sethp [Health] command to set an NPC or player's health to a specified amount, or to max if the amount is greater than their max.
- Cleanup #heal command message and logic.

[Commands] Add #sethp Command.

---

zone/command.cpp
zone/gm_commands/texture.cpp

[Commands] Cleanup #texture Command.

---

zone/command.cpp
zone/gm_commands/mysql.cpp

[Commands] Cleanup #mysql Command.

---

zone/CMakeLists.txt
zone/command.cpp
zone/command.h
zone/gm_commands/countitem.cpp

- Add #countitem [Item ID] command to count an item by ID on yourself or your player/NPC target.

[Commands] Add #countitem Command.

---

common/emu_constants.cpp
common/emu_constants.h
zone/gm_commands/flymode.cpp
zone/gm_commands/npcedit.cpp

- Add GetFlyModeName() and GetFlyModeMap() helper methods.
- Cleanup #npcedit flymode to use helper methods.

[Commands] Cleanup #flymode Command.

---

zone/CMakeLists.txt
zone/command.cpp
zone/command.h
zone/gm_commands/removeitem.cpp

- Add #removeitem [Item ID] [Amount] command to remove items by amount versus nuking them all, removes all if amount is greater than what you or your target have.

[Commands] Add #removeitem Command.

---

world/main.cpp
world/zonelist.cpp

[Cleanup] holdzones not used.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::getlanguagename(language_id) to Perl.
- Add eq.get_language_name(language_id) to Lua.

[Quest API] Add GetLanguageName() to Perl/Lua.

---

zone/client.cpp
zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/zonedb.h

- Add quest::getfactionname(faction_id) to Perl.
- Add eq.get_faction_name(faction_id) to Lua.

[Quest API] Add GetFactionName() to Perl/Lua.

---

common/emu_constants.cpp
common/emu_constants.h
zone/embparser_api.cpp
zone/gm_commands/npcedit.cpp
zone/lua_general.cpp
zone/mob.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add GetBodyTypeName() and GetBodyTypeMap() helper methods.
- Add quest::getbodytypename(bodytype_id) to Perl.
- Add eq.get_body_type_name(bodytype_id) to Lua.

[Quest API] Add GetBodyTypeName() to Perl/Lua.

---

zone/embparser_api.cpp
zone/lua_general.cpp
zone/questmgr.cpp
zone/questmgr.h

- Add quest::getldonthemename(theme_id) to Perl.
- Add eq.get_ldon_theme_name(theme_id) to Lua.

[Quest API] Add GetLDoNThemeName() to Perl/Lua.

---

zone/command.cpp
zone/gm_commands/setstartzone.cpp

- Add a message when setting start zone.
- Cleanup logic.

[Commands] Cleanup #setstartzone Command.

---

zone/spell_effects.cpp

Base on live descriptions of this effect, SPA 272 SE_CastingLevel2 should affect dispel chance if present. This SPA raises your effective casting level by the base value of the spell. Higher affecting casting levels make dispel more likely to be successful.
Updated cure blind to also use a level based modifier for success, since it is also described as using one.

[Spells] Update to dispel to use SPA 272 SE_CastingLevel2

---

common/database.cpp
common/database_conversions.cpp
common/guild_base.cpp
zone/zonedb.cpp

[Database] Escape reserved mysql keyword rank w/ backticks

---

zone/client_packet.cpp
zone/spells.cpp

Minor fix to resolve reported crash.

[Bug Fix] validspell check to fix reported crash bug.

---

zone/perl_hateentry.cpp

[Bug Fix] Fix Perl Croak for GetEnt()

---

zone/command.cpp
zone/gm_commands/set_adventure_points.cpp

[Commands] Cleanup #setadventurepoints Command.

---

zone/perl_client.cpp
zone/perl_mob.cpp

- Client::SendToInstance()
- Mob::DeleteBucket()
- Mob::GetBucket()
- Mob::GetBucketExpires()
- Mob::GetBucketRemaining()
- Mob::SetBucket()

[Bug Fix] Cleanup Perl croaks for Spire parser.

---

zone/attack.cpp

Added nullptr check when processing XTargetAutoHaters for pet owner.

[Bug Fix] XTarget Changes Causing Crashes

---

common/emu_constants.h
common/item_instance.cpp
common/item_instance.h
common/ruletypes.h
zone/client_packet.cpp
zone/tradeskills.cpp

- Disallows multiple augments via #augmentitem or otherwise.
- Added ItemInstance::ContainsAugmentByID(item_id) helper method for finding an augment in an item instance.

[Bug Fix] Disallow multiple augments in same item.

---

zone/common.h
zone/mob.cpp
zone/mob.h
zone/special_attacks.cpp
zone/spell_effects.cpp

Spells using SPA 193 SE_SkillAttack should not trigger weapon or spell procs when used.

[Spells] SPA 193 SE_SkillAttack will no longer trigger procs

---

zone/client_packet.cpp

Accidental deletion in PR #1900 broke Pet Stop.

[Bug Fix] Restored functionality to Pet Stop

---

zone/tradeskills.cpp

Fix for SPA 331 SE_Salvage which gives chance to return items upon tradeskill failure. 
Code was just broken in multiple places.

[Bug Fix] Fixed Salvage for tradeskills

---

zone/spells.cpp

This update fixes issue where bind sight would not take hold on pets and other clients.

[Spells] Bind sight can now be cast on pets and other clients.

---

zone/gm_commands/npceditmass.cpp

[Commands] Cleanup #npceditmass command.

---

zone/gm_commands/ginfo.cpp

- Use popup over chat messages.

[Commands] #ginfo Cleanup.

---

common/inventory_profile.cpp
common/inventory_profile.h
zone/lua_inventory.cpp
zone/lua_inventory.h
zone/perl_inventory.cpp

- Add $inventory->CountItemEquippedByID(item_id) to Perl.
- Add $inventory->HasItemEquippedByID(item_id) to Perl.
- Add inventory:CountItemEquippedByID(item_id) to Lua.
- Add inventory:HasItemEquippedByID(item_id) to Lua

[Quest API] Add inventory->CountItemEquippedByID(item_id) and inventory->HasItemEquippedByID(item_id) to Perl/Lua.

---

zone/spell_effects.cpp

Pets will no longer warp away after being Summoning to owner. Resolves https://github.com/EQEmu/Server/issues/1150

[Bug Fix] Summon Companion causing pets to warps away.

---

zone/client_packet.cpp
zone/mob.h
zone/spells.cpp

Fix for https://github.com/EQEmu/Server/pull/1954
Resolved: Bards not consuming item click charges on instant cast items
Resolved: Bards not respecting class/race/deity restrictions on instant cast items

[Bug Fix] Bard update fixes 1

---

zone/aa.cpp
zone/spells.cpp

Bug fix for https://github.com/EQEmu/Server/pull/1971
Something ended up inside a bracket it shouldn't when copy/pasting.

[Bug Fix] Disc timer fix when using focus redux

---

zone/effects.cpp
zone/spells.cpp

Fix for https://github.com/EQEmu/Server/pull/1982/
Don't forget to add a return true to your bools or bad things happen.

[Bug Fix] PR 1982

---

zone/gm_commands/version.cpp

- Utilize popup over chat message.

[Commands] Cleanup #version Command.

---

zone/gm_commands/netstats.cpp

- Utilize popup over chat messages.

[Commands] Cleanup #netstats Command.

---

zone/command.cpp
zone/gm_commands/hatelist.cpp
zone/hate_list.cpp

[Commands] Cleanup #hatelist Command.

---

zone/mob.h
zone/spell_effects.cpp
zone/spells.cpp

Resolved edge case AA recast timer fix where spell triggers could potentially prevent recast timer from setting even though primary spell took hold. Related to PR https://github.com/EQEmu/Server/pull/1989
other minor fixes/changes

[Bug Fix] Edge case AA reset timer issue fixes

---

zone/mob.cpp

After 20 years live finally decided to add a too far away message to /shield command. Stumbled upon it while verifying something.

[Combat] /shield command "too far away message"

---

zone/command.cpp
zone/gm_commands/setskillall.cpp

[Commands] Cleanup #setskillall Command.

---

zone/attack.cpp
zone/bonuses.cpp
zone/common.h
zone/mob.cpp
zone/spell_effects.cpp

Memory Corruption issue with SE_LimitToSkill when setting bonus. This will fix issues with skill procs.

[Bug Fix] Memory Corruption issue with SE_LimitToSkill when setting bonus.

---

common/spdat.cpp
zone/client_packet.cpp
zone/spell_effects.cpp

Update to https://github.com/EQEmu/Server/pull/1991
remove unknown effect error message
minor changes/updates.

[Bug Fix] Prevent error messages when casting invisible, updates to PR 1991

---

zone/command.cpp
zone/gm_commands/untraindisc.cpp

[Commands] Cleanup #untraindisc Command.

---

zone/spells.cpp

Bard songs from item clicks should not require components.

[Spells] Bard songs from item clicks should not require components

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.cpp
zone/npc.h
zone/perl_npc.cpp

This returns the stat value for everything you can set using $npc->ModifyNPCStat(string key, string value)
Beats having to look up every single individual npc stat return quest function for simple use cases.
Will likely expand this in the future to get more values from table.

[API] perl added GetNPCStat(identifier)

---

zone/spell_effects.cpp

Missing break causing unable to find aura message
https://github.com/EQEmu/Server/pull/2022

[Bug Fix] Missing break from PR 2022 causing aura message error

---

zone/spells.cpp

This PR as written would have locked client's spell bar on fail condition. This resolves that.
https://github.com/EQEmu/Server/pull/2032

[Bug Fix] PR 2032 would lock client on casting fail as written

---

zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

Functions to allow environmental damage to be altered from scripts.
Set client to mitigate or increase environmental damage taken. Negative value will reduce damage.
$client->GetEnvironmentDamageModifier()
$client->SetEnvironmentDamageModifier(int32 modifier)
Set client to be invulnerable to environmental damage
$client->InvulnerableEnvironmentDamage()
$client->SetInvulnerableEnvironmentDamage(bool invulnerable)

[API] Perl functions to set invulnerable to and modify environmental damage.

---

zone/spells.cpp

If your spell global or spell bucket used a string-based value such as `enabled` when the code would convert to an integer it would crash.
It now uses strings and determines if both values are numbers before doing a numeric comparison otherwise it does a string comparison.

[Bug Fix] Spell Buckets/Globals did not allow string-based values.

---

zone/client.cpp

Push of a fix @Trust posted in discord.

[Bug Fix] Fix for being able to skill up on corspe.

---

zone/gm_commands/peqzone.cpp
zone/questmgr.cpp
zone/zoning.cpp

The original #peqzone would bypass EVENT_ZONE this will make it properly fire

[Bug Fix] #peqzone no longer bypass Handle_OP_ZoneChange

---

zone/entity.cpp
zone/entity.h
zone/lua_entity_list.cpp
zone/lua_entity_list.h
zone/perl_entity.cpp

- Add $entity_list->GetBotListByCharacterID(character_id) to Perl.
- Add eq.get_entity_list():GetBotListByCharacterID(character_id) to Lua.

[Quest API] Add GetBotListByCharacterID() to Perl/Lua.

---

zone/bot_command.cpp

The math made items blueish purple no matter what values you gave as Red.

[Bots] Fix ^dyearmor command math.

---

zone/bot.cpp
zone/bot.h

- Remove Bot::BotTradeSwapItem().
- Remove Bot::ApplySpecialAttackMod().

[Bots] Remove unused methods.

---

common/eqemu_logsys_log_aliases.h

Simple PR that adds missing log aliases when BUILD_LOGGING is disabled

[Logging] Update BUILD_LOGGING=false Blank Aliases

---

.drone.yml

This should speed up Drone builds by utilizing ccache

[Drone] Speed up drone builds

---

zone/bot.cpp
zone/bot.h
zone/bot_command.cpp
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp

- Add $bot->AddItem(slot_id, item_id, charges, attuned, augment_one, augment_two, augment_three, augment_four, augment_five, augment_six) to Perl.
- Add $bot->CountItem(item_id) to Perl.
- Add $bot->HasItem(item_id) to Perl.
- Add $bot->RemoveItem(item_id) to Perl.
- Add bot:AddItem(slot_id, item_id, charges, attuned, augment_one, augment_two, augment_three, augment_four, augment_five, augment_six) to Lua.
- Add bot:CountItem(item_id) to Lua.
- Add bot:GetOwner() to Lua.
- Add bot:HasItem(item_id) to Lua.
- Add bot:RemoveItem(item_id) to Lua.
- Cleaned up ^inventorywindow command.
- Cleaned up ^inventorylist command.
- Cleaned up ^inventoryremove command.
Test Script and screenshot.
Lua Example:
```lua
if (e.message:find("#a")) then
local count_item = …
```

[Quest API] Expand Bot quest API functionality.

---

zone/command.cpp
zone/gm_commands/getvariable.cpp

[Commands] Cleanup #getvariable Command.

---

zone/gm_commands/freeze.cpp
zone/gm_commands/unfreeze.cpp

- Remove the ability to #freeze yourself.

[Commands] Cleanup #freeze and #unfreeze Commands.

---

zone/command.cpp
zone/gm_commands/attack.cpp

[Commands] Cleanup #attack Command.

---

zone/command.cpp
zone/gm_commands/gassign.cpp
zone/waypoints.cpp
zone/zonedb.h

[Commands] Cleanup #gassign Command.

---

zone/gm_commands/spawnfix.cpp

[Commands] Cleanup #spawnfix Command.

---

zone/command.cpp
zone/global_loot_manager.cpp
zone/gm_commands/shownpcgloballoot.cpp
zone/gm_commands/showzonegloballoot.cpp

[Commands] Cleanup #shownpcgloballoot and #showzonegloballoot Command.

---

zone/gm_commands/save.cpp

[Commands] Cleanup #save Command.

---

zone/command.cpp
zone/gm_commands/roambox.cpp

[Commands] Cleanup #roambox Command.

---

zone/command.cpp
zone/gm_commands/resetdisc_timer.cpp

[Commands] Cleanup #resetdisc_timer Command.

---

zone/command.cpp
zone/gm_commands/serverinfo.cpp

- Use popup instead of messages.

[Commands] Cleanup #serverinfo Command.

---

zone/gm_commands/sensetrap.cpp

[Commands] Cleanup #sensetrap Command.

---

zone/gm_commands/resetaa.cpp

[Commands] Cleanup #resetaa Command.

---

zone/gm_commands/reloadworldrules.cpp

[Commands] Cleanup #reloadrulesworld Command.

---

zone/trap.cpp

- Does not modify command file, just the function called by the command.

[Commands] Cleanup #trapinfo Command.

---

zone/gm_commands/summonburiedplayercorpse.cpp

[Commands] Cleanup #summonburiedplayercorpse Command.

---

zone/gm_commands/reloadtitles.cpp
zone/worldserver.cpp

[Commands] Cleanup #reloadtitles Command.

---

zone/command.cpp
zone/gm_commands/reloadperlexportsettings.cpp
zone/worldserver.cpp

[Commands] Cleanup #reloadperlexportsettings Command.

---

zone/command.cpp
zone/gm_commands/reloadallrules.cpp
zone/worldserver.cpp

[Commands] Cleanup #reloadallrules Command.

---

zone/command.cpp
zone/gm_commands/push.cpp

[Commands] Cleanup #push Command.

---

zone/command.cpp
zone/gm_commands/refreshgroup.cpp
zone/zonedb.cpp

[Commands] Cleanup #refreshgroup Command.

---

zone/gm_commands/randomfeatures.cpp
zone/mob.cpp

- Make #randomfeatures function for Iksar and Vah Shir.

[Commands] Cleanup #randomfeatures Command.

---

zone/gm_commands/questerrors.cpp
zone/quest_interface.h
zone/quest_parser_collection.cpp
zone/quest_parser_collection.h

[Commmands] Cleanup #questerrors Command.

---

zone/command.cpp
zone/gm_commands/npctypespawn.cpp

[Commands] Cleanup #npctypespawn Command.

---

zone/command.cpp
zone/gm_commands/npcsay.cpp
zone/gm_commands/npcshout.cpp

[Commands] Cleanup #npcsay and #npcshout Commands.

---

zone/command.cpp
zone/gm_commands/npcemote.cpp

[Commands] Cleanup #npcemote Command.

---

zone/command.cpp
zone/gm_commands/makepet.cpp

[Commands] Cleanup #makepet Command.

---

common/profanity_manager.cpp
common/profanity_manager.h
zone/gm_commands/profanity.cpp

[Commands] Cleanup #profanity Command.

---

zone/command.cpp
zone/gm_commands/time.cpp
zone/gm_commands/timezone.cpp

[Commands] Cleanup #time and #timezone Command.

---

world/zoneserver.cpp
world/zoneserver.h

Relevant to https://github.com/EQEmu/Server/issues/2111.

[Bug Fix] Fix possible issue where variables have the same name.

---

world/adventure.cpp
world/adventure.h
world/zoneserver.cpp
world/zoneserver.h

There may be more, these are just what I could find with a search through the source.

[Cleanup] Possible issues with variable/parameter name equality.

---

common/eqemu_logsys.h
common/eqemu_logsys_log_aliases.h
zone/aggro.cpp
zone/attack.cpp
zone/bot.cpp
zone/bot.h
zone/entity.cpp
zone/entity.h
zone/gm_commands/aggrozone.cpp
zone/hate_list.cpp
zone/hate_list.h
zone/lua_hate_list.cpp
zone/lua_hate_list.h
zone/lua_mob.cpp
zone/lua_mob.h
zone/mob.cpp
zone/mob.h
zone/perl_hateentry.cpp
zone/perl_mob.cpp
zone/special_attacks.cpp
zone/spell_effects.cpp
zone/tune.cpp

* Changes most hate references to signed instead of unsigned
* Adds logging category Hate
* Fixes GetHateTop issue from unsigned / signed comparison bug

[int64] Hate Fixes

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->GetHealAmount() to Perl.
- Add $client->GetSpellDamage() to Perl.
- Add client:GetHealAmount() to Lua
- Add client:GetSpellDamage() to Lua.

[Quest API] Add GetHealAmount() and GetSpellDamage() to Perl/Lua.

---

zone/zonedb.cpp
zone/zonedb.h

- Remove unused ZoneDatabase::UpdateZoneSafeCoords(const char* zonename, const glm::vec3& location);
- Remove unused ZoneDatabase::GetUseCFGSafeCoords();

[Cleanup] Remove unused methods.

---

zone/client.cpp
zone/client.h
zone/client_packet.cpp
zone/embparser_api.cpp
zone/gm_commands/lastname.cpp
zone/gm_commands/title.cpp
zone/gm_commands/titlesuffix.cpp
zone/lua_client.cpp
zone/lua_client.h
zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.cpp
zone/npc.h
zone/perl_client.cpp
zone/perl_npc.cpp
zone/questmgr.cpp
zone/questmgr.h
zone/titles.cpp
zone/titles.h

- Use strings instead of const chars*.
- Add optional parameter to SetAATitle in Lua so you can save to the database similar to Perl.
- Cleanup #lastname command.
- Cleanup #title command.
- Cleanup #titlesuffix command.

[Titles] Cleanup titles, title suffix, and last name methods.

---

zone/client.cpp
zone/gm_commands/path.cpp

- Client::Undye() was inside the #path command file.

[Cleanup] Move Client::Undye() to client.cpp from #path Command.

---

zone/gm_commands/kill.cpp

[Commands] Cleanup #kill Command.

---

zone/bot_command.cpp

- Convert bot_command_add calls to use constants instead of magic numbers.

[Bot Commands] Use Account Status Constants.

---

zone/aggro.cpp

Revert "[Aggro] Rooted mobs will add other hated targets to Hate list"

---

common/servertalk.h
zone/command.cpp
zone/gm_commands/oocmute.cpp
zone/worldserver.cpp

- Add ServerOOCMute_Struct for cleanliness.

[Commands] Cleanup #oocmute Command.

---

zone/entity.cpp

[Commands] Cleanup #corpsefix Command.

---

zone/gm_commands/findclass.cpp
zone/gm_commands/findrace.cpp
zone/mob.cpp
zone/mob.h

- Add bitmasks to player race messages.
- Add Mob::IsPlayerClass(class_id).

[Commands] Cleanup #findclass and #findrace Commands.

---

zone/command.cpp
zone/gm_commands/emptyinventory.cpp

- Breakout #emptyinventory into its own command file.
- Branch is old, had forgot I wrote this.

[Commands] Cleanup #emptyinventory Command.

---

zone/gm_commands/nudge.cpp

- Branch is old, had forgot I wrote this.

[Commands] Cleanup #nudge Command.

---

zone/task_manager.cpp

Fixes assumptions that activity loading makes around primitive types

[Tasks] Fix validation loading

---

zone/command.cpp
zone/gm_commands/date.cpp

[Commands] Cleanup #date Command.

---

world/client.cpp
world/client.h
zone/client.cpp
zone/mob.cpp

Some miscellaneous code cleanup based on visual studio/resharper warnings. I only included changes that were functionally identical.

[Code Cleanup] Resharper Warnings

---

zone/gm_commands/advnpcspawn.cpp
zone/mob.cpp

- Cleanup where std::stoi should be std::stoul.
- Cleanup ShowStats message to show NPC stats at bottom as well.

[Bug Fix] Fix issue where #advnpcspawn addspawn does not add spawn sometimes.

---

zone/client.cpp

Static code analysis found two instances of read out-of-bounds of an array issues in zone/client.cpp. This PR is to correct this potential error.

[Bug Fix] Fix two invalid data accesses in zone/client.cpp

---

zone/client_packet.cpp

Processing the hacker_str through EscapeString().

[Bug Fix] Hacker_Str was causing sql errors - Non Escaped

---

world/client.cpp
zone/guild.cpp

These leaks are rather rare, but still possible.

[Memory Leak] Fix memory leaks found by Quint

---

common/ruletypes.h
zone/merc.cpp
zone/special_attacks.cpp
zone/spell_effects.cpp
zone/spells.cpp

https://github.com/EQEmu/Server/issues/837 from 2019 notes a couple places that should use Focus Effect chat type instead of Spells chat type.

[Messages] Convert messages from Spells to FocusEffect where necessary.

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.h
zone/perl_npc.cpp
zone/waypoints.cpp

- Adds
-- mob:saveguardspot()
-- mob:saveguardspot(true)
Pending perl implementation

[Quest API] Expand SaveGuardSpot

---

zone/tradeskills.cpp

Require min tradeskill or above for autocombine.

[Bug Fix] Tradeskill Autocombine MinSkill

---

zone/client_process.cpp

Fix empty spawned merchants

---

common/shareddb.cpp
common/shareddb.h

Some warnings were from VS2022 in windows, and some were from Resharper.

[Cleanup] Cleanup code smells and compiler warnings in common/shareddb

---

common/ruletypes.h
zone/entity.cpp
zone/entity.h
zone/spell_effects.cpp

This should fix eqemu/master#2205

[Bug Fix] Add required distance to CoTH before aggro wipe

---

zone/zonedb.cpp

Fixes code smell lnt-accidental-copy in zonedb.cpp

[Cleanup] Fix unintended copies in zone/zonedb.cpp by changing auto to auto&

---

zone/bot.cpp
zone/bot_command.cpp
zone/client.cpp
zone/client_process.cpp
zone/gm_commands/kick.cpp
zone/gm_commands/object.cpp
zone/gm_commands/reload.cpp
zone/gm_commands/setlsinfo.cpp
zone/gm_commands/viewnpctype.cpp
zone/horse.cpp
zone/mob.cpp
zone/object.cpp
zone/trading.cpp
zone/worldserver.cpp
zone/zoning.cpp

Have not had a chance to even compile this let alone run it, hence the draft PR status.

[Bug Fix] Fix miscellaneous memory leaks related to EQApplicationPacket and it's pBuffer

---

zone/spell_effects.cpp
zone/string_ids.h

Added message string 1393 // You have been summoned!

[Cleanup] Update to EQEmu #2253 to clean up message strings

---

zone/client.cpp

- Default to true and set to false if they fail the proper check.

[Bug Fix] Fix Spell Bucket and Spell Global Logic Checks.

---

zone/perl_client.cpp
zone/perl_npc.cpp
zone/perl_object.cpp

Some methods were missing package.adds or didn't have their overloads.

[Quest API] Add missing methods/package.adds to Perl API.

---

common/shareddb.cpp
common/shareddb.h
zone/command.cpp

- Validates size of shared memory pool versus current count of database so people don't accidentally #hotfix and mess something up.
**Items**
**Spells**

[Validation] Add Size Validation to #hotfix.

---

common/ip_util.cpp

Remove use of bzero since it is deprecated for memset

[Code Cleanup] Remove bzero

---

world/shared_task_manager.cpp

Shared task replay timers used to be based on the task start time
(reducing the final lockout timer by elapsed task time).
Live changed this in the 2022 April 20 patch:
"Replay timers will now apply their full duration upon completion of
their associated task/quest."
Solo tasks and quests already did this
This also fixes a small bug where request timers were being
deleted when replacing replay timers for shared tasks

[Tasks] Apply full duration mission replay timers

---

zone/trading.cpp

https://github.com/EQEmu/Server/commit/b5c4357de2e14a1c97abbab26c60eee8ff308331#r77584958

This mem leak was missed due to merge issues in the previous PRs.

---

zone/task_client_state.cpp

Also removes the sound which does not occur

[Tasks] Use CashReward for Tasks

---

zone/loottables.cpp
zone/mob.h
zone/mob_ai.cpp
zone/special_attacks.cpp

[Feature] NPCs with bows and arrows do ranged attacks

---

zone/lua_npc.cpp
zone/lua_npc.h
zone/npc.h
zone/perl_npc.cpp

- Add $npc->IsRareSpawn() to Perl.
- Add npc:IsRareSpawn() to Lua.

[Quest API] Add IsRareSpawn() to Perl/Lua.

---

world/shared_task_manager.cpp

Small regression from refactoring

[Shared Tasks] Fix shared task message target

---

loginserver/world_server.cpp

clang was complaining about these.

[Code Cleanup] Resolve some warnings in loginserver/world_server.cpp

---

zone/bot.h
zone/lua_bot.cpp
zone/lua_bot.h
zone/perl_bot.cpp

- Add $bot->GetBotItem(slot_id) to Perl.
- Add $bot->GetBotItemIDBySlot(slot_id) to Perl.
- Add bot:GetBotItem(slot_id) to Lua.
- Add bot:GetBotItemIDBySlot(slot_id) to Lua.

[Quest API] Add GetBotItem() and GetBotItemIDBySlot() to Perl/Lua.

---

zone/client_packet.cpp
zone/task_client_state.cpp
zone/task_client_state.h
zone/task_manager.cpp

This makes it so clients can only accept tasks that have been offered

[Tasks] Add task accept packet validation

---

common/say_link.cpp
common/say_link.h
zone/gm_commands/door_manipulation.cpp

Simply adds helper function
```cpp
std::string Silent(const std::string &saylink_text, const std::string &link_name);
```
To be used in later PRs
Also passes string by reference to avoid copying

[Saylinks] Add Silent helper

---

zone/aura.cpp

Unsure if something changed or I just failed to test correctly

[Bug Fix] Resolve issue with trap auras casting on caster

---

zone/bot_command.cpp
zone/bot_database.cpp
zone/bot_database.h

There were some weird cases where this code would falsely say a bot group did not exist and this would disallow summoning this botgroup as well as deleting it.

[Bug Fix] Fix Bot Group Loading

---

zone/command.cpp
zone/command.h
zone/gm_commands/lootsim.cpp
zone/loottables.cpp
zone/npc.cpp
zone/npc.h

Implemented **#lootsim** command to simulate running loot benchmarks using live loot table data, using the actual loot logic
```
#lootsim [npc_type_id] [loottable_id] [iterations] [loot_log_enabled=0]
```
The simulator will spawn an NPC, run X specified iterations of loot runs against the NPC and print the results in a table afterwards.
Loot logging gets disabled unless otherwise specified because it can be very spammy if you don't for larger samples.
Iterations are clamped to 1k otherwise it takes so long the zone process can hang and your client can disconnect.
**Example Output In Game**
**Full Example With Global Loot**
```
[Sun Aug 14 00:36:55 2022] You say, '#lootsim 1001 10664 1000'
[Sun Aug 14 00:36:55 2022] ------------------------------------------------
[Sun Aug 14 00:36:55 …
```

[Loot] Add #lootsim (Loot Simulator) command

---

world/zoneserver.cpp

[Feature] Add Guild Chat to Console.

---

zone/zoning.cpp

[Zone] Add missing safe_heading assignment

---

zone/task_client_state.cpp

Cosmetic change, this one depends on the delivered task item patch for count to be completely accurate

[Tasks] Tweak task update messages

---

common/tasks.h
zone/gm_commands/findtask.cpp
zone/gm_commands/task.cpp
zone/task_client_state.cpp
zone/task_client_state.h
zone/task_manager.cpp
zone/task_manager.h

This allows removal of the task id limit (MAXTASKS)
There's some suspect places task data isn't verified but left unchanged
If memory use becomes too high once more live data is added tasks can be
stored in shared memory instead

[Tasks] Change zone task data container

---

zone/lua_client.cpp

Quest system will catch any errors and result it in being reported where
these weren't

[Cleanup] Rework Lua QuestReward to not use try/catch blocks

---

zone/object.cpp

Clang was complaining about these
Checking if first char is null should be faster than strlen

[Clean up] Tweak object name checking item's IDFile

---

zone/gm_commands/damage.cpp

Fixes annoying issue where it affected the client if no target

[Commands] Make #damage require a target

---

zone/task_client_state.cpp

Thought I tested this, maybe the variable name confused me and I did a last minute change

[Tasks] Let task reward find free bag slots

---

zone/gm_commands/spellinfo.cpp

[Bug Fix] Fix Spellinfo Command to work with SpellIDs above int16

---

zone/lua_parser.cpp

Define is _WINDOWS not WINDOWS

[Lua] Fix Luarocks

---

zone/client.cpp

Will filter out Focus Effects if Hide is selected under Options > Filters > Focus Effects

[Feature] Allow Focus Effects to be Filtered out.

---

common/database.cpp
common/database.h

Addresses https://github.com/EQEmu/Server/issues/2432

[Command] Fix #copycharacter command crash

---

utils/scripts/eqemu_server.pl

`fetch_latest_windows_appveyor()` is used in its place

[eqemu_server.pl] Remove non-working fetch_latest_windows_binaries()

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add $client->GetGMStatus() to Perl.
- Add client:GetGMStatus() to Lua.
- Fix client:Admin() using Lua_Safe_Call_Bool().
This is just a more descriptive form of $client->Admin() in Perl and client:Admin() in Lua.

[Quest API] Add GetGMStatus() to Perl/Lua.

---

common/http/httplib.h

**Changes**
- CPPHTTPLIB_NO_DEFAULT_USER_AGENT skips default user agent (https://github.com/yhirose/cpp-httplib/pull/1201)
- Add optional private key password to SSLServer ctor (https://github.com/yhirose/cpp-httplib/pull/1205)
- Upload unicode file name bug (https://github.com/yhirose/cpp-httplib/issues/1212)
- Skipping fragment string on server (https://github.com/yhirose/cpp-httplib/issues/1214, https://github.com/yhirose/cpp-httplib/issues/1215)
- BindIPAddress when force address family to IPV6 and set outbound interface (https://github.com/yhirose/cpp-httplib/issues/1235)
- Accept large data transfer over SSL (https://github.com/yhirose/cpp-httplib/pull/1261)
- Http server can't send file large than 2GB (https://github.com/yhirose/cpp-httplib/issues/1290)
- LeakSanitizer: Memory leak …

[Library] Bump httplib to 0.11.2

---

zone/entity.cpp
zone/gm_commands/repop.cpp
zone/spawn2.cpp

There were multiple issues wrapped up in this and quite a bit of time involved in isolating this problem.
Currently troubleshooting other server issues with other operators so I'll spare the details but the TLDR is that this should be fixed especially for Windows server operators where this problem was occurring.
Tested and verified after dozens of repops the issue is resolved

[Crash] Fix spawn race condition shown by #repop

---

zone/attack.cpp
zone/bot.cpp

Didn't find any more instances of these.

[Feature] Change Lifetap Emotes to be filterable.

---

zone/client.h
zone/client_packet.cpp
zone/string_ids.h

Functions same as scribing to spellbook, 
Will check if it's a valid upgrade (no downgrading possible) and present the player with a Yes/No Popup Prompt,

[Feature] Spell Ranks will now work with AllowSpellMemorizeFromItem Rule

---

common/database.cpp

Only added support for Soft Deletes if the Character Soft Deletes Rule is used. Would have been too much effort currently to add support for Hard Deletes.

[Feature] Soft Delete Bots on Character Soft Delete

---

zone/attack.cpp
zone/aura.cpp
zone/effects.cpp
zone/entity.cpp
zone/mob.cpp
zone/npc.cpp
zone/spells.cpp

PR adds extra safety of pointer validation checks where they currently don't exist

[Crash] Pointer validation in mob iteration loops

---

ucs/worldserver.cpp
world/zoneserver.cpp

Title is descriptive of change

[Logs] Have #reload logs also reload UCS logging

---

zone/client_packet.cpp

Reverts https://github.com/EQEmu/Server/pull/2424 as the true fix was https://github.com/EQEmu/Server/pull/2479

[Zoning] Revert #2424

---

zone/lua_corpse.cpp
zone/lua_corpse.h

[Quest API] Add Corpse::AddItem overloads for Lua

---

zone/client.cpp
zone/client.h

This api is only used by quests

[Cleanup] Send eqstr message in AddAAPoints

---

zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

Exports Client::ResetAlternateAdvancementRank

[Quest API] Add ResetAlternateAdvancementRank() to Perl/Lua.

---

zone/bot_command.cpp

Adds shortcut saylinks for giving items to bots or removing items from them.

[Bots] Add give/remove saylinks to ^itemuse.

---

zone/command.cpp
zone/gm_commands/dbspawn2.cpp

Add some descriptive messages so that you get some feedback from the command.

[Commands] Cleanup #dbspawn2 Command.

---

zone/lua_mob.cpp
zone/lua_mob.h
zone/perl_mob.cpp

- Add `$mob->GetUltimateOwner()` to Perl.
- Add `mob:GetUltimateOwner()` to Lua.
- Allows operators to get ultimate owner of something like a pet's pet or a pet's swarm pet.

[Quest API] Add GetUltimateOwner() to Perl/Lua.

---

zone/command.cpp
zone/gm_commands/scribespell.cpp
zone/gm_commands/scribespells.cpp

[Commands] Cleanup #scribespell and #scribespells Commands.

---

zone/client.cpp
zone/client_packet.cpp
zone/command.cpp
zone/gm_commands/devtools.cpp

[Commands] Cleanup #devtools Command.

---

zone/command.cpp
zone/gm_commands/opcode.cpp

[Commands] Cleanup #opcode Command.

---

zone/client.cpp
zone/command.cpp
zone/gm_commands/xtargets.cpp

[Commands] Cleanup #xtargets Command.

---

zone/bot_database.cpp

Query was off by 1, causing HP to load incorrectly.

[Bug Fix] Fix issue with Bot Loading with 0 Health

---

zone/client.cpp
zone/client.h
zone/lua_client.cpp
zone/lua_client.h
zone/perl_client.cpp

- Add `client:UpdateAdmin()`.
- Add `client:UpdateAdmin(from_database)`.
- Perl was sending `UpdateAdmin()` after `SetGMStatus()`, Lua wasn't, so only Perl was updating properly.
- Fix is to just put `UpdateAdmin()` inside `SetGMStatus()`.

[Bug Fix] Fix Flag Updating with SetGMStatus() in Lua.

---

zone/gm_commands/suspend.cpp

[Commands] Cleanup #suspend Command.

---

zone/command.cpp
zone/gm_commands/heromodel.cpp

[Commands] Cleanup #heromodel Command.

---

zone/command.cpp
zone/gm_commands/delacct.cpp

[Commands] Cleanup #delacct Command.
